In [50]:
import json
import pandas as pd

BATCH_SIZE = 50
IS_DEBUG = True
DEBUG_QUESTION_SIZE = 10
LLM_MODEL = "gpt-4.1"
DATASET_NAME = "hotpotQA"
KNOWLEDGE_GRAPH_PATH = 'outputs/knowledge_graphs'

## 1. Loading HotpotQA Dataset

In [51]:
train_hotpot_qa_path = r'C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\hotpotQA\hotpot_train_v1.1.json'
test_hotpot_qa_path = r'C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\hotpotQA\hotpot_test_v1.1.json'

In [52]:
with open(train_hotpot_qa_path, 'r', encoding='utf-8') as f:
    train_hotpot_qa_json = json.load(f)

with open(test_hotpot_qa_path, 'r', encoding='utf-8') as f:
    test_hotpot_qa_json = json.load(f)

In [53]:
train_hotpot_qa_json[0]

{'supporting_facts': [["Arthur's Magazine", 0], ['First for Women', 0]],
 'level': 'medium',
 'question': "Which magazine was started first Arthur's Magazine or First for Women?",
 'context': [['Radio City (Indian radio station)',
   ["Radio City is India's first private FM radio station and was started on 3 July 2001.",
    ' It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003).',
    ' It plays Hindi, English and regional songs.',
    ' It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007.',
    ' Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features.',
    ' The Radio station currently plays a mix of Hindi and Regional music.',
    ' Abraham Thomas is the CEO of the company.']],
  ['History of Albanian football',
   ['Football in Albania existed before the Albanian Football Federation (FSHF) was created.',
    " This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) .",
    ' Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946.',
    ' In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.']],
  ['Echosmith',
   ['Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California.',
    ' Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016.',
    ' Echosmith started first as "Ready Set Go!"',
    ' until they signed to Warner Bros.',
    ' Records in May 2012.',
    ' They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia.',
    ' The song was Warner Bros.',
    " Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold.",
    ' The band\'s debut album, "Talking Dreams", was released on October 8, 2013.']],
  ["Women's colleges in the Southern United States",
   ["Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States.",
    " Many started first as girls' seminaries or academies.",
    ' Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women.',
    ' Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.']],
  ['First Arthur County Courthouse and Jail',
   ['The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.']],
  ["Arthur's Magazine",
   ["Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century.",
    ' Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others.',
    ' In May 1846 it was merged into "Godey\'s Lady\'s Book".']],
  ['2014–15 Ukrainian Hockey Championship',
   ['The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship.',
    ' Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues.',
    ' Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014.',
    ' The regular season included just 12 rounds, where all the teams went to the semifinals.',
    ' In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.']],
  ['First for Women',
   ["First for Women is a woman's magazine published by Bauer Media Group in the USA.",
    ' The magazine was started in 1989.',
    ' It is based in Englewood Cliffs, New Jersey.',
    ' In 2011 the circulation of the magazine was 1,310,696 copies.']],
  ['Freeway Complex Fire',
   ['The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California.',
    ' The fire started as two separate fires on November 15, 2008.',
    ' The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later.',
    ' These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.']],
  ['William Rast',
   ['William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala.',
    ' It is most known for their premium jeans.',
    ' On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line.',
    ' The label also produces other clothing items such as jackets and tops.',
    ' The company started first as a denim line, later evolving into a men’s and women’s clothing line.']]],
 'answer': "Arthur's Magazine",
 '_id': '5a7a06935542990198eaf050',
 'type': 'comparison'}

In [54]:
test_hotpot_qa_json[0]

{'_id': '5a8b57f25542995d1e6f1371',
 'answer': 'yes',
 'question': 'Were Scott Derrickson and Ed Wood of the same nationality?',
 'supporting_facts': [['Scott Derrickson', 0], ['Ed Wood', 0]],
 'context': [['Adam Collis',
   ['Adam Collis is an American filmmaker and actor.',
    ' He attended the Duke University from 1986 to 1990 and the University of California, Los Angeles from 2007 to 2010.',
    ' He also studied cinema at the University of Southern California from 1991 to 1997.',
    ' Collis first work was the assistant director for the Scott Derrickson\'s short "Love in the Ruins" (1995).',
    ' In 1998, he played "Crankshaft" in Eric Koyanagi\'s "Hundred Percent".']],
  ['Ed Wood (film)',
   ['Ed Wood is a 1994 American biographical period comedy-drama film directed and produced by Tim Burton, and starring Johnny Depp as cult filmmaker Ed Wood.',
    " The film concerns the period in Wood's life when he made his best-known films as well as his relationship with actor Bela Lugosi, played by Martin Landau.",
    ' Sarah Jessica Parker, Patricia Arquette, Jeffrey Jones, Lisa Marie, and Bill Murray are among the supporting cast.']],
  ['Tyler Bates',
   ['Tyler Bates (born June 5, 1965) is an American musician, music producer, and composer for films, television, and video games.',
    ' Much of his work is in the action and horror film genres, with films like "Dawn of the Dead, 300, Sucker Punch," and "John Wick."',
    ' He has collaborated with directors like Zack Snyder, Rob Zombie, Neil Marshall, William Friedkin, Scott Derrickson, and James Gunn.',
    ' With Gunn, he has scored every one of the director\'s films; including "Guardians of the Galaxy", which became one of the highest grossing domestic movies of 2014, and its 2017 sequel.',
    ' In addition, he is also the lead guitarist of the American rock band Marilyn Manson, and produced its albums "The Pale Emperor" and "Heaven Upside Down".']],
  ['Doctor Strange (2016 film)',
   ['Doctor Strange is a 2016 American superhero film based on the Marvel Comics character of the same name, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures.',
    ' It is the fourteenth film of the Marvel Cinematic Universe (MCU).',
    ' The film was directed by Scott Derrickson, who wrote it with Jon Spaihts and C. Robert Cargill, and stars Benedict Cumberbatch as Stephen Strange, along with Chiwetel Ejiofor, Rachel McAdams, Benedict Wong, Michael Stuhlbarg, Benjamin Bratt, Scott Adkins, Mads Mikkelsen, and Tilda Swinton.',
    ' In "Doctor Strange", surgeon Strange learns the mystic arts after a career-ending car accident.']],
  ['Hellraiser: Inferno',
   ['Hellraiser: Inferno (also known as Hellraiser V: Inferno) is a 2000 American horror film.',
    ' It is the fifth installment in the "Hellraiser" series and the first "Hellraiser" film to go straight-to-DVD.',
    ' It was directed by Scott Derrickson and released on October 3, 2000.',
    " The film concerns a corrupt detective who discovers Lemarchand's box at a crime scene.",
    " The film's reviews were mixed."]],
  ['Sinister (film)',
   ['Sinister is a 2012 supernatural horror film directed by Scott Derrickson and written by Derrickson and C. Robert Cargill.',
    ' It stars Ethan Hawke as fictional true-crime writer Ellison Oswalt who discovers a box of home movies in his attic that puts his family in danger.']],
  ['Deliver Us from Evil (2014 film)',
   ['Deliver Us from Evil is a 2014 American supernatural horror film directed by Scott Derrickson and produced by Jerry Bruckheimer.',
    ' The film is officially based on a 2001 non-fiction book entitled "Beware the Night" by Ralph Sarchie and Lisa Collier Cool, and its marketing campaign highlighted that it was "inspired by actual accounts".',
    ' The film stars Eric Bana, Édgar Ramírez, Sean Harris, Olivia Munn, and Joel McHale in the main roles and was released on July 2, 2014.']],
  ['Woodson, Arkansas',
   ['Woodson is a census-designated place (CDP) in Pulaski County, Arkansas, in the United States.',
    ' Its population was 403 at the 2010 census.',
    ' It is part of the Little Rock–North Little Rock–Conway Metropolitan Statistical Area.',
    ' Woodson and its accompanying Woodson Lake and Wood Hollow are the namesake for Ed Wood Sr., a prominent plantation owner, trader, and businessman at the turn of the 20th century.',
    ' Woodson is adjacent to the Wood Plantation, the largest of the plantations own by Ed Wood Sr.']],
  ['Conrad Brooks',
   ['Conrad Brooks (born Conrad Biedrzycki on January 3, 1931 in Baltimore, Maryland) is an American actor.',
    ' He moved to Hollywood, California in 1948 to pursue a career in acting.',
    ' He got his start in movies appearing in Ed Wood films such as "Plan 9 from Outer Space", "Glen or Glenda", and "Jail Bait."',
    ' He took a break from acting during the 1960s and 1970s but due to the ongoing interest in the films of Ed Wood, he reemerged in the 1980s and has become a prolific actor.',
    ' He also has since gone on to write, produce and direct several films.']],
  ['The Exorcism of Emily Rose',
   ['The Exorcism of Emily Rose is a 2005 American legal drama horror film directed by Scott Derrickson and starring Laura Linney and Tom Wilkinson.',
    ' The film is loosely based on the story of Anneliese Michel and follows a self-proclaimed agnostic who acts as defense counsel (Linney) representing a parish priest (Wilkinson), accused by the state of negligent homicide after he performed an exorcism.']]],
 'type': 'comparison',
 'level': 'hard'}

In [55]:
for item in train_hotpot_qa_json[0]['context']:
    print(f"Title: {item[0]}")
    print(f"Paragraph: {item[1:]}")
    print("-" * 50)

Title: Radio City (Indian radio station)
Paragraph: [["Radio City is India's first private FM radio station and was started on 3 July 2001.", ' It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003).', ' It plays Hindi, English and regional songs.', ' It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007.', ' Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features.', ' The Radio station currently plays a mix of Hindi and Regional music.', ' Abraham Thomas is the CEO of the company.']]
--------------------------------------------------
Title: History of Albanian football
Paragraph: [['Football in Albania existed before the Albanian Football Federation (FSHF) was created.', " This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) .", ' Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946.', ' In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.']]
--------------------------------------------------
Title: Echosmith
Paragraph: [['Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California.', ' Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016.', ' Echosmith started first as "Ready Set Go!"', ' until they signed to Warner Bros.', ' Records in May 2012.', ' They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia.', ' The song was Warner Bros.', " Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold.", ' The band\'s debut album, "Talking Dreams", was released on October 8, 2013.']]
--------------------------------------------------
Title: Women's colleges in the Southern United States
Paragraph: [["Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States.", " Many started first as girls' seminaries or academies.", ' Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women.', ' Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.']]
--------------------------------------------------
Title: First Arthur County Courthouse and Jail
Paragraph: [['The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.']]
--------------------------------------------------
Title: Arthur's Magazine
Paragraph: [["Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century.", ' Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others.', ' In May 1846 it was merged into "Godey\'s Lady\'s Book".']]
--------------------------------------------------
Title: 2014–15 Ukrainian Hockey Championship
Paragraph: [['The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship.', ' Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues.', ' Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014.', ' The regular season included just 12 rounds, where all the teams went to the semifinals.', ' In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.']]
--------------------------------------------------
Title: First for Women
Paragraph: [["First for Women is a woman's magazine published by Bauer Media Group in the USA.", ' The magazine was started in 1989.', ' It is based in Englewood Cliffs, New Jersey.', ' In 2011 the circulation of the magazine was 1,310,696 copies.']]
--------------------------------------------------
Title: Freeway Complex Fire
Paragraph: [['The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California.', ' The fire started as two separate fires on November 15, 2008.', ' The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later.', ' These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.']]
--------------------------------------------------
Title: William Rast
Paragraph: [['William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala.', ' It is most known for their premium jeans.', ' On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line.', ' The label also produces other clothing items such as jackets and tops.', ' The company started first as a denim line, later evolving into a men’s and women’s clothing line.']]
--------------------------------------------------

In [56]:
train_batch_context = []
train_batch_question = []
train_batch_answer = []

if IS_DEBUG:
    train_hotpot_qa_json = train_hotpot_qa_json[:DEBUG_QUESTION_SIZE]
    test_hotpot_qa_json = test_hotpot_qa_json[:DEBUG_QUESTION_SIZE]

for i in range(0, len(train_hotpot_qa_json), BATCH_SIZE):
    batch = train_hotpot_qa_json[i:i + BATCH_SIZE]
    context = []
    question = []
    answer = []

    for item in batch:
        context_text = ""
        j = 1
        for ctx in item['context']:
            context_text += f"Title {j} : {ctx[0]} \nParagraph {j} : {''.join(ctx[1])}\n"
            j += 1
        context.append(context_text)
        question.append(item['question'])
        answer.append(item['answer'])

    train_batch_context.append(context)
    train_batch_question.append(question)
    train_batch_answer.append(answer)

In [57]:
if IS_DEBUG:
    batch_context = train_batch_context
    batch_question = train_batch_question
    batch_answer = train_batch_answer
else:
    batch_context = []
    batch_question = []
    batch_answer = []

In [58]:
for i in range(len(train_batch_context[0])):
    print(f"Batch {i + 1}:")
    print("Context:", train_batch_context[0][i])
    print("Question:", train_batch_question[0][i])
    print("Answer:", train_batch_answer[0][i])
    print("-" * 50)
    if i == 9:  # Limit to 3 batches for brevity
        break

Batch 1:
Context: Title 1 : Radio City (Indian radio station)
Paragraph 1 : Radio City is India's first private FM radio station and was started on 3 July 2001. It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003). It plays Hindi, English and regional songs. It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007. Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features. The Radio station currently plays a mix of Hindi and Regional music. Abraham Thomas is the CEO of the company.
Title 2 : History of Albanian football
Paragraph 2 : Football in Albania existed before the Albanian Football Federation (FSHF) was created. This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) . Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946. In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.
Title 3 : Echosmith
Paragraph 3 : Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California. Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016. Echosmith started first as "Ready Set Go!" until they signed to Warner Bros. Records in May 2012. They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia. The song was Warner Bros. Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold. The band's debut album, "Talking Dreams", was released on October 8, 2013.
Title 4 : Women's colleges in the Southern United States
Paragraph 4 : Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States. Many started first as girls' seminaries or academies. Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women. Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.
Title 5 : First Arthur County Courthouse and Jail
Paragraph 5 : The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.
Title 6 : Arthur's Magazine
Paragraph 6 : Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century. Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others. In May 1846 it was merged into "Godey's Lady's Book".
Title 7 : 2014–15 Ukrainian Hockey Championship
Paragraph 7 : The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship. Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues. Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014. The regular season included just 12 rounds, where all the teams went to the semifinals. In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.
Title 8 : First for Women
Paragraph 8 : First for Women is a woman's magazine published by Bauer Media Group in the USA. The magazine was started in 1989. It is based in Englewood Cliffs, New Jersey. In 2011 the circulation of the magazine was 1,310,696 copies.
Title 9 : Freeway Complex Fire
Paragraph 9 : The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California. The fire started as two separate fires on November 15, 2008. The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later. These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.
Title 10 : William Rast
Paragraph 10 : William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala. It is most known for their premium jeans. On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line. The label also produces other clothing items such as jackets and tops. The company started first as a denim line, later evolving into a men’s and women’s clothing line.

Question: Which magazine was started first Arthur's Magazine or First for Women?
Answer: Arthur's Magazine
--------------------------------------------------
Batch 2:
Context: Title 1 : Ritz-Carlton Jakarta
Paragraph 1 : The Ritz-Carlton Jakarta is a hotel and skyscraper in Jakarta, Indonesia and 14th Tallest building in Jakarta. It is located in city center of Jakarta, near Mega Kuningan, adjacent to the sister JW Marriott Hotel. It is operated by The Ritz-Carlton Hotel Company. The complex has two towers that comprises a hotel and the Airlangga Apartment respectively. The hotel was opened in 2005.
Title 2 : Oberoi family
Paragraph 2 : The Oberoi family is an Indian family that is famous for its involvement in hotels, namely through The Oberoi Group.
Title 3 : Ishqbaaaz
Paragraph 3 : Ishqbaaaz (English: "Lovers") is an Indian drama television series which is broadcast on Star Plus. It premiered on 27 June 2016 and airs Mon-Fri 10-11pm IST.Nakuul Mehta, Kunal Jaisingh and Leenesh Mattoo respectively portray Shivaay, Omkara and Rudra, the three heirs of the Oberoi family. The show initially focused on the tale of three brothers, later become centered on the love story of Shivaay and Annika (Surbhi Chandna); with the story of Omkara and Rudra being shifted to the spinoff series "Dil Boley Oberoi". In July 2017 "Dil Boley Oberoi" ended and the storylines were merged back into "Ishqbaaaz" which doubled its runtime.
Title 4 : Hotel Tallcorn
Paragraph 4 : The Hotel Tallcorn is located in Marshalltown, Iowa. Today it is called the Tallcorn Towers Apartments. Built in 1928 by the Eppley Hotel Company, local citizens contributed $120,000 to ensure the successful completion of this seven-story hotel. It was completed in connection to the seventy-fifth anniversary of Marshalltown. The hotel's sale in 1956 from the Eppley chain to the Sheraton Corporation was part of the second largest hotel sale in United States history. The Tallcorn was listed as a contributing property in the Marshalltown Downtown Historic District on the National Register of Historic Places in 2002.
Title 5 : Mohan Singh Oberoi
Paragraph 5 : Rai Bahadur Mohan Singh Oberoi (15 August 1898 – 3 May 2002) was an Indian hotelier, the founder and chairman of Oberoi Hotels & Resorts, India's second-largest hotel company, with 35 hotels in India, Sri Lanka, Nepal, Egypt, Australia and Hungary.
Title 6 : Hotel Bond
Paragraph 6 : Hotel Bond is a historic hotel, built in two stages in 1913 and 1921, in downtown Hartford, Connecticut by hotelier Harry S. Bond. It is located near Bushnell Park, and was considered the grandest hotel in Hartford during its heyday. The second section is a 12 story building attached to the 6 story first section. A Statler Hotel opened in the area in 1954, creating competition, and the Bond Hotel company declared bankruptcy shortly after that. It was bought by the California-based Masaglia Hotel chain, which began an incremental renovation program. In 1964 it was sold to a Cincinnati, Ohio investment group which announced extensive renovation plans. However, the financing plans fell through and the hotel was again in bankruptcy. The building was sold at auction to the Roman Catholic Archdiocese of Hartford in 1965, and it became the home of the Saint Francis Hospital School of Nursing. The Bond Ballroom reopened in 2001, with the rest of the building becoming a Homewood Suites by Hilton in 2006.
Title 7 : The Oberoi Group
Paragraph 7 : The Oberoi Group is a hotel company with its head office in Delhi. Founded in 1934, the company owns and/or operates 30+ luxury hotels and two river cruise ships in six countries, primarily under its Oberoi Hotels & Resorts and Trident Hotels brands.
Title 8 : Future Fibre Technologies
Paragraph 8 : Future Fibre Technologies (FFT) is a fiber optic sensing technologies company based in Melbourne, Australia, with its US head office in Mountain View, California, Middle East head office in Dubai, Indian head office in New Delhi and European head office in London. Founded in 1994, Future Fibre Technologies product line provides optical fiber intrusion detection systems for perimeters, buried oil and gas pipelines and data communication networks.
Title 9 : 289th Military Police Company
Paragraph 9 : The 289th Military Police Company was activated on 1 November 1994 and attached to Hotel Company, 3rd Infantry (The Old Guard), Fort Myer, Virginia. Hotel Company is the regiment's specialty company.
Title 10 : Glennwanis Hotel
Paragraph 10 : The Glennwanis Hotel is a historic hotel in Glennville, Georgia, Tattnall County, Georgia, built on the site of the Hughes Hotel. The hotel is located at 209-215 East Barnard Street. The old Hughes Hotel was built out of Georgia pine circa 1905 and burned in 1920. The Glennwanis was built in brick in 1926. The local Kiwanis club led the effort to get the replacement hotel built, and organized a Glennville Hotel Company with directors being local business leaders. The wife of a local doctor won a naming contest with the name "Glennwanis Hotel", a suggestion combining "Glennville" and "Kiwanis".

Question: The Oberoi family is part of a hotel company that has a head office in what city?
Answer: Delhi
--------------------------------------------------
Batch 3:
Context: Title 1 : Lisa Simpson
Paragraph 1 : Lisa Marie Simpson is a fictional character in the animated television series "The Simpsons". She is the middle child and most intelligent of the Simpson family. Voiced by Yeardley Smith, Lisa first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed her while waiting to meet James L. Brooks. Groening had been invited to pitch a series of shorts based on his comic "Life in Hell", but instead decided to create a new set of characters. He named the elder Simpson daughter after his younger sister Lisa Groening. After appearing on "The Tracey Ullman Show" for three years, the Simpson family were moved to their own series on Fox, which debuted on December 17, 1989.
Title 2 : Marge Simpson
Paragraph 2 : Marjorie Jacqueline "Marge" Simpson (née Bouvier) is a fictional character in the American animated sitcom "The Simpsons" and part of the eponymous family. She is voiced by Julie Kavner and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Marge was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on "Life in Hell" but instead decided to create a new set of characters. He named the character after his mother Margaret Groening. After appearing on "The Tracey Ullman Show" for three seasons, the Simpson family received their own series on Fox, which debuted December 17, 1989.
Title 3 : Bart Simpson
Paragraph 3 : Bartholomew JoJo "Bart" Simpson is a fictional character in the American animated television series "The Simpsons" and part of the Simpson family. He is voiced by Nancy Cartwright and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed Bart while waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip, "Life in Hell", but instead decided to create a new set of characters. While the rest of the characters were named after Groening's family members, Bart's name is an anagram of the word "brat". After appearing on "The Tracey Ullman Show" for three years, the Simpson family received its own series on Fox, which debuted December 17, 1989.
Title 4 : Allie Goertz
Paragraph 4 : Allison Beth "Allie" Goertz (born March 2, 1991) is an American musician. Goertz is known for her satirical songs based on various pop culture topics. Her videos are posted on YouTube under the name of Cossbysweater. Subjects of her songs have included the film "The Room", the character Milhouse from the television show "The Simpsons", and the game Dungeons & Dragons. Her style has been compared to that of Bo Burnham. In December 2015, Goertz released a concept album based on the Adult Swim series "Rick and Morty", "Sad Dance Songs", with the album's cover emulating the animation and logo of the series. The album was made possible through Kickstarter. She is co-host of Everything's Coming Up Podcast, a Simpsons-focused podcast along with Julia Prescott.
Title 5 : Milhouse Van Houten
Paragraph 5 : Milhouse Mussolini van Houten is a fictional character featured in the animated television series "The Simpsons", voiced by Pamela Hayden, and created by Matt Groening who named the character after President Richard Nixon's middle name. Later in the series, it is revealed that Milhouse's middle name is "Mussolini."
Title 6 : Los Angeles Reader
Paragraph 6 : Los Angeles Reader was a weekly paper established in 1978 and distributed in Los Angeles, United States. It followed the format of the (still active) Chicago Reader. The paper was known for having lengthy, thoughtful reviews of movies, plays and concerts in the LA area. James Vowell was its founding editor. Among its writers were Keith Fitzgerald, Nigey Lennon, Lionel Rolfe, Lawrence Wechsler, Mick Farren, Richard Meltzer, Heidi Dvorak, Chris Morris, Jerry Stahl, Steven Kane, Andy Klein, Allen Levy, Jim Goad, Kirk Silsbee, Henry Sheehan, Samantha Dunn, Natalie Nichols, Steve Appleford, Eric Mankin (also editor), Paul Birchall, Eddie Rivera (who wrote the paper's first cover story), Amy Steinberg, Harry Sheehan, Dan Sallit, Myron Meisel, David Ehrenstein. Tom Davis, Bruce Bebb, Stuart Goldman, Ernest Hardy, Kevin Uhrich, Erik Himmelsbach and David L. Ulin. It is famous for being the first newspaper to publish Matt Groening's cartoon strip, Life in Hell on April 25, 1980. James Vowell hired Matt Groening as his assistant editor in 1979. Groening was also originally a Reader music critic. It also ran a cartoon strip by David Lynch (director of Blue Velvet) called The Angriest Dog in the World, a strip notable for having exactly the same drawing panels for its entire run. James Vowell and his wife Codette Wallace bought the Reader from the Chicago Reader in February 1989. They sold "The Reader" to New Times Media in 1996, which merged it with the "Los Angeles View" to form "New Times LA".
Title 7 : Homer Simpson
Paragraph 7 : Homer Jay Simpson is a fictional character and the main protagonist of the American animated television series "The Simpsons" as the patriarch of the eponymous family. He is voiced by Dan Castellaneta and first appeared on television, along with the rest of his family, in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Homer was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip "Life in Hell" but instead decided to create a new set of characters. He named the character after his father, Homer Groening. After appearing for three seasons on "The Tracey Ullman Show", the Simpson family got their own series on Fox that debuted December 17, 1989.
Title 8 : List of The Simpsons video games
Paragraph 8 : "The Simpsons" is an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company. The series is a satirical parody of a middle class American lifestyle epitomized by its eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. It is set in the fictional town of Springfield, and lampoons American culture, society and television, and many aspects of the human condition. The family was conceived by Groening shortly before a pitch for a series of animated shorts with producer James L. Brooks. Groening created a dysfunctional family and named the characters after members of his own family, substituting Bart for his own name. The shorts became a part of "The Tracey Ullman Show" on April 19, 1987 and after a three-season run, the sketch was developed into a half-hour prime time show and became a hit series for Fox. The growing popularity of the series motivated video game developers to create video games based on the series. Two pinball machines have also been produced; one self-titled, that was only made available for a limited time after the first season finale (1990) and "The Simpsons Pinball Party" (2003). Additionally, several handheld device games have been released, such as "Bartman: Avenger of Evil" (1990) and "Bart Simpson's Cupcake Crisis" (1991).
Title 9 : The Simpsons: An Uncensored, Unauthorized History
Paragraph 9 : The Simpsons: An Uncensored, Unauthorized History is a non-fiction book about the American animated television series "The Simpsons". It was written by John Ortved, and first published in October 2009 by Faber and Faber. In the United Kingdom, the book is called Simpsons Confidential: The uncensored, totally unauthorised history of the world's greatest TV show by the people that made it. The book is an oral history of the show, and concentrates particularly on the writers and producers of the show. The book includes entire chapters devoted to key figures such as creator Matt Groening and James L. Brooks and Sam Simon, who helped develop the series. According to National Public Radio reviewer Linda Holmes, "Ortved's thesis, essentially, is that lots of people are responsible for the success of "The Simpsons", and their creator, Matt Groening, has too often been viewed as the sole source to the detriment of others who also deserve to be praised."
Title 10 : List of The Simpsons guest stars
Paragraph 10 : In addition to the show's regular cast of voice actors, celebrity guest stars have been a staple of "The Simpsons", an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company, since its first season. "The Simpsons" focuses on the eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. The family was initially conceived by Groening for a series of animated shorts, which originally aired as a part of "The Tracey Ullman Show" between 1987 and 1989. The shorts were developed into a half-hour prime time series which began in December 1989. The series' 27th season began in September 2015 and episodes of "The Simpsons" have aired. A feature film adaptation of the series called "The Simpsons Movie", was released in 2007.

Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
Answer: President Richard Nixon

In [59]:
del train_hotpot_qa_json
del test_hotpot_qa_json

## 2. Getting Triples from Context and Question

In [60]:
from dotenv import load_dotenv
import os

load_dotenv()
openai_api_key = os.getenv("OPENAI_API_KEY")

In [61]:
from langchain_openai import ChatOpenAI
from langchain_core.globals import set_debug, set_verbose, set_llm_cache
from langchain_community.cache import InMemoryCache
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

set_debug(False)
set_verbose(False)
set_llm_cache(InMemoryCache())

llm_model = ChatOpenAI(model=LLM_MODEL, api_key=openai_api_key)

In [62]:
system_msg = """
<role>
    You are an expert in natural language understanding and knowledge graph construction. Your task is to extract structured relationship triples from a context set (Titles and Paragraphs) and to convert a provided question into a set of question triples, using simple variable names (such as x, y, z, i, j, k) for unknown entities or values to be inferred.
</role>

<behavior>
    <rule name="Entity Extraction">
        Identify and extract unique entities from Titles and Paragraphs. Use canonical names.
    </rule>
    <rule name="Relationship Extraction">
        Extract explicit or clear implicit relationships between entities as (subject, relation, object) triples.
    </rule>
    <rule name="Temporal and Comparative Relations">
        Use relations like "started in", "founded by", "wrote a song about", "is named after", etc., matching the logic and semantics in the context or question.
    </rule>
    <rule name="Do Not Use Question for Context Triples">
        When extracting triples from the context, **do not consider the question or its requirements**. Extract all possible triples from the context, regardless of the question.
    </rule>
    <rule name="Variable Placeholders for Unknowns">
        For each unknown or answer to be found in the question, use a simple English variable (x, y, z, i, j, k, etc.) in place of the answer within the triples. Each distinct unknown in the question gets a unique variable.
    </rule>
    <rule name="Question Triple Decomposition">
        For each question, decompose it into one or more triples, using variable placeholders for any unknowns to be inferred from the context.
        Examples:
        - "Which magazine was started first Arthur's Magazine or First for Women?"
           (Arthur's Magazine, started in, x)
           (First for Women, started in, y)
        - "The Oberoi family is part of a hotel company that has a head office in what city?"
           (Oberoi family, is part of, x)
           (x, has head office in, y)
    </rule>
    <rule name="Formatting and Output">
        Output must contain four sections, in order:
        1. ### CONTEXT_REASONING — a step-by-step reasoning of how context triples were extracted
        2. ### CONTEXT_TRIPLES — list all extracted context triples, each on its own line
        3. ### QUESTION_REASONING — a step-by-step reasoning of how the question was decomposed into question triples
        4. ### QUESTIONS_TRIPLES — list the question triples, each on its own line
        Do not add explanations, numbering, or extra text.
    </rule>
</behavior>

<format>
1. Carefully read the <context> section.
2. Before extracting triples, explain step by step how you identify and select the entities and relationships in the context. Print this heading:
   ### CONTEXT_REASONING
   Then write your reasoning in clear, concise steps. Extract as many triples as you can from the context. **Do not focus on the question yet.**
3. After reasoning, extract and print context triples. Print this heading:
   ### CONTEXT_TRIPLES
   List each context triple on a new line. Extract as many triples as you can from the context. **Do not focus on the question yet.**
4. Carefully read the <question> section.
5. Before extracting question triples, explain step by step how you break down the question and assign variable placeholders. Print this heading:
   ### QUESTION_REASONING
   Then write your reasoning in clear, concise steps.
6. After reasoning, print the question triples. Print this heading:
   ### QUESTIONS_TRIPLES
   List each question triple on a new line, using variable placeholders (x, y, z, etc.) for unknowns.
7. After the last question triple, end with no extra text or parentheses.
</format>
"""

human_msg = """
<context>
{context}
</context>

<question>
{question}
</question>
"""

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [63]:
chain = prompt | llm_model | StrOutputParser()

In [64]:
batch_input_list = []
main_df = pd.DataFrame()

for i in range(len(batch_context)):
    batch_num_list = [i] * len(batch_context[i])
    question_num_list = list(range(1, len(batch_context[i]) + 1))
    context_list = []
    question_list = []
    answers_list = []

    batch_input_item = []
    j = 0
    for batch in range(len(batch_context[i])):
        context = batch_context[i][batch]
        batch_input_item.append({
            "context": context,
            "question": batch_question[i][j],
        })
        context_list.append(context)
        question_list.append(batch_question[i][j])
        answers_list.append(batch_answer[i][j])
        j += 1
    batch_input_list.append(batch_input_item)
    df = pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "context": context_list,
        "question": question_list,
        "answer": answers_list
    })
    main_df = pd.concat([main_df, df], ignore_index=True)

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1}:")
    for item in batch:
        print("Context:", item['context'])
        print("Question:", item['question'])
        print("-" * 50)

Batch 1:
Context: Title 1 : Radio City (Indian radio station)
Paragraph 1 : Radio City is India's first private FM radio station and was started on 3 July 2001. It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003). It plays Hindi, English and regional songs. It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007. Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features. The Radio station currently plays a mix of Hindi and Regional music. Abraham Thomas is the CEO of the company.
Title 2 : History of Albanian football
Paragraph 2 : Football in Albania existed before the Albanian Football Federation (FSHF) was created. This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) . Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946. In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.
Title 3 : Echosmith
Paragraph 3 : Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California. Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016. Echosmith started first as "Ready Set Go!" until they signed to Warner Bros. Records in May 2012. They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia. The song was Warner Bros. Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold. The band's debut album, "Talking Dreams", was released on October 8, 2013.
Title 4 : Women's colleges in the Southern United States
Paragraph 4 : Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States. Many started first as girls' seminaries or academies. Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women. Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.
Title 5 : First Arthur County Courthouse and Jail
Paragraph 5 : The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.
Title 6 : Arthur's Magazine
Paragraph 6 : Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century. Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others. In May 1846 it was merged into "Godey's Lady's Book".
Title 7 : 2014–15 Ukrainian Hockey Championship
Paragraph 7 : The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship. Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues. Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014. The regular season included just 12 rounds, where all the teams went to the semifinals. In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.
Title 8 : First for Women
Paragraph 8 : First for Women is a woman's magazine published by Bauer Media Group in the USA. The magazine was started in 1989. It is based in Englewood Cliffs, New Jersey. In 2011 the circulation of the magazine was 1,310,696 copies.
Title 9 : Freeway Complex Fire
Paragraph 9 : The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California. The fire started as two separate fires on November 15, 2008. The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later. These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.
Title 10 : William Rast
Paragraph 10 : William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala. It is most known for their premium jeans. On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line. The label also produces other clothing items such as jackets and tops. The company started first as a denim line, later evolving into a men’s and women’s clothing line.

Question: Which magazine was started first Arthur's Magazine or First for Women?
--------------------------------------------------
Context: Title 1 : Ritz-Carlton Jakarta
Paragraph 1 : The Ritz-Carlton Jakarta is a hotel and skyscraper in Jakarta, Indonesia and 14th Tallest building in Jakarta. It is located in city center of Jakarta, near Mega Kuningan, adjacent to the sister JW Marriott Hotel. It is operated by The Ritz-Carlton Hotel Company. The complex has two towers that comprises a hotel and the Airlangga Apartment respectively. The hotel was opened in 2005.
Title 2 : Oberoi family
Paragraph 2 : The Oberoi family is an Indian family that is famous for its involvement in hotels, namely through The Oberoi Group.
Title 3 : Ishqbaaaz
Paragraph 3 : Ishqbaaaz (English: "Lovers") is an Indian drama television series which is broadcast on Star Plus. It premiered on 27 June 2016 and airs Mon-Fri 10-11pm IST.Nakuul Mehta, Kunal Jaisingh and Leenesh Mattoo respectively portray Shivaay, Omkara and Rudra, the three heirs of the Oberoi family. The show initially focused on the tale of three brothers, later become centered on the love story of Shivaay and Annika (Surbhi Chandna); with the story of Omkara and Rudra being shifted to the spinoff series "Dil Boley Oberoi". In July 2017 "Dil Boley Oberoi" ended and the storylines were merged back into "Ishqbaaaz" which doubled its runtime.
Title 4 : Hotel Tallcorn
Paragraph 4 : The Hotel Tallcorn is located in Marshalltown, Iowa. Today it is called the Tallcorn Towers Apartments. Built in 1928 by the Eppley Hotel Company, local citizens contributed $120,000 to ensure the successful completion of this seven-story hotel. It was completed in connection to the seventy-fifth anniversary of Marshalltown. The hotel's sale in 1956 from the Eppley chain to the Sheraton Corporation was part of the second largest hotel sale in United States history. The Tallcorn was listed as a contributing property in the Marshalltown Downtown Historic District on the National Register of Historic Places in 2002.
Title 5 : Mohan Singh Oberoi
Paragraph 5 : Rai Bahadur Mohan Singh Oberoi (15 August 1898 – 3 May 2002) was an Indian hotelier, the founder and chairman of Oberoi Hotels & Resorts, India's second-largest hotel company, with 35 hotels in India, Sri Lanka, Nepal, Egypt, Australia and Hungary.
Title 6 : Hotel Bond
Paragraph 6 : Hotel Bond is a historic hotel, built in two stages in 1913 and 1921, in downtown Hartford, Connecticut by hotelier Harry S. Bond. It is located near Bushnell Park, and was considered the grandest hotel in Hartford during its heyday. The second section is a 12 story building attached to the 6 story first section. A Statler Hotel opened in the area in 1954, creating competition, and the Bond Hotel company declared bankruptcy shortly after that. It was bought by the California-based Masaglia Hotel chain, which began an incremental renovation program. In 1964 it was sold to a Cincinnati, Ohio investment group which announced extensive renovation plans. However, the financing plans fell through and the hotel was again in bankruptcy. The building was sold at auction to the Roman Catholic Archdiocese of Hartford in 1965, and it became the home of the Saint Francis Hospital School of Nursing. The Bond Ballroom reopened in 2001, with the rest of the building becoming a Homewood Suites by Hilton in 2006.
Title 7 : The Oberoi Group
Paragraph 7 : The Oberoi Group is a hotel company with its head office in Delhi. Founded in 1934, the company owns and/or operates 30+ luxury hotels and two river cruise ships in six countries, primarily under its Oberoi Hotels & Resorts and Trident Hotels brands.
Title 8 : Future Fibre Technologies
Paragraph 8 : Future Fibre Technologies (FFT) is a fiber optic sensing technologies company based in Melbourne, Australia, with its US head office in Mountain View, California, Middle East head office in Dubai, Indian head office in New Delhi and European head office in London. Founded in 1994, Future Fibre Technologies product line provides optical fiber intrusion detection systems for perimeters, buried oil and gas pipelines and data communication networks.
Title 9 : 289th Military Police Company
Paragraph 9 : The 289th Military Police Company was activated on 1 November 1994 and attached to Hotel Company, 3rd Infantry (The Old Guard), Fort Myer, Virginia. Hotel Company is the regiment's specialty company.
Title 10 : Glennwanis Hotel
Paragraph 10 : The Glennwanis Hotel is a historic hotel in Glennville, Georgia, Tattnall County, Georgia, built on the site of the Hughes Hotel. The hotel is located at 209-215 East Barnard Street. The old Hughes Hotel was built out of Georgia pine circa 1905 and burned in 1920. The Glennwanis was built in brick in 1926. The local Kiwanis club led the effort to get the replacement hotel built, and organized a Glennville Hotel Company with directors being local business leaders. The wife of a local doctor won a naming contest with the name "Glennwanis Hotel", a suggestion combining "Glennville" and "Kiwanis".

Question: The Oberoi family is part of a hotel company that has a head office in what city?
--------------------------------------------------
Context: Title 1 : Lisa Simpson
Paragraph 1 : Lisa Marie Simpson is a fictional character in the animated television series "The Simpsons". She is the middle child and most intelligent of the Simpson family. Voiced by Yeardley Smith, Lisa first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed her while waiting to meet James L. Brooks. Groening had been invited to pitch a series of shorts based on his comic "Life in Hell", but instead decided to create a new set of characters. He named the elder Simpson daughter after his younger sister Lisa Groening. After appearing on "The Tracey Ullman Show" for three years, the Simpson family were moved to their own series on Fox, which debuted on December 17, 1989.
Title 2 : Marge Simpson
Paragraph 2 : Marjorie Jacqueline "Marge" Simpson (née Bouvier) is a fictional character in the American animated sitcom "The Simpsons" and part of the eponymous family. She is voiced by Julie Kavner and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Marge was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on "Life in Hell" but instead decided to create a new set of characters. He named the character after his mother Margaret Groening. After appearing on "The Tracey Ullman Show" for three seasons, the Simpson family received their own series on Fox, which debuted December 17, 1989.
Title 3 : Bart Simpson
Paragraph 3 : Bartholomew JoJo "Bart" Simpson is a fictional character in the American animated television series "The Simpsons" and part of the Simpson family. He is voiced by Nancy Cartwright and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed Bart while waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip, "Life in Hell", but instead decided to create a new set of characters. While the rest of the characters were named after Groening's family members, Bart's name is an anagram of the word "brat". After appearing on "The Tracey Ullman Show" for three years, the Simpson family received its own series on Fox, which debuted December 17, 1989.
Title 4 : Allie Goertz
Paragraph 4 : Allison Beth "Allie" Goertz (born March 2, 1991) is an American musician. Goertz is known for her satirical songs based on various pop culture topics. Her videos are posted on YouTube under the name of Cossbysweater. Subjects of her songs have included the film "The Room", the character Milhouse from the television show "The Simpsons", and the game Dungeons & Dragons. Her style has been compared to that of Bo Burnham. In December 2015, Goertz released a concept album based on the Adult Swim series "Rick and Morty", "Sad Dance Songs", with the album's cover emulating the animation and logo of the series. The album was made possible through Kickstarter. She is co-host of Everything's Coming Up Podcast, a Simpsons-focused podcast along with Julia Prescott.
Title 5 : Milhouse Van Houten
Paragraph 5 : Milhouse Mussolini van Houten is a fictional character featured in the animated television series "The Simpsons", voiced by Pamela Hayden, and created by Matt Groening who named the character after President Richard Nixon's middle name. Later in the series, it is revealed that Milhouse's middle name is "Mussolini."
Title 6 : Los Angeles Reader
Paragraph 6 : Los Angeles Reader was a weekly paper established in 1978 and distributed in Los Angeles, United States. It followed the format of the (still active) Chicago Reader. The paper was known for having lengthy, thoughtful reviews of movies, plays and concerts in the LA area. James Vowell was its founding editor. Among its writers were Keith Fitzgerald, Nigey Lennon, Lionel Rolfe, Lawrence Wechsler, Mick Farren, Richard Meltzer, Heidi Dvorak, Chris Morris, Jerry Stahl, Steven Kane, Andy Klein, Allen Levy, Jim Goad, Kirk Silsbee, Henry Sheehan, Samantha Dunn, Natalie Nichols, Steve Appleford, Eric Mankin (also editor), Paul Birchall, Eddie Rivera (who wrote the paper's first cover story), Amy Steinberg, Harry Sheehan, Dan Sallit, Myron Meisel, David Ehrenstein. Tom Davis, Bruce Bebb, Stuart Goldman, Ernest Hardy, Kevin Uhrich, Erik Himmelsbach and David L. Ulin. It is famous for being the first newspaper to publish Matt Groening's cartoon strip, Life in Hell on April 25, 1980. James Vowell hired Matt Groening as his assistant editor in 1979. Groening was also originally a Reader music critic. It also ran a cartoon strip by David Lynch (director of Blue Velvet) called The Angriest Dog in the World, a strip notable for having exactly the same drawing panels for its entire run. James Vowell and his wife Codette Wallace bought the Reader from the Chicago Reader in February 1989. They sold "The Reader" to New Times Media in 1996, which merged it with the "Los Angeles View" to form "New Times LA".
Title 7 : Homer Simpson
Paragraph 7 : Homer Jay Simpson is a fictional character and the main protagonist of the American animated television series "The Simpsons" as the patriarch of the eponymous family. He is voiced by Dan Castellaneta and first appeared on television, along with the rest of his family, in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Homer was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip "Life in Hell" but instead decided to create a new set of characters. He named the character after his father, Homer Groening. After appearing for three seasons on "The Tracey Ullman Show", the Simpson family got their own series on Fox that debuted December 17, 1989.
Title 8 : List of The Simpsons video games
Paragraph 8 : "The Simpsons" is an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company. The series is a satirical parody of a middle class American lifestyle epitomized by its eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. It is set in the fictional town of Springfield, and lampoons American culture, society and television, and many aspects of the human condition. The family was conceived by Groening shortly before a pitch for a series of animated shorts with producer James L. Brooks. Groening created a dysfunctional family and named the characters after members of his own family, substituting Bart for his own name. The shorts became a part of "The Tracey Ullman Show" on April 19, 1987 and after a three-season run, the sketch was developed into a half-hour prime time show and became a hit series for Fox. The growing popularity of the series motivated video game developers to create video games based on the series. Two pinball machines have also been produced; one self-titled, that was only made available for a limited time after the first season finale (1990) and "The Simpsons Pinball Party" (2003). Additionally, several handheld device games have been released, such as "Bartman: Avenger of Evil" (1990) and "Bart Simpson's Cupcake Crisis" (1991).
Title 9 : The Simpsons: An Uncensored, Unauthorized History
Paragraph 9 : The Simpsons: An Uncensored, Unauthorized History is a non-fiction book about the American animated television series "The Simpsons". It was written by John Ortved, and first published in October 2009 by Faber and Faber. In the United Kingdom, the book is called Simpsons Confidential: The uncensored, totally unauthorised history of the world's greatest TV show by the people that made it. The book is an oral history of the show, and concentrates particularly on the writers and producers of the show. The book includes entire chapters devoted to key figures such as creator Matt Groening and James L. Brooks and Sam Simon, who helped develop the series. According to National Public Radio reviewer Linda Holmes, "Ortved's thesis, essentially, is that lots of people are responsible for the success of "The Simpsons", and their creator, Matt Groening, has too often been viewed as the sole source to the detriment of others who also deserve to be praised."
Title 10 : List of The Simpsons guest stars
Paragraph 10 : In addition to the show's regular cast of voice actors, celebrity guest stars have been a staple of "The Simpsons", an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company, since its first season. "The Simpsons" focuses on the eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. The family was initially conceived by Groening for a series of animated shorts, which originally aired as a part of "The Tracey Ullman Show" between 1987 and 1989. The shorts were developed into a half-hour prime time series which began in December 1989. The series' 27th season began in September 2015 and episodes of "The Simpsons" have aired. A feature film adaptation of the series called "The Simpsons Movie", was released in 2007.

Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
--------------------------------------------------
Context: Title 1 : Moloch: or, This Gentile World

In [65]:
main_df

,batch_num,question_num,context,question,answer
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long

In [16]:
graphs_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    graphs_str_list = chain.batch(batch)
    graphs_str_batch.append(graphs_str_list)

Batch 1 ... processing 10 items

In [17]:
for i, graphs_str_list in enumerate(graphs_str_batch):
    print(f"Batch {i + 1} ... processed {len(graphs_str_list)} items")
    for j, graph_str in enumerate(graphs_str_list):
        print(f"Item {j + 1}:")
        print(graph_str)
        print("-" * 50)

Batch 1 ... processed 10 items
Item 1:
### CONTEXT_REASONING
I begin by reading each title and paragraph, identifying key entities such as organizations, people, songs, places, dates, and relationships like "founded by," "started in," "played," "merged into," etc. For each magazine mentioned, like "Arthur's Magazine" and "First for Women," I look for relevant facts: who started them, when, where, and other notable events. For other contexts, I extract relationships such as "played in," "started as," "published in," "founded by," "merged into," "defeated," etc. I ensure all unique entities are covered and explicit and clear implicit relationships are captured in triple format, always focusing only on the context regardless of the question.

### CONTEXT_TRIPLES
(Radio City, is, India's first private FM radio station)
(Radio City, was started on, 3 July 2001)
(Radio City, broadcasts on, 91.1 megahertz)
(Radio City, earlier broadcasted on, 91.0 megahertz)
(Radio City, broadcasts from, Mumbai)
(Radio City, started in Mumbai, 2004)
(Radio City, started in Bengaluru, 2001)
(Radio City, broadcasts from, Lucknow)
(Radio City, broadcasts from, New Delhi)
(Radio City, started in New Delhi, 2003)
(Radio City, plays, Hindi songs)
(Radio City, plays, English songs)
(Radio City, plays, regional songs)
(Radio City, launched in Hyderabad, March 2006)
(Radio City, launched in Chennai, 7 July 2006)
(Radio City, launched in Visakhapatnam, October 2007)
(Radio City, launched music portal, PlanetRadiocity.com)
(PlanetRadiocity.com, offers, music news)
(PlanetRadiocity.com, offers, videos)
(PlanetRadiocity.com, offers, songs)
(PlanetRadiocity.com, offers, music-related features)
(Radio City, started New Media foray, May 2008)
(Radio City, CEO, Abraham Thomas)
(Football in Albania, existed before, Albanian Football Federation)
(Albanian team, registered at, Balkan Cup tournament)
(Balkan Cup tournament, started in, 1929)
(Albanian National Team, founded on, June 6, 1930)
(Albania, joined, FIFA)
(Albania, joined FIFA in, 1932)
(Albania, founding member of, UEFA)
(Albania, founding member of UEFA in, 1954)
(Albania, played first international match in, 1946)
(Albania, defeated, Yugoslavia)
(Echosmith, is, indie pop band)
(Echosmith, formed in, February 2009)
(Echosmith, formed in, Chino, California)
(Echosmith, originally formed as, quartet of siblings)
(Echosmith, current members, Sydney Sierota)
(Echosmith, current members, Noah Sierota)
(Echosmith, current members, Graham Sierota)
(Jamie Sierota, departed in, late 2016)
(Echosmith, started as, Ready Set Go!)
(Echosmith, signed to, Warner Bros. Records)
(Echosmith, signed to Warner Bros. Records, May 2012)
(Echosmith, best known for, "Cool Kids")
("Cool Kids", reached number, 13 on Billboard Hot 100)
("Cool Kids", certified double platinum by, RIAA)
("Cool Kids", sales in US, over 1,200,000)
("Cool Kids", certified double platinum by, ARIA in Australia)
("Cool Kids", fifth-biggest-selling-digital song of 2014 for Warner Bros. Records, true)
("Cool Kids", downloads sold, 1.3 million)
(Echosmith, debut album, "Talking Dreams")
("Talking Dreams", released on, October 8, 2013)
(Women's colleges in the Southern United States, refers to, undergraduate degree–granting institutions for women)
(Women's colleges in the Southern United States, often are, liberal arts colleges)
(Salem College, is, oldest female educational institution in the South)
(Wesleyan College, is, first established specifically as college for women)
(Mary Baldwin University, offers, coeducational graduate courses)
(Salem College, offers, coeducational graduate courses)
(First Arthur County Courthouse and Jail, was, perhaps the smallest court house in US)
(First Arthur County Courthouse and Jail, serves now as, museum)
(Arthur's Magazine, was, American literary periodical)
(Arthur's Magazine, published in, Philadelphia)
(Arthur's Magazine, published in, 19th century)
(Arthur's Magazine, edited by, T.S. Arthur)
(Arthur's Magazine, featured work by, Edgar A. Poe)
(Arthur's Magazine, featured work by, J.H. Ingraham)
(Arthur's Magazine, featured work by, Sarah Josepha Hale)
(Arthur's Magazine, featured work by, Thomas G. Spear)
(Arthur's Magazine, was published during, 1844–1846)
(Arthur's Magazine, was merged into, Godey's Lady's Book)
(Arthur's Magazine, merged into Godey's Lady's Book in, May 1846)
(2014–15 Ukrainian Hockey Championship, was, 23rd season of Ukrainian Hockey Championship)
(2014–15 Ukrainian Hockey Championship, had, four teams)
(Generals Kiev, only team participated previous season, true)
(2014–15 Ukrainian Hockey Championship, started after, year-end 2014)
(2014–15 Ukrainian Hockey Championship, regular season included, 12 rounds)
(2014–15 Ukrainian Hockey Championship, all teams went to, semifinals)
(ATEK Kiev, defeated, HK Kremenchuk in final)
(First for Women, is, woman's magazine)
(First for Women, published by, Bauer Media Group)
(First for Women, published in, USA)
(First for Women, started in, 1989)
(First for Women, based in, Englewood Cliffs, New Jersey)
(First for Women, circulation in 2011, 1,310,696)
(Freeway Complex Fire, was, 2008 wildfire)
(Freeway Complex Fire, occurred in, Santa Ana Canyon area)
(Freeway Complex Fire, occurred in, Orange County, California)
(Freeway Complex Fire, started on, November 15, 2008)
(Freeway Fire, started first, shortly after 9am)
(Landfill Fire, ignited, approximately 2 hours after Freeway Fire)
(Freeway Fire, merged with, Landfill Fire)
(Fire, destroyed, 314 residences in Anaheim Hills)
(Fire, destroyed, 314 residences in Yorba Linda)
(William Rast, is, American clothing line)
(William Rast, founded by, Justin Timberlake)
(William Rast, founded by, Trace Ayala)
(William Rast, is most known for, premium jeans)
(Justin Timberlake and Trace Ayala, held first fashion show for William Rast, October 17, 2006)
(William Rast, produces, jackets)
(William Rast, produces, tops)
(William Rast, started as, denim line)
(William Rast, evolved into, men’s and women’s clothing line)

### QUESTION_REASONING
The question asks which magazine was started first between "Arthur's Magazine" and "First for Women". The unknowns are the starting dates of both magazines. I need to represent:
- (Arthur's Magazine, was started on, x)
- (First for Women, was started on, y)
These will allow comparison to see which one was started first.

### QUESTIONS_TRIPLES
(Arthur's Magazine, was started on, x)
(First for Women, was started on, y)
--------------------------------------------------
Item 2:
### CONTEXT_REASONING
I first identify unique entities: "Ritz-Carlton Jakarta", "Jakarta", "Indonesia", "Mega Kuningan", "JW Marriott Hotel", "The Ritz-Carlton Hotel Company", "Airlangga Apartment", "Oberoi family", "The Oberoi Group", "Ishqbaaaz", "Star Plus", "Nakuul Mehta", "Kunal Jaisingh", "Leenesh Mattoo", "Shivaay", "Omkara", "Rudra", "Annika", "Surbhi Chandna", "Dil Boley Oberoi", "Hotel Tallcorn", "Marshalltown", "Iowa", "Tallcorn Towers Apartments", "Eppley Hotel Company", "Sheraton Corporation", "Marshalltown Downtown Historic District", "National Register of Historic Places", "Mohan Singh Oberoi", "Oberoi Hotels & Resorts", "Sri Lanka", "Nepal", "Egypt", "Australia", "Hungary", "Hotel Bond", "Hartford", "Connecticut", "Harry S. Bond", "Bushnell Park", "Statler Hotel", "Masaglia Hotel", "Saint Francis Hospital School of Nursing", "Roman Catholic Archdiocese of Hartford", "Homewood Suites by Hilton", "Cincinnati", "Future Fibre Technologies", "Melbourne", "Mountain View", "Dubai", "New Delhi", "London", "Glennwanis Hotel", "Glennville", "Tattnall County", "Hughes Hotel", "East Barnard Street", "Georgia pine", "Glennville Hotel Company", "Kiwanis club", "Kiwanis".
From the context, I extract explicit relationships such as founding, location, operations, property status, changes in name or owner, broadcast facts, roles, and organizational structure.
I map "Oberoi family" to "The Oberoi Group" through "is famous for its involvement in hotels, namely through The Oberoi Group". "The Oberoi Group" is a hotel company with its head office in Delhi. "Mohan Singh Oberoi" is founder and chairman of "Oberoi Hotels & Resorts", which is stated as India's second-largest hotel company and closely tied to "The Oberoi Group". "Oberoi Hotels & Resorts" appears to be a brand operated by "The Oberoi Group". "The Oberoi Group" operates hotels under "Oberoi Hotels & Resorts" and "Trident Hotels".
I extract temporal, naming, and structural relations for other entities without considering the question yet.

### CONTEXT_TRIPLES
(Ritz-Carlton Jakarta, is a, hotel)
(Ritz-Carlton Jakarta, is a, skyscraper)
(Ritz-Carlton Jakarta, is in, Jakarta)
(Ritz-Carlton Jakarta, is in, Indonesia)
(Ritz-Carlton Jakarta, is the, 14th Tallest building in Jakarta)
(Ritz-Carlton Jakarta, is located in, city center of Jakarta)
(Ritz-Carlton Jakarta, is near, Mega Kuningan)
(Ritz-Carlton Jakarta, is adjacent to, JW Marriott Hotel)
(Ritz-Carlton Jakarta, is operated by, The Ritz-Carlton Hotel Company)
(Ritz-Carlton Jakarta, complex has, two towers)
(one tower, comprises, hotel)
(other tower, comprises, Airlangga Apartment)
(Ritz-Carlton Jakarta, was opened in, 2005)
(Oberoi family, is an, Indian family)
(Oberoi family, is famous for involvement in, hotels)
(Oberoi family, is involved in hotels through, The Oberoi Group)
(Ishqbaaaz, is a, Indian drama television series)
(Ishqbaaaz, is broadcast on, Star Plus)
(Ishqbaaaz, premiered on, 27 June 2016)
(Ishqbaaaz, airs, Mon-Fri 10-11pm IST)
(Nakuul Mehta, portrays, Shivaay)
(Kunal Jaisingh, portrays, Omkara)
(Leenesh Mattoo, portrays, Rudra)
(Shivaay, is a, heir of Oberoi family)
(Omkara, is a, heir of Oberoi family)
(Rudra, is a, heir of Oberoi family)
(Ishqbaaaz, initially focuses on, tale of three brothers)
(Ishqbaaaz, later focuses on, love story of Shivaay and Annika)
(Annika, is portrayed by, Surbhi Chandna)
(Story of Omkara and Rudra, is shifted to, Dil Boley Oberoi)
(Dil Boley Oberoi, ended in, July 2017)
(After July 2017, storylines of Dil Boley Oberoi and Ishqbaaaz, were merged)
(Ishqbaaaz, doubled its runtime)
(Hotel Tallcorn, is located in, Marshalltown)
(Marshalltown, is in, Iowa)
(Hotel Tallcorn, is now called, Tallcorn Towers Apartments)
(Hotel Tallcorn, was built in, 1928)
(Hotel Tallcorn, was built by, Eppley Hotel Company)
(Local citizens, contributed, $120,000)
(Local citizens' contribution, ensured, successful completion of Hotel Tallcorn)
(Hotel Tallcorn, is a, seven-story hotel)
(Hotel Tallcorn, was completed in connection with, 75th anniversary of Marshalltown)
(Hotel Tallcorn, was sold in 1956 from, Eppley Hotel Company)
(Hotel Tallcorn, was sold in 1956 to, Sheraton Corporation)
(Hotel Tallcorn sale to Sheraton Corporation, was part of, second largest hotel sale in United States history)
(Hotel Tallcorn, listed as contributing property in, Marshalltown Downtown Historic District)
(Marshalltown Downtown Historic District, is on, National Register of Historic Places)
(Hotel Tallcorn, listed on National Register of Historic Places in, 2002)
(Mohan Singh Oberoi, is a, Indian hotelier)
(Mohan Singh Oberoi, is founder of, Oberoi Hotels & Resorts)
(Mohan Singh Oberoi, is chairman of, Oberoi Hotels & Resorts)
(Oberoi Hotels & Resorts, is, India's second-largest hotel company)
(Oberoi Hotels & Resorts, has, 35 hotels)
(Oberoi Hotels & Resorts, has hotels in, India)
(Oberoi Hotels & Resorts, has hotels in, Sri Lanka)
(Oberoi Hotels & Resorts, has hotels in, Nepal)
(Oberoi Hotels & Resorts, has hotels in, Egypt)
(Oberoi Hotels & Resorts, has hotels in, Australia)
(Oberoi Hotels & Resorts, has hotels in, Hungary)
(The Oberoi Group, is a, hotel company)
(The Oberoi Group, has head office in, Delhi)
(The Oberoi Group, was founded in, 1934)
(The Oberoi Group, owns or operates, 30+ luxury hotels)
(The Oberoi Group, owns or operates, two river cruise ships)
(The Oberoi Group, operates in, six countries)
(The Oberoi Group, operates primarily under, Oberoi Hotels & Resorts)
(The Oberoi Group, operates primarily under, Trident Hotels)
(Future Fibre Technologies, is a, fiber optic sensing technologies company)
(Future Fibre Technologies, is based in, Melbourne)
(Future Fibre Technologies, US head office is in, Mountain View)
(Future Fibre Technologies, Middle East head office is in, Dubai)
(Future Fibre Technologies, Indian head office is in, New Delhi)
(Future Fibre Technologies, European head office is in, London)
(Future Fibre Technologies, was founded in, 1994)
(Future Fibre Technologies, provides, optical fiber intrusion detection systems)
(optical fiber intrusion detection systems, are for, perimeters)
(optical fiber intrusion detection systems, are for, buried oil and gas pipelines)
(optical fiber intrusion detection systems, are for, data communication networks)
(289th Military Police Company, was activated on, 1 November 1994)
(289th Military Police Company, was attached to, Hotel Company, 3rd Infantry)
(Hotel Company, is, regiment's specialty company)
(Hotel Bond, is a, historic hotel)
(Hotel Bond, was built in, two stages)
(Hotel Bond, first stage was built in, 1913)
(Hotel Bond, second stage was built in, 1921)
(Hotel Bond, is in, downtown Hartford)
(Hartford, is in, Connecticut)
(Hotel Bond, was built by, Harry S. Bond)
(Hotel Bond, is located near, Bushnell Park)
(Hotel Bond, was considered, grandest hotel in Hartford during its heyday)
(second section of Hotel Bond, is a, 12 story building)
(second section of Hotel Bond, is attached to, 6 story first section)
(Statler Hotel, opened in the area in, 1954)
(Statler Hotel, created competition for, Hotel Bond)
(Bond Hotel company, declared bankruptcy, after 1954)
(Hotel Bond, was bought by, Masaglia Hotel chain)
(Masaglia Hotel chain, is, California-based)
(Masaglia Hotel chain, began, incremental renovation program)
(Building, was sold in 1964 to, Cincinnati investment group)
(Cincinnati investment group, announced, extensive renovation plans)
(Financing plans, fell through)
(Hotel Bond, was again in, bankruptcy)
(Building, was sold at auction to, Roman Catholic Archdiocese of Hartford)
(Building, became home of, Saint Francis Hospital School of Nursing)
(Bond Ballroom, reopened in, 2001)
(rest of the building, became, Homewood Suites by Hilton in 2006)
(Glennwanis Hotel, is a, historic hotel)
(Glennwanis Hotel, is in, Glennville)
(Glennville, is in, Tattnall County, Georgia)
(Glennwanis Hotel, is built on site of, Hughes Hotel)
(Glennwanis Hotel, is located at, 209-215 East Barnard Street)
(Hughes Hotel, was built out of, Georgia pine)
(Hughes Hotel, was built circa, 1905)
(Hughes Hotel, burned in, 1920)
(Glennwanis Hotel, was built in, 1926)
(Kiwanis club, led, effort to get replacement hotel built)
(Kiwanis club, organized, Glennville Hotel Company)
(Glennville Hotel Company, had directors who were, local business leaders)
(wife of local doctor, won, naming contest)
(name "Glennwanis Hotel", suggested by, wife of local doctor)
(name "Glennwanis Hotel", combines, Glennville)
(name "Glennwanis Hotel", combines, Kiwanis)

### QUESTION_REASONING
The question asks for the city in which the head office of the hotel company that the Oberoi family is part of is located. From the context, the Oberoi family is involved in The Oberoi Group. The Oberoi Group is a hotel company. The Oberoi Group has its head office in Delhi. Thus, to formalize the question decomposition:
1. Identify the unknown hotel company that the Oberoi family is part of — assign variable x.
2. Identify the unknown city y where the head office of x is located.

### QUESTIONS_TRIPLES
(Oberoi family, is part of, x)
(x, has head office in, y)
--------------------------------------------------
Item 3:
### CONTEXT_REASONING
To extract context triples, I first identify all unique entities mentioned, such as "Lisa Simpson", "The Simpsons", "Matt Groening", "James L. Brooks", "Life in Hell", "Fox", "Marge Simpson", "Bart Simpson", "Allie Goertz", "Milhouse Van Houten", "President Richard Nixon", etc. I pay attention to character relations, creators, voice actors, dates of events, naming origins, and publication info.

Relationships to extract include:
- Character appearances and roles in "The Simpsons".
- Who created or named each character.
- The real-life inspiration for character names (e.g., Bart is an anagram of "brat", Lisa is named after Lisa Groening, Marge after Margaret Groening, Homer after Homer Groening, Milhouse after President Richard Nixon's middle name).
- Career and creative works info for Allie Goertz.
- The direct actions of Matt Groening (creating, naming, being inspired by someone, etc.)

### CONTEXT_TRIPLES
(Lisa Simpson, is a character in, The Simpsons)
(Lisa Simpson, is the middle child of, Simpson family)
(Lisa Simpson, is voiced by, Yeardley Smith)
(Lisa Simpson, first appeared on television in, Good Night)
(Lisa Simpson, first appeared on television on, April 19, 1987)
(Lisa Simpson, was created by, Matt Groening)
(Lisa Simpson, was designed by, Matt Groening)
(Matt Groening, named Lisa Simpson after, Lisa Groening)
(Simpson family, got own series on, Fox)
(Simpson family, television series debuted on, December 17, 1989)
(Matt Groening, was invited to pitch shorts based on, Life in Hell)
(Matt Groening, met at office of, James L. Brooks)
(Marge Simpson, is a character in, The Simpsons)
(Marge Simpson, is part of, Simpson family)
(Marge Simpson, is voiced by, Julie Kavner)
(Marge Simpson, first appeared in, Good Night)
(Marge Simpson, first appeared on, April 19, 1987)
(Matt Groening, created Marge Simpson)
(Matt Groening, designed Marge Simpson)
(Matt Groening, named Marge Simpson after, Margaret Groening)
(Bart Simpson, is a character in, The Simpsons)
(Bart Simpson, is part of, Simpson family)
(Bart Simpson, is voiced by, Nancy Cartwright)
(Bart Simpson, first appeared in, Good Night)
(Bart Simpson, first appeared on, April 19, 1987)
(Matt Groening, created Bart Simpson)
(Matt Groening, designed Bart Simpson)
(Bart Simpson, name is anagram of, brat)
(Matt Groening, named Bart Simpson differently from, the rest of his family)
(Homer Simpson, is a character in, The Simpsons)
(Homer Simpson, is main protagonist of, The Simpsons)
(Homer Simpson, is voiced by, Dan Castellaneta)
(Homer Simpson, first appeared in, Good Night)
(Homer Simpson, first appeared on, April 19, 1987)
(Matt Groening, created Homer Simpson)
(Matt Groening, designed Homer Simpson)
(Matt Groening, named Homer Simpson after, Homer Groening)
(Milhouse Van Houten, is a character in, The Simpsons)
(Milhouse Van Houten, is voiced by, Pamela Hayden)
(Matt Groening, created Milhouse Van Houten)
(Matt Groening, named Milhouse Van Houten after, President Richard Nixon's middle name)
(Milhouse Van Houten, middle name is, Mussolini)
(Allie Goertz, is a musician)
(Allie Goertz, is an American)
(Allie Goertz, is a satirist)
(Allie Goertz, creates songs about, pop culture topics)
(Allie Goertz, posts videos on YouTube as, Cossbysweater)
(Allie Goertz, wrote a song about, Milhouse)
(Allie Goertz, is co-host of, Everything's Coming Up Podcast)
(Everything's Coming Up Podcast, is about, The Simpsons)
(Allie Goertz, co-hosts Everything's Coming Up Podcast with, Julia Prescott)

### QUESTION_REASONING
The question asks:
- Allie Goertz wrote a song about the "The Simpsons" character Milhouse.
- Milhouse was named by Matt Groening after _____.

Step-by-step decomposition:
1. The question points out that Allie Goertz wrote a song about Milhouse (which is provided in the context).
2. The key unknown to infer is "who Matt Groening named Milhouse after."
3. We represent "the person/figure Milhouse was named after" with a variable (x) in the triple.
4. The answer requires connecting: (Matt Groening, named Milhouse Van Houten after, x)

### QUESTIONS_TRIPLES
(Matt Groening, named Milhouse Van Houten after, x)
--------------------------------------------------
Item 4:
### CONTEXT_REASONING

In [44]:
graphs_str_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "graphs_str": []
})

for i, graphs_str_list in enumerate(graphs_str_batch):
    batch_num_list = [i] * len(graphs_str_list)
    question_num_list = list(range(1, len(graphs_str_list) + 1))
    graphs_str_df = pd.concat([graphs_str_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "graphs_str": graphs_str_list
    })], ignore_index=True)

del graphs_str_batch
del graphs_str_list
del batch_input_list
del batch_context
del batch_question
del batch_answer

graphs_str_df

   batch_num  question_num                                         graphs_str
0        0.0           1.0  ### CONTEXT_REASONING\nI begin by reading each...
1        0.0           2.0  ### CONTEXT_REASONING\nI first identify unique...
2        0.0           3.0  ### CONTEXT_REASONING\nTo extract context trip...
3        0.0           4.0  ### CONTEXT_REASONING\nI start by reading each...
4        0.0           5.0  ### CONTEXT_REASONING\nTo extract context trip...
5        0.0           6.0  ### CONTEXT_REASONING\nFirst, I identify named...
6        0.0           7.0  ### CONTEXT_REASONING\nTo extract context trip...
7        0.0           8.0  ### CONTEXT_REASONING\nFirst, I identify indiv...
8        0.0           9.0  ### CONTEXT_REASONING\n- First, I scan all par...
9        0.0          10.0  ### CONTEXT_REASONING\nFirst, I identify the k...

## 3. Parsing the Output and Building KGs

In [66]:
import re
from ast import literal_eval

def sanitize_str(name):
    """
    Sanitize a name by removing extra spaces, apostrophes, and ensuring proper formatting.
    """
    # Replace apostrophes with empty string
    name = name.replace("'s", "s")
    name = name.replace("'", "")

    # Replace spaces with underscores
    name = name.replace(" ", "_")

    # Remove any other problematic characters
    name = re.sub(r'[^\w\-_]', '', name)

    # Prefix if starts with digit
    if re.match(r"^\d", name):
        name = f"n{name}"

    # If empty string, return something safe
    if not name:
        name = "unknown"

    return name

def sanitize_entities_and_relations(triple):
    """
    Sanitize entities and relations in a triple by removing extra spaces and ensuring proper formatting.
    """
    return (
        sanitize_str(triple[0].strip()),  # Subject
        sanitize_str(triple[1].strip()),  # Relation
        sanitize_str(triple[2].strip())   # Object
    )


def parse_custom_triples(triples_str):
    triples = []
    for line in triples_str.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        # Remove enclosing parentheses
        if line.startswith('(') and line.endswith(')'):
            line = line[1:-1]
        # Now, split ONLY on the first two commas
        parts = []
        remaining = line
        for _ in range(2):
            # Find the first comma
            idx = remaining.find(',')
            if idx == -1:
                break
            parts.append(remaining[:idx].strip())
            remaining = remaining[idx+1:].strip()
        parts.append(remaining)
        if len(parts) == 3:
            triples.append(sanitize_entities_and_relations(tuple(parts)))
    return triples

def extract_sections(text):
    # Regex patterns for section headers
    context_reasoning_pat = r'### CONTEXT_REASONING\s*(.*?)\s*### CONTEXT_TRIPLES'
    context_triples_pat = r'### CONTEXT_TRIPLES\s*(.*?)\s*### QUESTION_REASONING'
    question_reasoning_pat = r'### QUESTION_REASONING\s*(.*?)\s*### QUESTIONS_TRIPLES'
    questions_triples_pat = r'### QUESTIONS_TRIPLES\s*(.*)$'

    # Extract sections using regex
    context_reasoning = re.search(context_reasoning_pat, text, re.DOTALL)
    context_triples = re.search(context_triples_pat, text, re.DOTALL)
    question_reasoning = re.search(question_reasoning_pat, text, re.DOTALL)
    questions_triples = re.search(questions_triples_pat, text, re.DOTALL)

    # Clean reasoning sections
    context_reasoning_str = context_reasoning.group(1).strip() if context_reasoning else ""
    question_reasoning_str = question_reasoning.group(1).strip() if question_reasoning else ""

    # Use the custom parser for triples
    context_triples_list = parse_custom_triples(context_triples.group(1)) if context_triples else []
    questions_triples_list = parse_custom_triples(questions_triples.group(1)) if questions_triples else []

    return context_reasoning_str, question_reasoning_str, context_triples_list, questions_triples_list

def extract_to_columns(row):
    context_reasoning, question_reasoning, context_triples, question_triples = extract_sections(row['graphs_str'])
    return pd.Series([context_reasoning, question_reasoning, context_triples, question_triples],
                     index=['context_reasoning', 'question_reasoning', 'context_triples', 'question_triples'])

In [67]:
graphs_str_df[['context_reasoning', 'question_reasoning', 'context_triples', 'question_triples']] = graphs_str_df.apply(extract_to_columns, axis=1)
graphs_str_df

,batch_num,question_num,graphs_str,context_reasoning,question_reasoning,context_triples,question_triples
0,0.0,1.0,### CONTEXT_REASONING\nI begin by reading each...,"I begin by reading each title and paragraph, i...",The question asks which magazine was started f...,"[(Radio_City, is, Indias_first_private_FM_radi...","[(Arthurs_Magazine, was_started_on, x), (First..."
1,0.0,2.0,### CONTEXT_REASONING\nI first identify unique...,"I first identify unique entities: ""Ritz-Carlto...",The question asks for the city in which the he...,"[(Ritz-Carlton_Jakarta, is_a, hotel), (Ritz-Ca...","[(Oberoi_family, is_part_of, x), (x, has_head_..."
2,0.0,3.0,### CONTEXT_REASONING\nTo extract context trip...,"To extract context triples, I first identify a...",The question asks:\n- Allie Goertz wrote a son...,"[(Lisa_Simpson, is_a_character_in, The_Simpson...","[(Matt_Groening, named_Milhouse_Van_Houten_aft..."
3,0.0,4.0,### CONTEXT_REASONING\nI start by reading each...,"I start by reading each title and paragraph, i...","The question asks for the nationality of ""Jame...","[(Moloch_or, This_Gentile_World, is_a_semi-aut...","[(Ewan_MacColl, was_married_to, Peggy_Seeger),..."
4,0.0,5.0,### CONTEXT_REASONING\nTo extract context trip...,"To extract context triples, I first identify t...",The question asks for a chemical in which cadm...,"[(Cadmium_chloride, is_a_compound_of, cadmium)...","[(Cadmium_chloride, is_slightly_soluble_in, x)..."
5,0.0,6.0,"### CONTEXT_REASONING\nFirst, I identify named...","First, I identify named entities within the co...",The question asks which tennis player won more...,"[(Li_Na, is_a, Chinese_professional_tennis_pla...","[(Henri_Leconte, won, x_Grand_Slam_titles), (J..."
6,0.0,7.0,### CONTEXT_REASONING\nTo extract context trip...,"To extract context triples, I identify all uni...",The question asks for the genus of moth in the...,"[(India, is_officially_known_as, Republic_of_I...","[(x, is_a, genus_of_moth), (x, is_found_in, In..."
7,0.0,8.0,"### CONTEXT_REASONING\nFirst, I identify indiv...","First, I identify individual entities—people, ...","I read the question, which asks for the name o...","[(Verano_de_Escándalo_1998, is_a, professional...","[(x, was_once_considered, best_kickboxer_in_th..."
8,0.0,9.0,"### CONTEXT_REASONING\n- First, I scan all par...","- First, I scan all paragraphs for named entit...",- The question asks about the Dutch-Belgian te...,"[(House_of_Anubis, is_a, mystery_television_se...","[(Het_Huis_Anubis, first_aired_in, x)]"
9,0.0,10.0,"### CONTEXT_REASONING\nFirst, I identify the k...","First, I identify the key entities mentioned i...",The question asks for the length of the track ...,"[(Mount_Panorama_Circuit, is_a, motor_racing_t...","[(n2013_Liqui_Moly_Bathurst_12_Hour, staged_at..."

In [68]:
main_df = main_df.merge(graphs_str_df, on=['batch_num', 'question_num'], how='left')
# del graphs_str_df
main_df

,batch_num,question_num,context,question,answer,graphs_str,context_reasoning,question_reasoning,context_triples,question_triples
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine,### CONTEXT_REASONING\nI begin by reading each...,"I begin by reading each title and paragraph, i...",The question asks which magazine was started f...,"[(Radio_City, is, Indias_first_private_FM_radi...","[(Arthurs_Magazine, was_started_on, x), (First..."
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi,### CONTEXT_REASONING\nI first identify unique...,"I first identify unique entities: ""Ritz-Carlto...",The question asks for the city in which the he...,"[(Ritz-Carlton_Jakarta, is_a, hotel), (Ritz-Ca...","[(Oberoi_family, is_part_of, x), (x, has_head_..."
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,### CONTEXT_REASONING\nTo extract context trip...,"To extract context triples, I first identify a...",The question asks:\n- Allie Goertz wrote a son...,"[(Lisa_Simpson, is_a_character_in, The_Simpson...","[(Matt_Groening, named_Milhouse_Van_Houten_aft..."
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American,### CONTEXT_REASONING\nI start by reading each...,"I start by reading each title and paragraph, i...","The question asks for the nationality of ""Jame...","[(Moloch_or, This_Gentile_World, is_a_semi-aut...","[(Ewan_MacColl, was_married_to, Peggy_Seeger),..."
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol,### CONTEXT_REASONING\nTo extract context trip...,"To extract context triples, I first identify t...",The question asks for a chemical in which cadm...,"[(Cadmium_chloride, is_a_compound_of, cadmium)...","[(Cadmium_chloride, is_slightly_soluble_in, x)..."
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark,"### CONTEXT_REASONING\nFirst, I identify named...","First, I identify named entities within the co...",The question asks which tennis player won more...,"[(Li_Na, is_a, Chinese_professional_tennis_pla...","[(Henri_Leconte, won, x_Grand_Slam_titles), (J..."
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae,### CONTEXT_REASONING\nTo extract context trip...,"To extract context triples, I identify all uni...",The question asks for the genus of moth in the...,"[(India, is_officially_known_as, Republic_of_I...","[(x, is_a, genus_of_moth), (x, is_found_in, In..."
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari,"### CONTEXT_REASONING\nFirst, I identify indiv...","First, I identify individual entities—people, ...","I read the question, which asks for the name o...","[(Verano_de_Escándalo_1998, is_a, professional...","[(x, was_once_considered, best_kickboxer_in_th..."
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006,"### CONTEXT_REASONING\n- First, I scan all par...","- First, I scan all paragraphs for named entit...",- The question asks about the Dutch-Belgian te...,"[(House_of_Anubis, is_a, mystery_television_se...","[(Het_Huis_Anubis, first_aired_in, x)]"
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long,"### CONTEXT_REASONING\nFirst, I identify the k...","First, I identify the key entities mentioned i...",The question asks for the length of the track ...,"[(Mount_Panorama_Circuit, is_a, motor_racing_t...","[(n2013_Liqui_Moly_Bathurst_12_Hour, staged_at..."

In [69]:
# Loop through each row. Save the context triples as OWL KG files
from rdflib import Graph, Namespace, RDF, RDFS, OWL, URIRef
import os

def save_kg_from_triples(triples, batch_num, question_num):
    g = Graph()
    EX = Namespace("http://example.org/")

    # Add triples to the graph
    for subject, relation, obj in triples:
        subject_uri = URIRef(EX[subject])
        object_uri = URIRef(EX[obj])
        g.add((subject_uri, URIRef(EX[relation]), object_uri))

    # Define the file path
    file_path = f"{KNOWLEDGE_GRAPH_PATH}/{DATASET_NAME}_ontology_b{batch_num}_q{question_num}.rdf"

    # Save the graph in OWL format
    g.serialize(destination=file_path, format='xml')
    print(f"Saved KG for batch {batch_num}, question {question_num} to {file_path}")

for index, row in main_df.iterrows():
    batch_num = row['batch_num']
    question_num = row['question_num']
    context_triples = row['context_triples']

    if context_triples:  # Only save if there are context triples
        save_kg_from_triples(context_triples, batch_num, question_num)

Saved KG for batch 0, question 1 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q1.rdf
Saved KG for batch 0, question 2 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q2.rdf
Saved KG for batch 0, question 3 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q3.rdf
Saved KG for batch 0, question 4 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q4.rdf
Saved KG for batch 0, question 5 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q5.rdf
Saved KG for batch 0, question 6 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q6.rdf
Saved KG for batch 0, question 7 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q7.rdf
Saved KG for batch 0, question 8 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q8.rdf
Saved KG for batch 0, question 9 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q9.rdf
Saved KG for batch 0, question 10 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q10.rdf