In [1]:
import json
import pandas as pd

BATCH_SIZE = 50
IS_DEBUG = True
DEBUG_QUESTION_SIZE = 10
LLM_MODEL = "gpt-4.1"
DATASET_NAME = "hotpotQA"
KNOWLEDGE_GRAPH_PATH = 'outputs/knowledge_graphs'

## 1. Loading HotpotQA Dataset

In [2]:
train_hotpot_qa_path = r'C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\hotpotQA\hotpot_train_v1.1.json'
test_hotpot_qa_path = r'C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\hotpotQA\hotpot_test_v1.1.json'

In [3]:
with open(train_hotpot_qa_path, 'r', encoding='utf-8') as f:
    train_hotpot_qa_json = json.load(f)

with open(test_hotpot_qa_path, 'r', encoding='utf-8') as f:
    test_hotpot_qa_json = json.load(f)

In [4]:
train_hotpot_qa_json[0]

{'supporting_facts': [["Arthur's Magazine", 0], ['First for Women', 0]],
 'level': 'medium',
 'question': "Which magazine was started first Arthur's Magazine or First for Women?",
 'context': [['Radio City (Indian radio station)',
   ["Radio City is India's first private FM radio station and was started on 3 July 2001.",
    ' It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003).',
    ' It plays Hindi, English and regional songs.',
    ' It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007.',
    ' Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features.',
    ' The Radio station currently plays a mix of Hindi and Regional music.',
    ' Abraham Thomas is the CEO of the company.']],
  ['History of Albanian football',
   ['Football in Albania existed before the Albanian Football Federation (FSHF) was created.',
    " This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) .",
    ' Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946.',
    ' In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.']],
  ['Echosmith',
   ['Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California.',
    ' Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016.',
    ' Echosmith started first as "Ready Set Go!"',
    ' until they signed to Warner Bros.',
    ' Records in May 2012.',
    ' They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia.',
    ' The song was Warner Bros.',
    " Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold.",
    ' The band\'s debut album, "Talking Dreams", was released on October 8, 2013.']],
  ["Women's colleges in the Southern United States",
   ["Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States.",
    " Many started first as girls' seminaries or academies.",
    ' Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women.',
    ' Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.']],
  ['First Arthur County Courthouse and Jail',
   ['The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.']],
  ["Arthur's Magazine",
   ["Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century.",
    ' Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others.',
    ' In May 1846 it was merged into "Godey\'s Lady\'s Book".']],
  ['2014–15 Ukrainian Hockey Championship',
   ['The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship.',
    ' Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues.',
    ' Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014.',
    ' The regular season included just 12 rounds, where all the teams went to the semifinals.',
    ' In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.']],
  ['First for Women',
   ["First for Women is a woman's magazine published by Bauer Media Group in the USA.",
    ' The magazine was started in 1989.',
    ' It is based in Englewood Cliffs, New Jersey.',
    ' In 2011 the circulation of the magazine was 1,310,696 copies.']],
  ['Freeway Complex Fire',
   ['The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California.',
    ' The fire started as two separate fires on November 15, 2008.',
    ' The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later.',
    ' These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.']],
  ['William Rast',
   ['William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala.',
    ' It is most known for their premium jeans.',
    ' On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line.',
    ' The label also produces other clothing items such as jackets and tops.',
    ' The company started first as a denim line, later evolving into a men’s and women’s clothing line.']]],
 'answer': "Arthur's Magazine",
 '_id': '5a7a06935542990198eaf050',
 'type': 'comparison'}

In [5]:
test_hotpot_qa_json[0]

{'_id': '5a8b57f25542995d1e6f1371',
 'answer': 'yes',
 'question': 'Were Scott Derrickson and Ed Wood of the same nationality?',
 'supporting_facts': [['Scott Derrickson', 0], ['Ed Wood', 0]],
 'context': [['Adam Collis',
   ['Adam Collis is an American filmmaker and actor.',
    ' He attended the Duke University from 1986 to 1990 and the University of California, Los Angeles from 2007 to 2010.',
    ' He also studied cinema at the University of Southern California from 1991 to 1997.',
    ' Collis first work was the assistant director for the Scott Derrickson\'s short "Love in the Ruins" (1995).',
    ' In 1998, he played "Crankshaft" in Eric Koyanagi\'s "Hundred Percent".']],
  ['Ed Wood (film)',
   ['Ed Wood is a 1994 American biographical period comedy-drama film directed and produced by Tim Burton, and starring Johnny Depp as cult filmmaker Ed Wood.',
    " The film concerns the period in Wood's life when he made his best-known films as well as his relationship with actor Bela Lugosi, played by Martin Landau.",
    ' Sarah Jessica Parker, Patricia Arquette, Jeffrey Jones, Lisa Marie, and Bill Murray are among the supporting cast.']],
  ['Tyler Bates',
   ['Tyler Bates (born June 5, 1965) is an American musician, music producer, and composer for films, television, and video games.',
    ' Much of his work is in the action and horror film genres, with films like "Dawn of the Dead, 300, Sucker Punch," and "John Wick."',
    ' He has collaborated with directors like Zack Snyder, Rob Zombie, Neil Marshall, William Friedkin, Scott Derrickson, and James Gunn.',
    ' With Gunn, he has scored every one of the director\'s films; including "Guardians of the Galaxy", which became one of the highest grossing domestic movies of 2014, and its 2017 sequel.',
    ' In addition, he is also the lead guitarist of the American rock band Marilyn Manson, and produced its albums "The Pale Emperor" and "Heaven Upside Down".']],
  ['Doctor Strange (2016 film)',
   ['Doctor Strange is a 2016 American superhero film based on the Marvel Comics character of the same name, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures.',
    ' It is the fourteenth film of the Marvel Cinematic Universe (MCU).',
    ' The film was directed by Scott Derrickson, who wrote it with Jon Spaihts and C. Robert Cargill, and stars Benedict Cumberbatch as Stephen Strange, along with Chiwetel Ejiofor, Rachel McAdams, Benedict Wong, Michael Stuhlbarg, Benjamin Bratt, Scott Adkins, Mads Mikkelsen, and Tilda Swinton.',
    ' In "Doctor Strange", surgeon Strange learns the mystic arts after a career-ending car accident.']],
  ['Hellraiser: Inferno',
   ['Hellraiser: Inferno (also known as Hellraiser V: Inferno) is a 2000 American horror film.',
    ' It is the fifth installment in the "Hellraiser" series and the first "Hellraiser" film to go straight-to-DVD.',
    ' It was directed by Scott Derrickson and released on October 3, 2000.',
    " The film concerns a corrupt detective who discovers Lemarchand's box at a crime scene.",
    " The film's reviews were mixed."]],
  ['Sinister (film)',
   ['Sinister is a 2012 supernatural horror film directed by Scott Derrickson and written by Derrickson and C. Robert Cargill.',
    ' It stars Ethan Hawke as fictional true-crime writer Ellison Oswalt who discovers a box of home movies in his attic that puts his family in danger.']],
  ['Deliver Us from Evil (2014 film)',
   ['Deliver Us from Evil is a 2014 American supernatural horror film directed by Scott Derrickson and produced by Jerry Bruckheimer.',
    ' The film is officially based on a 2001 non-fiction book entitled "Beware the Night" by Ralph Sarchie and Lisa Collier Cool, and its marketing campaign highlighted that it was "inspired by actual accounts".',
    ' The film stars Eric Bana, Édgar Ramírez, Sean Harris, Olivia Munn, and Joel McHale in the main roles and was released on July 2, 2014.']],
  ['Woodson, Arkansas',
   ['Woodson is a census-designated place (CDP) in Pulaski County, Arkansas, in the United States.',
    ' Its population was 403 at the 2010 census.',
    ' It is part of the Little Rock–North Little Rock–Conway Metropolitan Statistical Area.',
    ' Woodson and its accompanying Woodson Lake and Wood Hollow are the namesake for Ed Wood Sr., a prominent plantation owner, trader, and businessman at the turn of the 20th century.',
    ' Woodson is adjacent to the Wood Plantation, the largest of the plantations own by Ed Wood Sr.']],
  ['Conrad Brooks',
   ['Conrad Brooks (born Conrad Biedrzycki on January 3, 1931 in Baltimore, Maryland) is an American actor.',
    ' He moved to Hollywood, California in 1948 to pursue a career in acting.',
    ' He got his start in movies appearing in Ed Wood films such as "Plan 9 from Outer Space", "Glen or Glenda", and "Jail Bait."',
    ' He took a break from acting during the 1960s and 1970s but due to the ongoing interest in the films of Ed Wood, he reemerged in the 1980s and has become a prolific actor.',
    ' He also has since gone on to write, produce and direct several films.']],
  ['The Exorcism of Emily Rose',
   ['The Exorcism of Emily Rose is a 2005 American legal drama horror film directed by Scott Derrickson and starring Laura Linney and Tom Wilkinson.',
    ' The film is loosely based on the story of Anneliese Michel and follows a self-proclaimed agnostic who acts as defense counsel (Linney) representing a parish priest (Wilkinson), accused by the state of negligent homicide after he performed an exorcism.']]],
 'type': 'comparison',
 'level': 'hard'}

In [6]:
for item in train_hotpot_qa_json[0]['context']:
    print(f"Title: {item[0]}")
    print(f"Paragraph: {item[1:]}")
    print("-" * 50)

Title: Radio City (Indian radio station)
Paragraph: [["Radio City is India's first private FM radio station and was started on 3 July 2001.", ' It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003).', ' It plays Hindi, English and regional songs.', ' It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007.', ' Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features.', ' The Radio station currently plays a mix of Hindi and Regional music.', ' Abraham Thomas is the CEO of the company.']]
--------------------------------------------------
Title: History of Albanian football
Paragraph: [['Football in Albania existed before the Albanian Football Federation (FSHF) was created.', " This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) .", ' Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946.', ' In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.']]
--------------------------------------------------
Title: Echosmith
Paragraph: [['Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California.', ' Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016.', ' Echosmith started first as "Ready Set Go!"', ' until they signed to Warner Bros.', ' Records in May 2012.', ' They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia.', ' The song was Warner Bros.', " Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold.", ' The band\'s debut album, "Talking Dreams", was released on October 8, 2013.']]
--------------------------------------------------
Title: Women's colleges in the Southern United States
Paragraph: [["Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States.", " Many started first as girls' seminaries or academies.", ' Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women.', ' Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.']]
--------------------------------------------------
Title: First Arthur County Courthouse and Jail
Paragraph: [['The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.']]
--------------------------------------------------
Title: Arthur's Magazine
Paragraph: [["Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century.", ' Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others.', ' In May 1846 it was merged into "Godey\'s Lady\'s Book".']]
--------------------------------------------------
Title: 2014–15 Ukrainian Hockey Championship
Paragraph: [['The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship.', ' Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues.', ' Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014.', ' The regular season included just 12 rounds, where all the teams went to the semifinals.', ' In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.']]
--------------------------------------------------
Title: First for Women
Paragraph: [["First for Women is a woman's magazine published by Bauer Media Group in the USA.", ' The magazine was started in 1989.', ' It is based in Englewood Cliffs, New Jersey.', ' In 2011 the circulation of the magazine was 1,310,696 copies.']]
--------------------------------------------------
Title: Freeway Complex Fire
Paragraph: [['The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California.', ' The fire started as two separate fires on November 15, 2008.', ' The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later.', ' These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.']]
--------------------------------------------------
Title: William Rast
Paragraph: [['William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala.', ' It is most known for their premium jeans.', ' On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line.', ' The label also produces other clothing items such as jackets and tops.', ' The company started first as a denim line, later evolving into a men’s and women’s clothing line.']]
--------------------------------------------------

In [7]:
def divide_and_batch(train_json, batch_size):
    batch_context = []
    batch_question = []
    batch_answer = []

    for i in range(0, len(train_json), batch_size):
        batch = train_json[i:i + batch_size]
        context = []
        question = []
        answer = []

        for item in batch:
            context_text = ""
            j = 1
            for ctx in item['context']:
                context_text += f"Title {j} : {ctx[0]} \nParagraph {j} : {''.join(ctx[1])}\n"
                j += 1
            context.append(context_text)
            question.append(item['question'])
            answer.append(item['answer'])

        batch_context.append(context)
        batch_question.append(question)
        batch_answer.append(answer)

    return batch_context, batch_question, batch_answer

In [8]:
if IS_DEBUG:
    train_hotpot_qa_json = train_hotpot_qa_json[:DEBUG_QUESTION_SIZE]
    test_hotpot_qa_json = test_hotpot_qa_json[:DEBUG_QUESTION_SIZE]
    batch_context, batch_question, batch_answer = divide_and_batch(train_hotpot_qa_json, BATCH_SIZE)
else:
    batch_context, batch_question, batch_answer = divide_and_batch(test_hotpot_qa_json, BATCH_SIZE)

In [9]:
for i in range(len(batch_context[0])):
    print(f"Batch {i + 1}:")
    print("Context:", batch_context[0][i])
    print("Question:", batch_question[0][i])
    print("Answer:", batch_answer[0][i])
    print("-" * 50)
    if i == 9:  # Limit to 3 batches for brevity
        break

Batch 1:
Context: Title 1 : Radio City (Indian radio station)
Paragraph 1 : Radio City is India's first private FM radio station and was started on 3 July 2001. It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003). It plays Hindi, English and regional songs. It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007. Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features. The Radio station currently plays a mix of Hindi and Regional music. Abraham Thomas is the CEO of the company.
Title 2 : History of Albanian football
Paragraph 2 : Football in Albania existed before the Albanian Football Federation (FSHF) was created. This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) . Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946. In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.
Title 3 : Echosmith
Paragraph 3 : Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California. Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016. Echosmith started first as "Ready Set Go!" until they signed to Warner Bros. Records in May 2012. They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia. The song was Warner Bros. Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold. The band's debut album, "Talking Dreams", was released on October 8, 2013.
Title 4 : Women's colleges in the Southern United States
Paragraph 4 : Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States. Many started first as girls' seminaries or academies. Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women. Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.
Title 5 : First Arthur County Courthouse and Jail
Paragraph 5 : The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.
Title 6 : Arthur's Magazine
Paragraph 6 : Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century. Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others. In May 1846 it was merged into "Godey's Lady's Book".
Title 7 : 2014–15 Ukrainian Hockey Championship
Paragraph 7 : The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship. Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues. Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014. The regular season included just 12 rounds, where all the teams went to the semifinals. In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.
Title 8 : First for Women
Paragraph 8 : First for Women is a woman's magazine published by Bauer Media Group in the USA. The magazine was started in 1989. It is based in Englewood Cliffs, New Jersey. In 2011 the circulation of the magazine was 1,310,696 copies.
Title 9 : Freeway Complex Fire
Paragraph 9 : The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California. The fire started as two separate fires on November 15, 2008. The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later. These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.
Title 10 : William Rast
Paragraph 10 : William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala. It is most known for their premium jeans. On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line. The label also produces other clothing items such as jackets and tops. The company started first as a denim line, later evolving into a men’s and women’s clothing line.

Question: Which magazine was started first Arthur's Magazine or First for Women?
Answer: Arthur's Magazine
--------------------------------------------------
Batch 2:
Context: Title 1 : Ritz-Carlton Jakarta
Paragraph 1 : The Ritz-Carlton Jakarta is a hotel and skyscraper in Jakarta, Indonesia and 14th Tallest building in Jakarta. It is located in city center of Jakarta, near Mega Kuningan, adjacent to the sister JW Marriott Hotel. It is operated by The Ritz-Carlton Hotel Company. The complex has two towers that comprises a hotel and the Airlangga Apartment respectively. The hotel was opened in 2005.
Title 2 : Oberoi family
Paragraph 2 : The Oberoi family is an Indian family that is famous for its involvement in hotels, namely through The Oberoi Group.
Title 3 : Ishqbaaaz
Paragraph 3 : Ishqbaaaz (English: "Lovers") is an Indian drama television series which is broadcast on Star Plus. It premiered on 27 June 2016 and airs Mon-Fri 10-11pm IST.Nakuul Mehta, Kunal Jaisingh and Leenesh Mattoo respectively portray Shivaay, Omkara and Rudra, the three heirs of the Oberoi family. The show initially focused on the tale of three brothers, later become centered on the love story of Shivaay and Annika (Surbhi Chandna); with the story of Omkara and Rudra being shifted to the spinoff series "Dil Boley Oberoi". In July 2017 "Dil Boley Oberoi" ended and the storylines were merged back into "Ishqbaaaz" which doubled its runtime.
Title 4 : Hotel Tallcorn
Paragraph 4 : The Hotel Tallcorn is located in Marshalltown, Iowa. Today it is called the Tallcorn Towers Apartments. Built in 1928 by the Eppley Hotel Company, local citizens contributed $120,000 to ensure the successful completion of this seven-story hotel. It was completed in connection to the seventy-fifth anniversary of Marshalltown. The hotel's sale in 1956 from the Eppley chain to the Sheraton Corporation was part of the second largest hotel sale in United States history. The Tallcorn was listed as a contributing property in the Marshalltown Downtown Historic District on the National Register of Historic Places in 2002.
Title 5 : Mohan Singh Oberoi
Paragraph 5 : Rai Bahadur Mohan Singh Oberoi (15 August 1898 – 3 May 2002) was an Indian hotelier, the founder and chairman of Oberoi Hotels & Resorts, India's second-largest hotel company, with 35 hotels in India, Sri Lanka, Nepal, Egypt, Australia and Hungary.
Title 6 : Hotel Bond
Paragraph 6 : Hotel Bond is a historic hotel, built in two stages in 1913 and 1921, in downtown Hartford, Connecticut by hotelier Harry S. Bond. It is located near Bushnell Park, and was considered the grandest hotel in Hartford during its heyday. The second section is a 12 story building attached to the 6 story first section. A Statler Hotel opened in the area in 1954, creating competition, and the Bond Hotel company declared bankruptcy shortly after that. It was bought by the California-based Masaglia Hotel chain, which began an incremental renovation program. In 1964 it was sold to a Cincinnati, Ohio investment group which announced extensive renovation plans. However, the financing plans fell through and the hotel was again in bankruptcy. The building was sold at auction to the Roman Catholic Archdiocese of Hartford in 1965, and it became the home of the Saint Francis Hospital School of Nursing. The Bond Ballroom reopened in 2001, with the rest of the building becoming a Homewood Suites by Hilton in 2006.
Title 7 : The Oberoi Group
Paragraph 7 : The Oberoi Group is a hotel company with its head office in Delhi. Founded in 1934, the company owns and/or operates 30+ luxury hotels and two river cruise ships in six countries, primarily under its Oberoi Hotels & Resorts and Trident Hotels brands.
Title 8 : Future Fibre Technologies
Paragraph 8 : Future Fibre Technologies (FFT) is a fiber optic sensing technologies company based in Melbourne, Australia, with its US head office in Mountain View, California, Middle East head office in Dubai, Indian head office in New Delhi and European head office in London. Founded in 1994, Future Fibre Technologies product line provides optical fiber intrusion detection systems for perimeters, buried oil and gas pipelines and data communication networks.
Title 9 : 289th Military Police Company
Paragraph 9 : The 289th Military Police Company was activated on 1 November 1994 and attached to Hotel Company, 3rd Infantry (The Old Guard), Fort Myer, Virginia. Hotel Company is the regiment's specialty company.
Title 10 : Glennwanis Hotel
Paragraph 10 : The Glennwanis Hotel is a historic hotel in Glennville, Georgia, Tattnall County, Georgia, built on the site of the Hughes Hotel. The hotel is located at 209-215 East Barnard Street. The old Hughes Hotel was built out of Georgia pine circa 1905 and burned in 1920. The Glennwanis was built in brick in 1926. The local Kiwanis club led the effort to get the replacement hotel built, and organized a Glennville Hotel Company with directors being local business leaders. The wife of a local doctor won a naming contest with the name "Glennwanis Hotel", a suggestion combining "Glennville" and "Kiwanis".

Question: The Oberoi family is part of a hotel company that has a head office in what city?
Answer: Delhi
--------------------------------------------------
Batch 3:
Context: Title 1 : Lisa Simpson
Paragraph 1 : Lisa Marie Simpson is a fictional character in the animated television series "The Simpsons". She is the middle child and most intelligent of the Simpson family. Voiced by Yeardley Smith, Lisa first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed her while waiting to meet James L. Brooks. Groening had been invited to pitch a series of shorts based on his comic "Life in Hell", but instead decided to create a new set of characters. He named the elder Simpson daughter after his younger sister Lisa Groening. After appearing on "The Tracey Ullman Show" for three years, the Simpson family were moved to their own series on Fox, which debuted on December 17, 1989.
Title 2 : Marge Simpson
Paragraph 2 : Marjorie Jacqueline "Marge" Simpson (née Bouvier) is a fictional character in the American animated sitcom "The Simpsons" and part of the eponymous family. She is voiced by Julie Kavner and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Marge was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on "Life in Hell" but instead decided to create a new set of characters. He named the character after his mother Margaret Groening. After appearing on "The Tracey Ullman Show" for three seasons, the Simpson family received their own series on Fox, which debuted December 17, 1989.
Title 3 : Bart Simpson
Paragraph 3 : Bartholomew JoJo "Bart" Simpson is a fictional character in the American animated television series "The Simpsons" and part of the Simpson family. He is voiced by Nancy Cartwright and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed Bart while waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip, "Life in Hell", but instead decided to create a new set of characters. While the rest of the characters were named after Groening's family members, Bart's name is an anagram of the word "brat". After appearing on "The Tracey Ullman Show" for three years, the Simpson family received its own series on Fox, which debuted December 17, 1989.
Title 4 : Allie Goertz
Paragraph 4 : Allison Beth "Allie" Goertz (born March 2, 1991) is an American musician. Goertz is known for her satirical songs based on various pop culture topics. Her videos are posted on YouTube under the name of Cossbysweater. Subjects of her songs have included the film "The Room", the character Milhouse from the television show "The Simpsons", and the game Dungeons & Dragons. Her style has been compared to that of Bo Burnham. In December 2015, Goertz released a concept album based on the Adult Swim series "Rick and Morty", "Sad Dance Songs", with the album's cover emulating the animation and logo of the series. The album was made possible through Kickstarter. She is co-host of Everything's Coming Up Podcast, a Simpsons-focused podcast along with Julia Prescott.
Title 5 : Milhouse Van Houten
Paragraph 5 : Milhouse Mussolini van Houten is a fictional character featured in the animated television series "The Simpsons", voiced by Pamela Hayden, and created by Matt Groening who named the character after President Richard Nixon's middle name. Later in the series, it is revealed that Milhouse's middle name is "Mussolini."
Title 6 : Los Angeles Reader
Paragraph 6 : Los Angeles Reader was a weekly paper established in 1978 and distributed in Los Angeles, United States. It followed the format of the (still active) Chicago Reader. The paper was known for having lengthy, thoughtful reviews of movies, plays and concerts in the LA area. James Vowell was its founding editor. Among its writers were Keith Fitzgerald, Nigey Lennon, Lionel Rolfe, Lawrence Wechsler, Mick Farren, Richard Meltzer, Heidi Dvorak, Chris Morris, Jerry Stahl, Steven Kane, Andy Klein, Allen Levy, Jim Goad, Kirk Silsbee, Henry Sheehan, Samantha Dunn, Natalie Nichols, Steve Appleford, Eric Mankin (also editor), Paul Birchall, Eddie Rivera (who wrote the paper's first cover story), Amy Steinberg, Harry Sheehan, Dan Sallit, Myron Meisel, David Ehrenstein. Tom Davis, Bruce Bebb, Stuart Goldman, Ernest Hardy, Kevin Uhrich, Erik Himmelsbach and David L. Ulin. It is famous for being the first newspaper to publish Matt Groening's cartoon strip, Life in Hell on April 25, 1980. James Vowell hired Matt Groening as his assistant editor in 1979. Groening was also originally a Reader music critic. It also ran a cartoon strip by David Lynch (director of Blue Velvet) called The Angriest Dog in the World, a strip notable for having exactly the same drawing panels for its entire run. James Vowell and his wife Codette Wallace bought the Reader from the Chicago Reader in February 1989. They sold "The Reader" to New Times Media in 1996, which merged it with the "Los Angeles View" to form "New Times LA".
Title 7 : Homer Simpson
Paragraph 7 : Homer Jay Simpson is a fictional character and the main protagonist of the American animated television series "The Simpsons" as the patriarch of the eponymous family. He is voiced by Dan Castellaneta and first appeared on television, along with the rest of his family, in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Homer was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip "Life in Hell" but instead decided to create a new set of characters. He named the character after his father, Homer Groening. After appearing for three seasons on "The Tracey Ullman Show", the Simpson family got their own series on Fox that debuted December 17, 1989.
Title 8 : List of The Simpsons video games
Paragraph 8 : "The Simpsons" is an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company. The series is a satirical parody of a middle class American lifestyle epitomized by its eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. It is set in the fictional town of Springfield, and lampoons American culture, society and television, and many aspects of the human condition. The family was conceived by Groening shortly before a pitch for a series of animated shorts with producer James L. Brooks. Groening created a dysfunctional family and named the characters after members of his own family, substituting Bart for his own name. The shorts became a part of "The Tracey Ullman Show" on April 19, 1987 and after a three-season run, the sketch was developed into a half-hour prime time show and became a hit series for Fox. The growing popularity of the series motivated video game developers to create video games based on the series. Two pinball machines have also been produced; one self-titled, that was only made available for a limited time after the first season finale (1990) and "The Simpsons Pinball Party" (2003). Additionally, several handheld device games have been released, such as "Bartman: Avenger of Evil" (1990) and "Bart Simpson's Cupcake Crisis" (1991).
Title 9 : The Simpsons: An Uncensored, Unauthorized History
Paragraph 9 : The Simpsons: An Uncensored, Unauthorized History is a non-fiction book about the American animated television series "The Simpsons". It was written by John Ortved, and first published in October 2009 by Faber and Faber. In the United Kingdom, the book is called Simpsons Confidential: The uncensored, totally unauthorised history of the world's greatest TV show by the people that made it. The book is an oral history of the show, and concentrates particularly on the writers and producers of the show. The book includes entire chapters devoted to key figures such as creator Matt Groening and James L. Brooks and Sam Simon, who helped develop the series. According to National Public Radio reviewer Linda Holmes, "Ortved's thesis, essentially, is that lots of people are responsible for the success of "The Simpsons", and their creator, Matt Groening, has too often been viewed as the sole source to the detriment of others who also deserve to be praised."
Title 10 : List of The Simpsons guest stars
Paragraph 10 : In addition to the show's regular cast of voice actors, celebrity guest stars have been a staple of "The Simpsons", an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company, since its first season. "The Simpsons" focuses on the eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. The family was initially conceived by Groening for a series of animated shorts, which originally aired as a part of "The Tracey Ullman Show" between 1987 and 1989. The shorts were developed into a half-hour prime time series which began in December 1989. The series' 27th season began in September 2015 and episodes of "The Simpsons" have aired. A feature film adaptation of the series called "The Simpsons Movie", was released in 2007.

Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
Answer: President Richard Nixon

In [10]:
del train_hotpot_qa_json
del test_hotpot_qa_json

## 2. Getting Triples from Context and Question

In [11]:
from dotenv import load_dotenv
import os

load_dotenv()
openai_api_key = os.getenv("OPENAI_API_KEY")

In [12]:
from langchain_openai import ChatOpenAI
from langchain_core.globals import set_debug, set_verbose, set_llm_cache
from langchain_community.cache import InMemoryCache
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

set_debug(False)
set_verbose(False)
set_llm_cache(InMemoryCache())

llm_model = ChatOpenAI(model=LLM_MODEL, api_key=openai_api_key)

In [13]:
system_msg = """
<role>
    You are an expert in natural language understanding and knowledge graph construction. Your task is to extract structured relationship triples from a context set (Titles and Paragraphs), including both explicit and logically inferable facts.
</role>

<behavior>
    <rule name="Entity Extraction">
        Identify and extract unique entities from Titles and Paragraphs. Use canonical forms for names. Capture entities including people, organizations, locations, publications, dates, and events.
    </rule>
    <rule name="Relationship Extraction">
        Extract explicit and clearly implied relationships between entities in the form of (subject, relation, object) triples.
        This includes:
        - Temporal relations such as publication or operational time spans (e.g., "published during", "active from", "merged in").
        - Authorship, editorial, or contribution roles (e.g., "edited by", "featured work by").
        - Event-based or structural relations (e.g., "merged into", "founded by", "took over").
    </rule>
    <rule name="Completeness">
        Extract **as many valid and informative triples as possible**. Include relationships that are inferred logically but unambiguous in context (e.g., date ranges, geographic associations, contributor roles).
    </rule>
    <rule name="Formatting and Output">
        Output must contain two sections, in order:
        1. ### CONTEXT_REASONING — step-by-step reasoning describing how entities and relationships were selected or inferred.
        2. ### CONTEXT_TRIPLES — list all extracted triples, each on its own line in the format (entity_1, relationship, entity_2)
        Do not add explanations, numbering, or extra text outside of these sections.
    </rule>
</behavior>

<format>
1. Carefully read the <context> section.
2. Begin with this heading:
   ### CONTEXT_REASONING
   Then, write concise reasoning steps describing how entities and relationships were selected and interpreted.
3. After reasoning, print this heading:
   ### CONTEXT_TRIPLES
   Then list each extracted triple on a new line in the format (entity_1, relationship, entity_2).
4. Do not include any explanations, text, or comments after the last triple.
</format>
"""

human_msg = """
<context>
{context}
</context>
"""

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [14]:
chain = prompt | llm_model | StrOutputParser()

In [15]:
batch_input_list = []
main_df = pd.DataFrame()

for i in range(len(batch_context)):
    batch_num_list = [i] * len(batch_context[i])
    question_num_list = list(range(1, len(batch_context[i]) + 1))
    context_list = []
    question_list = []
    answers_list = []

    batch_input_item = []
    j = 0
    for batch in range(len(batch_context[i])):
        context = batch_context[i][batch]
        batch_input_item.append({
            "context": context
        })
        context_list.append(context)
        question_list.append(batch_question[i][j])
        answers_list.append(batch_answer[i][j])
        j += 1
    batch_input_list.append(batch_input_item)
    df = pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "context": context_list,
        "question": question_list,
        "answer": answers_list
    })
    main_df = pd.concat([main_df, df], ignore_index=True)

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1}:")
    for item in batch:
        print("Context:", item['context'])
        print("-" * 50)

Batch 1:
Context: Title 1 : Radio City (Indian radio station)
Paragraph 1 : Radio City is India's first private FM radio station and was started on 3 July 2001. It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003). It plays Hindi, English and regional songs. It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007. Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features. The Radio station currently plays a mix of Hindi and Regional music. Abraham Thomas is the CEO of the company.
Title 2 : History of Albanian football
Paragraph 2 : Football in Albania existed before the Albanian Football Federation (FSHF) was created. This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) . Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946. In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.
Title 3 : Echosmith
Paragraph 3 : Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California. Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016. Echosmith started first as "Ready Set Go!" until they signed to Warner Bros. Records in May 2012. They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia. The song was Warner Bros. Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold. The band's debut album, "Talking Dreams", was released on October 8, 2013.
Title 4 : Women's colleges in the Southern United States
Paragraph 4 : Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States. Many started first as girls' seminaries or academies. Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women. Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.
Title 5 : First Arthur County Courthouse and Jail
Paragraph 5 : The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.
Title 6 : Arthur's Magazine
Paragraph 6 : Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century. Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others. In May 1846 it was merged into "Godey's Lady's Book".
Title 7 : 2014–15 Ukrainian Hockey Championship
Paragraph 7 : The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship. Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues. Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014. The regular season included just 12 rounds, where all the teams went to the semifinals. In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.
Title 8 : First for Women
Paragraph 8 : First for Women is a woman's magazine published by Bauer Media Group in the USA. The magazine was started in 1989. It is based in Englewood Cliffs, New Jersey. In 2011 the circulation of the magazine was 1,310,696 copies.
Title 9 : Freeway Complex Fire
Paragraph 9 : The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California. The fire started as two separate fires on November 15, 2008. The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later. These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.
Title 10 : William Rast
Paragraph 10 : William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala. It is most known for their premium jeans. On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line. The label also produces other clothing items such as jackets and tops. The company started first as a denim line, later evolving into a men’s and women’s clothing line.

--------------------------------------------------
Context: Title 1 : Ritz-Carlton Jakarta
Paragraph 1 : The Ritz-Carlton Jakarta is a hotel and skyscraper in Jakarta, Indonesia and 14th Tallest building in Jakarta. It is located in city center of Jakarta, near Mega Kuningan, adjacent to the sister JW Marriott Hotel. It is operated by The Ritz-Carlton Hotel Company. The complex has two towers that comprises a hotel and the Airlangga Apartment respectively. The hotel was opened in 2005.
Title 2 : Oberoi family
Paragraph 2 : The Oberoi family is an Indian family that is famous for its involvement in hotels, namely through The Oberoi Group.
Title 3 : Ishqbaaaz
Paragraph 3 : Ishqbaaaz (English: "Lovers") is an Indian drama television series which is broadcast on Star Plus. It premiered on 27 June 2016 and airs Mon-Fri 10-11pm IST.Nakuul Mehta, Kunal Jaisingh and Leenesh Mattoo respectively portray Shivaay, Omkara and Rudra, the three heirs of the Oberoi family. The show initially focused on the tale of three brothers, later become centered on the love story of Shivaay and Annika (Surbhi Chandna); with the story of Omkara and Rudra being shifted to the spinoff series "Dil Boley Oberoi". In July 2017 "Dil Boley Oberoi" ended and the storylines were merged back into "Ishqbaaaz" which doubled its runtime.
Title 4 : Hotel Tallcorn
Paragraph 4 : The Hotel Tallcorn is located in Marshalltown, Iowa. Today it is called the Tallcorn Towers Apartments. Built in 1928 by the Eppley Hotel Company, local citizens contributed $120,000 to ensure the successful completion of this seven-story hotel. It was completed in connection to the seventy-fifth anniversary of Marshalltown. The hotel's sale in 1956 from the Eppley chain to the Sheraton Corporation was part of the second largest hotel sale in United States history. The Tallcorn was listed as a contributing property in the Marshalltown Downtown Historic District on the National Register of Historic Places in 2002.
Title 5 : Mohan Singh Oberoi
Paragraph 5 : Rai Bahadur Mohan Singh Oberoi (15 August 1898 – 3 May 2002) was an Indian hotelier, the founder and chairman of Oberoi Hotels & Resorts, India's second-largest hotel company, with 35 hotels in India, Sri Lanka, Nepal, Egypt, Australia and Hungary.
Title 6 : Hotel Bond
Paragraph 6 : Hotel Bond is a historic hotel, built in two stages in 1913 and 1921, in downtown Hartford, Connecticut by hotelier Harry S. Bond. It is located near Bushnell Park, and was considered the grandest hotel in Hartford during its heyday. The second section is a 12 story building attached to the 6 story first section. A Statler Hotel opened in the area in 1954, creating competition, and the Bond Hotel company declared bankruptcy shortly after that. It was bought by the California-based Masaglia Hotel chain, which began an incremental renovation program. In 1964 it was sold to a Cincinnati, Ohio investment group which announced extensive renovation plans. However, the financing plans fell through and the hotel was again in bankruptcy. The building was sold at auction to the Roman Catholic Archdiocese of Hartford in 1965, and it became the home of the Saint Francis Hospital School of Nursing. The Bond Ballroom reopened in 2001, with the rest of the building becoming a Homewood Suites by Hilton in 2006.
Title 7 : The Oberoi Group
Paragraph 7 : The Oberoi Group is a hotel company with its head office in Delhi. Founded in 1934, the company owns and/or operates 30+ luxury hotels and two river cruise ships in six countries, primarily under its Oberoi Hotels & Resorts and Trident Hotels brands.
Title 8 : Future Fibre Technologies
Paragraph 8 : Future Fibre Technologies (FFT) is a fiber optic sensing technologies company based in Melbourne, Australia, with its US head office in Mountain View, California, Middle East head office in Dubai, Indian head office in New Delhi and European head office in London. Founded in 1994, Future Fibre Technologies product line provides optical fiber intrusion detection systems for perimeters, buried oil and gas pipelines and data communication networks.
Title 9 : 289th Military Police Company
Paragraph 9 : The 289th Military Police Company was activated on 1 November 1994 and attached to Hotel Company, 3rd Infantry (The Old Guard), Fort Myer, Virginia. Hotel Company is the regiment's specialty company.
Title 10 : Glennwanis Hotel
Paragraph 10 : The Glennwanis Hotel is a historic hotel in Glennville, Georgia, Tattnall County, Georgia, built on the site of the Hughes Hotel. The hotel is located at 209-215 East Barnard Street. The old Hughes Hotel was built out of Georgia pine circa 1905 and burned in 1920. The Glennwanis was built in brick in 1926. The local Kiwanis club led the effort to get the replacement hotel built, and organized a Glennville Hotel Company with directors being local business leaders. The wife of a local doctor won a naming contest with the name "Glennwanis Hotel", a suggestion combining "Glennville" and "Kiwanis".

--------------------------------------------------
Context: Title 1 : Lisa Simpson
Paragraph 1 : Lisa Marie Simpson is a fictional character in the animated television series "The Simpsons". She is the middle child and most intelligent of the Simpson family. Voiced by Yeardley Smith, Lisa first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed her while waiting to meet James L. Brooks. Groening had been invited to pitch a series of shorts based on his comic "Life in Hell", but instead decided to create a new set of characters. He named the elder Simpson daughter after his younger sister Lisa Groening. After appearing on "The Tracey Ullman Show" for three years, the Simpson family were moved to their own series on Fox, which debuted on December 17, 1989.
Title 2 : Marge Simpson
Paragraph 2 : Marjorie Jacqueline "Marge" Simpson (née Bouvier) is a fictional character in the American animated sitcom "The Simpsons" and part of the eponymous family. She is voiced by Julie Kavner and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Marge was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on "Life in Hell" but instead decided to create a new set of characters. He named the character after his mother Margaret Groening. After appearing on "The Tracey Ullman Show" for three seasons, the Simpson family received their own series on Fox, which debuted December 17, 1989.
Title 3 : Bart Simpson
Paragraph 3 : Bartholomew JoJo "Bart" Simpson is a fictional character in the American animated television series "The Simpsons" and part of the Simpson family. He is voiced by Nancy Cartwright and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed Bart while waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip, "Life in Hell", but instead decided to create a new set of characters. While the rest of the characters were named after Groening's family members, Bart's name is an anagram of the word "brat". After appearing on "The Tracey Ullman Show" for three years, the Simpson family received its own series on Fox, which debuted December 17, 1989.
Title 4 : Allie Goertz
Paragraph 4 : Allison Beth "Allie" Goertz (born March 2, 1991) is an American musician. Goertz is known for her satirical songs based on various pop culture topics. Her videos are posted on YouTube under the name of Cossbysweater. Subjects of her songs have included the film "The Room", the character Milhouse from the television show "The Simpsons", and the game Dungeons & Dragons. Her style has been compared to that of Bo Burnham. In December 2015, Goertz released a concept album based on the Adult Swim series "Rick and Morty", "Sad Dance Songs", with the album's cover emulating the animation and logo of the series. The album was made possible through Kickstarter. She is co-host of Everything's Coming Up Podcast, a Simpsons-focused podcast along with Julia Prescott.
Title 5 : Milhouse Van Houten
Paragraph 5 : Milhouse Mussolini van Houten is a fictional character featured in the animated television series "The Simpsons", voiced by Pamela Hayden, and created by Matt Groening who named the character after President Richard Nixon's middle name. Later in the series, it is revealed that Milhouse's middle name is "Mussolini."
Title 6 : Los Angeles Reader
Paragraph 6 : Los Angeles Reader was a weekly paper established in 1978 and distributed in Los Angeles, United States. It followed the format of the (still active) Chicago Reader. The paper was known for having lengthy, thoughtful reviews of movies, plays and concerts in the LA area. James Vowell was its founding editor. Among its writers were Keith Fitzgerald, Nigey Lennon, Lionel Rolfe, Lawrence Wechsler, Mick Farren, Richard Meltzer, Heidi Dvorak, Chris Morris, Jerry Stahl, Steven Kane, Andy Klein, Allen Levy, Jim Goad, Kirk Silsbee, Henry Sheehan, Samantha Dunn, Natalie Nichols, Steve Appleford, Eric Mankin (also editor), Paul Birchall, Eddie Rivera (who wrote the paper's first cover story), Amy Steinberg, Harry Sheehan, Dan Sallit, Myron Meisel, David Ehrenstein. Tom Davis, Bruce Bebb, Stuart Goldman, Ernest Hardy, Kevin Uhrich, Erik Himmelsbach and David L. Ulin. It is famous for being the first newspaper to publish Matt Groening's cartoon strip, Life in Hell on April 25, 1980. James Vowell hired Matt Groening as his assistant editor in 1979. Groening was also originally a Reader music critic. It also ran a cartoon strip by David Lynch (director of Blue Velvet) called The Angriest Dog in the World, a strip notable for having exactly the same drawing panels for its entire run. James Vowell and his wife Codette Wallace bought the Reader from the Chicago Reader in February 1989. They sold "The Reader" to New Times Media in 1996, which merged it with the "Los Angeles View" to form "New Times LA".
Title 7 : Homer Simpson
Paragraph 7 : Homer Jay Simpson is a fictional character and the main protagonist of the American animated television series "The Simpsons" as the patriarch of the eponymous family. He is voiced by Dan Castellaneta and first appeared on television, along with the rest of his family, in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Homer was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip "Life in Hell" but instead decided to create a new set of characters. He named the character after his father, Homer Groening. After appearing for three seasons on "The Tracey Ullman Show", the Simpson family got their own series on Fox that debuted December 17, 1989.
Title 8 : List of The Simpsons video games
Paragraph 8 : "The Simpsons" is an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company. The series is a satirical parody of a middle class American lifestyle epitomized by its eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. It is set in the fictional town of Springfield, and lampoons American culture, society and television, and many aspects of the human condition. The family was conceived by Groening shortly before a pitch for a series of animated shorts with producer James L. Brooks. Groening created a dysfunctional family and named the characters after members of his own family, substituting Bart for his own name. The shorts became a part of "The Tracey Ullman Show" on April 19, 1987 and after a three-season run, the sketch was developed into a half-hour prime time show and became a hit series for Fox. The growing popularity of the series motivated video game developers to create video games based on the series. Two pinball machines have also been produced; one self-titled, that was only made available for a limited time after the first season finale (1990) and "The Simpsons Pinball Party" (2003). Additionally, several handheld device games have been released, such as "Bartman: Avenger of Evil" (1990) and "Bart Simpson's Cupcake Crisis" (1991).
Title 9 : The Simpsons: An Uncensored, Unauthorized History
Paragraph 9 : The Simpsons: An Uncensored, Unauthorized History is a non-fiction book about the American animated television series "The Simpsons". It was written by John Ortved, and first published in October 2009 by Faber and Faber. In the United Kingdom, the book is called Simpsons Confidential: The uncensored, totally unauthorised history of the world's greatest TV show by the people that made it. The book is an oral history of the show, and concentrates particularly on the writers and producers of the show. The book includes entire chapters devoted to key figures such as creator Matt Groening and James L. Brooks and Sam Simon, who helped develop the series. According to National Public Radio reviewer Linda Holmes, "Ortved's thesis, essentially, is that lots of people are responsible for the success of "The Simpsons", and their creator, Matt Groening, has too often been viewed as the sole source to the detriment of others who also deserve to be praised."
Title 10 : List of The Simpsons guest stars
Paragraph 10 : In addition to the show's regular cast of voice actors, celebrity guest stars have been a staple of "The Simpsons", an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company, since its first season. "The Simpsons" focuses on the eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. The family was initially conceived by Groening for a series of animated shorts, which originally aired as a part of "The Tracey Ullman Show" between 1987 and 1989. The shorts were developed into a half-hour prime time series which began in December 1989. The series' 27th season began in September 2015 and episodes of "The Simpsons" have aired. A feature film adaptation of the series called "The Simpsons Movie", was released in 2007.

--------------------------------------------------
Context: Title 1 : Moloch: or, This Gentile World

In [16]:
main_df

,batch_num,question_num,context,question,answer
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long

In [17]:
graphs_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    graphs_str_list = chain.batch(batch)
    graphs_str_batch.append(graphs_str_list)

Batch 1 ... processing 10 items

In [18]:
for i, graphs_str_list in enumerate(graphs_str_batch):
    print(f"Batch {i + 1} ... processed {len(graphs_str_list)} items")
    for j, graph_str in enumerate(graphs_str_list):
        print(f"Item {j + 1}:")
        print(graph_str)
        print("-" * 50)

Batch 1 ... processed 10 items
Item 1:
### CONTEXT_REASONING
Entities were identified by reviewing titles and paragraphs for unique names of organizations, people, places, dates, publications, and events. For relationship extraction, I selected explicit relationships (like "founded by", "edited by", "launched in", "published by", "certified by", etc.) and inferred logical relationships (like geographic locations, temporal spans, participation in events, evolution of organizations, etc.) where information was clear and unambiguous. Temporal spans (start/end dates), mergers, certifications, and transitions in organization structures were systematically extracted. Relationships involving products (e.g., songs, albums, clothing lines) and their associations (e.g., certified by, released on) were included when directly mentioned or unequivocally implied.

### CONTEXT_TRIPLES
(Radio City, is a, FM radio station)
(Radio City, is located in, India)
(Radio City, was started on, 3 July 2001)
(Radio City, broadcasts on, 91.1 MHz)
(Radio City, earlier broadcast on, 91.0 MHz)
(Radio City, broadcasts from, Mumbai)
(Radio City, started in, Mumbai)
(Radio City, started in, 2004)
(Radio City, broadcasts from, Bengaluru)
(Radio City, started in, Bengaluru)
(Radio City, started in, 2001)
(Radio City, broadcasts from, Lucknow)
(Radio City, broadcasts from, New Delhi)
(Radio City, started in, New Delhi)
(Radio City, started in, 2003)
(Radio City, plays, Hindi songs)
(Radio City, plays, English songs)
(Radio City, plays, regional songs)
(Radio City, launched in, Hyderabad)
(Radio City, launched in, March 2006)
(Radio City, launched in, Chennai)
(Radio City, launched in, 7 July 2006)
(Radio City, launched in, Visakhapatnam)
(Radio City, launched in, October 2007)
(Radio City, forayed into, New Media)
(Radio City, launched, PlanetRadiocity.com)
(PlanetRadiocity.com, was launched in, May 2008)
(PlanetRadiocity.com, offers, music related news)
(PlanetRadiocity.com, offers, music videos)
(PlanetRadiocity.com, offers, songs)
(PlanetRadiocity.com, offers, music-related features)
(Radio City, currently plays, Hindi music)
(Radio City, currently plays, Regional music)
(Abraham Thomas, is CEO of, Radio City)
(Football, existed in, Albania)
(Football in Albania, existed before, Albanian Football Federation)
(Albanian Football Federation, abbreviation, FSHF)
(Albania national football team, was registered at, Balkan Cup tournament)
(Balkan Cup tournament, took place during, 1929-1931)
(Balkan Cup tournament, started in, 1929)
(Albanian National Team, was founded on, 6 June 1930)
(Albania national football team, played first international match in, 1946)
(Albania national football team, defeated, Yugoslavia)
(Albania, joined, FIFA)
(Albania, joined FIFA in, June 1932)
(Albania, joined FIFA during, 12–16 June 1932 convention)
(Albania, was founding member of, UEFA)
(Albania, became founding member of UEFA in, 1954)
(Echosmith, is a, band)
(Echosmith, is located in, United States)
(Echosmith, is from, Chino, California)
(Echosmith, was formed in, February 2009)
(Echosmith, originally formed as, quartet of siblings)
(Echosmith, currently consists of, Sydney Sierota)
(Echosmith, currently consists of, Noah Sierota)
(Echosmith, currently consists of, Graham Sierota)
(Jamie Sierota, departed from, Echosmith)
(Jamie Sierota, departed in, late 2016)
(Echosmith, started first as, Ready Set Go!)
(Echosmith, signed to, Warner Bros. Records)
(Echosmith, signed with Warner Bros. Records in, May 2012)
(Echosmith, is best known for, Cool Kids)
(Cool Kids, is a, song)
(Cool Kids, reached number, 13)
(Cool Kids, charted on, Billboard Hot 100)
(Cool Kids, was certified, double platinum)
(Cool Kids, was certified by, RIAA)
(Cool Kids, achieved sales of, over 1,200,000 in United States)
(Cool Kids, was certified, double platinum by ARIA)
(Cool Kids, was certified in, Australia)
(Cool Kids, was, Warner Bros. Records' fifth-biggest-selling-digital song of 2014)
(Cool Kids, had downloads sold, 1.3 million)
(Echosmith, released debut album, Talking Dreams)
(Talking Dreams, was released on, 8 October 2013)
(Women's colleges in the Southern United States, are, undergraduate institutions)
(Women's colleges in the Southern United States, grant, bachelor’s degrees)
(Women's colleges in the Southern United States, are often, liberal arts colleges)
(Women's colleges in the Southern United States, are located in, Southern United States)
(Women's colleges in the Southern United States, student population is, exclusively or almost exclusively women)
(Many Southern women's colleges, started as, girls' seminaries or academies)
(Salem College, is, oldest female educational institution in the South)
(Wesleyan College, is, first college established specifically for women in South)
(Mary Baldwin University, offers, coeducational courses at graduate level)
(Salem College, offers, coeducational courses at graduate level)
(First Arthur County Courthouse and Jail, is located in, United States)
(First Arthur County Courthouse and Jail, was, perhaps the smallest courthouse in United States)
(First Arthur County Courthouse and Jail, currently serves as, museum)
(Arthur's Magazine, was a, literary periodical)
(Arthur's Magazine, was published in, Philadelphia)
(Arthur's Magazine, was published in, United States)
(Arthur's Magazine, was published during, 1844–1846)
(Arthur's Magazine, was edited by, T.S. Arthur)
(Arthur's Magazine, featured work by, Edgar A. Poe)
(Arthur's Magazine, featured work by, J.H. Ingraham)
(Arthur's Magazine, featured work by, Sarah Josepha Hale)
(Arthur's Magazine, featured work by, Thomas G. Spear)
(Arthur's Magazine, merged into, Godey's Lady's Book)
(Arthur's Magazine, merged in, May 1846)
(2014–15 Ukrainian Hockey Championship, was, 23rd season of Ukrainian Hockey Championship)
(2014–15 Ukrainian Hockey Championship, had, four teams)
(2014–15 Ukrainian Hockey Championship, season started after, 2014 year-end)
(Generals Kiev, participated in, 2014–15 Ukrainian Hockey Championship)
(Generals Kiev, also participated in, previous season)
(2014–15 Ukrainian Hockey Championship, regular season included, 12 rounds)
(All teams, qualified for, semifinals)
(ATEK Kiev, defeated, HK Kremenchuk)
(ATEK Kiev, defeated HK Kremenchuk in, final)
(HK Kremenchuk, was, regular season winner)
(First for Women, is a, woman's magazine)
(First for Women, is published by, Bauer Media Group)
(First for Women, is published in, United States)
(First for Women, was started in, 1989)
(First for Women, is based in, Englewood Cliffs, New Jersey)
(First for Women, had circulation of, 1,310,696 copies)
(First for Women, circulation figure in, 2011)
(Freeway Complex Fire, was a, wildfire)
(Freeway Complex Fire, occurred in, Santa Ana Canyon)
(Freeway Complex Fire, occurred in, Orange County, California)
(Freeway Complex Fire, occurred in, 2008)
(Freeway Complex Fire, started as, two separate fires)
(Freeway Fire, started first, after 9am, 15 November 2008)
(Landfill Fire, ignited, approximately 2 hours later)
(Freeway Complex Fire, two fires merged, a day later)
(Freeway Complex Fire, destroyed, 314 residences)
(Fire destroyed residences in, Anaheim Hills)
(Fire destroyed residences in, Yorba Linda)
(William Rast, is a, clothing line)
(William Rast, is located in, United States)
(William Rast, was founded by, Justin Timberlake)
(William Rast, was founded by, Trace Ayala)
(William Rast, is known for, premium jeans)
(William Rast, launched first fashion show on, 17 October 2006)
(William Rast, fashion show launched, William Rast clothing line)
(William Rast, produces, jackets)
(William Rast, produces, tops)
(William Rast, started as, denim line)
(William Rast, evolved into, men’s and women’s clothing line)
--------------------------------------------------
Item 2:
### CONTEXT_REASONING
First, I reviewed each paragraph and title for key entities: hotel names (Ritz-Carlton Jakarta, Hotel Tallcorn, Hotel Bond, Glennwanis Hotel), people (Mohan Singh Oberoi, Harry S. Bond), organizations (The Oberoi Group, Eppley Hotel Company, Sheraton Corporation, Oberoi family, Star Plus, Masaglia Hotel chain, Roman Catholic Archdiocese of Hartford, Saint Francis Hospital School of Nursing, Kiwanis club, Glennville Hotel Company, Homewood Suites by Hilton), places (Jakarta, Mega Kuningan, Marshalltown, Iowa, Hartford, Connecticut, Bushnell Park, Cincinatti, Ohio, Glennville, Tattnall County, Georgia, East Barnard Street, India, Sri Lanka, Nepal, Egypt, Australia, Hungary, Delhi, Melbourne, Mountain View, Dubai, New Delhi, London, Virginia, Fort Myer, Georgia), events (opening or sale years), and TV series (Ishqbaaaz, Dil Boley Oberoi).

For relationships, I connected:
- Hotels to their locations, owners/operators, and significant dates (founding, opening, sales).
- People to organizations they've founded or chaired (Mohan Singh Oberoi and Oberoi Hotels & Resorts).
- Families (Oberoi) to hotel groups and TV portrayals (Ishqbaaaz heirs).
- TV series to networks, air dates, characters, and spinoffs.
- Structural and temporal events such as company bankruptcies, mergers, renamings, and historic designations.
- Places as headquarters for organizations (FFT offices, Oberoi Group HQ).
- Explicit or implicit founding and contribution roles (Kiwanis club for Glennwanis Hotel).
- Geographical coverage of hotel companies.
- Distilled logically inferable but clear relationships (e.g., timeline merges in TV series, adjacency of hotels, or changes in property use).

### CONTEXT_TRIPLES
(Ritz-Carlton Jakarta, is located in, Jakarta)
(Ritz-Carlton Jakarta, is a, hotel)
(Ritz-Carlton Jakarta, is a, skyscraper)
(Ritz-Carlton Jakarta, is operated by, The Ritz-Carlton Hotel Company)
(Ritz-Carlton Jakarta, is near, Mega Kuningan)
(Ritz-Carlton Jakarta, is adjacent to, JW Marriott Hotel)
(Ritz-Carlton Jakarta, opened in, 2005)
(Ritz-Carlton Jakarta, has part, two towers)
(Ritz-Carlton Jakarta, contains, Airlangga Apartment)
(Ritz-Carlton Jakarta, is the, 14th Tallest building in Jakarta)
(Oberoi family, is based in, India)
(Oberoi family, is involved in, hotels)
(Oberoi family, is involved with, The Oberoi Group)
(Ishqbaaaz, is a, Indian drama television series)
(Ishqbaaaz, is broadcast on, Star Plus)
(Ishqbaaaz, premiered on, 27 June 2016)
(Ishqbaaaz, airs, Mon-Fri 10-11pm IST)
(Ishqbaaaz, features character, Shivaay)
(Ishqbaaaz, features character, Omkara)
(Ishqbaaaz, features character, Rudra)
(Nakuul Mehta, portrays, Shivaay)
(Kunal Jaisingh, portrays, Omkara)
(Leenesh Mattoo, portrays, Rudra)
(Shivaay, is heir of, Oberoi family)
(Omkara, is heir of, Oberoi family)
(Rudra, is heir of, Oberoi family)
(Ishqbaaaz, focused on, tale of three brothers)
(Ishqbaaaz, later centered on, love story of Shivaay and Annika)
(Annika, is portrayed by, Surbhi Chandna)
(Story of Omkara and Rudra, was shifted to, Dil Boley Oberoi)
(Dil Boley Oberoi, is a, spinoff series of Ishqbaaaz)
(Dil Boley Oberoi, ended in, July 2017)
(Dil Boley Oberoi, storyline merged into, Ishqbaaaz)
(Ishqbaaaz, runtime, doubled after July 2017)
(Hotel Tallcorn, is located in, Marshalltown)
(Hotel Tallcorn, is located in, Iowa)
(Hotel Tallcorn, today called, Tallcorn Towers Apartments)
(Hotel Tallcorn, was built in, 1928)
(Hotel Tallcorn, was built by, Eppley Hotel Company)
(Citizens of Marshalltown, contributed, $120,000)
(Hotel Tallcorn, was completed for, 75th anniversary of Marshalltown)
(Hotel Tallcorn, was sold from, Eppley Hotel Company)
(Hotel Tallcorn, was sold to, Sheraton Corporation)
(Sale of Hotel Tallcorn, took place in, 1956)
(Sale of Hotel Tallcorn, was part of, second largest hotel sale in US history)
(Hotel Tallcorn, listed as contributing property in, Marshalltown Downtown Historic District)
(Marshalltown Downtown Historic District, listed on, National Register of Historic Places)
(Listing on National Register of Historic Places for Hotel Tallcorn, was in, 2002)
(Mohan Singh Oberoi, was born on, 15 August 1898)
(Mohan Singh Oberoi, died on, 3 May 2002)
(Mohan Singh Oberoi, is a, Indian hotelier)
(Mohan Singh Oberoi, founded, Oberoi Hotels & Resorts)
(Mohan Singh Oberoi, was chairman of, Oberoi Hotels & Resorts)
(Oberoi Hotels & Resorts, is, India's second-largest hotel company)
(Oberoi Hotels & Resorts, operated, 35 hotels)
(Oberoi Hotels & Resorts, operates in, India)
(Oberoi Hotels & Resorts, operates in, Sri Lanka)
(Oberoi Hotels & Resorts, operates in, Nepal)
(Oberoi Hotels & Resorts, operates in, Egypt)
(Oberoi Hotels & Resorts, operates in, Australia)
(Oberoi Hotels & Resorts, operates in, Hungary)
(Hotel Bond, is located in, Hartford)
(Hotel Bond, is located in, Connecticut)
(Hotel Bond, is historic, True)
(Hotel Bond, was built in, 1913)
(Hotel Bond, was expanded in, 1921)
(Hotel Bond, was built by, Harry S. Bond)
(Harry S. Bond, is a, hotelier)
(Hotel Bond, is located near, Bushnell Park)
(Hotel Bond, had, 6 story first section)
(Hotel Bond, had, 12 story second section)
(A Statler Hotel, opened in, Hartford)
(A Statler Hotel, opened in, 1954)
(Statler Hotel opening, created competition for, Hotel Bond)
(Bond Hotel company, declared bankruptcy after, 1954)
(Hotel Bond, was bought by, Masaglia Hotel chain)
(Masaglia Hotel chain, began, incremental renovation program at Hotel Bond)
(Hotel Bond, was sold to, Cincinnati investment group)
(Sale to Cincinnati group, occurred in, 1964)
(Cincinnati investment group, announced, extensive renovation plans for Hotel Bond)
(Financing plans, failed for, Hotel Bond renovation)
(Hotel Bond, went bankrupt again after, failed financing)
(Hotel Bond, was sold at auction to, Roman Catholic Archdiocese of Hartford)
(Sale to Archdiocese, took place in, 1965)
(Hotel Bond, became home of, Saint Francis Hospital School of Nursing)
(Bond Ballroom, reopened in, 2001)
(The rest of Hotel Bond building, became, Homewood Suites by Hilton)
(Homewood Suites by Hilton at Hotel Bond, opened in, 2006)
(The Oberoi Group, is a, hotel company)
(The Oberoi Group, headquarters in, Delhi)
(The Oberoi Group, founded in, 1934)
(The Oberoi Group, owns or operates, 30+ luxury hotels)
(The Oberoi Group, operates, two river cruise ships)
(The Oberoi Group, operates in, six countries)
(The Oberoi Group, operates brands, Oberoi Hotels & Resorts)
(The Oberoi Group, operates brands, Trident Hotels)
(Future Fibre Technologies, is based in, Melbourne)
(Future Fibre Technologies, US head office, Mountain View)
(Future Fibre Technologies, Middle East head office, Dubai)
(Future Fibre Technologies, Indian head office, New Delhi)
(Future Fibre Technologies, European head office, London)
(Future Fibre Technologies, founded in, 1994)
(Future Fibre Technologies, provides, optical fiber intrusion detection systems)
(Optical fiber intrusion detection systems, used for, perimeters)
(Optical fiber intrusion detection systems, used for, buried oil and gas pipelines)
(Optical fiber intrusion detection systems, used for, data communication networks)
(289th Military Police Company, was activated on, 1 November 1994)
(289th Military Police Company, attached to, Hotel Company, 3rd Infantry (The Old Guard))
(289th Military Police Company, is based at, Fort Myer)
(Fort Myer, is located in, Virginia)
(Hotel Company (3rd Infantry), is specialty company of, regiment)
(Glennwanis Hotel, is a, historic hotel)
(Glennwanis Hotel, is located in, Glennville)
(Glennwanis Hotel, is located in, Tattnall County)
(Tattnall County, is located in, Georgia)
(Glennwanis Hotel, is located at, 209-215 East Barnard Street)
(Glennwanis Hotel, built on site of, Hughes Hotel)
(Hughes Hotel, was built out of, Georgia pine)
(Hughes Hotel, was built circa, 1905)
(Hughes Hotel, burned in, 1920)
(Glennwanis Hotel, was built in, 1926)
(Glennwanis Hotel, was built in, brick)
(Kiwanis club, led effort to build, Glennwanis Hotel)
(Glennville Hotel Company, organized by, Kiwanis club)
(Glennville Hotel Company, had directors who were, local business leaders)
(Naming contest, won by, wife of a local doctor)
(Name "Glennwanis Hotel", suggested by, wife of a local doctor)
(Name "Glennwanis Hotel", combines, Glennville)
(Name "Glennwanis Hotel", combines, Kiwanis)
(Glennwanis Hotel, replaced, Hughes Hotel)
--------------------------------------------------
Item 3:
### CONTEXT_REASONING
Entities selected include canonical names for characters (Lisa Simpson, Marge Simpson, Bart Simpson, Homer Simpson, Milhouse Van Houten), real people (Matt Groening, James L. Brooks, Yeardley Smith, Julie Kavner, Nancy Cartwright, Pamela Hayden, John Ortved, Sam Simon, Julia Prescott, Allie Goertz, Codette Wallace, James Vowell), organizations and publications (The Simpsons, The Tracey Ullman Show, Fox, Los Angeles Reader, Chicago Reader, New Times Media, New Times LA, Faber and Faber, National Public Radio, Adult Swim), works (Life in Hell, The Room, Dungeons & Dragons, Rick and Morty, Everything's Coming Up Podcast, The Angriest Dog in the World, The Simpsons Movie, Simpsons Confidential), locations (Los Angeles, Springfield, United States, United Kingdom), events/times (April 19, 1987, April 25, 1980, December 17, 1989, 1978, February 1989, 1996, 2007, September 2015, 1990, 1991, 2003, December 2015, March 2, 1991, October 2009), and other contributors (various writers of Los Angeles Reader). Relationships extracted include creators, voice actors, original appearances, basis for character names, publication and operational dates, publisher relationships, authorship, audio and editorial roles, mergers, and series developments. Inferred but unambiguous facts include relationships within the Simpson family, the sequence of the show’s development, and the use of real family names as inspiration for character names.

### CONTEXT_TRIPLES
(Lisa Simpson, is character in, The Simpsons)
(Lisa Simpson, is member of, Simpson family)
(Lisa Simpson, voiced by, Yeardley Smith)
(Lisa Simpson, first appeared on, The Tracey Ullman Show)
(Lisa Simpson, first appeared in, Good Night)
(Lisa Simpson, first appeared on, April 19, 1987)
(Lisa Simpson, created by, Matt Groening)
(Lisa Simpson, named after, Lisa Groening)
(Lisa Simpson, is daughter of, Homer Simpson)
(Lisa Simpson, is daughter of, Marge Simpson)
(Lisa Simpson, is sibling of, Bart Simpson)
(Matt Groening, created, Lisa Simpson)
(Marge Simpson, is character in, The Simpsons)
(Marge Simpson, is member of, Simpson family)
(Marge Simpson, voiced by, Julie Kavner)
(Marge Simpson, first appeared on, The Tracey Ullman Show)
(Marge Simpson, first appeared in, Good Night)
(Marge Simpson, first appeared on, April 19, 1987)
(Marge Simpson, created by, Matt Groening)
(Marge Simpson, named after, Margaret Groening)
(Marge Simpson, maiden name, Bouvier)
(Marge Simpson, is mother of, Bart Simpson)
(Marge Simpson, is mother of, Lisa Simpson)
(Marge Simpson, is mother of, Maggie Simpson)
(Marge Simpson, is wife of, Homer Simpson)
(Bart Simpson, is character in, The Simpsons)
(Bart Simpson, is member of, Simpson family)
(Bart Simpson, voiced by, Nancy Cartwright)
(Bart Simpson, first appeared on, The Tracey Ullman Show)
(Bart Simpson, first appeared in, Good Night)
(Bart Simpson, first appeared on, April 19, 1987)
(Bart Simpson, created by, Matt Groening)
(Bart Simpson, name is anagram of, brat)
(Bart Simpson, is son of, Homer Simpson)
(Bart Simpson, is son of, Marge Simpson)
(Bart Simpson, is sibling of, Lisa Simpson)
(Matt Groening, created, Bart Simpson)
(Homer Simpson, is character in, The Simpsons)
(Homer Simpson, is member of, Simpson family)
(Homer Simpson, voiced by, Dan Castellaneta)
(Homer Simpson, first appeared on, The Tracey Ullman Show)
(Homer Simpson, first appeared in, Good Night)
(Homer Simpson, first appeared on, April 19, 1987)
(Homer Simpson, created by, Matt Groening)
(Homer Simpson, named after, Homer Groening)
(Homer Simpson, is husband of, Marge Simpson)
(Homer Simpson, is father of, Bart Simpson)
(Homer Simpson, is father of, Lisa Simpson)

In [19]:
graphs_str_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "graphs_str": []
})

for i, graphs_str_list in enumerate(graphs_str_batch):
    batch_num_list = [i] * len(graphs_str_list)
    question_num_list = list(range(1, len(graphs_str_list) + 1))
    graphs_str_df = pd.concat([graphs_str_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "graphs_str": graphs_str_list
    })], ignore_index=True)

del graphs_str_batch
del graphs_str_list
del batch_input_list
del batch_context
del batch_question
del batch_answer

graphs_str_df

   batch_num  question_num                                         graphs_str
0        0.0           1.0  ### CONTEXT_REASONING\nEntities were identifie...
1        0.0           2.0  ### CONTEXT_REASONING\nFirst, I reviewed each ...
2        0.0           3.0  ### CONTEXT_REASONING\nEntities selected inclu...
3        0.0           4.0  ### CONTEXT_REASONING\nI first identified uniq...
4        0.0           5.0  ### CONTEXT_REASONING\nFirst, I identified ent...
5        0.0           6.0  ### CONTEXT_REASONING\nEntities were extracted...
6        0.0           7.0  ### CONTEXT_REASONING\nEntities were identifie...
7        0.0           8.0  ### CONTEXT_REASONING\nI read through each tit...
8        0.0           9.0  ### CONTEXT_REASONING\nEntities were extracted...
9        0.0          10.0  ### CONTEXT_REASONING\nEntities were identifie...

## 3. Parsing the Output and Building KGs

In [20]:
import re
from ast import literal_eval

def sanitize_str(name):
    """
    Sanitize a name by removing extra spaces, apostrophes, and ensuring proper formatting.
    """
    # Replace apostrophes with empty string
    name = name.replace("'s", "s")
    name = name.replace("'", "")

    # Replace spaces with underscores
    name = name.replace(" ", "_")
    name = name.replace("–", "_")

    # Remove any other problematic characters
    name = re.sub(r'[^\w\-_]', '', name)

    # Prefix if starts with digit
    if re.match(r"^\d", name):
        name = f"n{name}"

    # If empty string, return something safe
    if not name:
        name = "unknown"

    return name

def sanitize_entities_and_relations(triple):
    """
    Sanitize entities and relations in a triple by removing extra spaces and ensuring proper formatting.
    """
    return (
        sanitize_str(triple[0].strip().lower()),  # Subject
        sanitize_str(triple[1].strip().lower()),  # Relation
        sanitize_str(triple[2].strip().lower())   # Object
    )


def parse_custom_triples(triples_str):
    triples = []
    for line in triples_str.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        # Remove enclosing parentheses
        if line.startswith('(') and line.endswith(')'):
            line = line[1:-1]
        # Now, split ONLY on the first two commas
        parts = []
        remaining = line
        for _ in range(2):
            # Find the first comma
            idx = remaining.find(',')
            if idx == -1:
                break
            parts.append(remaining[:idx].strip())
            remaining = remaining[idx+1:].strip()
        parts.append(remaining)
        if len(parts) == 3:
            triples.append(sanitize_entities_and_relations(tuple(parts)))
    return triples

def extract_sections(text, reasoning_pat, triples_pat):
    # Extract sections using regex
    extracted_reasoning = re.search(reasoning_pat, text, re.DOTALL)
    extracted_triples = re.search(triples_pat, text, re.DOTALL)

    # Clean reasoning sections
    reasoning_str = extracted_reasoning.group(1).strip() if extracted_reasoning else ""

    # Use the custom parser for triples
    triples_list = parse_custom_triples(extracted_triples.group(1)) if extracted_triples else []

    return reasoning_str, triples_list

def extract_context_to_columns(row):
    # Regex patterns for section headers
    context_reasoning_pat = r'### CONTEXT_REASONING\s*(.*?)\s*### CONTEXT_TRIPLES'
    context_triples_pat = r'### CONTEXT_TRIPLES\s*(.*)'

    context_reasoning, context_triples = extract_sections(row['graphs_str'], context_reasoning_pat, context_triples_pat)
    return pd.Series([context_reasoning, context_triples],
                     index=['context_reasoning', 'context_triples'])

In [21]:
graphs_str_df[['context_reasoning', 'context_triples']] = graphs_str_df.apply(extract_context_to_columns, axis=1)
graphs_str_df

,batch_num,question_num,graphs_str,context_reasoning,context_triples
0,0.0,1.0,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified by reviewing titles a...,"[(radio_city, is_a, fm_radio_station), (radio_..."
1,0.0,2.0,"### CONTEXT_REASONING\nFirst, I reviewed each ...","First, I reviewed each paragraph and title for...","[(ritz-carlton_jakarta, is_located_in, jakarta..."
2,0.0,3.0,### CONTEXT_REASONING\nEntities selected inclu...,Entities selected include canonical names for ...,"[(lisa_simpson, is_character_in, the_simpsons)..."
3,0.0,4.0,### CONTEXT_REASONING\nI first identified uniq...,"I first identified unique entities, focusing o...","[(moloch_or, this_gentile_world, is_a_novel), ..."
4,0.0,5.0,"### CONTEXT_REASONING\nFirst, I identified ent...","First, I identified entities such as compounds...","[(cadmium_chloride, has_formula, cdcl), (cadmi..."
5,0.0,6.0,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted based on person names ...,"[(li_na, born_on, n26_february_1982), (li_na, ..."
6,0.0,7.0,### CONTEXT_REASONING\nEntities were identifie...,"Entities were identified as countries (India, ...","[(india, official_name, republic_of_india), (i..."
7,0.0,8.0,### CONTEXT_REASONING\nI read through each tit...,"I read through each title and paragraph, ident...","[(verano_de_escándalo_1998, is_a, professional..."
8,0.0,9.0,### CONTEXT_REASONING\nEntities were extracted...,"Entities were extracted from series titles, cr...","[(house_of_anubis, is_a_television_series_deve..."
9,0.0,10.0,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified by parsing titles and...,"[(mount_panorama_circuit, located_in, bathurst..."

In [22]:
main_df = main_df.merge(graphs_str_df, on=['batch_num', 'question_num'], how='left')
# del graphs_str_df
main_df

,batch_num,question_num,context,question,answer,graphs_str,context_reasoning,context_triples
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified by reviewing titles a...,"[(radio_city, is_a, fm_radio_station), (radio_..."
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi,"### CONTEXT_REASONING\nFirst, I reviewed each ...","First, I reviewed each paragraph and title for...","[(ritz-carlton_jakarta, is_located_in, jakarta..."
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,### CONTEXT_REASONING\nEntities selected inclu...,Entities selected include canonical names for ...,"[(lisa_simpson, is_character_in, the_simpsons)..."
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American,### CONTEXT_REASONING\nI first identified uniq...,"I first identified unique entities, focusing o...","[(moloch_or, this_gentile_world, is_a_novel), ..."
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol,"### CONTEXT_REASONING\nFirst, I identified ent...","First, I identified entities such as compounds...","[(cadmium_chloride, has_formula, cdcl), (cadmi..."
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted based on person names ...,"[(li_na, born_on, n26_february_1982), (li_na, ..."
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae,### CONTEXT_REASONING\nEntities were identifie...,"Entities were identified as countries (India, ...","[(india, official_name, republic_of_india), (i..."
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari,### CONTEXT_REASONING\nI read through each tit...,"I read through each title and paragraph, ident...","[(verano_de_escándalo_1998, is_a, professional..."
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006,### CONTEXT_REASONING\nEntities were extracted...,"Entities were extracted from series titles, cr...","[(house_of_anubis, is_a_television_series_deve..."
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified by parsing titles and...,"[(mount_panorama_circuit, located_in, bathurst..."

In [23]:
# Loop through each row. Save the context triples as OWL KG files
from rdflib import Graph, Namespace, RDF, RDFS, OWL, URIRef
import os

def save_kg_from_triples(triples, batch_num, question_num):
    g = Graph()
    EX = Namespace("http://example.org/")

    # Add triples to the graph
    for subject, relation, obj in triples:
        subject_uri = URIRef(EX[subject])
        object_uri = URIRef(EX[obj])
        g.add((subject_uri, URIRef(EX[relation]), object_uri))

    # Define the file path
    file_path = f"{KNOWLEDGE_GRAPH_PATH}/{DATASET_NAME}_ontology_b{batch_num}_q{question_num}.rdf"

    # Save the graph in OWL format
    g.serialize(destination=file_path, format='xml')
    print(f"Saved KG for batch {batch_num}, question {question_num} to {file_path}")

for index, row in main_df.iterrows():
    batch_num = row['batch_num']
    question_num = row['question_num']
    context_triples = row['context_triples']

    if context_triples:  # Only save if there are context triples
        save_kg_from_triples(context_triples, batch_num, question_num)

Saved KG for batch 0, question 1 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q1.rdf
Saved KG for batch 0, question 2 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q2.rdf
Saved KG for batch 0, question 3 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q3.rdf
Saved KG for batch 0, question 4 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q4.rdf
Saved KG for batch 0, question 5 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q5.rdf
Saved KG for batch 0, question 6 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q6.rdf
Saved KG for batch 0, question 7 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q7.rdf
Saved KG for batch 0, question 8 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q8.rdf
Saved KG for batch 0, question 9 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q9.rdf
Saved KG for batch 0, question 10 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q10.rdf

## 4. Extracting Entities from Questions

In [24]:
batch_input_list = []

for i in range(0, main_df.shape[0], BATCH_SIZE):
    batch_df = main_df.iloc[i:i+BATCH_SIZE]
    batch_input_item = []

    for i, (index, row) in enumerate(batch_df.iterrows()):
        batch_input_item.append({
            "question": row['question']
        })
    batch_input_list.append(batch_input_item)

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1}:")
    for item in batch:
        print("Question:", item['question'])
        print("-" * 50)

Batch 1:
Question: Which magazine was started first Arthur's Magazine or First for Women?
--------------------------------------------------
Question: The Oberoi family is part of a hotel company that has a head office in what city?
--------------------------------------------------
Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
--------------------------------------------------
Question:  What nationality was James Henry Miller's wife?
--------------------------------------------------
Question: Cadmium Chloride is slightly soluble in this chemical, it is also called what?
--------------------------------------------------
Question: Which tennis player won more Grand Slam titles, Henri Leconte or Jonathan Stark?
--------------------------------------------------
Question: Which genus of moth in the world's seventh-largest country contains only one species?
--------------------------------------------------
Question: Who was once considered the best kick boxer in the world, however he has been involved in a number of controversies relating to his "unsportsmanlike conducts" in the sport and crimes of violence outside of the ring.
--------------------------------------------------
Question: The Dutch-Belgian television series that "House of Anubis" was based on first aired in what year?
--------------------------------------------------
Question: What is the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged?
--------------------------------------------------

In [25]:
system_msg = """
<role>
    You are an expert in natural language understanding and knowledge graph construction. Your task is to convert a provided question into a set of question triples, using simple variable names (such as x, y, z, i, j, k) for unknown entities or values to be inferred.
</role>

<behavior>
    <rule name="Entity Extraction">
        Identify and extract unique entities. Use canonical names.
    </rule>
    <rule name="Relationship Extraction">
        Extract explicit or clear implicit relationships between entities as (subject, relation, object) triples.
    </rule>
    <rule name="Temporal and Comparative Relations">
        Use relations like "started in", "founded by", "wrote a song about", "is named after", etc., matching the logic and semantics in the context or question.
    </rule>
    <rule name="Variable Placeholders for Unknowns">
        For each unknown or answer to be found in the question, use a simple English variable (x, y, z, i, j, k, etc.) in place of the answer within the triples. Each distinct unknown in the question gets a unique variable.
    </rule>
    <rule name="Question Triple Decomposition">
        For each question, decompose it into one or more triples, using variable placeholders for any unknowns to be inferred from the context.
        Examples:
        - "Which magazine was started first Arthur's Magazine or First for Women?"
           (Arthur's Magazine, started in, x)
           (First for Women, started in, y)
        - "The Oberoi family is part of a hotel company that has a head office in what city?"
           (Oberoi family, is part of, x)
           (x, has head office in, y)
    </rule>
    <rule name="Formatting and Output">
        Output must contain four sections, in order:
        1. ### QUESTION_REASONING — a step-by-step reasoning of how the question was decomposed into question triples
        2. ### QUESTIONS_TRIPLES — list the question triples, each on its own line. each on its own line in the format (entity_1, relationship, entity_2)
        Do not add explanations, numbering, or extra text.
    </rule>
</behavior>

<format>
1. Carefully read the <question> section.
2. Before extracting question triples, explain step by step how you break down the question and assign variable placeholders. Print this heading:
   ### QUESTION_REASONING
   Then write your reasoning in clear, concise steps.
3. After reasoning, print the question triples. Print this heading:
   ### QUESTIONS_TRIPLES
   List each question triple on a new line, using variable placeholders (x, y, z, etc.) for unknowns.
4. After the last question triple, end with no extra text or parentheses.
</format>
"""

human_msg = """
<question>
{question}
</question>
"""

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [26]:
chain = prompt | llm_model | StrOutputParser()

In [27]:
question_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    question_str_list = chain.batch(batch)
    question_str_batch.append(question_str_list)

Batch 1 ... processing 10 items

In [28]:
for i, question_str_list in enumerate(question_str_batch):
    print(f"Batch {i + 1} ... processed {len(question_str_list)} items")
    for j, graph_str in enumerate(question_str_list):
        print(f"Item {j + 1}:")
        print(graph_str)
        print("-" * 50)

Batch 1 ... processed 10 items
Item 1:
### QUESTION_REASONING
The question is asking for a comparison between two magazines: Arthur's Magazine and First for Women. The explicit property in question is the start date ("was started first"), which involves the dates each magazine was started. Since the actual start dates are unknowns, assign variables (x for Arthur's Magazine and y for First for Women). To infer which was "started first," we need both start years as separate unknowns in the triples.

### QUESTIONS_TRIPLES
(Arthur's Magazine, started in, x)
(First for Women, started in, y)
--------------------------------------------------
Item 2:
### QUESTION_REASONING
First, I identify the main entities mentioned: "Oberoi family", "hotel company", and "city" (unknown). The question asks for the city where the hotel company (of which the Oberoi family is part) has its head office. The specific hotel company is not named but is associated with the Oberoi family. The unknown to find is the city, which receives the placeholder variable (x).

To decompose: The Oberoi family is part of some hotel company (assign variable y to the hotel company). That hotel company (y) has its head office in city (x).

### QUESTIONS_TRIPLES
(Oberoi family, is part of, y)
(y, has head office in, x)
--------------------------------------------------
Item 3:
### QUESTION_REASONING
First, identify the entities: Allie Goertz, "The Simpsons", Milhouse, and Matt Groening. The question statement gives (Allie Goertz, wrote a song about, Milhouse) and (Milhouse, is a character in, The Simpsons). The core question to answer is: Who did Matt Groening name Milhouse after? Here, the person Milhouse is named after is unknown and will be represented as x. So we extract: (Matt Groening, named Milhouse after, x).

### QUESTIONS_TRIPLES
(Allie Goertz, wrote a song about, Milhouse)
(Milhouse, is a character in, The Simpsons)
(Matt Groening, named Milhouse after, x)
--------------------------------------------------
Item 4:
### QUESTION_REASONING
The question is asking about the nationality of James Henry Miller's wife. The entity "James Henry Miller" is known. The wife is an unknown person related to James Henry Miller as "wife," so I represent her as variable x. The nationality of x is the answer being sought, so I use another variable y for this unknown value.

### QUESTIONS_TRIPLES
(James Henry Miller, has wife, x)
(x, has nationality, y)
--------------------------------------------------
Item 5:
### QUESTION_REASONING
First, identify the statements within the question. The question mentions Cadmium Chloride and a chemical in which it is slightly soluble. The chemical's name is not specified (unknown), so assign a variable (x) for it. The question then asks for an alternative name for Cadmium Chloride, which is also unknown (assign y). Decompose into two relationships: one about the solubility and one about the alternative name.

### QUESTIONS_TRIPLES
(Cadmium Chloride, is slightly soluble in, x)
(Cadmium Chloride, is also called, y)
--------------------------------------------------
Item 6:
### QUESTION_REASONING
The question is comparing the number of Grand Slam titles won by two specific tennis players: Henri Leconte and Jonathan Stark. For each player, we need to extract the number of Grand Slam titles they won, using variables for unknown values. Then, we need to compare these numbers to determine who won more titles. Therefore, we define:
- For Henri Leconte: (Henri Leconte, won Grand Slam titles, x)
- For Jonathan Stark: (Jonathan Stark, won Grand Slam titles, y)
- The comparative relation: (x, greater than, y)

### QUESTIONS_TRIPLES
(Henri Leconte, won Grand Slam titles, x)
(Jonathan Stark, won Grand Slam titles, y)
(x, greater than, y)
--------------------------------------------------
Item 7:
### QUESTION_REASONING
1. The question is asking for the genus of moth (unknown, assign variable x) that meets certain criteria.
2. The criteria are: (a) the genus is located in the world's seventh-largest country (which is an entity, assign variable y), and (b) the genus contains only one species.
3. The phrase "seventh-largest country" refers to a country ranked seventh by area; variable y represents this country.
4. Therefore, we need to represent: x is a genus of moth in y, x contains only one species.

### QUESTIONS_TRIPLES
(x, is a genus of moth in, y)
(y, is the world's seventh-largest country, true)
(x, contains only one species, true)
--------------------------------------------------
Item 8:
### QUESTION_REASONING
The question is asking for the identity of a person (unknown, assign variable x) with the following features: (1) once considered the best kick boxer in the world, (2) he has been involved in a number of controversies relating to his "unsportsmanlike conducts" in the sport, and (3) he has been involved in crimes of violence outside of the ring. "Who" signals the unknown is a person. To structure the knowledge, we identify the following triples: The person x was once considered the best kick boxer in the world; the person x was involved in controversies relating to "unsportsmanlike conducts"; the controversies are in the sport of kickboxing; the person x was involved in crimes of violence; the crimes of violence are outside of the ring.

### QUESTIONS_TRIPLES
(x, was once considered, best kick boxer in the world)
(x, was involved in, y)
(y, relates to, unsportsmanlike conducts)
(y, occurred in, kickboxing)
(x, was involved in, z)
(z, relates to, crimes of violence)
(z, occurred in, outside of the ring)
--------------------------------------------------
Item 9:
### QUESTION_REASONING
1. Identify the main entities in the question: "House of Anubis" and the Dutch-Belgian television series it was based on.
2. The question asks for the year when that Dutch-Belgian television series first aired.
3. The Dutch-Belgian television series is an unknown, so assign variable x to it.
4. The question is asking in what year (unknown, use variable y) the series (x) first aired.
5. Also, extract the relationship that "House of Anubis" was based on x.

### QUESTIONS_TRIPLES
(House of Anubis, was based on, x)
(x, first aired in, y)
--------------------------------------------------
Item 10:
### QUESTION_REASONING
1. Identify the main entities in the question: "2013 Liqui Moly Bathurst 12 Hour" (an event) and the "track" where the event was staged.
2. The question asks for the "length" of the "track" associated with the event.
3. The location/track is an unknown entity (x) where the event was staged.
4. The length of this track is the value to be inferred (y).
5. Both unknowns are assigned variables: the track is x, its length is y.

### QUESTIONS_TRIPLES
(2013 Liqui Moly Bathurst 12 Hour, was staged at, x)
(x, has length, y)
--------------------------------------------------

In [29]:
questions_str_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "questions_str": []
})

for i, graphs_str_list in enumerate(question_str_batch):
    batch_num_list = [i] * len(graphs_str_list)
    question_num_list = list(range(1, len(graphs_str_list) + 1))
    questions_str_df = pd.concat([questions_str_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "questions_str": graphs_str_list
    })], ignore_index=True)

questions_str_df

   batch_num  question_num                                      questions_str
0        0.0           1.0  ### QUESTION_REASONING\nThe question is asking...
1        0.0           2.0  ### QUESTION_REASONING\nFirst, I identify the ...
2        0.0           3.0  ### QUESTION_REASONING\nFirst, identify the en...
3        0.0           4.0  ### QUESTION_REASONING\nThe question is asking...
4        0.0           5.0  ### QUESTION_REASONING\nFirst, identify the st...
5        0.0           6.0  ### QUESTION_REASONING\nThe question is compar...
6        0.0           7.0  ### QUESTION_REASONING\n1. The question is ask...
7        0.0           8.0  ### QUESTION_REASONING\nThe question is asking...
8        0.0           9.0  ### QUESTION_REASONING\n1. Identify the main e...
9        0.0          10.0  ### QUESTION_REASONING\n1. Identify the main e...

In [30]:
def extract_question_to_columns(row):
    # Regex patterns for section headers
    questions_reasoning_pat = r'### QUESTION_REASONING\s*(.*?)\s*### QUESTIONS_TRIPLES'
    questions_triples_pat = r'### QUESTIONS_TRIPLES\s*(.*)'

    questions_reasoning, questions_triples = extract_sections(row['questions_str'], questions_reasoning_pat, questions_triples_pat)
    return pd.Series([questions_reasoning, questions_triples],
                     index=['question_reasoning', 'question_triples'])

questions_str_df[['question_reasoning', 'question_triples']] = questions_str_df.apply(extract_question_to_columns, axis=1)
questions_str_df

,batch_num,question_num,questions_str,question_reasoning,question_triples
0,0.0,1.0,### QUESTION_REASONING\nThe question is asking...,The question is asking for a comparison betwee...,"[(arthurs_magazine, started_in, x), (first_for..."
1,0.0,2.0,"### QUESTION_REASONING\nFirst, I identify the ...","First, I identify the main entities mentioned:...","[(oberoi_family, is_part_of, y), (y, has_head_..."
2,0.0,3.0,"### QUESTION_REASONING\nFirst, identify the en...","First, identify the entities: Allie Goertz, ""T...","[(allie_goertz, wrote_a_song_about, milhouse),..."
3,0.0,4.0,### QUESTION_REASONING\nThe question is asking...,The question is asking about the nationality o...,"[(james_henry_miller, has_wife, x), (x, has_na..."
4,0.0,5.0,"### QUESTION_REASONING\nFirst, identify the st...","First, identify the statements within the ques...","[(cadmium_chloride, is_slightly_soluble_in, x)..."
5,0.0,6.0,### QUESTION_REASONING\nThe question is compar...,The question is comparing the number of Grand ...,"[(henri_leconte, won_grand_slam_titles, x), (j..."
6,0.0,7.0,### QUESTION_REASONING\n1. The question is ask...,1. The question is asking for the genus of mot...,"[(x, is_a_genus_of_moth_in, y), (y, is_the_wor..."
7,0.0,8.0,### QUESTION_REASONING\nThe question is asking...,The question is asking for the identity of a p...,"[(x, was_once_considered, best_kick_boxer_in_t..."
8,0.0,9.0,### QUESTION_REASONING\n1. Identify the main e...,1. Identify the main entities in the question:...,"[(house_of_anubis, was_based_on, x), (x, first..."
9,0.0,10.0,### QUESTION_REASONING\n1. Identify the main e...,1. Identify the main entities in the question:...,"[(n2013_liqui_moly_bathurst_12_hour, was_stage..."

In [31]:
main_df = main_df.merge(questions_str_df, on=['batch_num', 'question_num'], how='left')
# del graphs_str_df
main_df

,batch_num,question_num,context,question,answer,graphs_str,context_reasoning,context_triples,questions_str,question_reasoning,question_triples
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified by reviewing titles a...,"[(radio_city, is_a, fm_radio_station), (radio_...",### QUESTION_REASONING\nThe question is asking...,The question is asking for a comparison betwee...,"[(arthurs_magazine, started_in, x), (first_for..."
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi,"### CONTEXT_REASONING\nFirst, I reviewed each ...","First, I reviewed each paragraph and title for...","[(ritz-carlton_jakarta, is_located_in, jakarta...","### QUESTION_REASONING\nFirst, I identify the ...","First, I identify the main entities mentioned:...","[(oberoi_family, is_part_of, y), (y, has_head_..."
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,### CONTEXT_REASONING\nEntities selected inclu...,Entities selected include canonical names for ...,"[(lisa_simpson, is_character_in, the_simpsons)...","### QUESTION_REASONING\nFirst, identify the en...","First, identify the entities: Allie Goertz, ""T...","[(allie_goertz, wrote_a_song_about, milhouse),..."
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American,### CONTEXT_REASONING\nI first identified uniq...,"I first identified unique entities, focusing o...","[(moloch_or, this_gentile_world, is_a_novel), ...",### QUESTION_REASONING\nThe question is asking...,The question is asking about the nationality o...,"[(james_henry_miller, has_wife, x), (x, has_na..."
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol,"### CONTEXT_REASONING\nFirst, I identified ent...","First, I identified entities such as compounds...","[(cadmium_chloride, has_formula, cdcl), (cadmi...","### QUESTION_REASONING\nFirst, identify the st...","First, identify the statements within the ques...","[(cadmium_chloride, is_slightly_soluble_in, x)..."
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted based on person names ...,"[(li_na, born_on, n26_february_1982), (li_na, ...",### QUESTION_REASONING\nThe question is compar...,The question is comparing the number of Grand ...,"[(henri_leconte, won_grand_slam_titles, x), (j..."
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae,### CONTEXT_REASONING\nEntities were identifie...,"Entities were identified as countries (India, ...","[(india, official_name, republic_of_india), (i...",### QUESTION_REASONING\n1. The question is ask...,1. The question is asking for the genus of mot...,"[(x, is_a_genus_of_moth_in, y), (y, is_the_wor..."
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari,### CONTEXT_REASONING\nI read through each tit...,"I read through each title and paragraph, ident...","[(verano_de_escándalo_1998, is_a, professional...",### QUESTION_REASONING\nThe question is asking...,The question is asking for the identity of a p...,"[(x, was_once_considered, best_kick_boxer_in_t..."
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006,### CONTEXT_REASONING\nEntities were extracted...,"Entities were extracted from series titles, cr...","[(house_of_anubis, is_a_television_series_deve...",### QUESTION_REASONING\n1. Identify the main e...,1. Identify the main entities in the question:...,"[(house_of_anubis, was_based_on, x), (x, first..."
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified by parsing titles and...,"[(mount_panorama_circuit, located_in, bathurst...",### QUESTION_REASONING\n1. Identify the main e...,1. Identify the main entities in the question:...,"[(n2013_liqui_moly_bathurst_12_hour, was_stage..."

## 5. Extracting sub-graphs from KGs

In [32]:
import threading
import numpy as np
from queue import Queue
from langchain_openai import OpenAIEmbeddings
import ast

def short_name(uri):
    s = str(uri)
    if '#' in s:
        return s.split('#')[-1]
    elif '/' in s:
        return s.split('/')[-1]
    return s

def load_embedding_dict(csv_path):
    embedding_dict = {}
    if os.path.exists(csv_path):
        print(f"Loading existing embeddings from '{csv_path}'...")
        df = pd.read_csv(csv_path)
        for _, row in df.iterrows():
            emb = ast.literal_eval(row["embedding"]) if isinstance(row["embedding"], str) else row["embedding"]
            embedding_dict[row["string"]] = emb
    else:
        print(f"No embedding cache found. Initializing '{csv_path}' as empty.")
        pd.DataFrame(columns=["string", "embedding"]).to_csv(csv_path, index=False)
    return embedding_dict

def get_embedding(text, embedding_dict, lock, embedder):
    with lock:
        if text in embedding_dict:
            print(f"Embedding for '{text}' found in cache.")
            return embedding_dict[text]
    print(f"Requesting embedding for '{text}'...")
    emb = embedder.embed_query(text)
    with lock:
        embedding_dict[text] = emb
    print(f"Embedding for '{text}' cached.")
    return emb

def cosine_similarity(vec1, vec2):
    v1 = np.array(vec1)
    v2 = np.array(vec2)
    if np.linalg.norm(v1) == 0 or np.linalg.norm(v2) == 0:
        return 0.0
    return float(np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)))

def bfs_n_hop_triples(graph, start_entity, n):
    visited = set([start_entity])
    current_level = set([start_entity])
    neighborhood_triples = set()
    for hop in range(n):
        next_level = set()
        for node in current_level:
            # Outgoing
            for s, p, o in graph.triples((node, None, None)):
                next_level.add(o)
                neighborhood_triples.add((short_name(s), short_name(p), short_name(o)))
            # Incoming
            for s, p, o in graph.triples((None, None, node)):
                next_level.add(s)
                neighborhood_triples.add((short_name(s), short_name(p), short_name(o)))
        next_level -= visited
        if not next_level:
            break
        visited |= next_level
        current_level = next_level
    return list(neighborhood_triples)

def extract_entities(graph):
    entities = set()
    for s, p, o in graph:
        entities.add(s)
        entities.add(o)
    return list(entities)

def worker(entity_queue, graph, key_embedding, per, n, embedding_dict, lock, neighborhoods, matched_entities, embedder, thread_id):
    print(f"[Thread {thread_id}] started.")
    while not entity_queue.empty():
        entity = entity_queue.get()
        try:
            entity_label = short_name(entity)
            emb = get_embedding(entity_label, embedding_dict, lock, embedder)
            sim = cosine_similarity(key_embedding, emb)
            if sim >= per:
                triples = bfs_n_hop_triples(graph, entity, n)
                with lock:
                    neighborhoods.extend(triples)
                    matched_entities.append(entity_label)
        except Exception as e:
            print(f"[Thread {thread_id}] Error processing entity {entity}: {e}")
        finally:
            entity_queue.task_done()
    print(f"[Thread {thread_id}] finished.")

def kg_neighborhood_extractor(
    rdf_path, per, n, key, k=4, embedding_model="text-embedding-3-small", embedding_csv_path="embedding_dict.csv"
):
    print("Loading RDF graph...")
    graph = Graph()
    graph.parse(rdf_path)
    print("Extracting entities...")
    entities = extract_entities(graph)
    print(f"Total entities found: {len(entities)}")

    embedding_dict = load_embedding_dict(embedding_csv_path)
    neighborhoods = []
    matched_entities = []
    lock = threading.Lock()

    print(f"Initializing LangChain OpenAIEmbeddings with model '{embedding_model}'...")
    embedder = OpenAIEmbeddings(model=embedding_model)

    print(f"Getting embedding for search key: '{key}'")
    key_embedding = get_embedding(key, embedding_dict, lock, embedder)

    entity_queue = Queue()
    for entity in entities:
        entity_queue.put(entity)

    threads = []
    for i in range(k):
        t = threading.Thread(
            target=worker,
            args=(
                entity_queue,
                graph,
                key_embedding,
                per,
                n,
                embedding_dict,
                lock,
                neighborhoods,
                matched_entities,
                embedder,
                i+1,
            ),
        )
        t.start()
        threads.append(t)

    entity_queue.join()
    for t in threads:
        t.join()

    # Deduplicate triples
    neighborhoods = list({triple for triple in neighborhoods})

    # Save embedding_dict to CSV
    with lock:
        rows = [
            {"string": s, "embedding": ",".join(map(str, v))}
            for s, v in embedding_dict.items()
        ]
        df = pd.DataFrame(rows)
        df.to_csv("embedding_dict.csv", index=False)

    print("\nSummary:")
    print(f"Matched entities: {matched_entities}")
    print(f"Total unique triples in neighborhoods: {len(neighborhoods)}")
    print("Embeddings saved as 'embedding_dict.csv'")
    return neighborhoods

In [33]:
# neighborhoods = kg_neighborhood_extractor(
#     rdf_path="outputs/knowledge_graphs/hotpotQA_ontology_b0_q1.rdf",
#     per=0.75, n=2, key="arthurs_magazine", k=3, embedding_model="text-embedding-3-small"
# )
# print("\nNeighborhood triples:")
# for triple in neighborhoods:
#     print(triple)

Loading RDF graph...
Extracting entities...
Total entities found: 148
Loading existing embeddings from 'embedding_dict.csv'...
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'arthurs_magazine'
Embedding for 'arthurs_magazine' found in cache.
[Thread 1] started.
Embedding for 'arthurs_magazine' found in cache.
Embedding for 'bengaluru' found in cache.
Requesting embedding for 'a_day_later'...
[Thread 2] started.
Requesting embedding for 'n2014_year-end'...
[Thread 3] started.
Embedding for 'may_1846' found in cache.
Embedding for 'echosmith' found in cache.
Requesting embedding for 'first_college_established_specifically_for_women_in_south'...
Embedding for 'n2014_year-end' cached.
Embedding for 'bauer_media_group' found in cache.
Requesting embedding for 'perhaps_the_smallest_courthouse_in_united_states'...
Embedding for 'first_college_established_specifically_for_women_in_south' cached.
Requesting embedding for 'music_videos'...
Embedding for 'a_day_later' cached.
Requesting embedding for 'bachelors_degrees'...
Embedding for 'bachelors_degrees' cached.
Embedding for 'santa_ana_canyon' found in cache.
Embedding for 'justin_timberlake' found in cache.
Requesting embedding for 'new_media'...
Embedding for 'perhaps_the_smallest_courthouse_in_united_states' cached.
Requesting embedding for 'girls_seminaries_or_academies'...
Embedding for 'music_videos' cached.
Embedding for 'clothing_line' found in cache.
Embedding for 'n2001' found in cache.
Embedding for 'music-related_features' found in cache.
Requesting embedding for 'riaa'...
Embedding for 'girls_seminaries_or_academies' cached.
Embedding for 'n2008' found in cache.
Requesting embedding for 'hindi_music'...
Embedding for 'new_media' cached.
Embedding for 'n910_mhz' found in cache.
Embedding for 'womans_magazine' found in cache.
Embedding for 'wesleyan_college' found in cache.
Embedding for 'englewood_cliffs_new_jersey' found in cache.
Embedding for 'new_delhi' found in cache.
Embedding for 'cool_kids' found in cache.
Embedding for 'two_separate_fires' found in cache.
Embedding for 'hk_kremenchuk' found in cache.
Embedding for 'four_teams' found in cache.
Embedding for 'wildfire' found in cache.
Embedding for 'oldest_female_educational_institution_in_the_south' found in cache.
Requesting embedding for 'regional_music'...
Embedding for 'riaa' cached.
Embedding for 'noah_sierota' found in cache.
Requesting embedding for 'june_1932'...
Embedding for 'june_1932' cached.
Requesting embedding for 'regional_songs'...
Embedding for 'hindi_music' cached.
Embedding for 'salem_college' found in cache.
Requesting embedding for 'n2011'...
Embedding for 'regional_songs' cached.
Embedding for 'southern_united_states' found in cache.
Embedding for 'february_2009' found in cache.
Embedding for 'double_platinum_by_aria' found in cache.
Embedding for 'n1310696_copies' found in cache.
Embedding for 'chino_california' found in cache.
Embedding for 'orange_county_california' found in cache.
Embedding for 'sydney_sierota' found in cache.
Requesting embedding for 'hindi_songs'...
Embedding for 'regional_music' cached.
Requesting embedding for 'all_teams'...
Embedding for 'all_teams' cached.
Embedding for 'mary_baldwin_university' found in cache.
Embedding for 'denim_line' found in cache.
Embedding for 'band' found in cache.
Embedding for 'museum' found in cache.
Requesting embedding for 'fm_radio_station'...
Embedding for 'n2011' cached.
Embedding for 'planetradiocitycom' found in cache.
Requesting embedding for 'over_1200000_in_united_states'...
Embedding for 'fm_radio_station' cached.
Requesting embedding for 'football'...
Embedding for 'hindi_songs' cached.
Requesting embedding for 'quartet_of_siblings'...
Embedding for 'football' cached.
Embedding for 'regular_season_winner' found in cache.
Embedding for 'n911_mhz' found in cache.
Requesting embedding for 'fshf'...
Embedding for 'over_1200000_in_united_states' cached.
Embedding for 'football_in_albania' found in cache.
Embedding for 'abraham_thomas' found in cache.
Embedding for 'n1946' found in cache.
Embedding for 'first_arthur_county_courthouse_and_jail' found in cache.
Requesting embedding for 'billboard_hot_100'...
Embedding for 'quartet_of_siblings' cached.
Embedding for 'premium_jeans' found in cache.
Embedding for 'previous_season' found in cache.
Embedding for 'n7_july_2006' found in cache.
Embedding for 'coeducational_courses_at_graduate_level' found in cache.
Embedding for 'n3_july_2001' found in cache.
Embedding for 'fifa' found in cache.
Embedding for 'godeys_ladys_book' found in cache.
Embedding for 'n23rd_season_of_ukrainian_hockey_championship' found in cache.
Requesting embedding for 'n13'...
Embedding for 'fshf' cached.
Embedding for 'freeway_complex_fire' found in cache.
Embedding for 'n2003' found in cache.
Embedding for 'semifinals' found in cache.
Embedding for 'freeway_fire' found in cache.
Embedding for 'trace_ayala' found in cache.
Embedding for 'albanian_national_team' found in cache.
Requesting embedding for 'balkan_cup_tournament'...
Embedding for 'n13' cached.
Embedding for 'n1954' found in cache.
Embedding for 'music_related_news' found in cache.
Embedding for 'n6_june_1930' found in cache.
Requesting embedding for 'australia'...
Embedding for 'balkan_cup_tournament' cached.
Embedding for 'october_2007' found in cache.
Requesting embedding for 'n1844_1846'...
Embedding for 'australia' cached.
Embedding for 'chennai' found in cache.
Embedding for 'ready_set_go' found in cache.
Embedding for 'hyderabad' found in cache.
Embedding for 'jamie_sierota' found in cache.
Embedding for 'double_platinum' found in cache.
Embedding for 'mens_and_womens_clothing_line' found in cache.
Requesting embedding for 'india'...
Embedding for 'billboard_hot_100' cached.
Requesting embedding for 'william_rast_clothing_line'...
Embedding for 'william_rast_clothing_line' cached.
Embedding for 'n1989' found in cache.
Embedding for 'sarah_josepha_hale' found in cache.
Embedding for 'william_rast' found in cache.
Requesting embedding for 'warner_bros_records_fifth-biggest-selling-digital_song_of_2014'...
Embedding for 'n1844_1846' cached.
Embedding for 'jh_ingraham' found in cache.
Embedding for 'may_2008' found in cache.
Embedding for 'ts_arthur' found in cache.
Embedding for 'edgar_a_poe' found in cache.
Embedding for 'talking_dreams' found in cache.
Requesting embedding for 'final'...
Embedding for 'india' cached.
Embedding for 'jackets' found in cache.
Embedding for 'atek_kiev' found in cache.
Embedding for 'songs' found in cache.
Embedding for 'lucknow' found in cache.
Embedding for 'n314_residences' found in cache.
Embedding for 'womens_colleges_in_the_southern_united_states' found in cache.
Embedding for 'liberal_arts_colleges' found in cache.
Requesting embedding for 'english_songs'...
Embedding for 'english_songs' cached.
Embedding for 'tops' found in cache.
Requesting embedding for 'exclusively_or_almost_exclusively_women'...
Embedding for 'final' cached.
Embedding for 'albanian_football_federation' found in cache.
Embedding for 'radio_city' found in cache.
Requesting embedding for 'after_9am_15_november_2008'...
Embedding for 'warner_bros_records_fifth-biggest-selling-digital_song_of_2014' cached.
Embedding for 'united_states' found in cache.
Embedding for 'uefa' found in cache.
Embedding for 'march_2006' found in cache.
Embedding for 'n13_million' found in cache.
Embedding for 'literary_periodical' found in cache.
Requesting embedding for 'approximately_2_hours_later'...
Embedding for 'after_9am_15_november_2008' cached.
Embedding for 'first_for_women' found in cache.
Embedding for 'may_2012' found in cache.
Embedding for 'n2004' found in cache.
Requesting embedding for 'many_southern_womens_colleges'...
Embedding for 'approximately_2_hours_later' cached.
Embedding for 'philadelphia' found in cache.
Embedding for 'landfill_fire' found in cache.
Embedding for 'undergraduate_institutions' found in cache.
Requesting embedding for 'n1929'...
Embedding for 'many_southern_womens_colleges' cached.
Embedding for 'warner_bros_records' found in cache.
Requesting embedding for 'n12_16_june_1932_convention'...
Embedding for 'exclusively_or_almost_exclusively_women' cached.
Embedding for 'visakhapatnam' found in cache.
Embedding for 'thomas_g_spear' found in cache.
Embedding for 'late_2016' found in cache.
Requesting embedding for 'n2014_15_ukrainian_hockey_championship'...
Embedding for 'n12_16_june_1932_convention' cached.
Embedding for 'n17_october_2006' found in cache.
Embedding for 'graham_sierota' found in cache.
Embedding for 'n12_rounds' found in cache.
Embedding for 'yugoslavia' found in cache.
Embedding for 'n8_october_2013' found in cache.
Requesting embedding for 'n1929-1931'...
Embedding for 'n2014_15_ukrainian_hockey_championship' cached.
Embedding for 'mumbai' found in cache.
Embedding for 'generals_kiev' found in cache.
Requesting embedding for 'song'...
Embedding for 'n1929' cached.
Requesting embedding for 'albania_national_football_team'...
Embedding for 'song' cached.
Embedding for 'albania' found in cache.
[Thread 3] finished.
Embedding for 'albania_national_football_team' cached.
[Thread 2] finished.
Embedding for 'n1929-1931' cached.
[Thread 1] finished.

Summary:
Matched entities: ['arthurs_magazine']
Total unique triples in neighborhoods: 15
Embeddings saved as 'embedding_dict.csv'

Neighborhood triples:
('arthurs_magazine', 'was_edited_by', 'ts_arthur')
('arthurs_magazine', 'merged_in', 'may_1846')
('arthurs_magazine', 'was_published_during', 'n1844_1846')
('arthurs_magazine', 'was_a', 'literary_periodical')
('arthurs_magazine', 'was_published_in', 'philadelphia')
('arthurs_magazine', 'merged_into', 'godeys_ladys_book')
('arthurs_magazine', 'featured_work_by', 'jh_ingraham')
('arthurs_magazine', 'featured_work_by', 'sarah_josepha_hale')
('william_rast', 'is_located_in', 'united_states')
('arthurs_magazine', 'was_published_in', 'united_states')
('arthurs_magazine', 'featured_work_by', 'edgar_a_poe')
('arthurs_magazine', 'featured_work_by', 'thomas_g_spear')
('first_arthur_county_courthouse_and_jail', 'is_located_in', 'united_states')
('echosmith', 'is_located_in', 'united_states')
('first_for_women', 'is_published_in', 'united_states')

In [41]:
# loop through each row in main_df and extract neighborhoods
batch_input_list = []

for i in range(0, main_df.shape[0], BATCH_SIZE):
    batch_df = main_df.iloc[i:i+BATCH_SIZE]
    batch_input_item = []

    for i, (index, row) in enumerate(batch_df.iterrows()):
        reference_triples = []
        for triple in row['question_triples']:
            # Extract reference_triples using question_triples
            if len(triple[0]) > 1:
                reference_triples += kg_neighborhood_extractor(
                    rdf_path=f"{KNOWLEDGE_GRAPH_PATH}/{DATASET_NAME}_ontology_b{row['batch_num']}_q{row['question_num']}.rdf",
                    per=0.75, n=2, key=triple[0], k=3, embedding_model="text-embedding-3-small"
                )

            if len(triple[2]) > 1:
                reference_triples += kg_neighborhood_extractor(
                    rdf_path=f"{KNOWLEDGE_GRAPH_PATH}/{DATASET_NAME}_ontology_b{row['batch_num']}_q{row['question_num']}.rdf",
                    per=0.75, n=2, key=triple[2], k=3, embedding_model="text-embedding-3-small"
                )

        batch_input_item.append({
            "question": row['question'],
            "reference_triples": reference_triples
        })
    batch_input_list.append(batch_input_item)
    break

Loading RDF graph...
Extracting entities...
Total entities found: 148
Loading existing embeddings from 'embedding_dict.csv'...
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'arthurs_magazine'
Embedding for 'arthurs_magazine' found in cache.
[Thread 1] started.
Embedding for 'arthurs_magazine' found in cache.
Embedding for 'bengaluru' found in cache.
Embedding for 'a_day_later' found in cache.
Embedding for 'n2014_year-end' found in cache.
Embedding for 'may_1846' found in cache.
Embedding for 'echosmith' found in cache.
Embedding for 'first_college_established_specifically_for_women_in_south' found in cache.
Embedding for 'bauer_media_group' found in cache.
Embedding for 'perhaps_the_smallest_courthouse_in_united_states' found in cache.
Embedding for 'music_videos' found in cache.
Embedding for 'bachelors_degrees' found in cache.
Embedding for 'santa_ana_canyon' found in cache.
Embedding for 'justin_timberlake' found in cache.
Embedding for 'new_media' found in cache.
Embedding for 'girls_seminaries_or_academies' found in cache.
Embedding for 'clothing_line' found in cache.
Embedding for 'n2001' found in cache.
Embedding for 'music-related_features' found in cache.
Embedding for 'riaa' found in cache.
Embedding for 'n2008' found in cache.
Embedding for 'hindi_music' found in cache.
Embedding for 'n910_mhz' found in cache.
Embedding for 'womans_magazine' found in cache.
[Thread 2] started.
Embedding for 'wesleyan_college' found in cache.
Embedding for 'englewood_cliffs_new_jersey' found in cache.
[Thread 3] started.
Embedding for 'new_delhi' found in cache.
Embedding for 'cool_kids' found in cache.
Embedding for 'two_separate_fires' found in cache.
Embedding for 'hk_kremenchuk' found in cache.
Embedding for 'four_teams' found in cache.
Embedding for 'wildfire' found in cache.
Embedding for 'oldest_female_educational_institution_in_the_south' found in cache.
Embedding for 'regional_music' found in cache.
Embedding for 'noah_sierota' found in cache.
Embedding for 'june_1932' found in cache.
Embedding for 'regional_songs' found in cache.
Embedding for 'salem_college' found in cache.
Embedding for 'n2011' found in cache.
Embedding for 'southern_united_states' found in cache.
Embedding for 'february_2009' found in cache.
Embedding for 'double_platinum_by_aria' found in cache.
Embedding for 'n1310696_copies' found in cache.
Embedding for 'chino_california' found in cache.
Embedding for 'orange_county_california' found in cache.
Embedding for 'sydney_sierota' found in cache.
Embedding for 'hindi_songs' found in cache.
Embedding for 'all_teams' found in cache.
Embedding for 'mary_baldwin_university' found in cache.
Embedding for 'denim_line' found in cache.
Embedding for 'band' found in cache.
Embedding for 'museum' found in cache.
Embedding for 'fm_radio_station' found in cache.
Embedding for 'planetradiocitycom' found in cache.
Embedding for 'over_1200000_in_united_states' found in cache.
Embedding for 'football' found in cache.
Embedding for 'quartet_of_siblings' found in cache.
Embedding for 'regular_season_winner' found in cache.
Embedding for 'n911_mhz' found in cache.
Embedding for 'fshf' found in cache.
Embedding for 'football_in_albania' found in cache.
Embedding for 'abraham_thomas' found in cache.
Embedding for 'n1946' found in cache.
Embedding for 'first_arthur_county_courthouse_and_jail' found in cache.
Embedding for 'billboard_hot_100' found in cache.
Embedding for 'premium_jeans' found in cache.
Embedding for 'previous_season' found in cache.
Embedding for 'n7_july_2006' found in cache.
Embedding for 'coeducational_courses_at_graduate_level' found in cache.
Embedding for 'n3_july_2001' found in cache.
Embedding for 'fifa' found in cache.
Embedding for 'godeys_ladys_book' found in cache.
Embedding for 'n23rd_season_of_ukrainian_hockey_championship' found in cache.
Embedding for 'n13' found in cache.
Embedding for 'freeway_complex_fire' found in cache.
Embedding for 'n2003' found in cache.
Embedding for 'semifinals' found in cache.
Embedding for 'freeway_fire' found in cache.
Embedding for 'trace_ayala' found in cache.
Embedding for 'albanian_national_team' found in cache.
Embedding for 'balkan_cup_tournament' found in cache.
Embedding for 'n1954' found in cache.
Embedding for 'music_related_news' found in cache.
Embedding for 'n6_june_1930' found in cache.
Embedding for 'australia' found in cache.
Embedding for 'october_2007' found in cache.
Embedding for 'n1844_1846' found in cache.
Embedding for 'chennai' found in cache.
Embedding for 'ready_set_go' found in cache.
Embedding for 'hyderabad' found in cache.
Embedding for 'jamie_sierota' found in cache.
Embedding for 'double_platinum' found in cache.
Embedding for 'mens_and_womens_clothing_line' found in cache.
Embedding for 'india' found in cache.
Embedding for 'william_rast_clothing_line' found in cache.
Embedding for 'n1989' found in cache.
Embedding for 'sarah_josepha_hale' found in cache.
Embedding for 'william_rast' found in cache.
Embedding for 'warner_bros_records_fifth-biggest-selling-digital_song_of_2014' found in cache.
Embedding for 'jh_ingraham' found in cache.
Embedding for 'may_2008' found in cache.
Embedding for 'ts_arthur' found in cache.
Embedding for 'edgar_a_poe' found in cache.
Embedding for 'talking_dreams' found in cache.
Embedding for 'final' found in cache.
Embedding for 'jackets' found in cache.
Embedding for 'atek_kiev' found in cache.
Embedding for 'songs' found in cache.
Embedding for 'lucknow' found in cache.
Embedding for 'n314_residences' found in cache.
Embedding for 'womens_colleges_in_the_southern_united_states' found in cache.
Embedding for 'liberal_arts_colleges' found in cache.
Embedding for 'english_songs' found in cache.
Embedding for 'tops' found in cache.
Embedding for 'exclusively_or_almost_exclusively_women' found in cache.
Embedding for 'albanian_football_federation' found in cache.
Embedding for 'radio_city' found in cache.
Embedding for 'after_9am_15_november_2008' found in cache.
Embedding for 'united_states' found in cache.
Embedding for 'uefa' found in cache.
Embedding for 'march_2006' found in cache.
Embedding for 'n13_million' found in cache.
Embedding for 'literary_periodical' found in cache.
Embedding for 'approximately_2_hours_later' found in cache.
Embedding for 'first_for_women' found in cache.
Embedding for 'may_2012' found in cache.
Embedding for 'n2004' found in cache.
Embedding for 'many_southern_womens_colleges' found in cache.
Embedding for 'philadelphia' found in cache.
Embedding for 'landfill_fire' found in cache.
Embedding for 'undergraduate_institutions' found in cache.
Embedding for 'n1929' found in cache.
Embedding for 'warner_bros_records' found in cache.
Embedding for 'n12_16_june_1932_convention' found in cache.
Embedding for 'visakhapatnam' found in cache.
Embedding for 'thomas_g_spear' found in cache.
Embedding for 'late_2016' found in cache.
Embedding for 'n2014_15_ukrainian_hockey_championship' found in cache.
Embedding for 'n17_october_2006' found in cache.
Embedding for 'graham_sierota' found in cache.
Embedding for 'n12_rounds' found in cache.
Embedding for 'yugoslavia' found in cache.
Embedding for 'n8_october_2013' found in cache.
Embedding for 'n1929-1931' found in cache.
Embedding for 'mumbai' found in cache.
Embedding for 'generals_kiev' found in cache.
Embedding for 'song' found in cache.
Embedding for 'albania_national_football_team' found in cache.
Embedding for 'albania' found in cache.
[Thread 2] finished.
[Thread 1] finished.
[Thread 3] finished.

Summary:
Matched entities: ['arthurs_magazine']
Total unique triples in neighborhoods: 15
Embeddings saved as 'embedding_dict.csv'
Loading RDF graph...
Extracting entities...
Total entities found: 148
Loading existing embeddings from 'embedding_dict.csv'...
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'first_for_women'
Embedding for 'first_for_women' found in cache.
[Thread 1] started.
Embedding for 'arthurs_magazine' found in cache.
Embedding for 'bengaluru' found in cache.
Embedding for 'a_day_later' found in cache.
Embedding for 'n2014_year-end' found in cache.
Embedding for 'may_1846' found in cache.
Embedding for 'echosmith' found in cache.
Embedding for 'first_college_established_specifically_for_women_in_south' found in cache.
Embedding for 'bauer_media_group' found in cache.
Embedding for 'perhaps_the_smallest_courthouse_in_united_states' found in cache.
Embedding for 'music_videos' found in cache.
Embedding for 'bachelors_degrees' found in cache.
Embedding for 'santa_ana_canyon' found in cache.
Embedding for 'justin_timberlake' found in cache.
Embedding for 'new_media' found in cache.
Embedding for 'girls_seminaries_or_academies' found in cache.
Embedding for 'clothing_line' found in cache.
Embedding for 'n2001' found in cache.
Embedding for 'music-related_features' found in cache.
[Thread 2] started.
Embedding for 'riaa' found in cache.
Embedding for 'n2008' found in cache.
Embedding for 'hindi_music' found in cache.
Embedding for 'n910_mhz' found in cache.
Embedding for 'womans_magazine' found in cache.
Embedding for 'wesleyan_college' found in cache.
Embedding for 'englewood_cliffs_new_jersey' found in cache.
Embedding for 'new_delhi' found in cache.
Embedding for 'cool_kids' found in cache.
Embedding for 'two_separate_fires' found in cache.
[Thread 3] started.
Embedding for 'hk_kremenchuk' found in cache.
Embedding for 'four_teams' found in cache.
Embedding for 'wildfire' found in cache.
Embedding for 'oldest_female_educational_institution_in_the_south' found in cache.
Embedding for 'regional_music' found in cache.
Embedding for 'noah_sierota' found in cache.
Embedding for 'june_1932' found in cache.
Embedding for 'regional_songs' found in cache.
Embedding for 'salem_college' found in cache.
Embedding for 'n2011' found in cache.
Embedding for 'southern_united_states' found in cache.
Embedding for 'february_2009' found in cache.
Embedding for 'double_platinum_by_aria' found in cache.
Embedding for 'n1310696_copies' found in cache.
Embedding for 'chino_california' found in cache.
Embedding for 'orange_county_california' found in cache.
Embedding for 'sydney_sierota' found in cache.
Embedding for 'hindi_songs' found in cache.
Embedding for 'all_teams' found in cache.
Embedding for 'mary_baldwin_university' found in cache.
Embedding for 'denim_line' found in cache.
Embedding for 'band' found in cache.
Embedding for 'museum' found in cache.
Embedding for 'fm_radio_station' found in cache.
Embedding for 'planetradiocitycom' found in cache.
Embedding for 'over_1200000_in_united_states' found in cache.
Embedding for 'football' found in cache.
Embedding for 'quartet_of_siblings' found in cache.
Embedding for 'regular_season_winner' found in cache.
Embedding for 'n911_mhz' found in cache.
Embedding for 'fshf' found in cache.
Embedding for 'football_in_albania' found in cache.
Embedding for 'abraham_thomas' found in cache.
Embedding for 'n1946' found in cache.
Embedding for 'first_arthur_county_courthouse_and_jail' found in cache.
Embedding for 'billboard_hot_100' found in cache.
Embedding for 'premium_jeans' found in cache.
Embedding for 'previous_season' found in cache.
Embedding for 'n7_july_2006' found in cache.
Embedding for 'coeducational_courses_at_graduate_level' found in cache.
Embedding for 'n3_july_2001' found in cache.
Embedding for 'fifa' found in cache.
Embedding for 'godeys_ladys_book' found in cache.
Embedding for 'n23rd_season_of_ukrainian_hockey_championship' found in cache.
Embedding for 'n13' found in cache.
Embedding for 'freeway_complex_fire' found in cache.
Embedding for 'n2003' found in cache.
Embedding for 'semifinals' found in cache.
Embedding for 'freeway_fire' found in cache.
Embedding for 'trace_ayala' found in cache.
Embedding for 'albanian_national_team' found in cache.
Embedding for 'balkan_cup_tournament' found in cache.
Embedding for 'n1954' found in cache.
Embedding for 'music_related_news' found in cache.
Embedding for 'n6_june_1930' found in cache.
Embedding for 'australia' found in cache.
Embedding for 'october_2007' found in cache.
Embedding for 'n1844_1846' found in cache.
Embedding for 'chennai' found in cache.
Embedding for 'ready_set_go' found in cache.
Embedding for 'hyderabad' found in cache.
Embedding for 'jamie_sierota' found in cache.
Embedding for 'double_platinum' found in cache.
Embedding for 'mens_and_womens_clothing_line' found in cache.
Embedding for 'india' found in cache.
Embedding for 'william_rast_clothing_line' found in cache.
Embedding for 'n1989' found in cache.
Embedding for 'sarah_josepha_hale' found in cache.
Embedding for 'william_rast' found in cache.
Embedding for 'warner_bros_records_fifth-biggest-selling-digital_song_of_2014' found in cache.
Embedding for 'jh_ingraham' found in cache.
Embedding for 'may_2008' found in cache.
Embedding for 'ts_arthur' found in cache.
Embedding for 'edgar_a_poe' found in cache.
Embedding for 'talking_dreams' found in cache.
Embedding for 'final' found in cache.
Embedding for 'jackets' found in cache.
Embedding for 'atek_kiev' found in cache.
Embedding for 'songs' found in cache.
Embedding for 'lucknow' found in cache.
Embedding for 'n314_residences' found in cache.
Embedding for 'womens_colleges_in_the_southern_united_states' found in cache.
Embedding for 'liberal_arts_colleges' found in cache.
Embedding for 'english_songs' found in cache.
Embedding for 'tops' found in cache.
Embedding for 'exclusively_or_almost_exclusively_women' found in cache.
Embedding for 'albanian_football_federation' found in cache.
Embedding for 'radio_city' found in cache.
Embedding for 'after_9am_15_november_2008' found in cache.
Embedding for 'united_states' found in cache.
Embedding for 'uefa' found in cache.
Embedding for 'march_2006' found in cache.
Embedding for 'n13_million' found in cache.
Embedding for 'literary_periodical' found in cache.
Embedding for 'approximately_2_hours_later' found in cache.
Embedding for 'first_for_women' found in cache.
Embedding for 'may_2012' found in cache.
Embedding for 'n2004' found in cache.
Embedding for 'many_southern_womens_colleges' found in cache.
Embedding for 'philadelphia' found in cache.
Embedding for 'landfill_fire' found in cache.
Embedding for 'undergraduate_institutions' found in cache.
Embedding for 'n1929' found in cache.
Embedding for 'warner_bros_records' found in cache.
Embedding for 'n12_16_june_1932_convention' found in cache.
Embedding for 'visakhapatnam' found in cache.
Embedding for 'thomas_g_spear' found in cache.
Embedding for 'late_2016' found in cache.
Embedding for 'n2014_15_ukrainian_hockey_championship' found in cache.
Embedding for 'n17_october_2006' found in cache.
Embedding for 'graham_sierota' found in cache.
Embedding for 'n12_rounds' found in cache.
Embedding for 'yugoslavia' found in cache.
Embedding for 'n8_october_2013' found in cache.
Embedding for 'n1929-1931' found in cache.
Embedding for 'mumbai' found in cache.
Embedding for 'generals_kiev' found in cache.
Embedding for 'song' found in cache.
Embedding for 'albania_national_football_team' found in cache.
Embedding for 'albania' found in cache.
[Thread 2] finished.
[Thread 1] finished.
[Thread 3] finished.

Summary:
Matched entities: ['first_for_women']
Total unique triples in neighborhoods: 11
Embeddings saved as 'embedding_dict.csv'
Loading RDF graph...
Extracting entities...
Total entities found: 142
Loading existing embeddings from 'embedding_dict.csv'...
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'oberoi_family'
Embedding for 'oberoi_family' found in cache.
[Thread 1] started.
Embedding for 'brick' found in cache.
Embedding for 'omkara' found in cache.
Embedding for 'fort_myer' found in cache.
Embedding for 'skyscraper' found in cache.
Embedding for 'n120000' found in cache.
Embedding for 'cincinnati_investment_group' found in cache.
Embedding for 'local_business_leaders' found in cache.
Embedding for 'london' found in cache.
Embedding for 'naming_contest' found in cache.
Embedding for 'kunal_jaisingh' found in cache.
Embedding for 'n1964' found in cache.
Embedding for 'n75th_anniversary_of_marshalltown' found in cache.
Embedding for 'n1913' found in cache.
Embedding for 'surbhi_chandna' found in cache.
Embedding for 'nakuul_mehta' found in cache.
Embedding for 'indian_drama_television_series' found in cache.
Embedding for 'historic_hotel' found in cache.
Embedding for 'homewood_suites_by_hilton_at_hotel_bond' found in cache.
Embedding for 'n1921' found in cache.
Embedding for 'kiwanis_club' found in cache.
Embedding for 'a_statler_hotel' found in cache.
[Thread 2] started.
Embedding for 'hughes_hotel' found in cache.
Embedding for 'n2001' found in cache.
Embedding for 'national_register_of_historic_places' found in cache.
Embedding for 'hotel_bond_renovation' found in cache.
Embedding for 'glennville' found in cache.
Embedding for 'rudra' found in cache.
Embedding for 'n1920' found in cache.
Embedding for 'new_delhi' found in cache.
Embedding for 'marshalltown_downtown_historic_district' found in cache.
Embedding for 'homewood_suites_by_hilton' found in cache.
Embedding for 'jakarta' found in cache.
Embedding for 'sale_to_cincinnati_group' found in cache.
[Thread 3] started.
Embedding for 'kiwanis' found in cache.
Embedding for 'hotel_company_3rd_infantry' found in cache.
Embedding for 'shivaay' found in cache.
Embedding for 'n2006' found in cache.
Embedding for 'six_countries' found in cache.
Embedding for 'connecticut' found in cache.
Embedding for 'oberoi_family' found in cache.
Embedding for 'sale_of_hotel_tallcorn' found in cache.
Embedding for 'true' found in cache.
Embedding for 'harry_s_bond' found in cache.
Embedding for 'spinoff_series_of_ishqbaaaz' found in cache.
Embedding for 'hungary' found in cache.
Embedding for 'n1965' found in cache.
Embedding for 'tale_of_three_brothers' found in cache.
Embedding for 'glennwanis_hotel' found in cache.
Embedding for 'saint_francis_hospital_school_of_nursing' found in cache.
Embedding for 'hotel_company' found in cache.
Embedding for 'trident_hotels' found in cache.
Embedding for 'oberoi_hotels__resorts' found in cache.
Embedding for 'bond_hotel_company' found in cache.
Embedding for 'tallcorn_towers_apartments' found in cache.
Embedding for 'star_plus' found in cache.
Embedding for 'future_fibre_technologies' found in cache.
Embedding for 'n15_august_1898' found in cache.
Embedding for 'hotel' found in cache.
Embedding for 'two_towers' found in cache.
Embedding for 'n289th_military_police_company' found in cache.
Embedding for 'nepal' found in cache.
Embedding for 'perimeters' found in cache.
Embedding for 'jw_marriott_hotel' found in cache.
Embedding for 'citizens_of_marshalltown' found in cache.
Embedding for 'airlangga_apartment' found in cache.
Embedding for 'n1954' found in cache.
Embedding for 'optical_fiber_intrusion_detection_systems' found in cache.
Embedding for 'bushnell_park' found in cache.
Embedding for 'n1_november_1994' found in cache.
Embedding for 'australia' found in cache.
Embedding for 'n27_june_2016' found in cache.
Embedding for 'n30_luxury_hotels' found in cache.
Embedding for 'n12_story_second_section' found in cache.
Embedding for 'hotel_company_3rd_infantry_the_old_guard' found in cache.
Embedding for 'leenesh_mattoo' found in cache.
Embedding for 'glennville_hotel_company' found in cache.
Embedding for 'love_story_of_shivaay_and_annika' found in cache.
Embedding for 'egypt' found in cache.
Embedding for 'n1926' found in cache.
Embedding for 'indias_second-largest_hotel_company' found in cache.
Embedding for 'the_ritz-carlton_hotel_company' found in cache.
Embedding for 'melbourne' found in cache.
Embedding for 'masaglia_hotel_chain' found in cache.
Embedding for 'regiment' found in cache.
Embedding for 'hotels' found in cache.

In [45]:
# convert '_' into ' ' and remove first 'n' if second charactor is an integer of every entity or relationship of reference_triples
def format_reference_triples(reference_triples):
    formatted_triples = []
    for triple in reference_triples:
        subject, relation, obj = triple
        subject = subject.replace('_', ' ')
        relation = relation.replace('_', ' ')
        obj = obj.replace('_', ' ')
        if subject.startswith('n') and subject[1].isdigit():
            subject = subject[1:]
        if obj.startswith('n') and obj[1].isdigit():
            obj = obj[1:]
        formatted_triples.append((subject, relation, obj))
    return formatted_triples

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i} ... processing {len(batch)} items")
    for j, item in enumerate(batch):
        item['reference_triples'] = format_reference_triples(item['reference_triples'])
        print(f"Item {j}:")
        print("Question:", item['question'])
        print("Reference Triples:", item['reference_triples'])
        print("-" * 50)

Batch 0 ... processing 10 items
Item 0:
Question: Which magazine was started first Arthur's Magazine or First for Women?
Reference Triples: [('arthurs magazine', 'was edited by', 'ts arthur'), ('arthurs magazine', 'merged in', 'may 1846'), ('arthurs magazine', 'was published during', '1844 1846'), ('arthurs magazine', 'was a', 'literary periodical'), ('arthurs magazine', 'was published in', 'philadelphia'), ('arthurs magazine', 'merged into', 'godeys ladys book'), ('arthurs magazine', 'featured work by', 'jh ingraham'), ('arthurs magazine', 'featured work by', 'sarah josepha hale'), ('william rast', 'is located in', 'united states'), ('arthurs magazine', 'was published in', 'united states'), ('arthurs magazine', 'featured work by', 'edgar a poe'), ('arthurs magazine', 'featured work by', 'thomas g spear'), ('first arthur county courthouse and jail', 'is located in', 'united states'), ('echosmith', 'is located in', 'united states'), ('first for women', 'is published in', 'united states'), ('first for women', 'circulation figure in', '2011'), ('william rast', 'is located in', 'united states'), ('arthurs magazine', 'was published in', 'united states'), ('first for women', 'had circulation of', '1310696 copies'), ('first arthur county courthouse and jail', 'is located in', 'united states'), ('first for women', 'is a', 'womans magazine'), ('first for women', 'was started in', '1989'), ('echosmith', 'is located in', 'united states'), ('first for women', 'is based in', 'englewood cliffs new jersey'), ('first for women', 'is published in', 'united states'), ('first for women', 'is published by', 'bauer media group')]
--------------------------------------------------
Item 1:
Question: The Oberoi family is part of a hotel company that has a head office in what city?
Reference Triples: [('the oberoi group', 'headquarters in', 'delhi'), ('oberoi family', 'is involved in', 'hotels'), ('the oberoi group', 'operates in', 'six countries'), ('ishqbaaaz', 'features character', 'omkara'), ('rudra', 'is heir of', 'oberoi family'), ('omkara', 'is heir of', 'oberoi family'), ('nakuul mehta', 'portrays', 'shivaay'), ('oberoi family', 'is based in', 'india'), ('leenesh mattoo', 'portrays', 'rudra'), ('ishqbaaaz', 'features character', 'shivaay'), ('the oberoi group', 'founded in', '1934'), ('the oberoi group', 'is a', 'hotel company'), ('oberoi hotels  resorts', 'operates in', 'india'), ('oberoi family', 'is involved with', 'the oberoi group'), ('the oberoi group', 'operates', 'two river cruise ships'), ('the oberoi group', 'operates brands', 'trident hotels'), ('shivaay', 'is heir of', 'oberoi family'), ('the oberoi group', 'operates brands', 'oberoi hotels  resorts'), ('kunal jaisingh', 'portrays', 'omkara'), ('the oberoi group', 'owns or operates', '30 luxury hotels'), ('ishqbaaaz', 'features character', 'rudra')]
--------------------------------------------------
Item 2:
Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?

## 6. Getting the final answer

In [51]:
system_msg = """
<role>
    You are a logical reasoning expert tasked with answering questions based only on provided structured knowledge in the form of Reference Triples.
</role>

<behavior>
    <rule name="Step-by-Step Reasoning">
        Use the reference triples to deduce relevant facts in a step-by-step manner. Clearly identify which triples are used for each inference.
    </rule>
    <rule name="Comparative Reasoning">
        When comparing entities, extract or infer comparable attributes (e.g., start dates, founding years) and use them to conclude which comes first, is larger, etc., as applicable.
    </rule>
    <rule name="Answer Reporting">
        At the end of your reasoning, provide the final answer on a new line prefixed with "### FINAL_ANSWER", followed by the concise answer on the next line.
        If the data is insufficient to answer the question definitively, return "insufficient data".
    </rule>
</behavior>

<format>
1. Carefully examine the <question> and <reference_triples>.
2. Begin with step-by-step reasoning based strictly on the reference triples.
3. End your output with the heading "### FINAL_ANSWER" followed by the answer on the next line.
</format>
"""

human_msg = """
<question>
{question}
</question>

<reference triples>
{reference_triples}
</reference triples>
"""

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [52]:
chain = prompt | llm_model | StrOutputParser()

In [53]:
answer_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    answer_str_list = chain.batch(batch)
    answer_str_batch.append(answer_str_list)

Batch 1 ... processing 10 items

In [54]:
for i, answer_str_list in enumerate(answer_str_batch):
    print(f"Batch {i + 1} ... processed {len(answer_str_list)} items")
    for j, answer_str in enumerate(answer_str_list):
        print(f"Item {j + 1}:")
        print(answer_str)
        print("-" * 50)

# Arthur's Magazine
# Delhi
# President Richard Nixon
# American
# alcohol
# Jonathan Stark
# Crambidae
# Badr Hari
# 2006
# 6.213 km long

Batch 1 ... processed 10 items
Item 1:
Step-by-Step Reasoning:

1. The question asks which magazine was started first: Arthur's Magazine or First for Women.
2. From the reference triples:
   - ('arthurs magazine', 'was published during', '1844 1846') suggests that Arthur's Magazine started in 1844.
   - ('first for women', 'was started in', '1989') states that First for Women was started in 1989.
3. Comparing these two years:
   - Arthur's Magazine: 1844
   - First for Women: 1989
4. 1844 predates 1989.

### FINAL_ANSWER
Arthur's Magazine was started first.
--------------------------------------------------
Item 2:
Step-by-step reasoning:

1. We need to find the city where the head office of the hotel company that the Oberoi family is part of is located.
2. The triple ('oberoi family', 'is involved in', 'hotels') suggests the Oberoi family is linked to the hotel industry.
3. The triple ('oberoi family', 'is involved with', 'the oberoi group') shows specifically that the Oberoi family is involved with "the oberoi group".
4. The triple ('the oberoi group', 'is a', 'hotel company') clarifies that "the oberoi group" is a hotel company.
5. The triple ('the oberoi group', 'headquarters in', 'delhi') gives the location of the head office of "the oberoi group".

Thus, connecting these, the Oberoi family is part of "the oberoi group," which is a hotel company headquartered in Delhi.

### FINAL_ANSWER
delhi
--------------------------------------------------
Item 3:
Step-by-step reasoning:

1. The question asks: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
2. Identify key facts from the triples:
   - ('allie goertz', 'created songs about', 'milhouse van houten')
     - Confirms Allie Goertz wrote a song about Milhouse Van Houten.
   - ('milhouse van houten', 'is character in', 'the simpsons')
     - Confirms Milhouse is a character in "The Simpsons".
   - ('milhouse van houten', 'created by', 'matt groening')
     - Confirms Matt Groening created Milhouse.
   - ('milhouse van houten', 'named after', 'richard nixon')
     - This triple specifies Milhouse Van Houten (the Simpson's character) is named after 'richard nixon'.

3. The question specifically asks, "who Matt Groening named [Milhouse] after?"

Conclusion:
- According to the triple ('milhouse van houten', 'named after', 'richard nixon'), Milhouse was named after Richard Nixon.

### FINAL_ANSWER
Richard Nixon
--------------------------------------------------
Item 4:
Step-by-Step Reasoning:

1. The question asks for the nationality of James Henry Miller's wife.
2. Identify who James Henry Miller is:
   - Reference triple: ('ewan maccoll', 'also known as', 'james henry miller')
   - So, James Henry Miller = Ewan MacColl.
3. Find Ewan MacColl's wife:
   - Reference triple: ('peggy seeger', 'was married to', 'ewan maccoll')
4. The question now becomes: What is the nationality of Peggy Seeger?
5. Reference triple: ('peggy seeger', 'is american', 'unknown')
   - The format may be non-standard, but from the structure, it is highly likely this refers to Peggy Seeger being American.

### FINAL_ANSWER
American
--------------------------------------------------
Item 5:
Step-by-step reasoning:
1. The question asks: "Cadmium Chloride is slightly soluble in this chemical, it is also called what?"
2. From the triples: ('cadmium chloride', 'is slightly soluble in', 'alcohol').
3. Next, we need to check if "alcohol" is also called something else.
4. From the triples: ('ethanol', 'synonym', 'alcohol').
5. Therefore, "alcohol" is also called "ethanol".

### FINAL_ANSWER
ethanol
--------------------------------------------------
Item 6:
Step-by-step reasoning:

1. The question asks which tennis player won more Grand Slam titles: Henri Leconte or Jonathan Stark.
2. Identify relevant triples showing Grand Slam titles for both:
   - For Henri Leconte:
     - ('henri leconte', 'won', '1984 french open mens doubles'): This indicates he won one Grand Slam title (1984 French Open Men's Doubles).
   - For Jonathan Stark:
     - ('jonathan stark', 'won', '1994 french open mens doubles'): He won the 1994 French Open Men's Doubles.
     - ('jonathan stark', 'won', '1995 wimbledon mixed doubles'): He also won the 1995 Wimbledon Mixed Doubles.
3. Counting Grand Slam titles:
   - Henri Leconte: 1 Grand Slam title (1984 French Open Men's Doubles)
   - Jonathan Stark: 2 Grand Slam titles (1994 French Open Men's Doubles and 1995 Wimbledon Mixed Doubles)
4. Compare the totals: Jonathan Stark has 2; Henri Leconte has 1.

### FINAL_ANSWER
Jonathan Stark
--------------------------------------------------
Item 7:
Step-by-step reasoning:

1. The question asks for a genus of moth found in the world's seventh-largest country, which contains only one species.
2. From the triples: ('india', 'is seventh-largest country by', 'area'), so India is the country in question.
3. Looking for moths found in India:
   - ('indogrammodes pectinicornalis', 'is found in', 'india')
   - ('nepita conferta', 'is found in', 'india')
4. Now, check for information on genus:
   - The species 'indogrammodes pectinicornalis' is likely from the genus 'Indogrammodes' (based on binomial nomenclature).
   - The species 'nepita conferta' is likely from the genus 'Nepita'.
5. The question wants the genus that contains only one species.
6. There are no triples explicitly listing all species in each genus, but inference can be made:
   - Only one species is mentioned for the genus 'Indogrammodes': 'indogrammodes pectinicornalis'.
   - For 'Nepita', only 'nepita conferta' is mentioned.
7. However, the use of only one species for 'Indogrammodes' and the unique-sounding genus name suggest 'Indogrammodes' is monotypic, containing only 'Indogrammodes pectinicornalis'.
8. The question asks for the genus, so the answer is 'Indogrammodes'.

### FINAL_ANSWER
Indogrammodes
--------------------------------------------------
Item 8:
Step-by-Step Reasoning:

1. The question asks for someone who was once considered the best kick boxer in the world, involved in controversies for "unsportsmanlike conducts" and "crimes of violence outside of the ring."
2. According to the triples:
   - ('badr hari', 'is prominent in', 'kickboxing')
   - ('badr hari', 'is a', 'kickboxer')
   - ('badr hari', 'is former champion of', 'k-1 heavyweight')
   - ('badr hari', 'is former champion of', 'its showtime heavyweight world')
   - ('badr hari', 'was k-1 heavyweight champion', 'from 2007 to 2008')
   - ('badr hari', 'was its showtime champion', 'from 2009 to 2010')
These indicate that Badr Hari was at one time the champion of major kickboxing organizations, suggesting he was once considered the best.
3. Furthermore:
   - ('badr hari', 'involved in', 'controversies relating to unsportsmanlike conduct')
   - ('badr hari', 'involved in', 'crimes of violence outside the ring')
These match precisely the details in the question regarding controversies and crimes.
4. No other entities are mentioned in the triples; all records refer to Badr Hari.

### FINAL_ANSWER
badr hari
--------------------------------------------------
Item 9:
Step-by-step reasoning:

1. The question asks about the first airing year of the Dutch-Belgian television series that "House of Anubis" was based on.
2. From the triple: ('house of anubis', 'is based on', 'het huis anubis')
   - "House of Anubis" is based on "het huis anubis".
3. We now identify when "het huis anubis" first aired.
4. From the triple: ('het huis anubis', 'first aired in', 'september 2006')
   - This gives the first air date for "het huis anubis" as September 2006.
5. Since "House of Anubis" is based on "het huis anubis", the answer to the question is the year when "het huis anubis" first aired: 2006.

### FINAL_ANSWER
2006
--------------------------------------------------
Item 10:
Step-by-step reasoning:

1. The question asks about the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged.

2. From the triple: ('2013 liqui moly bathurst 12 hour', 'held at', 'mount panorama circuit'), we know the 2013 event was held at Mount Panorama Circuit.

3. To find the length of this circuit, examine the triples for any relevant details about Mount Panorama Circuit's length.

4. The relevant triple is: ('mount panorama circuit', 'length', '6213 km'), which gives the length of Mount Panorama Circuit.

5. Therefore, the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged is 6.213 km.

### FINAL_ANSWER
6.213 km
--------------------------------------------------

In [55]:
questions_str_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "questions_str": []
})

for i, answer_str_list in enumerate(answer_str_batch):
    batch_num_list = [i] * len(answer_str_list)
    question_num_list = list(range(1, len(answer_str_list) + 1))
    questions_str_df = pd.concat([questions_str_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "questions_str": answer_str_list
    })], ignore_index=True)

questions_str_df

   batch_num  question_num                                      questions_str
0        0.0           1.0  Step-by-Step Reasoning:\n\n1. The question ask...
1        0.0           2.0  Step-by-step reasoning:\n\n1. We need to find ...
2        0.0           3.0  Step-by-step reasoning:\n\n1. The question ask...
3        0.0           4.0  Step-by-Step Reasoning:\n\n1. The question ask...
4        0.0           5.0  Step-by-step reasoning:\n1. The question asks:...
5        0.0           6.0  Step-by-step reasoning:\n\n1. The question ask...
6        0.0           7.0  Step-by-step reasoning:\n\n1. The question ask...
7        0.0           8.0  Step-by-Step Reasoning:\n\n1. The question ask...
8        0.0           9.0  Step-by-step reasoning:\n\n1. The question ask...
9        0.0          10.0  Step-by-step reasoning:\n\n1. The question ask...