In [1]:
import json
import pandas as pd

BATCH_SIZE = 50
IS_DEBUG = True
DEBUG_QUESTION_SIZE = 10
# LLM_MODEL = "gpt-4.1-mini"
LLM_MODEL = "gpt-4.1"
DATASET_NAME = "hotpotQA"
KNOWLEDGE_GRAPH_PATH = 'outputs/knowledge_graphs'

## 1. Loading HotpotQA Dataset

In [2]:
train_hotpot_qa_path = r'C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\hotpotQA\hotpot_train_v1.1.json'
test_hotpot_qa_path = r'C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\hotpotQA\hotpot_test_v1.1.json'

In [3]:
with open(train_hotpot_qa_path, 'r', encoding='utf-8') as f:
    train_hotpot_qa_json = json.load(f)

with open(test_hotpot_qa_path, 'r', encoding='utf-8') as f:
    test_hotpot_qa_json = json.load(f)

In [4]:
train_hotpot_qa_json[0]

{'supporting_facts': [["Arthur's Magazine", 0], ['First for Women', 0]],
 'level': 'medium',
 'question': "Which magazine was started first Arthur's Magazine or First for Women?",
 'context': [['Radio City (Indian radio station)',
   ["Radio City is India's first private FM radio station and was started on 3 July 2001.",
    ' It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003).',
    ' It plays Hindi, English and regional songs.',
    ' It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007.',
    ' Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features.',
    ' The Radio station currently plays a mix of Hindi and Regional music.',
    ' Abraham Thomas is the CEO of the company.']],
  ['History of Albanian football',
   ['Football in Albania existed before the Albanian Football Federation (FSHF) was created.',
    " This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) .",
    ' Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946.',
    ' In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.']],
  ['Echosmith',
   ['Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California.',
    ' Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016.',
    ' Echosmith started first as "Ready Set Go!"',
    ' until they signed to Warner Bros.',
    ' Records in May 2012.',
    ' They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia.',
    ' The song was Warner Bros.',
    " Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold.",
    ' The band\'s debut album, "Talking Dreams", was released on October 8, 2013.']],
  ["Women's colleges in the Southern United States",
   ["Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States.",
    " Many started first as girls' seminaries or academies.",
    ' Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women.',
    ' Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.']],
  ['First Arthur County Courthouse and Jail',
   ['The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.']],
  ["Arthur's Magazine",
   ["Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century.",
    ' Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others.',
    ' In May 1846 it was merged into "Godey\'s Lady\'s Book".']],
  ['2014–15 Ukrainian Hockey Championship',
   ['The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship.',
    ' Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues.',
    ' Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014.',
    ' The regular season included just 12 rounds, where all the teams went to the semifinals.',
    ' In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.']],
  ['First for Women',
   ["First for Women is a woman's magazine published by Bauer Media Group in the USA.",
    ' The magazine was started in 1989.',
    ' It is based in Englewood Cliffs, New Jersey.',
    ' In 2011 the circulation of the magazine was 1,310,696 copies.']],
  ['Freeway Complex Fire',
   ['The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California.',
    ' The fire started as two separate fires on November 15, 2008.',
    ' The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later.',
    ' These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.']],
  ['William Rast',
   ['William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala.',
    ' It is most known for their premium jeans.',
    ' On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line.',
    ' The label also produces other clothing items such as jackets and tops.',
    ' The company started first as a denim line, later evolving into a men’s and women’s clothing line.']]],
 'answer': "Arthur's Magazine",
 '_id': '5a7a06935542990198eaf050',
 'type': 'comparison'}

In [5]:
test_hotpot_qa_json[0]

{'_id': '5a8b57f25542995d1e6f1371',
 'answer': 'yes',
 'question': 'Were Scott Derrickson and Ed Wood of the same nationality?',
 'supporting_facts': [['Scott Derrickson', 0], ['Ed Wood', 0]],
 'context': [['Adam Collis',
   ['Adam Collis is an American filmmaker and actor.',
    ' He attended the Duke University from 1986 to 1990 and the University of California, Los Angeles from 2007 to 2010.',
    ' He also studied cinema at the University of Southern California from 1991 to 1997.',
    ' Collis first work was the assistant director for the Scott Derrickson\'s short "Love in the Ruins" (1995).',
    ' In 1998, he played "Crankshaft" in Eric Koyanagi\'s "Hundred Percent".']],
  ['Ed Wood (film)',
   ['Ed Wood is a 1994 American biographical period comedy-drama film directed and produced by Tim Burton, and starring Johnny Depp as cult filmmaker Ed Wood.',
    " The film concerns the period in Wood's life when he made his best-known films as well as his relationship with actor Bela Lugosi, played by Martin Landau.",
    ' Sarah Jessica Parker, Patricia Arquette, Jeffrey Jones, Lisa Marie, and Bill Murray are among the supporting cast.']],
  ['Tyler Bates',
   ['Tyler Bates (born June 5, 1965) is an American musician, music producer, and composer for films, television, and video games.',
    ' Much of his work is in the action and horror film genres, with films like "Dawn of the Dead, 300, Sucker Punch," and "John Wick."',
    ' He has collaborated with directors like Zack Snyder, Rob Zombie, Neil Marshall, William Friedkin, Scott Derrickson, and James Gunn.',
    ' With Gunn, he has scored every one of the director\'s films; including "Guardians of the Galaxy", which became one of the highest grossing domestic movies of 2014, and its 2017 sequel.',
    ' In addition, he is also the lead guitarist of the American rock band Marilyn Manson, and produced its albums "The Pale Emperor" and "Heaven Upside Down".']],
  ['Doctor Strange (2016 film)',
   ['Doctor Strange is a 2016 American superhero film based on the Marvel Comics character of the same name, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures.',
    ' It is the fourteenth film of the Marvel Cinematic Universe (MCU).',
    ' The film was directed by Scott Derrickson, who wrote it with Jon Spaihts and C. Robert Cargill, and stars Benedict Cumberbatch as Stephen Strange, along with Chiwetel Ejiofor, Rachel McAdams, Benedict Wong, Michael Stuhlbarg, Benjamin Bratt, Scott Adkins, Mads Mikkelsen, and Tilda Swinton.',
    ' In "Doctor Strange", surgeon Strange learns the mystic arts after a career-ending car accident.']],
  ['Hellraiser: Inferno',
   ['Hellraiser: Inferno (also known as Hellraiser V: Inferno) is a 2000 American horror film.',
    ' It is the fifth installment in the "Hellraiser" series and the first "Hellraiser" film to go straight-to-DVD.',
    ' It was directed by Scott Derrickson and released on October 3, 2000.',
    " The film concerns a corrupt detective who discovers Lemarchand's box at a crime scene.",
    " The film's reviews were mixed."]],
  ['Sinister (film)',
   ['Sinister is a 2012 supernatural horror film directed by Scott Derrickson and written by Derrickson and C. Robert Cargill.',
    ' It stars Ethan Hawke as fictional true-crime writer Ellison Oswalt who discovers a box of home movies in his attic that puts his family in danger.']],
  ['Deliver Us from Evil (2014 film)',
   ['Deliver Us from Evil is a 2014 American supernatural horror film directed by Scott Derrickson and produced by Jerry Bruckheimer.',
    ' The film is officially based on a 2001 non-fiction book entitled "Beware the Night" by Ralph Sarchie and Lisa Collier Cool, and its marketing campaign highlighted that it was "inspired by actual accounts".',
    ' The film stars Eric Bana, Édgar Ramírez, Sean Harris, Olivia Munn, and Joel McHale in the main roles and was released on July 2, 2014.']],
  ['Woodson, Arkansas',
   ['Woodson is a census-designated place (CDP) in Pulaski County, Arkansas, in the United States.',
    ' Its population was 403 at the 2010 census.',
    ' It is part of the Little Rock–North Little Rock–Conway Metropolitan Statistical Area.',
    ' Woodson and its accompanying Woodson Lake and Wood Hollow are the namesake for Ed Wood Sr., a prominent plantation owner, trader, and businessman at the turn of the 20th century.',
    ' Woodson is adjacent to the Wood Plantation, the largest of the plantations own by Ed Wood Sr.']],
  ['Conrad Brooks',
   ['Conrad Brooks (born Conrad Biedrzycki on January 3, 1931 in Baltimore, Maryland) is an American actor.',
    ' He moved to Hollywood, California in 1948 to pursue a career in acting.',
    ' He got his start in movies appearing in Ed Wood films such as "Plan 9 from Outer Space", "Glen or Glenda", and "Jail Bait."',
    ' He took a break from acting during the 1960s and 1970s but due to the ongoing interest in the films of Ed Wood, he reemerged in the 1980s and has become a prolific actor.',
    ' He also has since gone on to write, produce and direct several films.']],
  ['The Exorcism of Emily Rose',
   ['The Exorcism of Emily Rose is a 2005 American legal drama horror film directed by Scott Derrickson and starring Laura Linney and Tom Wilkinson.',
    ' The film is loosely based on the story of Anneliese Michel and follows a self-proclaimed agnostic who acts as defense counsel (Linney) representing a parish priest (Wilkinson), accused by the state of negligent homicide after he performed an exorcism.']]],
 'type': 'comparison',
 'level': 'hard'}

In [6]:
for item in train_hotpot_qa_json[0]['context']:
    print(f"Title: {item[0]}")
    print(f"Paragraph: {item[1:]}")
    print("-" * 50)

Title: Radio City (Indian radio station)
Paragraph: [["Radio City is India's first private FM radio station and was started on 3 July 2001.", ' It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003).', ' It plays Hindi, English and regional songs.', ' It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007.', ' Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features.', ' The Radio station currently plays a mix of Hindi and Regional music.', ' Abraham Thomas is the CEO of the company.']]
--------------------------------------------------
Title: History of Albanian football
Paragraph: [['Football in Albania existed before the Albanian Football Federation (FSHF) was created.', " This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) .", ' Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946.', ' In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.']]
--------------------------------------------------
Title: Echosmith
Paragraph: [['Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California.', ' Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016.', ' Echosmith started first as "Ready Set Go!"', ' until they signed to Warner Bros.', ' Records in May 2012.', ' They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia.', ' The song was Warner Bros.', " Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold.", ' The band\'s debut album, "Talking Dreams", was released on October 8, 2013.']]
--------------------------------------------------
Title: Women's colleges in the Southern United States
Paragraph: [["Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States.", " Many started first as girls' seminaries or academies.", ' Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women.', ' Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.']]
--------------------------------------------------
Title: First Arthur County Courthouse and Jail
Paragraph: [['The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.']]
--------------------------------------------------
Title: Arthur's Magazine
Paragraph: [["Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century.", ' Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others.', ' In May 1846 it was merged into "Godey\'s Lady\'s Book".']]
--------------------------------------------------
Title: 2014–15 Ukrainian Hockey Championship
Paragraph: [['The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship.', ' Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues.', ' Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014.', ' The regular season included just 12 rounds, where all the teams went to the semifinals.', ' In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.']]
--------------------------------------------------
Title: First for Women
Paragraph: [["First for Women is a woman's magazine published by Bauer Media Group in the USA.", ' The magazine was started in 1989.', ' It is based in Englewood Cliffs, New Jersey.', ' In 2011 the circulation of the magazine was 1,310,696 copies.']]
--------------------------------------------------
Title: Freeway Complex Fire
Paragraph: [['The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California.', ' The fire started as two separate fires on November 15, 2008.', ' The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later.', ' These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.']]
--------------------------------------------------
Title: William Rast
Paragraph: [['William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala.', ' It is most known for their premium jeans.', ' On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line.', ' The label also produces other clothing items such as jackets and tops.', ' The company started first as a denim line, later evolving into a men’s and women’s clothing line.']]
--------------------------------------------------

In [7]:
def divide_and_batch(train_json, batch_size):
    batch_context = []
    batch_question = []
    batch_answer = []

    for i in range(0, len(train_json), batch_size):
        batch = train_json[i:i + batch_size]
        context = []
        question = []
        answer = []

        for item in batch:
            context_text = ""
            j = 1
            for ctx in item['context']:
                context_text += f"Title {j} : {ctx[0]} \nParagraph {j} : {''.join(ctx[1])}\n"
                j += 1
            context.append(context_text)
            question.append(item['question'])
            answer.append(item['answer'])

        batch_context.append(context)
        batch_question.append(question)
        batch_answer.append(answer)

    return batch_context, batch_question, batch_answer

In [8]:
if IS_DEBUG:
    train_hotpot_qa_json = train_hotpot_qa_json[:DEBUG_QUESTION_SIZE]
    test_hotpot_qa_json = test_hotpot_qa_json[:DEBUG_QUESTION_SIZE]
    batch_context, batch_question, batch_answer = divide_and_batch(train_hotpot_qa_json, BATCH_SIZE)
else:
    batch_context, batch_question, batch_answer = divide_and_batch(test_hotpot_qa_json, BATCH_SIZE)

In [9]:
for i in range(len(batch_context[0])):
    print(f"Batch {i + 1}:")
    print("Context:", batch_context[0][i])
    print("Question:", batch_question[0][i])
    print("Answer:", batch_answer[0][i])
    print("-" * 50)
    if i == 9:  # Limit to 3 batches for brevity
        break

Batch 1:
Context: Title 1 : Radio City (Indian radio station)
Paragraph 1 : Radio City is India's first private FM radio station and was started on 3 July 2001. It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003). It plays Hindi, English and regional songs. It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007. Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features. The Radio station currently plays a mix of Hindi and Regional music. Abraham Thomas is the CEO of the company.
Title 2 : History of Albanian football
Paragraph 2 : Football in Albania existed before the Albanian Football Federation (FSHF) was created. This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) . Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946. In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.
Title 3 : Echosmith
Paragraph 3 : Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California. Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016. Echosmith started first as "Ready Set Go!" until they signed to Warner Bros. Records in May 2012. They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia. The song was Warner Bros. Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold. The band's debut album, "Talking Dreams", was released on October 8, 2013.
Title 4 : Women's colleges in the Southern United States
Paragraph 4 : Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States. Many started first as girls' seminaries or academies. Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women. Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.
Title 5 : First Arthur County Courthouse and Jail
Paragraph 5 : The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.
Title 6 : Arthur's Magazine
Paragraph 6 : Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century. Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others. In May 1846 it was merged into "Godey's Lady's Book".
Title 7 : 2014–15 Ukrainian Hockey Championship
Paragraph 7 : The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship. Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues. Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014. The regular season included just 12 rounds, where all the teams went to the semifinals. In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.
Title 8 : First for Women
Paragraph 8 : First for Women is a woman's magazine published by Bauer Media Group in the USA. The magazine was started in 1989. It is based in Englewood Cliffs, New Jersey. In 2011 the circulation of the magazine was 1,310,696 copies.
Title 9 : Freeway Complex Fire
Paragraph 9 : The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California. The fire started as two separate fires on November 15, 2008. The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later. These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.
Title 10 : William Rast
Paragraph 10 : William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala. It is most known for their premium jeans. On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line. The label also produces other clothing items such as jackets and tops. The company started first as a denim line, later evolving into a men’s and women’s clothing line.

Question: Which magazine was started first Arthur's Magazine or First for Women?
Answer: Arthur's Magazine
--------------------------------------------------
Batch 2:
Context: Title 1 : Ritz-Carlton Jakarta
Paragraph 1 : The Ritz-Carlton Jakarta is a hotel and skyscraper in Jakarta, Indonesia and 14th Tallest building in Jakarta. It is located in city center of Jakarta, near Mega Kuningan, adjacent to the sister JW Marriott Hotel. It is operated by The Ritz-Carlton Hotel Company. The complex has two towers that comprises a hotel and the Airlangga Apartment respectively. The hotel was opened in 2005.
Title 2 : Oberoi family
Paragraph 2 : The Oberoi family is an Indian family that is famous for its involvement in hotels, namely through The Oberoi Group.
Title 3 : Ishqbaaaz
Paragraph 3 : Ishqbaaaz (English: "Lovers") is an Indian drama television series which is broadcast on Star Plus. It premiered on 27 June 2016 and airs Mon-Fri 10-11pm IST.Nakuul Mehta, Kunal Jaisingh and Leenesh Mattoo respectively portray Shivaay, Omkara and Rudra, the three heirs of the Oberoi family. The show initially focused on the tale of three brothers, later become centered on the love story of Shivaay and Annika (Surbhi Chandna); with the story of Omkara and Rudra being shifted to the spinoff series "Dil Boley Oberoi". In July 2017 "Dil Boley Oberoi" ended and the storylines were merged back into "Ishqbaaaz" which doubled its runtime.
Title 4 : Hotel Tallcorn
Paragraph 4 : The Hotel Tallcorn is located in Marshalltown, Iowa. Today it is called the Tallcorn Towers Apartments. Built in 1928 by the Eppley Hotel Company, local citizens contributed $120,000 to ensure the successful completion of this seven-story hotel. It was completed in connection to the seventy-fifth anniversary of Marshalltown. The hotel's sale in 1956 from the Eppley chain to the Sheraton Corporation was part of the second largest hotel sale in United States history. The Tallcorn was listed as a contributing property in the Marshalltown Downtown Historic District on the National Register of Historic Places in 2002.
Title 5 : Mohan Singh Oberoi
Paragraph 5 : Rai Bahadur Mohan Singh Oberoi (15 August 1898 – 3 May 2002) was an Indian hotelier, the founder and chairman of Oberoi Hotels & Resorts, India's second-largest hotel company, with 35 hotels in India, Sri Lanka, Nepal, Egypt, Australia and Hungary.
Title 6 : Hotel Bond
Paragraph 6 : Hotel Bond is a historic hotel, built in two stages in 1913 and 1921, in downtown Hartford, Connecticut by hotelier Harry S. Bond. It is located near Bushnell Park, and was considered the grandest hotel in Hartford during its heyday. The second section is a 12 story building attached to the 6 story first section. A Statler Hotel opened in the area in 1954, creating competition, and the Bond Hotel company declared bankruptcy shortly after that. It was bought by the California-based Masaglia Hotel chain, which began an incremental renovation program. In 1964 it was sold to a Cincinnati, Ohio investment group which announced extensive renovation plans. However, the financing plans fell through and the hotel was again in bankruptcy. The building was sold at auction to the Roman Catholic Archdiocese of Hartford in 1965, and it became the home of the Saint Francis Hospital School of Nursing. The Bond Ballroom reopened in 2001, with the rest of the building becoming a Homewood Suites by Hilton in 2006.
Title 7 : The Oberoi Group
Paragraph 7 : The Oberoi Group is a hotel company with its head office in Delhi. Founded in 1934, the company owns and/or operates 30+ luxury hotels and two river cruise ships in six countries, primarily under its Oberoi Hotels & Resorts and Trident Hotels brands.
Title 8 : Future Fibre Technologies
Paragraph 8 : Future Fibre Technologies (FFT) is a fiber optic sensing technologies company based in Melbourne, Australia, with its US head office in Mountain View, California, Middle East head office in Dubai, Indian head office in New Delhi and European head office in London. Founded in 1994, Future Fibre Technologies product line provides optical fiber intrusion detection systems for perimeters, buried oil and gas pipelines and data communication networks.
Title 9 : 289th Military Police Company
Paragraph 9 : The 289th Military Police Company was activated on 1 November 1994 and attached to Hotel Company, 3rd Infantry (The Old Guard), Fort Myer, Virginia. Hotel Company is the regiment's specialty company.
Title 10 : Glennwanis Hotel
Paragraph 10 : The Glennwanis Hotel is a historic hotel in Glennville, Georgia, Tattnall County, Georgia, built on the site of the Hughes Hotel. The hotel is located at 209-215 East Barnard Street. The old Hughes Hotel was built out of Georgia pine circa 1905 and burned in 1920. The Glennwanis was built in brick in 1926. The local Kiwanis club led the effort to get the replacement hotel built, and organized a Glennville Hotel Company with directors being local business leaders. The wife of a local doctor won a naming contest with the name "Glennwanis Hotel", a suggestion combining "Glennville" and "Kiwanis".

Question: The Oberoi family is part of a hotel company that has a head office in what city?
Answer: Delhi
--------------------------------------------------
Batch 3:
Context: Title 1 : Lisa Simpson
Paragraph 1 : Lisa Marie Simpson is a fictional character in the animated television series "The Simpsons". She is the middle child and most intelligent of the Simpson family. Voiced by Yeardley Smith, Lisa first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed her while waiting to meet James L. Brooks. Groening had been invited to pitch a series of shorts based on his comic "Life in Hell", but instead decided to create a new set of characters. He named the elder Simpson daughter after his younger sister Lisa Groening. After appearing on "The Tracey Ullman Show" for three years, the Simpson family were moved to their own series on Fox, which debuted on December 17, 1989.
Title 2 : Marge Simpson
Paragraph 2 : Marjorie Jacqueline "Marge" Simpson (née Bouvier) is a fictional character in the American animated sitcom "The Simpsons" and part of the eponymous family. She is voiced by Julie Kavner and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Marge was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on "Life in Hell" but instead decided to create a new set of characters. He named the character after his mother Margaret Groening. After appearing on "The Tracey Ullman Show" for three seasons, the Simpson family received their own series on Fox, which debuted December 17, 1989.
Title 3 : Bart Simpson
Paragraph 3 : Bartholomew JoJo "Bart" Simpson is a fictional character in the American animated television series "The Simpsons" and part of the Simpson family. He is voiced by Nancy Cartwright and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed Bart while waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip, "Life in Hell", but instead decided to create a new set of characters. While the rest of the characters were named after Groening's family members, Bart's name is an anagram of the word "brat". After appearing on "The Tracey Ullman Show" for three years, the Simpson family received its own series on Fox, which debuted December 17, 1989.
Title 4 : Allie Goertz
Paragraph 4 : Allison Beth "Allie" Goertz (born March 2, 1991) is an American musician. Goertz is known for her satirical songs based on various pop culture topics. Her videos are posted on YouTube under the name of Cossbysweater. Subjects of her songs have included the film "The Room", the character Milhouse from the television show "The Simpsons", and the game Dungeons & Dragons. Her style has been compared to that of Bo Burnham. In December 2015, Goertz released a concept album based on the Adult Swim series "Rick and Morty", "Sad Dance Songs", with the album's cover emulating the animation and logo of the series. The album was made possible through Kickstarter. She is co-host of Everything's Coming Up Podcast, a Simpsons-focused podcast along with Julia Prescott.
Title 5 : Milhouse Van Houten
Paragraph 5 : Milhouse Mussolini van Houten is a fictional character featured in the animated television series "The Simpsons", voiced by Pamela Hayden, and created by Matt Groening who named the character after President Richard Nixon's middle name. Later in the series, it is revealed that Milhouse's middle name is "Mussolini."
Title 6 : Los Angeles Reader
Paragraph 6 : Los Angeles Reader was a weekly paper established in 1978 and distributed in Los Angeles, United States. It followed the format of the (still active) Chicago Reader. The paper was known for having lengthy, thoughtful reviews of movies, plays and concerts in the LA area. James Vowell was its founding editor. Among its writers were Keith Fitzgerald, Nigey Lennon, Lionel Rolfe, Lawrence Wechsler, Mick Farren, Richard Meltzer, Heidi Dvorak, Chris Morris, Jerry Stahl, Steven Kane, Andy Klein, Allen Levy, Jim Goad, Kirk Silsbee, Henry Sheehan, Samantha Dunn, Natalie Nichols, Steve Appleford, Eric Mankin (also editor), Paul Birchall, Eddie Rivera (who wrote the paper's first cover story), Amy Steinberg, Harry Sheehan, Dan Sallit, Myron Meisel, David Ehrenstein. Tom Davis, Bruce Bebb, Stuart Goldman, Ernest Hardy, Kevin Uhrich, Erik Himmelsbach and David L. Ulin. It is famous for being the first newspaper to publish Matt Groening's cartoon strip, Life in Hell on April 25, 1980. James Vowell hired Matt Groening as his assistant editor in 1979. Groening was also originally a Reader music critic. It also ran a cartoon strip by David Lynch (director of Blue Velvet) called The Angriest Dog in the World, a strip notable for having exactly the same drawing panels for its entire run. James Vowell and his wife Codette Wallace bought the Reader from the Chicago Reader in February 1989. They sold "The Reader" to New Times Media in 1996, which merged it with the "Los Angeles View" to form "New Times LA".
Title 7 : Homer Simpson
Paragraph 7 : Homer Jay Simpson is a fictional character and the main protagonist of the American animated television series "The Simpsons" as the patriarch of the eponymous family. He is voiced by Dan Castellaneta and first appeared on television, along with the rest of his family, in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Homer was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip "Life in Hell" but instead decided to create a new set of characters. He named the character after his father, Homer Groening. After appearing for three seasons on "The Tracey Ullman Show", the Simpson family got their own series on Fox that debuted December 17, 1989.
Title 8 : List of The Simpsons video games
Paragraph 8 : "The Simpsons" is an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company. The series is a satirical parody of a middle class American lifestyle epitomized by its eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. It is set in the fictional town of Springfield, and lampoons American culture, society and television, and many aspects of the human condition. The family was conceived by Groening shortly before a pitch for a series of animated shorts with producer James L. Brooks. Groening created a dysfunctional family and named the characters after members of his own family, substituting Bart for his own name. The shorts became a part of "The Tracey Ullman Show" on April 19, 1987 and after a three-season run, the sketch was developed into a half-hour prime time show and became a hit series for Fox. The growing popularity of the series motivated video game developers to create video games based on the series. Two pinball machines have also been produced; one self-titled, that was only made available for a limited time after the first season finale (1990) and "The Simpsons Pinball Party" (2003). Additionally, several handheld device games have been released, such as "Bartman: Avenger of Evil" (1990) and "Bart Simpson's Cupcake Crisis" (1991).
Title 9 : The Simpsons: An Uncensored, Unauthorized History
Paragraph 9 : The Simpsons: An Uncensored, Unauthorized History is a non-fiction book about the American animated television series "The Simpsons". It was written by John Ortved, and first published in October 2009 by Faber and Faber. In the United Kingdom, the book is called Simpsons Confidential: The uncensored, totally unauthorised history of the world's greatest TV show by the people that made it. The book is an oral history of the show, and concentrates particularly on the writers and producers of the show. The book includes entire chapters devoted to key figures such as creator Matt Groening and James L. Brooks and Sam Simon, who helped develop the series. According to National Public Radio reviewer Linda Holmes, "Ortved's thesis, essentially, is that lots of people are responsible for the success of "The Simpsons", and their creator, Matt Groening, has too often been viewed as the sole source to the detriment of others who also deserve to be praised."
Title 10 : List of The Simpsons guest stars
Paragraph 10 : In addition to the show's regular cast of voice actors, celebrity guest stars have been a staple of "The Simpsons", an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company, since its first season. "The Simpsons" focuses on the eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. The family was initially conceived by Groening for a series of animated shorts, which originally aired as a part of "The Tracey Ullman Show" between 1987 and 1989. The shorts were developed into a half-hour prime time series which began in December 1989. The series' 27th season began in September 2015 and episodes of "The Simpsons" have aired. A feature film adaptation of the series called "The Simpsons Movie", was released in 2007.

Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
Answer: President Richard Nixon

In [10]:
del train_hotpot_qa_json
del test_hotpot_qa_json

## 2. Getting Triples from Context and Question

In [11]:
from dotenv import load_dotenv
import os

load_dotenv()
openai_api_key = os.getenv("OPENAI_API_KEY")

In [12]:
from langchain_openai import ChatOpenAI
from langchain_core.globals import set_debug, set_verbose, set_llm_cache
from langchain_community.cache import InMemoryCache
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

set_debug(False)
set_verbose(False)
set_llm_cache(InMemoryCache())

llm_model = ChatOpenAI(model=LLM_MODEL, api_key=openai_api_key)

In [13]:
system_msg = """
<role>
    You are an expert in natural language understanding and knowledge graph construction. Your task is to extract structured relationship triples from a context set (Titles and Paragraphs), including both explicit and logically inferable facts.
</role>

<behavior>
    <rule name="Entity Extraction">
        Identify and extract unique entities from Titles and Paragraphs. Use canonical forms for names. Capture entities including people, organizations, locations, publications, dates, and events.
    </rule>
    <rule name="Relationship Extraction">
        Extract explicit and clearly implied relationships between entities in the form of (subject, relation, object) triples.
        This includes:
        - Temporal relations such as publication or operational time spans (e.g., "published during", "active from", "merged in").
        - Authorship, editorial, or contribution roles (e.g., "edited by", "featured work by").
        - Event-based or structural relations (e.g., "merged into", "founded by", "took over").
    </rule>
    <rule name="Completeness">
        Extract **as many valid and informative triples as possible**. Include relationships that are inferred logically but unambiguous in context (e.g., date ranges, geographic associations, contributor roles).
    </rule>
    <rule name="Formatting and Output">
        Output must contain two sections, in order:
        1. ### CONTEXT_REASONING — step-by-step reasoning describing how entities and relationships were selected or inferred.
        2. ### CONTEXT_TRIPLES — list all extracted triples, each on its own line in the format (entity_1, relationship, entity_2)
        Do not add explanations, numbering, or extra text outside of these sections.
    </rule>
</behavior>

<format>
1. Carefully read the <context> section.
2. Begin with this heading:
   ### CONTEXT_REASONING
   Then, write concise reasoning steps describing how entities and relationships were selected and interpreted.
3. After reasoning, print this heading:
   ### CONTEXT_TRIPLES
   Then list each extracted triple on a new line in the format (entity_1, relationship, entity_2).
4. Do not include any explanations, text, or comments after the last triple.
</format>
"""

human_msg = """
<context>
{context}
</context>
"""

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [14]:
chain = prompt | llm_model | StrOutputParser()

In [15]:
batch_input_list = []
main_df = pd.DataFrame()

for i in range(len(batch_context)):
    batch_num_list = [i] * len(batch_context[i])
    question_num_list = list(range(1, len(batch_context[i]) + 1))
    context_list = []
    question_list = []
    answers_list = []

    batch_input_item = []
    j = 0
    for batch in range(len(batch_context[i])):
        context = batch_context[i][batch]
        batch_input_item.append({
            "context": context
        })
        context_list.append(context)
        question_list.append(batch_question[i][j])
        answers_list.append(batch_answer[i][j])
        j += 1
    batch_input_list.append(batch_input_item)
    df = pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "context": context_list,
        "question": question_list,
        "answer": answers_list
    })
    main_df = pd.concat([main_df, df], ignore_index=True)

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1}:")
    for item in batch:
        print("Context:", item['context'])
        print("-" * 50)

Batch 1:
Context: Title 1 : Radio City (Indian radio station)
Paragraph 1 : Radio City is India's first private FM radio station and was started on 3 July 2001. It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003). It plays Hindi, English and regional songs. It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007. Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features. The Radio station currently plays a mix of Hindi and Regional music. Abraham Thomas is the CEO of the company.
Title 2 : History of Albanian football
Paragraph 2 : Football in Albania existed before the Albanian Football Federation (FSHF) was created. This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) . Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946. In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.
Title 3 : Echosmith
Paragraph 3 : Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California. Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016. Echosmith started first as "Ready Set Go!" until they signed to Warner Bros. Records in May 2012. They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia. The song was Warner Bros. Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold. The band's debut album, "Talking Dreams", was released on October 8, 2013.
Title 4 : Women's colleges in the Southern United States
Paragraph 4 : Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States. Many started first as girls' seminaries or academies. Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women. Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.
Title 5 : First Arthur County Courthouse and Jail
Paragraph 5 : The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.
Title 6 : Arthur's Magazine
Paragraph 6 : Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century. Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others. In May 1846 it was merged into "Godey's Lady's Book".
Title 7 : 2014–15 Ukrainian Hockey Championship
Paragraph 7 : The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship. Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues. Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014. The regular season included just 12 rounds, where all the teams went to the semifinals. In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.
Title 8 : First for Women
Paragraph 8 : First for Women is a woman's magazine published by Bauer Media Group in the USA. The magazine was started in 1989. It is based in Englewood Cliffs, New Jersey. In 2011 the circulation of the magazine was 1,310,696 copies.
Title 9 : Freeway Complex Fire
Paragraph 9 : The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California. The fire started as two separate fires on November 15, 2008. The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later. These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.
Title 10 : William Rast
Paragraph 10 : William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala. It is most known for their premium jeans. On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line. The label also produces other clothing items such as jackets and tops. The company started first as a denim line, later evolving into a men’s and women’s clothing line.

--------------------------------------------------
Context: Title 1 : Ritz-Carlton Jakarta
Paragraph 1 : The Ritz-Carlton Jakarta is a hotel and skyscraper in Jakarta, Indonesia and 14th Tallest building in Jakarta. It is located in city center of Jakarta, near Mega Kuningan, adjacent to the sister JW Marriott Hotel. It is operated by The Ritz-Carlton Hotel Company. The complex has two towers that comprises a hotel and the Airlangga Apartment respectively. The hotel was opened in 2005.
Title 2 : Oberoi family
Paragraph 2 : The Oberoi family is an Indian family that is famous for its involvement in hotels, namely through The Oberoi Group.
Title 3 : Ishqbaaaz
Paragraph 3 : Ishqbaaaz (English: "Lovers") is an Indian drama television series which is broadcast on Star Plus. It premiered on 27 June 2016 and airs Mon-Fri 10-11pm IST.Nakuul Mehta, Kunal Jaisingh and Leenesh Mattoo respectively portray Shivaay, Omkara and Rudra, the three heirs of the Oberoi family. The show initially focused on the tale of three brothers, later become centered on the love story of Shivaay and Annika (Surbhi Chandna); with the story of Omkara and Rudra being shifted to the spinoff series "Dil Boley Oberoi". In July 2017 "Dil Boley Oberoi" ended and the storylines were merged back into "Ishqbaaaz" which doubled its runtime.
Title 4 : Hotel Tallcorn
Paragraph 4 : The Hotel Tallcorn is located in Marshalltown, Iowa. Today it is called the Tallcorn Towers Apartments. Built in 1928 by the Eppley Hotel Company, local citizens contributed $120,000 to ensure the successful completion of this seven-story hotel. It was completed in connection to the seventy-fifth anniversary of Marshalltown. The hotel's sale in 1956 from the Eppley chain to the Sheraton Corporation was part of the second largest hotel sale in United States history. The Tallcorn was listed as a contributing property in the Marshalltown Downtown Historic District on the National Register of Historic Places in 2002.
Title 5 : Mohan Singh Oberoi
Paragraph 5 : Rai Bahadur Mohan Singh Oberoi (15 August 1898 – 3 May 2002) was an Indian hotelier, the founder and chairman of Oberoi Hotels & Resorts, India's second-largest hotel company, with 35 hotels in India, Sri Lanka, Nepal, Egypt, Australia and Hungary.
Title 6 : Hotel Bond
Paragraph 6 : Hotel Bond is a historic hotel, built in two stages in 1913 and 1921, in downtown Hartford, Connecticut by hotelier Harry S. Bond. It is located near Bushnell Park, and was considered the grandest hotel in Hartford during its heyday. The second section is a 12 story building attached to the 6 story first section. A Statler Hotel opened in the area in 1954, creating competition, and the Bond Hotel company declared bankruptcy shortly after that. It was bought by the California-based Masaglia Hotel chain, which began an incremental renovation program. In 1964 it was sold to a Cincinnati, Ohio investment group which announced extensive renovation plans. However, the financing plans fell through and the hotel was again in bankruptcy. The building was sold at auction to the Roman Catholic Archdiocese of Hartford in 1965, and it became the home of the Saint Francis Hospital School of Nursing. The Bond Ballroom reopened in 2001, with the rest of the building becoming a Homewood Suites by Hilton in 2006.
Title 7 : The Oberoi Group
Paragraph 7 : The Oberoi Group is a hotel company with its head office in Delhi. Founded in 1934, the company owns and/or operates 30+ luxury hotels and two river cruise ships in six countries, primarily under its Oberoi Hotels & Resorts and Trident Hotels brands.
Title 8 : Future Fibre Technologies
Paragraph 8 : Future Fibre Technologies (FFT) is a fiber optic sensing technologies company based in Melbourne, Australia, with its US head office in Mountain View, California, Middle East head office in Dubai, Indian head office in New Delhi and European head office in London. Founded in 1994, Future Fibre Technologies product line provides optical fiber intrusion detection systems for perimeters, buried oil and gas pipelines and data communication networks.
Title 9 : 289th Military Police Company
Paragraph 9 : The 289th Military Police Company was activated on 1 November 1994 and attached to Hotel Company, 3rd Infantry (The Old Guard), Fort Myer, Virginia. Hotel Company is the regiment's specialty company.
Title 10 : Glennwanis Hotel
Paragraph 10 : The Glennwanis Hotel is a historic hotel in Glennville, Georgia, Tattnall County, Georgia, built on the site of the Hughes Hotel. The hotel is located at 209-215 East Barnard Street. The old Hughes Hotel was built out of Georgia pine circa 1905 and burned in 1920. The Glennwanis was built in brick in 1926. The local Kiwanis club led the effort to get the replacement hotel built, and organized a Glennville Hotel Company with directors being local business leaders. The wife of a local doctor won a naming contest with the name "Glennwanis Hotel", a suggestion combining "Glennville" and "Kiwanis".

--------------------------------------------------
Context: Title 1 : Lisa Simpson
Paragraph 1 : Lisa Marie Simpson is a fictional character in the animated television series "The Simpsons". She is the middle child and most intelligent of the Simpson family. Voiced by Yeardley Smith, Lisa first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed her while waiting to meet James L. Brooks. Groening had been invited to pitch a series of shorts based on his comic "Life in Hell", but instead decided to create a new set of characters. He named the elder Simpson daughter after his younger sister Lisa Groening. After appearing on "The Tracey Ullman Show" for three years, the Simpson family were moved to their own series on Fox, which debuted on December 17, 1989.
Title 2 : Marge Simpson
Paragraph 2 : Marjorie Jacqueline "Marge" Simpson (née Bouvier) is a fictional character in the American animated sitcom "The Simpsons" and part of the eponymous family. She is voiced by Julie Kavner and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Marge was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on "Life in Hell" but instead decided to create a new set of characters. He named the character after his mother Margaret Groening. After appearing on "The Tracey Ullman Show" for three seasons, the Simpson family received their own series on Fox, which debuted December 17, 1989.
Title 3 : Bart Simpson
Paragraph 3 : Bartholomew JoJo "Bart" Simpson is a fictional character in the American animated television series "The Simpsons" and part of the Simpson family. He is voiced by Nancy Cartwright and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed Bart while waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip, "Life in Hell", but instead decided to create a new set of characters. While the rest of the characters were named after Groening's family members, Bart's name is an anagram of the word "brat". After appearing on "The Tracey Ullman Show" for three years, the Simpson family received its own series on Fox, which debuted December 17, 1989.
Title 4 : Allie Goertz
Paragraph 4 : Allison Beth "Allie" Goertz (born March 2, 1991) is an American musician. Goertz is known for her satirical songs based on various pop culture topics. Her videos are posted on YouTube under the name of Cossbysweater. Subjects of her songs have included the film "The Room", the character Milhouse from the television show "The Simpsons", and the game Dungeons & Dragons. Her style has been compared to that of Bo Burnham. In December 2015, Goertz released a concept album based on the Adult Swim series "Rick and Morty", "Sad Dance Songs", with the album's cover emulating the animation and logo of the series. The album was made possible through Kickstarter. She is co-host of Everything's Coming Up Podcast, a Simpsons-focused podcast along with Julia Prescott.
Title 5 : Milhouse Van Houten
Paragraph 5 : Milhouse Mussolini van Houten is a fictional character featured in the animated television series "The Simpsons", voiced by Pamela Hayden, and created by Matt Groening who named the character after President Richard Nixon's middle name. Later in the series, it is revealed that Milhouse's middle name is "Mussolini."
Title 6 : Los Angeles Reader
Paragraph 6 : Los Angeles Reader was a weekly paper established in 1978 and distributed in Los Angeles, United States. It followed the format of the (still active) Chicago Reader. The paper was known for having lengthy, thoughtful reviews of movies, plays and concerts in the LA area. James Vowell was its founding editor. Among its writers were Keith Fitzgerald, Nigey Lennon, Lionel Rolfe, Lawrence Wechsler, Mick Farren, Richard Meltzer, Heidi Dvorak, Chris Morris, Jerry Stahl, Steven Kane, Andy Klein, Allen Levy, Jim Goad, Kirk Silsbee, Henry Sheehan, Samantha Dunn, Natalie Nichols, Steve Appleford, Eric Mankin (also editor), Paul Birchall, Eddie Rivera (who wrote the paper's first cover story), Amy Steinberg, Harry Sheehan, Dan Sallit, Myron Meisel, David Ehrenstein. Tom Davis, Bruce Bebb, Stuart Goldman, Ernest Hardy, Kevin Uhrich, Erik Himmelsbach and David L. Ulin. It is famous for being the first newspaper to publish Matt Groening's cartoon strip, Life in Hell on April 25, 1980. James Vowell hired Matt Groening as his assistant editor in 1979. Groening was also originally a Reader music critic. It also ran a cartoon strip by David Lynch (director of Blue Velvet) called The Angriest Dog in the World, a strip notable for having exactly the same drawing panels for its entire run. James Vowell and his wife Codette Wallace bought the Reader from the Chicago Reader in February 1989. They sold "The Reader" to New Times Media in 1996, which merged it with the "Los Angeles View" to form "New Times LA".
Title 7 : Homer Simpson
Paragraph 7 : Homer Jay Simpson is a fictional character and the main protagonist of the American animated television series "The Simpsons" as the patriarch of the eponymous family. He is voiced by Dan Castellaneta and first appeared on television, along with the rest of his family, in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Homer was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip "Life in Hell" but instead decided to create a new set of characters. He named the character after his father, Homer Groening. After appearing for three seasons on "The Tracey Ullman Show", the Simpson family got their own series on Fox that debuted December 17, 1989.
Title 8 : List of The Simpsons video games
Paragraph 8 : "The Simpsons" is an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company. The series is a satirical parody of a middle class American lifestyle epitomized by its eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. It is set in the fictional town of Springfield, and lampoons American culture, society and television, and many aspects of the human condition. The family was conceived by Groening shortly before a pitch for a series of animated shorts with producer James L. Brooks. Groening created a dysfunctional family and named the characters after members of his own family, substituting Bart for his own name. The shorts became a part of "The Tracey Ullman Show" on April 19, 1987 and after a three-season run, the sketch was developed into a half-hour prime time show and became a hit series for Fox. The growing popularity of the series motivated video game developers to create video games based on the series. Two pinball machines have also been produced; one self-titled, that was only made available for a limited time after the first season finale (1990) and "The Simpsons Pinball Party" (2003). Additionally, several handheld device games have been released, such as "Bartman: Avenger of Evil" (1990) and "Bart Simpson's Cupcake Crisis" (1991).
Title 9 : The Simpsons: An Uncensored, Unauthorized History
Paragraph 9 : The Simpsons: An Uncensored, Unauthorized History is a non-fiction book about the American animated television series "The Simpsons". It was written by John Ortved, and first published in October 2009 by Faber and Faber. In the United Kingdom, the book is called Simpsons Confidential: The uncensored, totally unauthorised history of the world's greatest TV show by the people that made it. The book is an oral history of the show, and concentrates particularly on the writers and producers of the show. The book includes entire chapters devoted to key figures such as creator Matt Groening and James L. Brooks and Sam Simon, who helped develop the series. According to National Public Radio reviewer Linda Holmes, "Ortved's thesis, essentially, is that lots of people are responsible for the success of "The Simpsons", and their creator, Matt Groening, has too often been viewed as the sole source to the detriment of others who also deserve to be praised."
Title 10 : List of The Simpsons guest stars
Paragraph 10 : In addition to the show's regular cast of voice actors, celebrity guest stars have been a staple of "The Simpsons", an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company, since its first season. "The Simpsons" focuses on the eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. The family was initially conceived by Groening for a series of animated shorts, which originally aired as a part of "The Tracey Ullman Show" between 1987 and 1989. The shorts were developed into a half-hour prime time series which began in December 1989. The series' 27th season began in September 2015 and episodes of "The Simpsons" have aired. A feature film adaptation of the series called "The Simpsons Movie", was released in 2007.

--------------------------------------------------
Context: Title 1 : Moloch: or, This Gentile World

In [16]:
main_df

,batch_num,question_num,context,question,answer
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long

In [17]:
graphs_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    graphs_str_list = chain.batch(batch)
    graphs_str_batch.append(graphs_str_list)

Batch 1 ... processing 10 items

In [18]:
for i, graphs_str_list in enumerate(graphs_str_batch):
    print(f"Batch {i + 1} ... processed {len(graphs_str_list)} items")
    for j, graph_str in enumerate(graphs_str_list):
        print(f"Item {j + 1}:")
        print(graph_str)
        print("-" * 50)

Batch 1 ... processed 10 items
Item 1:
### CONTEXT_REASONING
Entities were extracted by identifying names of organizations, people, places, events, publications, dates, and notable subject nouns across all paragraphs. Relationships were derived from verbs and logically implied facts, such as operational spans, launch events, founder roles, published in or during time periods, and mergers. For instance, “Radio City” entities connect to specific cities and dates as stations launched there. Authorship and editorial relationships were found for magazines, with contributor work inferred where artists’ works were featured. Event unions (such as fire mergers), achievements (such as championship wins), and specifics about organizations (like target demographic or geographic location) were also meticulously extracted. For entities mentioned with time qualifiers (e.g., “oldest”, “first”), both temporal and distinction-based relationships were considered.

### CONTEXT_TRIPLES
(Radio City, is, radio station)
(Radio City, is, India's first private FM radio station)
(Radio City, started on, 3 July 2001)
(Radio City, broadcasts on, 91.1 megahertz)
(Radio City, broadcast frequency was, 91.0 megahertz)
(Radio City, broadcasts from, Mumbai)
(Radio City, launched in city, Mumbai)
(Mumbai, received Radio City, 2004)
(Radio City, broadcasts from, Bengaluru)
(Bengaluru, received Radio City, 2001)
(Radio City, broadcasts from, Lucknow)
(Radio City, broadcasts from, New Delhi)
(New Delhi, received Radio City, 2003)
(Radio City, plays, Hindi songs)
(Radio City, plays, English songs)
(Radio City, plays, regional songs)
(Radio City, launched in, Hyderabad)
(Hyderabad, received Radio City, March 2006)
(Radio City, launched in, Chennai)
(Chennai, received Radio City, 7 July 2006)
(Radio City, launched in, Visakhapatnam)
(Visakhapatnam, received Radio City, October 2007)
(Radio City, forayed into, New Media)
(Radio City, launched, PlanetRadiocity.com)
(PlanetRadiocity.com, launched in, May 2008)
(PlanetRadiocity.com, offers, music-related news)
(PlanetRadiocity.com, offers, videos)
(PlanetRadiocity.com, offers, songs)
(PlanetRadiocity.com, offers, music-related features)
(Radio City, CEO, Abraham Thomas)
(Radio City, plays, mix of Hindi and Regional music)
(Football, existed in, Albania)
(Albanian Football Federation, abbreviation, FSHF)
(Albanian Football Federation, created after, football existed in Albania)
(Albania, registered at, Balkan Cup)
(Balkan Cup, took place during, 1929-1931)
(Albanian national team, founded on, 6 June 1930)
(Albanian national team, first international match, 1946)
(Albanian national team, defeated, Yugoslavia)
(Albania, joined, FIFA)
(Albania, joined FIFA at event, 12–16 June 1932 convention)
(Albania, founding member of, UEFA)
(Albania, became UEFA founding member, 1954)
(Echosmith, is, American indie pop band)
(Echosmith, formed in, February 2009)
(Echosmith, formed in, Chino, California)
(Echosmith, original members, Sydney Sierota)
(Echosmith, original members, Noah Sierota)
(Echosmith, original members, Graham Sierota)
(Echosmith, original members, Jamie Sierota)
(Jamie Sierota, departed from, Echosmith)
(Jamie Sierota, left Echosmith, late 2016)
(Echosmith, former name, Ready Set Go!)
(Echosmith, signed to, Warner Bros. Records)
(Echosmith, signed to Warner Bros. Records, May 2012)
(Echosmith, known for, Cool Kids)
(Cool Kids, reached position, 13 on Billboard Hot 100)
(Cool Kids, certified, double platinum by RIAA)
(Cool Kids, certified, double platinum by ARIA)
(Cool Kids, sold in US, over 1,200,000 units)
(Cool Kids, Warner Bros. Records fifth-biggest-selling-digital song, 2014)
(Cool Kids, digital downloads sold, 1.3 million)
(Echosmith, debut album, Talking Dreams)
(Talking Dreams, released on, October 8, 2013)
(Women’s colleges in the Southern United States, is, undergraduate institutions)
(Women’s colleges in the Southern United States, are, bachelor's degree-granting institutions)
(Women’s colleges in the Southern United States, mostly, liberal arts colleges)
(Women's colleges in the Southern United States, student population, women)
(Women’s colleges in the Southern United States, located in, Southern United States)
(Women’s colleges in the Southern United States, origin, started as girls’ seminaries or academies)
(Salem College, is, oldest female educational institution in the South)
(Salem College, offers, coeducational graduate courses)
(Wesleyan College, is, first college established specifically for women in the South)
(Mary Baldwin University, offers, coeducational graduate courses)
(First Arthur County Courthouse and Jail, is, courthouse)
(First Arthur County Courthouse and Jail, is, jail)
(First Arthur County Courthouse and Jail, was, perhaps smallest courthouse in the United States)
(First Arthur County Courthouse and Jail, current use, museum)
(Arthur's Magazine, is, American literary periodical)
(Arthur's Magazine, published in, Philadelphia)
(Arthur's Magazine, published during, 1844–1846)
(T.S. Arthur, editor of, Arthur's Magazine)
(Edgar A. Poe, featured in, Arthur's Magazine)
(J.H. Ingraham, featured in, Arthur's Magazine)
(Sarah Josepha Hale, featured in, Arthur's Magazine)
(Thomas G. Spear, featured in, Arthur's Magazine)
(Arthur's Magazine, merged into, Godey's Lady's Book)
(Merger of Arthur's Magazine and Godey's Lady's Book, happened, May 1846)
(2014–15 Ukrainian Hockey Championship, is, ice hockey season)
(2014–15 Ukrainian Hockey Championship, is, 23rd season of the Ukrainian Hockey Championship)
(2014–15 Ukrainian Hockey Championship, number of teams, four)
(2014–15 Ukrainian Hockey Championship, occurred during, political instability in Ukraine)
(2014–15 Ukrainian Hockey Championship, occurred during, economic issues)
(Generals Kiev, participated in, Ukrainian Hockey Championship previous season)
(2014–15 Ukrainian Hockey Championship, started after, year-end 2014)
(2014–15 Ukrainian Hockey Championship, regular season rounds, 12)
(All teams, reached, semifinals in 2014–15 Ukrainian Hockey Championship)
(ATEK Kiev, defeated, HK Kremenchuk)
(HK Kremenchuk, was, regular season winner)
(ATEK Kiev, won, 2014–15 Ukrainian Hockey Championship final)
(First for Women, is, magazine)
(First for Women, target audience, women)
(First for Women, published by, Bauer Media Group)
(First for Women, published in, USA)
(First for Women, started in, 1989)
(First for Women, based in, Englewood Cliffs, New Jersey)
(First for Women, circulation, 1,310,696 copies in 2011)
(Freeway Complex Fire, is, wildfire)
(Freeway Complex Fire, occurred in, Santa Ana Canyon)
(Freeway Complex Fire, occurred in, Orange County, California)
(Freeway Complex Fire, occurred in, 2008)
(Freeway Complex Fire, started as, Freeway Fire)
(Freeway Fire, ignited on, November 15, 2008)
(Freeway Fire, started at, after 9am)
(Landfill Fire, ignited, 2 hours after Freeway Fire)
(Freeway Complex Fire, formed by, merger of Freeway Fire and Landfill Fire)
(Merger of Freeway Fire and Landfill Fire, happened, a day after November 15, 2008)
(Freeway Complex Fire, destroyed, 314 residences)
(314 residences, located in, Anaheim Hills)
(314 residences, located in, Yorba Linda)
(William Rast, is, American clothing line)
(William Rast, founded by, Justin Timberlake)
(William Rast, founded by, Trace Ayala)
(William Rast, known for, premium jeans)
(Justin Timberlake, held first William Rast fashion show, October 17, 2006)
(Trace Ayala, held first William Rast fashion show, October 17, 2006)
(William Rast, produces, jackets)
(William Rast, produces, tops)
(William Rast, started as, denim line)
(William Rast, evolved into, men’s and women’s clothing line)
--------------------------------------------------
Item 2:
### CONTEXT_REASONING
Entities were extracted based on clear mentions of people, organizations, locations, hotels, television series, hotel companies, and events across the paragraphs. Relationships include location, construction/completion dates, operational roles, ownership, rebranding, and mergers, as well as familial and fictional connections. Temporal details (years, date ranges), authorship/founder roles, ownership changes, architectural/structural facts, and broadcast information for the TV series are also presented when either explicit or logically derivable. For instance, hotel sales, mergers, broadcast times, and familial or fictional relationships were all considered. Inferred relationships, such as "merges back" from the TV show context or hotel company association due to founding or ownership, are included when contextually clear.

### CONTEXT_TRIPLES
(Ritz-Carlton Jakarta, is a, hotel)
(Ritz-Carlton Jakarta, is a, skyscraper)
(Ritz-Carlton Jakarta, located in, Jakarta)
(Ritz-Carlton Jakarta, located in, Indonesia)
(Ritz-Carlton Jakarta, is, 14th tallest building in Jakarta)
(Ritz-Carlton Jakarta, located near, Mega Kuningan)
(Ritz-Carlton Jakarta, adjacent to, JW Marriott Hotel)
(Ritz-Carlton Jakarta, operated by, The Ritz-Carlton Hotel Company)
(Ritz-Carlton Jakarta, comprises, two towers)
(Ritz-Carlton Jakarta, has part, hotel)
(Ritz-Carlton Jakarta, has part, Airlangga Apartment)
(Ritz-Carlton Jakarta, opened in, 2005)
(Jakarta, is in, Indonesia)
(JW Marriott Hotel, is a, hotel)
(Airlangga Apartment, is a, apartment)
(Oberoi family, is a, Indian family)
(Oberoi family, famous for, involvement in hotels)
(Oberoi family, associated with, The Oberoi Group)
(Ishqbaaaz, is a, Indian drama television series)
(Ishqbaaaz, broadcast on, Star Plus)
(Ishqbaaaz, premiered on, 27 June 2016)
(Ishqbaaaz, airs on, Mon-Fri 10-11pm IST)
(Nakuul Mehta, portrays, Shivaay)
(Kunal Jaisingh, portrays, Omkara)
(Leenesh Mattoo, portrays, Rudra)
(Shivaay, is heir of, Oberoi family)
(Omkara, is heir of, Oberoi family)
(Rudra, is heir of, Oberoi family)
(Ishqbaaaz, initially focused on, tale of three brothers)
(Annika, portrayed by, Surbhi Chandna)
(Ishqbaaaz, later focused on, love story of Shivaay and Annika)
(Ishqbaaaz, shifted story of Omkara and Rudra to, Dil Boley Oberoi)
(Dil Boley Oberoi, is a, spinoff series)
(Dil Boley Oberoi, merged back into, Ishqbaaaz)
(Ishqbaaaz, doubled runtime after, July 2017 merge)
(Hotel Tallcorn, located in, Marshalltown)
(Hotel Tallcorn, located in, Iowa)
(Hotel Tallcorn, called today, Tallcorn Towers Apartments)
(Hotel Tallcorn, built by, Eppley Hotel Company)
(Hotel Tallcorn, built in, 1928)
(Local citizens, contributed to, Hotel Tallcorn completion)
(Hotel Tallcorn, completed in connection to, seventy-fifth anniversary of Marshalltown)
(Hotel Tallcorn, sold from, Eppley Hotel Company)
(Hotel Tallcorn, sold to, Sheraton Corporation)
(Hotel Tallcorn, sale in, 1956)
(Hotel Tallcorn, sale as part of, second largest hotel sale in United States history)
(Hotel Tallcorn, listed as, contributing property in Marshalltown Downtown Historic District)
(Hotel Tallcorn, listed on, National Register of Historic Places)
(Hotel Tallcorn, listed in, 2002)
(Marshalltown Downtown Historic District, located in, Marshalltown)
(Mohan Singh Oberoi, full name, Rai Bahadur Mohan Singh Oberoi)
(Mohan Singh Oberoi, birth date, 15 August 1898)
(Mohan Singh Oberoi, death date, 3 May 2002)
(Mohan Singh Oberoi, is a, Indian hotelier)
(Mohan Singh Oberoi, founder of, Oberoi Hotels & Resorts)
(Mohan Singh Oberoi, chairman of, Oberoi Hotels & Resorts)
(Oberoi Hotels & Resorts, is a, hotel company)
(Oberoi Hotels & Resorts, second-largest hotel company in India)
(Oberoi Hotels & Resorts, has, 35 hotels)
(Oberoi Hotels & Resorts, hotels in, India)
(Oberoi Hotels & Resorts, hotels in, Sri Lanka)
(Oberoi Hotels & Resorts, hotels in, Nepal)
(Oberoi Hotels & Resorts, hotels in, Egypt)
(Oberoi Hotels & Resorts, hotels in, Australia)
(Oberoi Hotels & Resorts, hotels in, Hungary)
(Hotel Bond, is a, historic hotel)
(Hotel Bond, located in, Hartford)
(Hotel Bond, located in, Connecticut)
(Hotel Bond, built in, 1913)
(Hotel Bond, second section built in, 1921)
(Hotel Bond, built by, Harry S. Bond)
(Hotel Bond, near, Bushnell Park)
(Hotel Bond, considered as, grandest hotel in Hartford during heyday)
(Hotel Bond, second section, 12 story building)
(Hotel Bond, first section, 6 story building)
(Statler Hotel, opened in, Hartford)
(Statler Hotel, opened in, 1954)
(Statler Hotel, created competition for, Hotel Bond)
(Hotel Bond, declared bankruptcy, after 1954)
(Hotel Bond, bought by, Masaglia Hotel chain)
(Masaglia Hotel chain, based in, California)
(Masaglia Hotel chain, began, incremental renovation of Hotel Bond)
(Hotel Bond, sold to, Cincinnati investment group)
(Hotel Bond, sold in, 1964)
(Cincinnati investment group, announced, extensive renovation plans for Hotel Bond)
(Hotel Bond, entered bankruptcy again, after 1964)
(Hotel Bond, sold at auction to, Roman Catholic Archdiocese of Hartford)
(Hotel Bond, became home of, Saint Francis Hospital School of Nursing)
(Hotel Bond Ballroom, reopened in, 2001)
(Hotel Bond building, became, Homewood Suites by Hilton)
(Building, became Homewood Suites by Hilton, in 2006)
(Roman Catholic Archdiocese of Hartford, located in, Hartford)
(Glennwanis Hotel, is a, historic hotel)
(Glennwanis Hotel, located in, Glennville)
(Glennwanis Hotel, located in, Tattnall County)
(Glennwanis Hotel, built on site of, Hughes Hotel)
(Glennwanis Hotel, address, 209-215 East Barnard Street)
(Hughes Hotel, built circa, 1905)
(Hughes Hotel, built using, Georgia pine)
(Hughes Hotel, burned in, 1920)
(Glennwanis Hotel, built in, 1926)
(Glennwanis Hotel, built using, brick)
(local Kiwanis club, led effort to build, Glennwanis Hotel)
(Glennville Hotel Company, organized by, local Kiwanis club)
(Glennville Hotel Company, had directors, local business leaders)
(wife of local doctor, won, naming contest for Glennwanis Hotel)
(Glennwanis Hotel, name combines, Glennville and Kiwanis)
(The Oberoi Group, is a, hotel company)
(The Oberoi Group, head office in, Delhi)
(The Oberoi Group, founded in, 1934)
(The Oberoi Group, owns or operates, 30+ luxury hotels)
(The Oberoi Group, owns or operates, two river cruise ships)
(The Oberoi Group, presence in, six countries)
(The Oberoi Group, operates brands, Oberoi Hotels & Resorts)
(The Oberoi Group, operates brands, Trident Hotels)
(Future Fibre Technologies, is a, fiber optic sensing technologies company)
(Future Fibre Technologies, based in, Melbourne)
(Future Fibre Technologies, US head office in, Mountain View)
(Future Fibre Technologies, Middle East head office in, Dubai)
(Future Fibre Technologies, Indian head office in, New Delhi)
(Future Fibre Technologies, European head office in, London)
(Future Fibre Technologies, founded in, 1994)
(Future Fibre Technologies, product line provides, optical fiber intrusion detection systems)
(Future Fibre Technologies, intrusion detection for, perimeters)
(Future Fibre Technologies, intrusion detection for, buried oil and gas pipelines)
(Future Fibre Technologies, intrusion detection for, data communication networks)
(289th Military Police Company, activated on, 1 November 1994)
(289th Military Police Company, attached to, Hotel Company, 3rd Infantry)
(Hotel Company, 3rd Infantry, is, The Old Guard)
(Hotel Company, is, regiment's specialty company)
(Marshalltown, located in, Iowa)
(Glennville, located in, Tattnall County)
(Tattnall County, located in, Georgia)
(Hartford, located in, Connecticut)
(Mountain View, located in, California)
(Melbourne, located in, Australia)
(Delhi, located in, India)
(New Delhi, located in, India)
(Dubai, located in, United Arab Emirates)
(London, located in, United Kingdom)
(Annika, is a, character in Ishqbaaaz)
(Shivaay, is a, character in Ishqbaaaz)
(Omkara, is a, character in Ishqbaaaz)
(Rudra, is a, character in Ishqbaaaz)
(Surbhi Chandna, portrays, Annika)
--------------------------------------------------
Item 3:
### CONTEXT_REASONING
Entities are extracted by identifying unique names of people, fictional characters, companies, media properties, publications, dates, and events explicitly mentioned or inferable from the text. Relationships include creation/design, voice acting, character naming inspiration, publication events and dates, authorship, editorial roles, contributor roles, publication mergers, and adaptation relations. Temporal relations are also inferred when duration or debut dates are stated. Fictional relationships within the Simpson family and career highlights are also mapped. Relationships between series, episodes, comics, and derivative works such as video games or books are extracted. Guest appearances and key contributors to "The Simpsons" are associated accordingly. Inferred relations (such as family relations for Simpsons characters and naming patterns) are included where unambiguously supported.

### CONTEXT_TRIPLES
(Lisa Simpson, is fictional character in, The Simpsons)
(Lisa Simpson, is voiced by, Yeardley Smith)
(Lisa Simpson, first appeared in, The Tracey Ullman Show short Good Night)
(Lisa Simpson, first appeared on, April 19, 1987)
(Lisa Simpson, is middle child of, Simpson family)
(Lisa Simpson, is daughter of, Marge Simpson)
(Lisa Simpson, is daughter of, Homer Simpson)
(Lisa Simpson, is sibling of, Bart Simpson)
(Lisa Simpson, is sibling of, Maggie Simpson)
(Matt Groening, created and designed, Lisa Simpson)
(Matt Groening, named Lisa Simpson after, Lisa Groening)
(The Simpsons, debuted on Fox, December 17, 1989)
(The Simpsons, is set in, Springfield)
(The Simpsons, created by, Matt Groening)
(The Simpsons, is developed for, Fox Broadcasting Company)
(The Simpsons, adapted from, The Tracey Ullman Show shorts)
(The Tracey Ullman Show short Good Night, aired on, April 19, 1987)
(Matt Groening, created while waiting to meet, James L. Brooks)
(Matt Groening, pitched, Life in Hell)
(Matt Groening, created, Simpson family)

(Marge Simpson, is fictional character in, The Simpsons)
(Marge Simpson, is voiced by, Julie Kavner)
(Marge Simpson, née, Bouvier)
(Marge Simpson, first appeared in, The Tracey Ullman Show short Good Night)
(Marge Simpson, first appeared on, April 19, 1987)
(Marge Simpson, is mother of, Bart Simpson)
(Marge Simpson, is mother of, Lisa Simpson)
(Marge Simpson, is mother of, Maggie Simpson)
(Marge Simpson, is wife of, Homer Simpson)
(Matt Groening, created and designed, Marge Simpson)
(Matt Groening, named Marge Simpson after, Margaret Groening)

(Bart Simpson, is fictional character in, The Simpsons)
(Bart Simpson, is voiced by, Nancy Cartwright)
(Bart Simpson, first appeared in, The Tracey Ullman Show short Good Night)
(Bart Simpson, first appeared on, April 19, 1987)
(Bart Simpson, is son of, Homer Simpson)
(Bart Simpson, is son of, Marge Simpson)
(Bart Simpson, is sibling of, Lisa Simpson)
(Bart Simpson, is sibling of, Maggie Simpson)
(Matt Groening, created and designed, Bart Simpson)
(Bart Simpson, name is anagram of, brat)

(Homer Simpson, is fictional character in, The Simpsons)
(Homer Simpson, is voiced by, Dan Castellaneta)
(Homer Simpson, first appeared in, The Tracey Ullman Show short Good Night)
(Homer Simpson, first appeared on, April 19, 1987)
(Homer Simpson, is father of, Bart Simpson)
(Homer Simpson, is father of, Lisa Simpson)
(Homer Simpson, is father of, Maggie Simpson)
(Homer Simpson, is husband of, Marge Simpson)
(Matt Groening, created and designed, Homer Simpson)
(Matt Groening, named Homer Simpson after, Homer Groening)

(Maggie Simpson, is member of, Simpson family)
(Maggie Simpson, is sibling of, Bart Simpson)
(Maggie Simpson, is sibling of, Lisa Simpson)
(Maggie Simpson, is daughter of, Marge Simpson)
(Maggie Simpson, is daughter of, Homer Simpson)

(The Simpsons family, originally appeared on, The Tracey Ullman Show)
(The Simpsons family, appeared on The Tracey Ullman Show, from 1987 to 1989)
(The Simpsons, received own series on Fox, December 17, 1989)
(The Simpsons, features main characters, Homer Simpson)
(The Simpsons, features main characters, Marge Simpson)
(The Simpsons, features main characters, Bart Simpson)

In [19]:
graphs_str_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "graphs_str": []
})

for i, graphs_str_list in enumerate(graphs_str_batch):
    batch_num_list = [i] * len(graphs_str_list)
    question_num_list = list(range(1, len(graphs_str_list) + 1))
    graphs_str_df = pd.concat([graphs_str_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "graphs_str": graphs_str_list
    })], ignore_index=True)

del graphs_str_batch
del graphs_str_list
del batch_input_list
del batch_context
del batch_question
del batch_answer

graphs_str_df

   batch_num  question_num                                         graphs_str
0        0.0           1.0  ### CONTEXT_REASONING\nEntities were extracted...
1        0.0           2.0  ### CONTEXT_REASONING\nEntities were extracted...
2        0.0           3.0  ### CONTEXT_REASONING\nEntities are extracted ...
3        0.0           4.0  ### CONTEXT_REASONING\nEntities were extracted...
4        0.0           5.0  ### CONTEXT_REASONING\nEntities were extracted...
5        0.0           6.0  ### CONTEXT_REASONING\nEntities were identifie...
6        0.0           7.0  ### CONTEXT_REASONING\nEntities were extracted...
7        0.0           8.0  ### CONTEXT_REASONING\nFirst, I identified uni...
8        0.0           9.0  ### CONTEXT_REASONING\nI identified television...
9        0.0          10.0  ### CONTEXT_REASONING\nFirst, I identified maj...

## 3. Parsing the Output and Building KGs

In [20]:
import re
from ast import literal_eval


def sanitize_str(name):
    """
    Sanitize a name by removing extra spaces, apostrophes, and ensuring proper formatting.
    """
    # Replace apostrophes with empty string
    name = name.replace("'s", "s")
    name = name.replace("'", "")

    # Replace spaces with underscores
    name = name.replace(" ", "_")
    name = name.replace("–", "_")

    # Remove any other problematic characters
    name = re.sub(r'[^\w\.\-_]', '', name)

    # Prefix if starts with digit
    if re.match(r"^\d", name):
        name = f"n{name}"

    # If empty string, return something safe
    if not name:
        name = "unknown"

    return name


def sanitize_entities_and_relations(triple):
    """
    Sanitize entities and relations in a triple by removing extra spaces and ensuring proper formatting.
    """
    return (
        sanitize_str(triple[0].strip().lower()),  # Subject
        sanitize_str(triple[1].strip().lower()),  # Relation
        sanitize_str(triple[2].strip().lower())  # Object
    )


def parse_custom_triples(triples_str):
    triples = []
    for line in triples_str.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        # Remove enclosing parentheses
        if line.startswith('(') and line.endswith(')'):
            line = line[1:-1]
        # Now, split ONLY on the first two commas
        parts = []
        remaining = line
        for _ in range(2):
            # Find the first comma
            idx = remaining.find(',')
            if idx == -1:
                break
            parts.append(remaining[:idx].strip())
            remaining = remaining[idx + 1:].strip()
        parts.append(remaining)
        if len(parts) == 3:
            triples.append(sanitize_entities_and_relations(tuple(parts)))
    return triples


def extract_sections(text, reasoning_pat, triples_pat):
    # Extract sections using regex
    extracted_reasoning = re.search(reasoning_pat, text, re.DOTALL)
    extracted_triples = re.search(triples_pat, text, re.DOTALL)

    # Clean reasoning sections
    reasoning_str = extracted_reasoning.group(1).strip() if extracted_reasoning else ""

    # Use the custom parser for triples
    triples_list = parse_custom_triples(extracted_triples.group(1)) if extracted_triples else []

    return reasoning_str, triples_list


def extract_context_to_columns(row):
    # Regex patterns for section headers
    context_reasoning_pat = r'### CONTEXT_REASONING\s*(.*?)\s*### CONTEXT_TRIPLES'
    context_triples_pat = r'### CONTEXT_TRIPLES\s*(.*)'

    context_reasoning, context_triples = extract_sections(row['graphs_str'], context_reasoning_pat, context_triples_pat)
    return pd.Series([context_reasoning, context_triples],
                     index=['context_reasoning', 'context_triples'])

In [21]:
graphs_str_df[['context_reasoning', 'context_triples']] = graphs_str_df.apply(extract_context_to_columns, axis=1)
graphs_str_df

,batch_num,question_num,graphs_str,context_reasoning,context_triples
0,0.0,1.0,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted by identifying names o...,"[(radio_city, is, radio_station), (radio_city,..."
1,0.0,2.0,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted based on clear mention...,"[(ritz-carlton_jakarta, is_a, hotel), (ritz-ca..."
2,0.0,3.0,### CONTEXT_REASONING\nEntities are extracted ...,Entities are extracted by identifying unique n...,"[(lisa_simpson, is_fictional_character_in, the..."
3,0.0,4.0,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted from titles and paragr...,"[(moloch_or, this_gentile_world, written_by_he..."
4,0.0,5.0,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted from each title and pa...,"[(cadmium_chloride, is_a, chemical_compound), ..."
5,0.0,6.0,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified as prominent individu...,"[(li_na, born_on, n26_february_1982), (li_na, ..."
6,0.0,7.0,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted by identifying country...,"[(india, official_name, republic_of_india), (i..."
7,0.0,8.0,"### CONTEXT_REASONING\nFirst, I identified uni...","First, I identified unique entities from each ...","[(verano_de_escándalo_1998, held_on, september..."
8,0.0,9.0,### CONTEXT_REASONING\nI identified television...,"I identified television series, people, organi...","[(house_of_anubis, is_a, television_series), (..."
9,0.0,10.0,"### CONTEXT_REASONING\nFirst, I identified maj...","First, I identified major entities: Mount Pano...","[(mount_panorama_circuit, located_in, bathurst..."

In [22]:
main_df = main_df.merge(graphs_str_df, on=['batch_num', 'question_num'], how='left')
# del graphs_str_df
main_df

,batch_num,question_num,context,question,answer,graphs_str,context_reasoning,context_triples
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted by identifying names o...,"[(radio_city, is, radio_station), (radio_city,..."
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted based on clear mention...,"[(ritz-carlton_jakarta, is_a, hotel), (ritz-ca..."
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,### CONTEXT_REASONING\nEntities are extracted ...,Entities are extracted by identifying unique n...,"[(lisa_simpson, is_fictional_character_in, the..."
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted from titles and paragr...,"[(moloch_or, this_gentile_world, written_by_he..."
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted from each title and pa...,"[(cadmium_chloride, is_a, chemical_compound), ..."
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified as prominent individu...,"[(li_na, born_on, n26_february_1982), (li_na, ..."
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted by identifying country...,"[(india, official_name, republic_of_india), (i..."
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari,"### CONTEXT_REASONING\nFirst, I identified uni...","First, I identified unique entities from each ...","[(verano_de_escándalo_1998, held_on, september..."
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006,### CONTEXT_REASONING\nI identified television...,"I identified television series, people, organi...","[(house_of_anubis, is_a, television_series), (..."
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long,"### CONTEXT_REASONING\nFirst, I identified maj...","First, I identified major entities: Mount Pano...","[(mount_panorama_circuit, located_in, bathurst..."

In [23]:
# Loop through each row. Save the context triples as OWL KG files
from rdflib import Graph, Namespace, RDF, RDFS, OWL, URIRef
import os


def save_kg_from_triples(triples, batch_num, question_num):
    g = Graph()
    EX = Namespace("http://example.org/")

    # Add triples to the graph
    for subject, relation, obj in triples:
        subject_uri = URIRef(EX[subject])
        object_uri = URIRef(EX[obj])
        g.add((subject_uri, URIRef(EX[relation]), object_uri))

    # Define the file path
    file_path = f"{KNOWLEDGE_GRAPH_PATH}/{DATASET_NAME}_ontology_b{batch_num}_q{question_num}.rdf"

    # Save the graph in OWL format
    g.serialize(destination=file_path, format='xml')
    print(f"Saved KG for batch {batch_num}, question {question_num} to {file_path}")


for index, row in main_df.iterrows():
    batch_num = row['batch_num']
    question_num = row['question_num']
    context_triples = row['context_triples']

    if context_triples:  # Only save if there are context triples
        save_kg_from_triples(context_triples, batch_num, question_num)

Saved KG for batch 0, question 1 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q1.rdf
Saved KG for batch 0, question 2 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q2.rdf
Saved KG for batch 0, question 3 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q3.rdf
Saved KG for batch 0, question 4 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q4.rdf
Saved KG for batch 0, question 5 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q5.rdf
Saved KG for batch 0, question 6 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q6.rdf
Saved KG for batch 0, question 7 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q7.rdf
Saved KG for batch 0, question 8 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q8.rdf
Saved KG for batch 0, question 9 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q9.rdf
Saved KG for batch 0, question 10 to outputs/knowledge_graphs/hotpotQA_ontology_b0_q10.rdf

## 4. Extracting Entities from Questions

In [24]:
batch_input_list = []

for i in range(0, main_df.shape[0], BATCH_SIZE):
    batch_df = main_df.iloc[i:i + BATCH_SIZE]
    batch_input_item = []

    for i, (index, row) in enumerate(batch_df.iterrows()):
        batch_input_item.append({
            "question": row['question']
        })
    batch_input_list.append(batch_input_item)

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1}:")
    for item in batch:
        print("Question:", item['question'])
        print("-" * 50)

Batch 1:
Question: Which magazine was started first Arthur's Magazine or First for Women?
--------------------------------------------------
Question: The Oberoi family is part of a hotel company that has a head office in what city?
--------------------------------------------------
Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
--------------------------------------------------
Question:  What nationality was James Henry Miller's wife?
--------------------------------------------------
Question: Cadmium Chloride is slightly soluble in this chemical, it is also called what?
--------------------------------------------------
Question: Which tennis player won more Grand Slam titles, Henri Leconte or Jonathan Stark?
--------------------------------------------------
Question: Which genus of moth in the world's seventh-largest country contains only one species?
--------------------------------------------------
Question: Who was once considered the best kick boxer in the world, however he has been involved in a number of controversies relating to his "unsportsmanlike conducts" in the sport and crimes of violence outside of the ring.
--------------------------------------------------
Question: The Dutch-Belgian television series that "House of Anubis" was based on first aired in what year?
--------------------------------------------------
Question: What is the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged?
--------------------------------------------------

In [25]:
system_msg = """
<role>
    You are an expert in natural language understanding and knowledge graph construction. Your task is to convert a provided question into a set of question triples, using simple variable names (such as x, y, z, i, j, k) for unknown entities or values to be inferred.
</role>

<behavior>
    <rule name="Entity Extraction">
        Identify and extract unique entities. Use canonical names.
    </rule>
    <rule name="Relationship Extraction">
        Extract explicit or clear implicit relationships between entities as (subject, relation, object) triples.
    </rule>
    <rule name="Temporal and Comparative Relations">
        Use relations like "started in", "founded by", "wrote a song about", "is named after", etc., matching the logic and semantics in the context or question.
    </rule>
    <rule name="Variable Placeholders for Unknowns">
        For each unknown or answer to be found in the question, use a simple English variable (x, y, z, i, j, k, etc.) in place of the answer within the triples. Each distinct unknown in the question gets a unique variable.
    </rule>
    <rule name="Question Triple Decomposition">
        For each question, decompose it into one or more triples, using variable placeholders for any unknowns to be inferred from the context.
        Examples:
        - "Which magazine was started first Arthur's Magazine or First for Women?"
           (Arthur's Magazine, started in, x)
           (First for Women, started in, y)
        - "The Oberoi family is part of a hotel company that has a head office in what city?"
           (Oberoi family, is part of, x)
           (x, has head office in, y)
    </rule>
    <rule name="Formatting and Output">
        Output must contain four sections, in order:
        1. ### QUESTION_REASONING — a step-by-step reasoning of how the question was decomposed into question triples
        2. ### QUESTIONS_TRIPLES — list the question triples, each on its own line. each on its own line in the format (entity_1, relationship, entity_2)
        Do not add explanations, numbering, or extra text.
    </rule>
</behavior>

<format>
1. Carefully read the <question> section.
2. Before extracting question triples, explain step by step how you break down the question and assign variable placeholders. Print this heading:
   ### QUESTION_REASONING
   Then write your reasoning in clear, concise steps.
3. After reasoning, print the question triples. Print this heading:
   ### QUESTIONS_TRIPLES
   List each question triple on a new line, using variable placeholders (x, y, z, etc.) for unknowns.
4. After the last question triple, end with no extra text or parentheses.
</format>
"""

human_msg = """
<question>
{question}
</question>
"""

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [26]:
chain = prompt | llm_model | StrOutputParser()

In [27]:
question_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    question_str_list = chain.batch(batch)
    question_str_batch.append(question_str_list)

Batch 1 ... processing 10 items

In [28]:
for i, question_str_list in enumerate(question_str_batch):
    print(f"Batch {i + 1} ... processed {len(question_str_list)} items")
    for j, graph_str in enumerate(question_str_list):
        print(f"Item {j + 1}:")
        print(graph_str)
        print("-" * 50)

Batch 1 ... processed 10 items
Item 1:
### QUESTION_REASONING
I identified two entities in the question: "Arthur's Magazine" and "First for Women". The question is asking to compare the starting dates of both magazines to determine which was started first. The unknowns here are the dates each magazine started, so I assign variables to these dates: x for Arthur's Magazine and y for First for Women.

### QUESTIONS_TRIPLES
(Arthur's Magazine, started in, x)
(First for Women, started in, y)
--------------------------------------------------
Item 2:
### QUESTION_REASONING
The question is asking for the city where the head office of a certain hotel company is located. The company in question is one that the Oberoi family is part of. There are two key unknowns: the name of the hotel company (represented by variable x), and the city where its head office is located (represented by variable y). First, we relate the Oberoi family to the hotel company using "is part of". Next, we relate the hotel company to its head office city with "has head office in".

### QUESTIONS_TRIPLES
(Oberoi family, is part of, x)
(x, has head office in, y)
--------------------------------------------------
Item 3:
### QUESTION_REASONING
First, identify the main entities: Allie Goertz (musician and satirist), "The Simpsons" (TV show), Milhouse (character), Matt Groening (creator of "The Simpsons"). The question states that Allie Goertz wrote a song about Milhouse. It also asks who Matt Groening named Milhouse after, making the person Milhouse was named after the unknown to be represented by a variable, x. The decomposition involves: (1) Allie Goertz wrote a song about Milhouse, (2) Milhouse is a character from "The Simpsons," (3) Matt Groening named Milhouse after x.

### QUESTIONS_TRIPLES
(Allie Goertz, wrote a song about, Milhouse)
(Milhouse, is a character of, The Simpsons)
(Matt Groening, named Milhouse after, x)
--------------------------------------------------
Item 4:
### QUESTION_REASONING
The question asks for the nationality of James Henry Miller's wife. The entities involved are "James Henry Miller," his "wife," and her "nationality." The wife is an unknown entity (x), and her nationality is another unknown (y). Therefore, two triples are needed: one linking James Henry Miller to his wife, and another linking the wife to her nationality.

### QUESTIONS_TRIPLES
(James Henry Miller, has wife, x)
(x, has nationality, y)
--------------------------------------------------
Item 5:
### QUESTION_REASONING
First, identify entities: "Cadmium Chloride" and a chemical (unknown, so assign variable x) in which it is slightly soluble. The chemical is referenced by the phrase "this chemical", so it gets the placeholder x. The next clause asks for what "it" (referring to the chemical, i.e., x) is also called—this is another unknown, so use variable y. Relationships are: (Cadmium Chloride, is slightly soluble in, x) and (x, is also called, y).

### QUESTIONS_TRIPLES
(Cadmium Chloride, is slightly soluble in, x)
(x, is also called, y)
--------------------------------------------------
Item 6:
### QUESTION_REASONING
First, identify the two entities being compared: Henri Leconte and Jonathan Stark, both tennis players. The comparison concerns the number of Grand Slam titles won by each. Assign variable x to represent the number of Grand Slam titles won by Henri Leconte, and variable y for the number won by Jonathan Stark. The unknown being asked is which player has the greater number of titles. This requires triples expressing how many Grand Slam titles each won.

### QUESTIONS_TRIPLES
(Henri Leconte, won number of Grand Slam titles, x)
(Jonathan Stark, won number of Grand Slam titles, y)
(x, compared to, y)
--------------------------------------------------
Item 7:
### QUESTION_REASONING
1. The question asks for a genus of moth (unknown, assign variable x).
2. The genus is located in the world's seventh-largest country (unknown, assign variable y).
3. The genus contains only one species, i.e., it is a monotypic genus.
4. The world's seventh-largest country (by area) is implied and should be represented as a variable to be inferred.
5. The relationships required: (genus x, located in, country y), (genus x, contains number of species, 1).

### QUESTIONS_TRIPLES
(x, is a genus of, moth)
(x, located in, y)
(y, is the world's seventh-largest country, true)
(x, contains number of species, 1)
--------------------------------------------------
Item 8:
### QUESTION_REASONING
First, I identify the main subject of the question: a person who was once considered the best kick boxer in the world. This is the unknown entity to be inferred — assign variable x.
Next, the person (x) has a reputation: considered the best in the sport of kick boxing (relation: considered the best in) by some authority or general consensus.
Additionally, x has been involved in controversies relating to "unsportsmanlike conducts" in kick boxing (relation: involved in, object: controversies relating to "unsportsmanlike conducts" in kick boxing).
Furthermore, x has been involved in crimes of violence outside the ring (relation: involved in, object: crimes of violence outside of the ring).
These become the key relationships to explicitly represent as triples.

### QUESTIONS_TRIPLES
(x, was considered the best in, kick boxing)
(x, involved in, controversies relating to "unsportsmanlike conducts" in kick boxing)
(x, involved in, crimes of violence outside of the ring)
--------------------------------------------------
Item 9:
### QUESTION_REASONING
First, identify that "House of Anubis" is based on a Dutch-Belgian television series, which is an unknown entity (assign variable x). The question asks for the year this series (x) first aired, that is, the starting year (assign variable y). Thus, two relationships need to be captured: (1) "House of Anubis" is based on x; (2) x first aired in year y.

### QUESTIONS_TRIPLES
(House of Anubis, is based on, x)
(x, first aired in, y)
--------------------------------------------------
Item 10:
### QUESTION_REASONING
First, identify the main event: "2013 Liqui Moly Bathurst 12 Hour." The question asks for the length of the track where this event was staged. Therefore, the event occurred at a specific track (unknown, assign variable x). The length of that track is also unknown (assign variable y). The relationships are: the event was staged at x, and x has length y.

### QUESTIONS_TRIPLES
(2013 Liqui Moly Bathurst 12 Hour, was staged at, x)
(x, has length, y)
--------------------------------------------------

In [29]:
questions_str_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "questions_str": []
})

for i, graphs_str_list in enumerate(question_str_batch):
    batch_num_list = [i] * len(graphs_str_list)
    question_num_list = list(range(1, len(graphs_str_list) + 1))
    questions_str_df = pd.concat([questions_str_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "questions_str": graphs_str_list
    })], ignore_index=True)

questions_str_df

   batch_num  question_num                                      questions_str
0        0.0           1.0  ### QUESTION_REASONING\nI identified two entit...
1        0.0           2.0  ### QUESTION_REASONING\nThe question is asking...
2        0.0           3.0  ### QUESTION_REASONING\nFirst, identify the ma...
3        0.0           4.0  ### QUESTION_REASONING\nThe question asks for ...
4        0.0           5.0  ### QUESTION_REASONING\nFirst, identify entiti...
5        0.0           6.0  ### QUESTION_REASONING\nFirst, identify the tw...
6        0.0           7.0  ### QUESTION_REASONING\n1. The question asks f...
7        0.0           8.0  ### QUESTION_REASONING\nFirst, I identify the ...
8        0.0           9.0  ### QUESTION_REASONING\nFirst, identify that "...
9        0.0          10.0  ### QUESTION_REASONING\nFirst, identify the ma...

In [30]:
def extract_question_to_columns(row):
    # Regex patterns for section headers
    questions_reasoning_pat = r'### QUESTION_REASONING\s*(.*?)\s*### QUESTIONS_TRIPLES'
    questions_triples_pat = r'### QUESTIONS_TRIPLES\s*(.*)'

    questions_reasoning, questions_triples = extract_sections(row['questions_str'], questions_reasoning_pat,
                                                              questions_triples_pat)
    return pd.Series([questions_reasoning, questions_triples],
                     index=['question_reasoning', 'question_triples'])


questions_str_df[['question_reasoning', 'question_triples']] = questions_str_df.apply(extract_question_to_columns,
                                                                                      axis=1)
questions_str_df

,batch_num,question_num,questions_str,question_reasoning,question_triples
0,0.0,1.0,### QUESTION_REASONING\nI identified two entit...,"I identified two entities in the question: ""Ar...","[(arthurs_magazine, started_in, x), (first_for..."
1,0.0,2.0,### QUESTION_REASONING\nThe question is asking...,The question is asking for the city where the ...,"[(oberoi_family, is_part_of, x), (x, has_head_..."
2,0.0,3.0,"### QUESTION_REASONING\nFirst, identify the ma...","First, identify the main entities: Allie Goert...","[(allie_goertz, wrote_a_song_about, milhouse),..."
3,0.0,4.0,### QUESTION_REASONING\nThe question asks for ...,The question asks for the nationality of James...,"[(james_henry_miller, has_wife, x), (x, has_na..."
4,0.0,5.0,"### QUESTION_REASONING\nFirst, identify entiti...","First, identify entities: ""Cadmium Chloride"" a...","[(cadmium_chloride, is_slightly_soluble_in, x)..."
5,0.0,6.0,"### QUESTION_REASONING\nFirst, identify the tw...","First, identify the two entities being compare...","[(henri_leconte, won_number_of_grand_slam_titl..."
6,0.0,7.0,### QUESTION_REASONING\n1. The question asks f...,1. The question asks for a genus of moth (unkn...,"[(x, is_a_genus_of, moth), (x, located_in, y),..."
7,0.0,8.0,"### QUESTION_REASONING\nFirst, I identify the ...","First, I identify the main subject of the ques...","[(x, was_considered_the_best_in, kick_boxing),..."
8,0.0,9.0,"### QUESTION_REASONING\nFirst, identify that ""...","First, identify that ""House of Anubis"" is base...","[(house_of_anubis, is_based_on, x), (x, first_..."
9,0.0,10.0,"### QUESTION_REASONING\nFirst, identify the ma...","First, identify the main event: ""2013 Liqui Mo...","[(n2013_liqui_moly_bathurst_12_hour, was_stage..."

In [31]:
main_df = main_df.merge(questions_str_df, on=['batch_num', 'question_num'], how='left')
# del graphs_str_df
main_df

,batch_num,question_num,context,question,answer,graphs_str,context_reasoning,context_triples,questions_str,question_reasoning,question_triples
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted by identifying names o...,"[(radio_city, is, radio_station), (radio_city,...",### QUESTION_REASONING\nI identified two entit...,"I identified two entities in the question: ""Ar...","[(arthurs_magazine, started_in, x), (first_for..."
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted based on clear mention...,"[(ritz-carlton_jakarta, is_a, hotel), (ritz-ca...",### QUESTION_REASONING\nThe question is asking...,The question is asking for the city where the ...,"[(oberoi_family, is_part_of, x), (x, has_head_..."
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,### CONTEXT_REASONING\nEntities are extracted ...,Entities are extracted by identifying unique n...,"[(lisa_simpson, is_fictional_character_in, the...","### QUESTION_REASONING\nFirst, identify the ma...","First, identify the main entities: Allie Goert...","[(allie_goertz, wrote_a_song_about, milhouse),..."
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted from titles and paragr...,"[(moloch_or, this_gentile_world, written_by_he...",### QUESTION_REASONING\nThe question asks for ...,The question asks for the nationality of James...,"[(james_henry_miller, has_wife, x), (x, has_na..."
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted from each title and pa...,"[(cadmium_chloride, is_a, chemical_compound), ...","### QUESTION_REASONING\nFirst, identify entiti...","First, identify entities: ""Cadmium Chloride"" a...","[(cadmium_chloride, is_slightly_soluble_in, x)..."
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified as prominent individu...,"[(li_na, born_on, n26_february_1982), (li_na, ...","### QUESTION_REASONING\nFirst, identify the tw...","First, identify the two entities being compare...","[(henri_leconte, won_number_of_grand_slam_titl..."
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted by identifying country...,"[(india, official_name, republic_of_india), (i...",### QUESTION_REASONING\n1. The question asks f...,1. The question asks for a genus of moth (unkn...,"[(x, is_a_genus_of, moth), (x, located_in, y),..."
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari,"### CONTEXT_REASONING\nFirst, I identified uni...","First, I identified unique entities from each ...","[(verano_de_escándalo_1998, held_on, september...","### QUESTION_REASONING\nFirst, I identify the ...","First, I identify the main subject of the ques...","[(x, was_considered_the_best_in, kick_boxing),..."
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006,### CONTEXT_REASONING\nI identified television...,"I identified television series, people, organi...","[(house_of_anubis, is_a, television_series), (...","### QUESTION_REASONING\nFirst, identify that ""...","First, identify that ""House of Anubis"" is base...","[(house_of_anubis, is_based_on, x), (x, first_..."
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long,"### CONTEXT_REASONING\nFirst, I identified maj...","First, I identified major entities: Mount Pano...","[(mount_panorama_circuit, located_in, bathurst...","### QUESTION_REASONING\nFirst, identify the ma...","First, identify the main event: ""2013 Liqui Mo...","[(n2013_liqui_moly_bathurst_12_hour, was_stage..."

## 5. Extracting sub-graphs from KGs

In [32]:
import hashlib
import math
import threading
from queue import Queue
from typing import Iterable, List, Tuple, Set

import psycopg2
from psycopg2.pool import SimpleConnectionPool
from psycopg2 import extensions as _pg_ext
from psycopg2 import sql
from pgvector.psycopg2 import register_vector

from rdflib import Graph, URIRef, BNode, Literal
from langchain_openai import OpenAIEmbeddings

# ------------------------------
# Configuration (DB EXACTLY as provided)
# ------------------------------
db_config = {
    'dbname': 'langchain',
    'user': 'langchain',
    'password': 'langchain',
    'host': 'localhost',
    'port': '6024'
}

# ------------------------------
# Connection pool + helpers
# ------------------------------
_DB_POOL = None
_DB_POOL_LOCK = threading.Lock()


def _get_pool() -> SimpleConnectionPool:
    global _DB_POOL
    if _DB_POOL is None:
        with _DB_POOL_LOCK:
            if _DB_POOL is None:
                _DB_POOL = SimpleConnectionPool(
                    minconn=1,
                    maxconn=16,  # adjust if you increase thread count
                    **db_config
                )
    return _DB_POOL


def _get_conn():
    pool = _get_pool()
    conn = pool.getconn()
    try:
        # Register pgvector adapter once per connection
        register_vector(conn)
    except Exception:
        pass
    _reset_conn(conn)
    return conn


def _put_conn(conn):
    try:
        _reset_conn(conn)  # return clean
    finally:
        _get_pool().putconn(conn)


def _reset_conn(conn):
    """Ensure the connection is not stuck in a failed or open transaction."""
    try:
        if conn.get_transaction_status() != _pg_ext.TRANSACTION_STATUS_IDLE:
            conn.rollback()
    except Exception:
        try:
            conn.rollback()
        except Exception:
            pass


# ------------------------------
# Schema management
# ------------------------------
def ensure_schema(embedding_dim: int = 1536):
    """
    - CREATE EXTENSION on a short-lived autocommit connection
    - CREATE TABLE/INDEXES on a pooled connection in a transaction
    """
    # 1) CREATE EXTENSION on its own connection (autocommit)
    try:
        ext_conn = psycopg2.connect(**db_config)
        ext_conn.autocommit = True
        with ext_conn.cursor() as cur:
            try:
                cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")
            except psycopg2.Error as e:
                print("[ensure_schema] WARNING: CREATE EXTENSION vector failed.")
                print("[ensure_schema] pgerror:\n", getattr(e, "pgerror", str(e)))
                # Not fatal if already installed or if perms are restricted
    finally:
        try:
            ext_conn.close()
        except Exception:
            pass

    # 2) CREATE TABLE / INDEXES via pooled connection
    conn = _get_conn()
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(sql.SQL("""
                    CREATE TABLE IF NOT EXISTS embeddings_cache (
                        id              BIGSERIAL PRIMARY KEY,
                        hash_word       TEXT        NOT NULL,
                        word            TEXT        NOT NULL,
                        word_embedding  vector({dim}) NOT NULL,
                        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
                        updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
                        UNIQUE (hash_word),
                        UNIQUE (word)
                    );
                """).format(dim=sql.Literal(embedding_dim)))

                # Attempt to align dimension (noop if same). May fail if existing data incompatible.
                try:
                    cur.execute(sql.SQL("""
                        ALTER TABLE embeddings_cache
                        ALTER COLUMN word_embedding TYPE vector({dim});
                    """).format(dim=sql.Literal(embedding_dim)))
                except psycopg2.Error as e:
                    print("[ensure_schema] NOTE: Could not alter word_embedding dimension.")
                    print("[ensure_schema] pgerror:\n", getattr(e, "pgerror", str(e)))

                cur.execute("""
                    CREATE INDEX IF NOT EXISTS idx_embeddings_cache_hash_word
                    ON embeddings_cache (hash_word);
                """)
    except psycopg2.Error as e:
        try:
            conn.rollback()
        except Exception:
            pass
        print("[ensure_schema] ERROR: DDL transaction failed and was rolled back.")
        print("[ensure_schema] pgerror:\n", getattr(e, "pgerror", str(e)))
        raise
    finally:
        _put_conn(conn)


# ---------- HASH HELPER ----------
def sha256_hex(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


# ------------------------------
# Cache ops (DB)
# ------------------------------
def fetch_embedding_from_db(word: str):
    """
    Returns list[float] if present, else None.
    """
    h = sha256_hex(word)
    conn = _get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT word_embedding FROM embeddings_cache WHERE hash_word = %s",
                (h,)
            )
            row = cur.fetchone()
            return list(row[0]) if row else None
    finally:
        _put_conn(conn)


def upsert_embedding_in_db(word: str, embedding: List[float]):
    h = sha256_hex(word)
    conn = _get_conn()
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO embeddings_cache (hash_word, word, word_embedding)
                    VALUES (%s, %s, %s)
                    ON CONFLICT (hash_word) DO UPDATE
                    SET word = EXCLUDED.word,
                        word_embedding = EXCLUDED.word_embedding,
                        updated_at = now();
                    """,
                    (h, word, embedding)
                )
    finally:
        _put_conn(conn)

In [33]:
import threading
import numpy as np
from queue import Queue
from langchain_openai import OpenAIEmbeddings
import ast


def short_name(uri):
    s = str(uri)
    if '#' in s:
        return s.split('#')[-1]
    elif '/' in s:
        return s.split('/')[-1]
    return s


# def load_embedding_dict(csv_path):
#     embedding_dict = {}
#     if os.path.exists(csv_path):
#         print(f"Loading existing embeddings from '{csv_path}'...")
#         df = pd.read_csv(csv_path)
#         for _, row in df.iterrows():
#             emb = ast.literal_eval(row["embedding"]) if isinstance(row["embedding"], str) else row["embedding"]
#             embedding_dict[row["string"]] = emb
#     else:
#         print(f"No embedding cache found. Initializing '{csv_path}' as empty.")
#         pd.DataFrame(columns=["string", "embedding"]).to_csv(csv_path, index=False)
#     return embedding_dict

def get_or_create_embedding(word: str, embedder: OpenAIEmbeddings) -> List[float]:
    cached = fetch_embedding_from_db(word)
    if cached is not None:
        return cached
    emb = embedder.embed_query(clean_entity(word))
    upsert_embedding_in_db(word, emb)
    return emb

# def get_embedding(text, embedding_dict, lock, embedder):
#     with lock:
#         if text in embedding_dict:
#             print(f"Embedding for '{text}' found in cache.")
#             return embedding_dict[text]
#     print(f"Requesting embedding for '{text}'...")
#     emb = embedder.embed_query(text)
#     with lock:
#         embedding_dict[text] = emb
#     print(f"Embedding for '{text}' cached.")
#     return emb

def cosine_similarity(vec1, vec2):
    v1 = np.array(vec1)
    v2 = np.array(vec2)
    if np.linalg.norm(v1) == 0 or np.linalg.norm(v2) == 0:
        return 0.0
    return float(np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)))


def bfs_n_hop_triples(graph, start_entity, n):
    visited = set([start_entity])
    current_level = set([start_entity])
    neighborhood_triples = set()
    for hop in range(n):
        next_level = set()
        for node in current_level:
            # Outgoing
            for s, p, o in graph.triples((node, None, None)):
                next_level.add(o)
                neighborhood_triples.add((short_name(s), short_name(p), short_name(o)))
            # Incoming
            for s, p, o in graph.triples((None, None, node)):
                next_level.add(s)
                neighborhood_triples.add((short_name(s), short_name(p), short_name(o)))
        next_level -= visited
        if not next_level:
            break
        visited |= next_level
        current_level = next_level
    return list(neighborhood_triples)


def extract_entities(graph):
    entities = set()
    for s, p, o in graph:
        # s = s.replace('_', ' ')
        # o = o.replace('_', ' ')
        # if s.startswith('n') and s[1].isdigit():
        #     s = s[1:]
        # if o.startswith('n') and o[1].isdigit():
        #     o = o[1:]
        entities.add(s)
        entities.add(o)
    return list(entities)


def clean_entity(entity):
    """
    Cleans the entity string by removing unwanted characters and formatting.
    """
    entity = entity.replace('_', ' ')
    if entity.startswith('n') and entity[1].isdigit():
        entity = entity[1:]
    return entity.strip().lower()


def worker(entity_queue,
           graph,
           key,
           key_embedding,
           per,
           n,
           neighborhoods,
           matched_entities,
           embedder,
           thread_id: int = 0,  # <-- default so it won't crash if omitted
           lock: threading.Lock = None):
    print(f"[Thread {thread_id}] started.")
    while not entity_queue.empty():
        entity = entity_queue.get()
        try:
            # entity_label = short_name(entity)
            entity_label = entity
            # emb = get_embedding(entity_label, embedding_dict, lock, embedder)
            emb = get_or_create_embedding(short_name(entity), embedder)
            sim = cosine_similarity(key_embedding, emb)
            if sim >= per:
                print(f"similarity for '{key}' and '{short_name(entity)}' is {sim:.4f}")
                print(f"Extracting {n}-hop triples for entity '{entity}'")
                triples = bfs_n_hop_triples(graph, entity, n)
                with lock:
                    neighborhoods.extend(triples)
                    matched_entities.append(entity_label)
        except Exception as e:
            print(f"[Thread {thread_id}] Error processing entity {entity}: {e}")
        finally:
            entity_queue.task_done()
    print(f"[Thread {thread_id}] finished.")

# def kg_neighborhood_extractor(
#     rdf_path, per, n, key, k=4, embedding_model="text-embedding-3-small", embedding_csv_path="embedding_dict.csv"
# ):
#     print("Loading RDF graph...")
#     graph = Graph()
#     graph.parse(rdf_path)
#     print("Extracting entities...")
#     entities = extract_entities(graph)
#     print(f"Total entities found: {len(entities)}")
#
#     embedding_dict = load_embedding_dict(embedding_csv_path)
#     neighborhoods = []
#     matched_entities = []
#     lock = threading.Lock()
#
#     print(f"Initializing LangChain OpenAIEmbeddings with model '{embedding_model}'...")
#     embedder = OpenAIEmbeddings(model=embedding_model)
#
#     print(f"Getting embedding for search key: '{key}'")
#     key_embedding = get_embedding(key, embedding_dict, lock, embedder)
#
#     entity_queue = Queue()
#     for entity in entities:
#         entity_queue.put(entity)
#
#     threads = []
#     for i in range(k):
#         t = threading.Thread(
#             target=worker,
#             args=(
#                 entity_queue,
#                 graph,
#                 key_embedding,
#                 per,
#                 n,
#                 embedding_dict,
#                 lock,
#                 neighborhoods,
#                 matched_entities,
#                 embedder,
#                 i+1,
#             ),
#         )
#         t.start()
#         threads.append(t)
#
#     entity_queue.join()
#     for t in threads:
#         t.join()
#
#     # Deduplicate triples
#     neighborhoods = list({triple for triple in neighborhoods})
#
#     # Save embedding_dict to CSV
#     with lock:
#         rows = [
#             {"string": s, "embedding": ",".join(map(str, v))}
#             for s, v in embedding_dict.items()
#         ]
#         df = pd.DataFrame(rows)
#         df.to_csv("embedding_dict.csv", index=False)
#
#     print("\nSummary:")
#     print(f"Matched entities: {matched_entities}")
#     print(f"Total unique triples in neighborhoods: {len(neighborhoods)}")
#     print("Embeddings saved as 'embedding_dict.csv'")
#     return neighborhoods

In [34]:
# ---------- MAIN FUNCTION (DB-backed cache) ----------
def kg_neighborhood_extractor(
        rdf_path,
        per,
        n,
        key,
        k=4,
        embedding_model="text-embedding-3-small",
        embedding_dim=1536  # keep in sync with the model you use
):
    """
    Args:
        rdf_path: path to RDF/XML/Turtle/etc. file supported by rdflib
        per: cosine similarity threshold (0..1) to treat an entity as a match
        n: number of BFS hops for neighborhood expansion
        key: search string to embed & compare with entity labels
        k: number of worker threads
        embedding_model: OpenAI embedding model name (via LangChain)
        embedding_dim: pgvector column dimension; must match the model in use
    """
    print("Ensuring DB schema...")
    ensure_schema(embedding_dim=embedding_dim)

    print("Loading RDF graph...")
    graph = Graph()
    graph.parse(rdf_path)

    print("Extracting entities...")
    entities = extract_entities(graph)
    print(f"Total entities found: {len(entities)}")

    neighborhoods: List[Tuple[str, str, str]] = []
    matched_entities: List[Tuple[str, float]] = []
    lock = threading.Lock()

    print(f"Initializing LangChain OpenAIEmbeddings with model '{embedding_model}'...")
    embedder = OpenAIEmbeddings(model=embedding_model)

    print(f"Getting embedding for search key: '{key}'")
    key_embedding = get_or_create_embedding(key, embedder)

    # Queue up work
    entity_queue = Queue()
    for ent in entities:
        entity_queue.put(ent)

    # Threads
    threads = []
    for i in range(k):
        t = threading.Thread(
            target=worker,
            args=(
                entity_queue,
                graph,
                key,
                key_embedding,
                per,
                n,
                neighborhoods,
                matched_entities,
                embedder,
                i + 1,  # <-- thread_id
                lock,  # <-- lock
            ),
            daemon=True,
        )
        t.start()
        threads.append(t)

    # Wait
    entity_queue.join()
    for t in threads:
        t.join()

    # Deduplicate triples
    neighborhoods = list({tr for tr in neighborhoods})

    # Optional: show cache size
    cached_count = None
    conn = _get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM embeddings_cache;")
            cached_count = cur.fetchone()[0]
    finally:
        _put_conn(conn)

    print("\nSummary:")
    print(f"Matched entities (label, similarity): {matched_entities}")
    print(f"Total unique triples in neighborhoods: {len(neighborhoods)}")
    if cached_count is not None:
        print(f"Embeddings cached in DB: {cached_count}")

    return neighborhoods

In [35]:
# neighborhoods = kg_neighborhood_extractor(
#     rdf_path="outputs/knowledge_graphs/hotpotQA_ontology_b0_q1.rdf",
#     per=0.75, n=2, key="arthurs_magazine", k=3, embedding_model="text-embedding-3-small"
# )
# print("\nNeighborhood triples:")
# for triple in neighborhoods:
#     print(triple)

In [36]:
# loop through each row in main_df and extract neighborhoods
batch_input_list = []

for i in range(0, main_df.shape[0], BATCH_SIZE):
    batch_df = main_df.iloc[i:i + BATCH_SIZE]
    batch_input_item = []

    for i, (index, row) in enumerate(batch_df.iterrows()):
        reference_triples = []
        for triple in row['question_triples']:
            # Extract reference_triples using question_triples
            if len(triple[0]) > 1:
                reference_triples += kg_neighborhood_extractor(
                    rdf_path=f"{KNOWLEDGE_GRAPH_PATH}/{DATASET_NAME}_ontology_b{row['batch_num']}_q{row['question_num']}.rdf",
                    per=0.75, n=3, key=triple[0], k=3, embedding_model="text-embedding-3-small"
                )
            print("-" * 50)
            if len(triple[2]) > 1:
                reference_triples += kg_neighborhood_extractor(
                    rdf_path=f"{KNOWLEDGE_GRAPH_PATH}/{DATASET_NAME}_ontology_b{row['batch_num']}_q{row['question_num']}.rdf",
                    per=0.75, n=3, key=triple[2], k=3, embedding_model="text-embedding-3-small"
                )

        batch_input_item.append({
            "question": row['question'],
            "reference_triples": reference_triples
        })
    print("=" * 50)
    batch_input_list.append(batch_input_item)
    break

Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 145
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'arthurs_magazine'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'arthurs_magazine' and 'arthurs_magazine' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/arthurs_magazine'
[Thread 2] finished.
[Thread 3] finished.
[Thread 1] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/arthurs_magazine')]
Total unique triples in neighborhoods: 9
Embeddings cached in DB: 1331
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 145
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'first_for_women'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'first_for_women' and 'first_for_women' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/first_for_women'
[Thread 3] finished.
[Thread 1] finished.
[Thread 2] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/first_for_women')]
Total unique triples in neighborhoods: 13
Embeddings cached in DB: 1331
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 137
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'oberoi_family'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'oberoi_family' and 'oberoi_family' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/oberoi_family'
[Thread 3] finished.
[Thread 1] finished.
[Thread 2] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/oberoi_family')]
Total unique triples in neighborhoods: 34
Embeddings cached in DB: 1371
--------------------------------------------------
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 129
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'allie_goertz'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'allie_goertz' and 'allie_goertz' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/allie_goertz'
[Thread 2] finished.
[Thread 1] finished.
[Thread 3] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/allie_goertz')]
Total unique triples in neighborhoods: 62
Embeddings cached in DB: 1402
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 129
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'milhouse'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'milhouse' and 'milhouse_van_houten' is 0.8512
Extracting 3-hop triples for entity 'http://example.org/milhouse_van_houten'
[Thread 3] finished.
[Thread 2] finished.
[Thread 1] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/milhouse_van_houten')]
Total unique triples in neighborhoods: 146
Embeddings cached in DB: 1402
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 129
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'milhouse'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'milhouse' and 'milhouse_van_houten' is 0.8512
Extracting 3-hop triples for entity 'http://example.org/milhouse_van_houten'
[Thread 3] finished.
[Thread 1] finished.
[Thread 2] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/milhouse_van_houten')]
Total unique triples in neighborhoods: 146
Embeddings cached in DB: 1402
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 129
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'the_simpsons'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'the_simpsons' and 'simpson_family' is 0.7633
Extracting 3-hop triples for entity 'http://example.org/simpson_family'
similarity for 'the_simpsons' and 'the_simpsons_movie' is 0.7996
Extracting 3-hop triples for entity 'http://example.org/the_simpsons_movie'
similarity for 'the_simpsons' and 'the_simpsons' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/the_simpsons'
similarity for 'the_simpsons' and 'homer_simpson' is 0.7648
Extracting 3-hop triples for entity 'http://example.org/homer_simpson'
similarity for 'the_simpsons' and 'the_simpsons_family' is 0.8122
Extracting 3-hop triples for entity 'http://example.org/the_simpsons_family'
[Thread 2] finished.
[Thread 3] finished.
[Thread 1] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/simpson_family'), rdflib.term.URIRef('http://example.org/the_simpsons_movie'), rdflib.term.URIRef('http://example.org/the_simpsons'), rdflib.term.URIRef('http://example.org/homer_simpson'), rdflib.term.URIRef('http://example.org/the_simpsons_family')]
Total unique triples in neighborhoods: 144
Embeddings cached in DB: 1402
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 129
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'matt_groening'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'matt_groening' and 'homer_groening' is 0.7711
Extracting 3-hop triples for entity 'http://example.org/homer_groening'
similarity for 'matt_groening' and 'matt_groening' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/matt_groening'
similarity for 'matt_groening' and 'matt_groening_as_assistant_editor' is 0.7507
Extracting 3-hop triples for entity 'http://example.org/matt_groening_as_assistant_editor'
[Thread 2] finished.
[Thread 3] finished.
[Thread 1] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/homer_groening'), rdflib.term.URIRef('http://example.org/matt_groening'), rdflib.term.URIRef('http://example.org/matt_groening_as_assistant_editor')]
Total unique triples in neighborhoods: 149
Embeddings cached in DB: 1402
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 85
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'james_henry_miller'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'james_henry_miller' and 'james_henry_miller' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/james_henry_miller'
similarity for 'james_henry_miller' and 'henry_miller' is 0.7638
Extracting 3-hop triples for entity 'http://example.org/henry_miller'
similarity for 'james_henry_miller' and 'birth_name_james_henry_miller' is 0.7976
Extracting 3-hop triples for entity 'http://example.org/birth_name_james_henry_miller'
[Thread 1] finished.
[Thread 2] finished.
[Thread 3] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/james_henry_miller'), rdflib.term.URIRef('http://example.org/henry_miller'), rdflib.term.URIRef('http://example.org/birth_name_james_henry_miller')]
Total unique triples in neighborhoods: 62
Embeddings cached in DB: 1435
--------------------------------------------------
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 122
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'cadmium_chloride'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'cadmium_chloride' and 'cadmium' is 0.8751
Extracting 3-hop triples for entity 'http://example.org/cadmium'
similarity for 'cadmium_chloride' and 'cadmium_chloride' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/cadmium_chloride'
[Thread 1] finished.
[Thread 2] finished.
[Thread 3] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/cadmium'), rdflib.term.URIRef('http://example.org/cadmium_chloride')]
Total unique triples in neighborhoods: 102
Embeddings cached in DB: 1466
--------------------------------------------------
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 128
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'henri_leconte'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'henri_leconte' and 'henri_leconte' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/henri_leconte'
[Thread 1] finished.
[Thread 3] finished.
[Thread 2] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/henri_leconte')]
Total unique triples in neighborhoods: 90
Embeddings cached in DB: 1502
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 128
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'jonathan_stark'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'jonathan_stark' and 'jonathan_stark' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/jonathan_stark'
[Thread 1] finished.
[Thread 2] finished.
[Thread 3] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/jonathan_stark')]
Total unique triples in neighborhoods: 115
Embeddings cached in DB: 1502
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 89
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'moth'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
[Thread 2] finished.
[Thread 3] finished.
[Thread 1] finished.

Summary:
Matched entities (label, similarity): []
Total unique triples in neighborhoods: 0
Embeddings cached in DB: 1515
--------------------------------------------------
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 89
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'true'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
[Thread 3] finished.
[Thread 2] finished.
[Thread 1] finished.

Summary:
Matched entities (label, similarity): []
Total unique triples in neighborhoods: 0
Embeddings cached in DB: 1515
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 89
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'n1'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
[Thread 1] finished.
[Thread 2] finished.
[Thread 3] finished.

Summary:
Matched entities (label, similarity): []
Total unique triples in neighborhoods: 0
Embeddings cached in DB: 1515
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 116
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'kick_boxing'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'kick_boxing' and 'kickboxing' is 0.9122
Extracting 3-hop triples for entity 'http://example.org/kickboxing'
similarity for 'kick_boxing' and 'kick_boxer' is 0.8025
Extracting 3-hop triples for entity 'http://example.org/kick_boxer'
[Thread 3] finished.
[Thread 2] finished.
[Thread 1] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/kickboxing'), rdflib.term.URIRef('http://example.org/kick_boxer')]
Total unique triples in neighborhoods: 49
Embeddings cached in DB: 1565
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 116
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'controversies_relating_to_unsportsmanlike_conducts_in_kick_boxing'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'controversies_relating_to_unsportsmanlike_conducts_in_kick_boxing' and 'controversies_for_unsportsmanlike_conduct' is 0.7500
Extracting 3-hop triples for entity 'http://example.org/controversies_for_unsportsmanlike_conduct'
[Thread 3] finished.
[Thread 1] finished.
[Thread 2] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/controversies_for_unsportsmanlike_conduct')]
Total unique triples in neighborhoods: 23
Embeddings cached in DB: 1566
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 116
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'crimes_of_violence_outside_of_the_ring'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'crimes_of_violence_outside_of_the_ring' and 'crimes_of_violence_outside_ring' is 0.9527
Extracting 3-hop triples for entity 'http://example.org/crimes_of_violence_outside_ring'
[Thread 2] finished.
[Thread 3] finished.
[Thread 1] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/crimes_of_violence_outside_ring')]
Total unique triples in neighborhoods: 23
Embeddings cached in DB: 1567
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 124
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'house_of_anubis'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'house_of_anubis' and 'house_of_anubis' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/house_of_anubis'
similarity for 'house_of_anubis' and 'het_huis_anubis' is 0.7505
Extracting 3-hop triples for entity 'http://example.org/het_huis_anubis'
[Thread 3] finished.
similarity for 'house_of_anubis' and 'list_of_house_of_anubis_episodes' is 0.7729
Extracting 3-hop triples for entity 'http://example.org/list_of_house_of_anubis_episodes'
[Thread 2] finished.
[Thread 1] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/house_of_anubis'), rdflib.term.URIRef('http://example.org/het_huis_anubis'), rdflib.term.URIRef('http://example.org/list_of_house_of_anubis_episodes')]
Total unique triples in neighborhoods: 46
Embeddings cached in DB: 1591
--------------------------------------------------
--------------------------------------------------
Ensuring DB schema...
Loading RDF graph...
Extracting entities...
Total entities found: 75
Initializing LangChain OpenAIEmbeddings with model 'text-embedding-3-small'...
Getting embedding for search key: 'n2013_liqui_moly_bathurst_12_hour'
[Thread 1] started.
[Thread 2] started.
[Thread 3] started.
similarity for 'n2013_liqui_moly_bathurst_12_hour' and 'n2017_liqui_moly_bathurst_12_hour' is 0.9493
Extracting 3-hop triples for entity 'http://example.org/n2017_liqui_moly_bathurst_12_hour'
similarity for 'n2013_liqui_moly_bathurst_12_hour' and 'n2015_liqui_moly_bathurst_12_hour' is 0.9349
Extracting 3-hop triples for entity 'http://example.org/n2015_liqui_moly_bathurst_12_hour'
similarity for 'n2013_liqui_moly_bathurst_12_hour' and 'liqui_moly_bathurst_12_hour' is 0.9097
Extracting 3-hop triples for entity 'http://example.org/liqui_moly_bathurst_12_hour'
similarity for 'n2013_liqui_moly_bathurst_12_hour' and 'n2013_liqui_moly_bathurst_12_hour' is 1.0000
Extracting 3-hop triples for entity 'http://example.org/n2013_liqui_moly_bathurst_12_hour'
similarity for 'n2013_liqui_moly_bathurst_12_hour' and 'n2016_liqui_moly_bathurst_12_hour' is 0.9451
Extracting 3-hop triples for entity 'http://example.org/n2016_liqui_moly_bathurst_12_hour'
similarity for 'n2013_liqui_moly_bathurst_12_hour' and 'first_hour_of_2013_liqui_moly_bathurst_12_hour' is 0.8996
Extracting 3-hop triples for entity 'http://example.org/first_hour_of_2013_liqui_moly_bathurst_12_hour'
similarity for 'n2013_liqui_moly_bathurst_12_hour' and 'n2014_liqui_moly_bathurst_12_hour' is 0.9630
Extracting 3-hop triples for entity 'http://example.org/n2014_liqui_moly_bathurst_12_hour'
similarity for 'n2013_liqui_moly_bathurst_12_hour' and 'n2018_liqui_moly_bathurst_12_hour' is 0.9431
Extracting 3-hop triples for entity 'http://example.org/n2018_liqui_moly_bathurst_12_hour'
[Thread 2] finished.
[Thread 1] finished.
[Thread 3] finished.

Summary:
Matched entities (label, similarity): [rdflib.term.URIRef('http://example.org/n2017_liqui_moly_bathurst_12_hour'), rdflib.term.URIRef('http://example.org/n2015_liqui_moly_bathurst_12_hour'), rdflib.term.URIRef('http://example.org/liqui_moly_bathurst_12_hour'), rdflib.term.URIRef('http://example.org/n2013_liqui_moly_bathurst_12_hour'), rdflib.term.URIRef('http://example.org/n2016_liqui_moly_bathurst_12_hour'), rdflib.term.URIRef('http://example.org/first_hour_of_2013_liqui_moly_bathurst_12_hour'), rdflib.term.URIRef('http://example.org/n2014_liqui_moly_bathurst_12_hour'), rdflib.term.URIRef('http://example.org/n2018_liqui_moly_bathurst_12_hour')]
Total unique triples in neighborhoods: 117
Embeddings cached in DB: 1615
--------------------------------------------------
--------------------------------------------------
==================================================

In [37]:
# convert '_' into ' ' and remove first 'n' if second charactor is an integer of every entity or relationship of reference_triples
def format_reference_triples(reference_triples):
    formatted_triples = []
    for triple in reference_triples:
        subject, relation, obj = triple
        subject = subject.replace('_', ' ')
        relation = relation.replace('_', ' ')
        obj = obj.replace('_', ' ')
        if subject.startswith('n') and subject[1].isdigit():
            subject = subject[1:]
        if obj.startswith('n') and obj[1].isdigit():
            obj = obj[1:]
        formatted_triples.append((subject, relation, obj))
    return formatted_triples


for i, batch in enumerate(batch_input_list):
    print(f"Batch {i} ... processing {len(batch)} items")
    for j, item in enumerate(batch):
        item['reference_triples'] = format_reference_triples(item['reference_triples'])
        print(f"Item {j}:")
        print("Question:", item['question'])
        print("Reference Triples:", item['reference_triples'])
        print("-" * 50)

Batch 0 ... processing 10 items
Item 0:
Question: Which magazine was started first Arthur's Magazine or First for Women?
Reference Triples: [('arthurs magazine', 'published in', 'philadelphia'), ('arthurs magazine', 'is', 'american literary periodical'), ('t.s. arthur', 'editor of', 'arthurs magazine'), ('sarah josepha hale', 'featured in', 'arthurs magazine'), ('arthurs magazine', 'published during', '1844 1846'), ('thomas g. spear', 'featured in', 'arthurs magazine'), ('arthurs magazine', 'merged into', 'godeys ladys book'), ('j.h. ingraham', 'featured in', 'arthurs magazine'), ('edgar a. poe', 'featured in', 'arthurs magazine'), ('first for women', 'published in', 'usa'), ('womens colleges in the southern united states', 'origin', 'started as girls seminaries or academies'), ('womens colleges in the southern united states', 'located in', 'southern united states'), ('first for women', 'based in', 'englewood cliffs new jersey'), ('first for women', 'circulation', '1310696 copies in 2011'), ('womens colleges in the southern united states', 'is', 'undergraduate institutions'), ('womens colleges in the southern united states', 'mostly', 'liberal arts colleges'), ('first for women', 'target audience', 'women'), ('first for women', 'published by', 'bauer media group'), ('first for women', 'started in', '1989'), ('first for women', 'is', 'magazine'), ('womens colleges in the southern united states', 'are', 'bachelors degree-granting institutions'), ('womens colleges in the southern united states', 'student population', 'women')]
--------------------------------------------------
Item 1:
Question: The Oberoi family is part of a hotel company that has a head office in what city?
Reference Triples: [('mohan singh oberoi', 'founder of', 'oberoi hotels  resorts'), ('oberoi hotels  resorts', 'hotels in', 'hungary'), ('hotel company', 'is', 'regiments specialty company'), ('omkara', 'is heir of', 'oberoi family'), ('delhi', 'located in', 'india'), ('shivaay', 'is heir of', 'oberoi family'), ('rudra', 'is a', 'character in ishqbaaaz'), ('kunal jaisingh', 'portrays', 'omkara'), ('hotel company', 'n3rd infantry', 'is the old guard'), ('nakuul mehta', 'portrays', 'shivaay'), ('omkara', 'is a', 'character in ishqbaaaz'), ('oberoi hotels  resorts', 'hotels in', 'india'), ('leenesh mattoo', 'portrays', 'rudra'), ('the oberoi group', 'owns or operates', 'two river cruise ships'), ('the oberoi group', 'is a', 'hotel company'), ('shivaay', 'is a', 'character in ishqbaaaz'), ('the oberoi group', 'presence in', 'six countries'), ('the oberoi group', 'founded in', '1934'), ('annika', 'is a', 'character in ishqbaaaz'), ('oberoi hotels  resorts', 'is a', 'hotel company'), ('oberoi hotels  resorts', 'hotels in', 'egypt'), ('oberoi hotels  resorts', 'hotels in', 'nepal'), ('the oberoi group', 'owns or operates', '30 luxury hotels'), ('the oberoi group', 'operates brands', 'oberoi hotels  resorts'), ('rudra', 'is heir of', 'oberoi family'), ('mohan singh oberoi', 'chairman of', 'oberoi hotels  resorts'), ('oberoi hotels  resorts', 'hotels in', 'sri lanka'), ('oberoi family', 'famous for', 'involvement in hotels'), ('oberoi hotels  resorts', 'has', '35 hotels'), ('oberoi family', 'associated with', 'the oberoi group'), ('the oberoi group', 'operates brands', 'trident hotels'), ('the oberoi group', 'head office in', 'delhi'), ('oberoi hotels  resorts', 'hotels in', 'australia'), ('oberoi family', 'is a', 'indian family')]
--------------------------------------------------
Item 2:
Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?

## 6. Getting the final answer

In [38]:
system_msg = """
<role>
    You are a logical reasoning expert tasked with answering questions based only on provided structured knowledge in the form of Reference Triples.
</role>

<behavior>
    <rule name="Step-by-Step Reasoning">
        Use the reference triples to deduce relevant facts in a step-by-step manner. Clearly identify which triples are used for each inference.
    </rule>
    <rule name="Comparative Reasoning">
        When comparing entities, extract or infer comparable attributes (e.g., start dates, founding years) and use them to conclude which comes first, is larger, etc., as applicable.
    </rule>
    <rule name="Answer Reporting">
        At the end of your reasoning, provide the final answer on a new line prefixed with "### FINAL_ANSWER", followed by the concise answer on the next line.
        If the data is insufficient to answer the question definitively, return "insufficient data".
    </rule>
</behavior>

<format>
1. Carefully examine the <question> and <reference_triples>.
2. Begin with step-by-step reasoning based strictly on the reference triples.
3. End your output with the heading "### FINAL_ANSWER" followed by the answer on the next line.
</format>
"""

human_msg = """
<question>
{question}
</question>

<reference triples>
{reference_triples}
</reference triples>
"""

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [39]:
chain = prompt | llm_model | StrOutputParser()

In [40]:
answer_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    answer_str_list = chain.batch(batch)
    answer_str_batch.append(answer_str_list)

Batch 1 ... processing 10 items

In [41]:
for i, answer_str_list in enumerate(answer_str_batch):
    print(f"Batch {i + 1} ... processed {len(answer_str_list)} items")
    for j, answer_str in enumerate(answer_str_list):
        print(f"Item {j + 1}:")
        print(answer_str)
        print("-" * 50)

# Arthur's Magazine
# Delhi
# President Richard Nixon
# American
# alcohol
# Jonathan Stark
# Crambidae
# Badr Hari
# 2006
# 6.213 km long

Batch 1 ... processed 10 items
Item 1:
Step-by-Step Reasoning:

1. The question asks which magazine was started first: Arthur's Magazine or First for Women.
2. Locate relevant start/publish information for each magazine in the reference triples.

- For "arthurs magazine":
    - Triple: ('arthurs magazine', 'published during', '1844 1846')
      This indicates Arthur's Magazine was active during 1844 to 1846, so it started no later than 1844.
- For "first for women":
    - Triple: ('first for women', 'started in', '1989')
      This indicates First for Women started in 1989.

3. Now, compare the starting years:
    - Arthur's Magazine: 1844
    - First for Women: 1989

4. 1844 comes before 1989.

### FINAL_ANSWER
Arthur's Magazine was started first.
--------------------------------------------------
Item 2:
Step-by-step reasoning:

1. The question asks about the city where the head office is located for the hotel company associated with the Oberoi family.
2. From the triple ('oberoi family', 'associated with', 'the oberoi group'), it is established that The Oberoi Group is the hotel company linked to the Oberoi family.
3. The triple ('the oberoi group', 'is a', 'hotel company') confirms The Oberoi Group is a hotel company.
4. The triple ('the oberoi group', 'head office in', 'delhi') directly states the head office of The Oberoi Group is in Delhi.
5. This matches the requirement of the question regarding the city where the head office of the Oberoi family's hotel company is located.

### FINAL_ANSWER
Delhi
--------------------------------------------------
Item 3:
Step-by-step reasoning:

1. The question asks about the person who Matt Groening named the "The Simpsons" character Milhouse after.

2. The relevant reference triple to this is:
   - ('matt groening', 'named milhouse after', 'richard nixons middle name')

3. Therefore, Matt Groening named the character Milhouse after "Richard Nixon's middle name."

4. To complete the answer, the triple shows the exact statement, and there's no ambiguity or missing link.

### FINAL_ANSWER
Richard Nixon's middle name
--------------------------------------------------
Item 4:
Step-by-step reasoning:

1. The question asks for the nationality of James Henry Miller's wife.
2. From the triples: ('james henry miller', 'stage name', 'ewan maccoll'), we see that James Henry Miller is also known as Ewan MacColl.
3. To determine his wife, we look for relationships involving Ewan MacColl and marriage.
4. There is: ('peggy seeger', 'married to', 'ewan maccoll') and ('peggy seeger', 'was married until ewan maccolls death in', '1989'), so his wife is Peggy Seeger.
5. We need to determine Peggy Seeger's nationality.
6. The following triples reference Peggy Seeger:
    - ('peggy seeger', 'lived in britain for', 'more than 30 years') → This tells us about her residence, but not nationality.
    - ('peggy seeger', 'also well known in', 'britain') → Again, only about notoriety.
    - ('peggy seeger', 'occupation', 'folksinger') → Related to career.
    - ('peggy seeger', 'birth name', 'margaret seeger') → Her original name.
7. None of the triples directly state Peggy Seeger's nationality.

### FINAL_ANSWER
insufficient data
--------------------------------------------------
Item 5:
Step-by-step reasoning:

1. The question asks: "Cadmium Chloride is slightly soluble in this chemical, it is also called what?"
2. Looking for reference triples about the solubility of cadmium chloride:
   - ('cadmium chloride', 'is slightly soluble in', 'alcohol')
   This means the chemical is "alcohol".
3. Now, we need to find what "alcohol" is also called.
   - ('ethanol', 'is also known as', 'ethyl alcohol')
   - ('ethanol', 'is also known as', 'drinking alcohol')
   - ('ethanol', 'is a', 'alcohol')
   Ethanol is a specific type of alcohol, and the question refers generally to "alcohol". Based on the reference triples, "alcohol" refers to "ethanol", which is also known as "ethyl alcohol" and "drinking alcohol".

### FINAL_ANSWER
ethyl alcohol (ethanol)
--------------------------------------------------
Item 6:
Step-by-step reasoning:

1. The question asks which tennis player won more Grand Slam titles: Henri Leconte or Jonathan Stark.

2. We need to identify the number of Grand Slam titles each player won, using the relevant reference triples.

3. For Henri Leconte:
   - ('henri leconte', 'won singles title at', '1986 german open') – The German Open is not a Grand Slam tournament, so this does not count.
   - ('henri leconte', 'reached singles final', '1988 french open') – He reached the final but did not win, so this does not count as a win.
   - ('henri leconte', 'won doubles title', '1984 french open mens doubles') – French Open is a Grand Slam tournament, so Henri Leconte has 1 Grand Slam title (in men’s doubles).

4. For Jonathan Stark:
   - ('jonathan stark', 'won grand slam doubles title', '1994 french open mens doubles') – French Open is a Grand Slam, 1 title (in men’s doubles).
   - ('jonathan stark', 'won grand slam mixed doubles title', '1995 wimbledon championships mixed doubles') – Wimbledon is a Grand Slam, 1 more title (in mixed doubles).
   - In total, Jonathan Stark has 2 Grand Slam titles.

5. Comparative Reasoning:
   - Henri Leconte: 1 Grand Slam title (men's doubles).
   - Jonathan Stark: 2 Grand Slam titles (1 men's doubles, 1 mixed doubles).

6. Conclusion: Jonathan Stark won more Grand Slam titles than Henri Leconte.

### FINAL_ANSWER
Jonathan Stark
--------------------------------------------------
Item 7:
Step-by-step reasoning:

1. The question asks for a genus of moth in the world's seventh-largest country that contains only one species.
2. The world's seventh-largest country by area is India.
3. According to the reference triples, there is no data provided about any genus of moth, their species count, their distributions, or their presence in India.

### FINAL_ANSWER
insufficient data
--------------------------------------------------
Item 8:
Step-by-step reasoning:

1. The question asks for a person who was once considered the best kick boxer in the world, and who has been involved in controversies regarding "unsportsmanlike conducts" and crimes of violence outside of the ring.
2. Let's look for references to "kick boxer," champions, and controversies in the reference triples.
3. The entity 'badr hari' appears multiple times with the following information:
   - ('badr hari', 'profession', 'super heavyweight kickboxer')
   - ('badr hari', 'prominent in', 'kickboxing')
   - ('badr hari', 'former champion of', 'k-1 heavyweight')
   - ('badr hari', 'k-1 heavyweight champion period', '20072008')
   - ('badr hari', 'finalist of', 'k-1 world grand prix 2009')
   - ('badr hari', 'its showtime champion period', '2009-2010')
   - ('badr hari', 'former champion of', 'its showtime heavyweight world champion')
   - ('badr hari', 'involved in', 'controversies for unsportsmanlike conduct')
   - ('badr hari', 'involved in', 'crimes of violence outside ring')

4. Badr Hari is described as a super heavyweight kickboxer, a prominent figure in kickboxing, and a former K-1 heavyweight champion (with championship periods given).
5. Badr Hari is noted as being involved in "controversies for unsportsmanlike conduct" and "crimes of violence outside ring".
6. The attributes match the description in the question: top-level kickboxer (once considered best), and history of controversy and violent crime outside the ring.
7. No other kickboxer in the reference triples is associated with both top championship status and such controversies.
8. The entity "kick boxer" appearing in other triples refers generically or as a nickname, with no detailed controversies or criminal activities attached.

### FINAL_ANSWER
Badr Hari
--------------------------------------------------
Item 9:
Step-by-step reasoning:

1. The question asks: "The Dutch-Belgian television series that 'House of Anubis' was based on first aired in what year?"

2. We need to identify which series "House of Anubis" was based on.
   - Reference triple: ('house of anubis', 'based on', 'het huis anubis')
   - So, "House of Anubis" is based on "het huis anubis".

3. We need to find out when "het huis anubis" first aired.
   - Reference triple: ('het huis anubis', 'first aired in', 'september 2006')

4. So, "het huis anubis" first aired in September 2006.

### FINAL_ANSWER
September 2006
--------------------------------------------------
Item 10:
Step-by-step reasoning:

1. The question asks for the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged.

2. From the reference triples:
   - ('2013 liqui moly bathurst 12 hour', 'held at', 'mount panorama circuit')
   This confirms the 2013 event was held at Mount Panorama Circuit.

3. Next, we need the length of Mount Panorama Circuit. The relevant triple is:
   - ('mount panorama circuit', 'length', '6.213 km')
   This tells us the track's length.

### FINAL_ANSWER
6.213 km
--------------------------------------------------

In [42]:
llm_answer_str_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "llm_answer_str": []
})

for i, answer_str_list in enumerate(answer_str_batch):
    batch_num_list = [i] * len(answer_str_list)
    question_num_list = list(range(1, len(answer_str_list) + 1))
    llm_answer_str_df = pd.concat([llm_answer_str_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "llm_answer_str": answer_str_list
    })], ignore_index=True)

llm_answer_str_df

   batch_num  question_num                                     llm_answer_str
0        0.0           1.0  Step-by-Step Reasoning:\n\n1. The question ask...
1        0.0           2.0  Step-by-step reasoning:\n\n1. The question ask...
2        0.0           3.0  Step-by-step reasoning:\n\n1. The question ask...
3        0.0           4.0  Step-by-step reasoning:\n\n1. The question ask...
4        0.0           5.0  Step-by-step reasoning:\n\n1. The question ask...
5        0.0           6.0  Step-by-step reasoning:\n\n1. The question ask...
6        0.0           7.0  Step-by-step reasoning:\n\n1. The question ask...
7        0.0           8.0  Step-by-step reasoning:\n\n1. The question ask...
8        0.0           9.0  Step-by-step reasoning:\n\n1. The question ask...
9        0.0          10.0  Step-by-step reasoning:\n\n1. The question ask...

In [43]:
# Extract the final answer from the answer_str

def extract_final_answer(row):
    # Regex pattern to find the final answer
    final_answer_pat = r'### FINAL_ANSWER\s*(.*)'
    match = re.search(final_answer_pat, row['llm_answer_str'], re.DOTALL)
    return match.group(1).strip() if match else "No answer found"


llm_answer_str_df['llm_answer'] = llm_answer_str_df.apply(extract_final_answer, axis=1)
llm_answer_str_df

,batch_num,question_num,llm_answer_str,llm_answer
0,0.0,1.0,Step-by-Step Reasoning:\n\n1. The question ask...,Arthur's Magazine was started first.
1,0.0,2.0,Step-by-step reasoning:\n\n1. The question ask...,Delhi
2,0.0,3.0,Step-by-step reasoning:\n\n1. The question ask...,Richard Nixon's middle name
3,0.0,4.0,Step-by-step reasoning:\n\n1. The question ask...,insufficient data
4,0.0,5.0,Step-by-step reasoning:\n\n1. The question ask...,ethyl alcohol (ethanol)
5,0.0,6.0,Step-by-step reasoning:\n\n1. The question ask...,Jonathan Stark
6,0.0,7.0,Step-by-step reasoning:\n\n1. The question ask...,insufficient data
7,0.0,8.0,Step-by-step reasoning:\n\n1. The question ask...,Badr Hari
8,0.0,9.0,Step-by-step reasoning:\n\n1. The question ask...,September 2006
9,0.0,10.0,Step-by-step reasoning:\n\n1. The question ask...,6.213 km

In [44]:
# Merge the llm_answer_str_df with main_df to get the final answers
main_df = main_df.merge(llm_answer_str_df, on=['batch_num', 'question_num'], how='left')
del llm_answer_str_df

In [45]:
main_df[['question', 'batch_num', 'question_num', 'answer', 'llm_answer']]

,question,batch_num,question_num,answer,llm_answer
0,Which magazine was started first Arthur's Maga...,0,1,Arthur's Magazine,Arthur's Magazine was started first.
1,The Oberoi family is part of a hotel company t...,0,2,Delhi,Delhi
2,Musician and satirist Allie Goertz wrote a son...,0,3,President Richard Nixon,Richard Nixon's middle name
3,What nationality was James Henry Miller's wife?,0,4,American,insufficient data
4,Cadmium Chloride is slightly soluble in this c...,0,5,alcohol,ethyl alcohol (ethanol)
5,Which tennis player won more Grand Slam titles...,0,6,Jonathan Stark,Jonathan Stark
6,Which genus of moth in the world's seventh-lar...,0,7,Crambidae,insufficient data
7,Who was once considered the best kick boxer in...,0,8,Badr Hari,Badr Hari
8,"The Dutch-Belgian television series that ""Hous...",0,9,2006,September 2006
9,What is the length of the track where the 2013...,0,10,6.213 km long,6.213 km

## 7. Calculating the accuracy

In [46]:
system_msg = """
<role>
    You are a meticulous LLM answer evaluator. Your task is to determine if the provided llm_answer correctly matches the correct_answer for a given question.
</role>

<behavior>
    <rule name="case-insensitive-match">
        Treat answers as correct even if their case (uppercase/lowercase) does not match, as long as the content matches.
    </rule>
    <rule name="synonyms-acceptable">
        Accept synonyms, short forms, or equivalent factual answers (e.g., "alcohol" and "ethanol") as correct, unless there is a clear difference in meaning or context.
    </rule>
    <rule name="factual-containment">
        Accept answers that contain the correct answer as a substring, or are paraphrased, provided no contradictory information is introduced.
    </rule>
    <rule name="insufficient-data">
        Mark as incorrect if llm_answer indicates "insufficient data" or similar phrases, but a correct factual answer is actually provided in correct_answer.
    </rule>
    <rule name="incorrect-content">
        Mark as incorrect if the llm_answer gives a wrong, contradictory, or irrelevant response compared to correct_answer.
    </rule>
    <rule name="format-neutrality">
        Do not penalize for minor differences in format, such as punctuation or extra explanatory words, as long as the meaning is unchanged.
    </rule>
    <rule name="numerical-tolerance">
        For numerical answers, accept equivalent formats (e.g., "2006" and "September 2006" are correct if both indicate the correct year), but mark as incorrect if the core value is wrong.
    </rule>
</behavior>

<format>
1) Output your reasoning step by step, referencing the question, correct_answer, and llm_answer.
2) Clearly state if the llm_answer matches the correct_answer according to the behavior rules above.
3) End your output with the heading "### FINAL_ANSWER" followed by TRUE if the llm_answer is correct or FALSE if incorrect.
</format>
"""

human_msg = """
<question>
{question}
</question>

<correct_answer>
{correct_answer}
</correct_answer>

<llm_answer>
{llm_answer}
</llm_answer>
"""

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [47]:
chain = prompt | llm_model | StrOutputParser()

In [48]:
# preparing the input for the evaluation chain
batch_input_list = []

for i in range(0, main_df.shape[0], BATCH_SIZE):
    batch_df = main_df.iloc[i:i + BATCH_SIZE]
    batch_input_item = []

    for i, (index, row) in enumerate(batch_df.iterrows()):
        batch_input_item.append({
            "question": row['question'],
            "correct_answer": row['answer'],
            "llm_answer": row['llm_answer']
        })
    batch_input_list.append(batch_input_item)

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1}:")
    for item in batch:
        print("Question:", item['question'])
        print("Correct Answer:", item['correct_answer'])
        print("LLM Answer:", item['llm_answer'])
        print("-" * 50)

Batch 1:
Question: Which magazine was started first Arthur's Magazine or First for Women?
Correct Answer: Arthur's Magazine
LLM Answer: Arthur's Magazine was started first.
--------------------------------------------------
Question: The Oberoi family is part of a hotel company that has a head office in what city?
Correct Answer: Delhi
LLM Answer: Delhi
--------------------------------------------------
Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
Correct Answer: President Richard Nixon
LLM Answer: Richard Nixon's middle name
--------------------------------------------------
Question:  What nationality was James Henry Miller's wife?
Correct Answer: American
LLM Answer: insufficient data
--------------------------------------------------
Question: Cadmium Chloride is slightly soluble in this chemical, it is also called what?
Correct Answer: alcohol
LLM Answer: ethyl alcohol (ethanol)
--------------------------------------------------
Question: Which tennis player won more Grand Slam titles, Henri Leconte or Jonathan Stark?
Correct Answer: Jonathan Stark
LLM Answer: Jonathan Stark
--------------------------------------------------
Question: Which genus of moth in the world's seventh-largest country contains only one species?
Correct Answer: Crambidae
LLM Answer: insufficient data
--------------------------------------------------
Question: Who was once considered the best kick boxer in the world, however he has been involved in a number of controversies relating to his "unsportsmanlike conducts" in the sport and crimes of violence outside of the ring.
Correct Answer: Badr Hari
LLM Answer: Badr Hari
--------------------------------------------------
Question: The Dutch-Belgian television series that "House of Anubis" was based on first aired in what year?
Correct Answer: 2006
LLM Answer: September 2006
--------------------------------------------------
Question: What is the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged?
Correct Answer: 6.213 km long
LLM Answer: 6.213 km
--------------------------------------------------

In [49]:
answer_check_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    answer_check_str_list = chain.batch(batch)
    answer_check_str_batch.append(answer_check_str_list)

Batch 1 ... processing 10 items

In [50]:
for i, answer_check_str_list in enumerate(answer_check_str_batch):
    print(f"Batch {i + 1} ... processed {len(answer_check_str_list)} items")
    for j, answer_check_str in enumerate(answer_check_str_list):
        print(f"Item {j + 1}:")
        print(answer_check_str)
        print("-" * 50)

Batch 1 ... processed 10 items
Item 1:
1) Step-by-step reasoning:
- The question is: Which magazine was started first Arthur's Magazine or First for Women?
- The correct_answer is: Arthur's Magazine
- The llm_answer is: Arthur's Magazine was started first.

- The llm_answer directly answers the question in a clear, affirmative sentence.
- It states that "Arthur's Magazine was started first," which is exactly the information requested and matches the correct_answer.
- According to the rules:
    - case-insensitive-match: Both answers refer to "Arthur's Magazine," case is not an issue.
    - factual-containment: The llm_answer restates the correct fact and does not add contradictory or irrelevant information.
    - format-neutrality: The answer is slightly rephrased but the meaning and content are fully correct.

2) The llm_answer matches the correct_answer according to all provided behavior rules.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 2:
1) Let's evaluate the question, correct_answer, and llm_answer:

- Question: Asks for the city where the Oberoi family's hotel company has its head office.
- correct_answer: "Delhi"
- llm_answer: "Delhi"

2) Step-by-step evaluation against rules:
- The content of correct_answer and llm_answer is identical ("Delhi").
- The answer is case-insensitive, per the rules.
- There is no contradiction, incorrect content, or extraneous information.
- Format is not an issue ("Delhi" is a single word city name).

3) The llm_answer directly matches the correct_answer according to all rules. There is no ambiguity.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 3:
1) Reasoning step by step:
- The question asks who Matt Groening named the "The Simpsons" character Milhouse after.
- The correct_answer is "President Richard Nixon."
- The llm_answer is "Richard Nixon's middle name."
- Let's evaluate according to the rules:
    - The character Milhouse was named after President Richard Nixon, who had the middle name "Milhous." Thus, the name "Milhouse" refers specifically to Nixon's middle name, which aligns with "Richard Nixon's middle name."
    - According to the synonym rule and factual-containment rule, referring to "Richard Nixon's middle name" is a precise part of "President Richard Nixon."
    - There is no contradictory information, the factual connection is maintained.
    - The llm_answer is sufficiently accurate because it clearly references the correct origination of the name as it relates to President Nixon.

2) Does the llm_answer match the correct_answer?
- Yes, because "Richard Nixon's middle name" is an acceptable, even more specific, formulation of "President Richard Nixon," in the context of naming the character Milhouse.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 4:
1) Reasoning step by step:

- The question asks for the nationality of James Henry Miller's wife.
- The correct_answer is "American."
- The llm_answer is "insufficient data."

Behavior rules analysis:
- According to the "insufficient-data" rule: If llm_answer indicates "insufficient data" or similar phrases, but a correct factual answer is actually provided in correct_answer, mark as incorrect.
- In this scenario, a correct answer exists ("American"), but the llm_answer claims there is insufficient data.

2) Conclusion: The llm_answer does not match the correct_answer.

### FINAL_ANSWER
FALSE
--------------------------------------------------
Item 5:
1) Let's analyze the question, which asks about the alternative name for the chemical in which Cadmium Chloride is slightly soluble, and that chemical is also known as what.

2) The correct_answer is "alcohol."

3) The llm_answer given is "ethyl alcohol (ethanol)."

4) According to the behavior rules:
   - "ethanol" and "alcohol" are acceptable synonyms (rule: synonyms-acceptable).
   - "ethyl alcohol" is the standard chemical name for ethanol, which is the main alcohol commonly referred to as "alcohol" in solvents and chemistry.
   - The llm_answer provides both "ethyl alcohol" and its scientific name "ethanol." Both are more specific but directly reference "alcohol."
   - There is no contradictory or irrelevant information and no format error.

5) Therefore, by the rules, the llm_answer is fully correct based on factual containment, synonyms, and format neutrality.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 6:
1) The question asks which tennis player, between Henri Leconte and Jonathan Stark, won more Grand Slam titles.
2) The correct_answer is "Jonathan Stark".
3) The llm_answer is "Jonathan Stark".
4) Both answers are the same, with no difference in case, content, or meaning.
5) There are no issues regarding synonyms, format, or numerical interpretation.
6) According to the behavior rules, the llm_answer exactly matches the correct_answer.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 7:
1) Step-by-step reasoning:
- The question asks: "Which genus of moth in the world's seventh-largest country contains only one species?"
- The correct_answer is "Crambidae." (Note: Crambidae is technically a family, but following the given correct_answer.)
- The llm_answer is "insufficient data."

Behavior Rule Application:
- According to the "insufficient-data" rule, if the llm_answer claims insufficient data but a correct answer is given, the answer must be marked as incorrect.
- There is a clear factual answer supplied by correct_answer ("Crambidae"), but the llm_answer does not attempt the answer and says "insufficient data" instead.

2) Therefore, the llm_answer does not match the correct_answer.

### FINAL_ANSWER
FALSE
--------------------------------------------------
Item 8:
1) Reasoning:
- The question asks for the name of a kick boxer once considered the best in the world, who is also known for controversies related to unsportsmanlike conduct and violent crimes outside the ring.
- The correct_answer provided is "Badr Hari".
- The llm_answer is also "Badr Hari".
- The answers match exactly, both in terms of the name and spelling. There are no case issues, synonym/short form issues, or any extraneous or contradictory information.
- All behavior rules are satisfied: case-insensitive match, factual containment, and format neutrality.

2) Conclusion:
- The llm_answer matches the correct_answer according to all listed rules.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 9:
1) Reasoning step-by-step:
- The question asks for the year when the Dutch-Belgian television series that "House of Anubis" was based on first aired.
- The correct_answer provided is "2006".
- The llm_answer is "September 2006".
- Rule "numerical-tolerance" states that for numerical answers, equivalent formats (such as "2006" and "September 2006") are accepted if both indicate the correct year.
- Both the correct_answer and llm_answer reference the same year (2006), with the llm_answer giving extra, but still correct, detail by specifying the month.

2) The llm_answer matches the correct_answer according to the rules—specifically the numerical-tolerance and factual-containment rules.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 10:
1) Reasoning step by step:
- The question asks for the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged.
- The correct_answer is "6.213 km long."
- The llm_answer is "6.213 km."
- According to the rules:
  - "case-insensitive-match" applies, but there is no case issue here.
  - "format-neutrality" allows for minor differences, such as omitting "long."
  - The numerical value ("6.213 km") matches exactly in both the correct_answer and llm_answer.
  - No contradictory or additional information is present in the llm_answer.

2) The llm_answer matches the correct_answer according to the behavior rules above.

### FINAL_ANSWER
TRUE
--------------------------------------------------

In [51]:
# Create a DataFrame to store the evaluation results
answer_check_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "answer_check_str": []
})

for i, answer_check_str_list in enumerate(answer_check_str_batch):
    batch_num_list = [i] * len(answer_check_str_list)
    question_num_list = list(range(1, len(answer_check_str_list) + 1))
    answer_check_df = pd.concat([answer_check_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "answer_check_str": answer_check_str_list
    })], ignore_index=True)

In [52]:
answer_check_df

   batch_num  question_num                                   answer_check_str
0        0.0           1.0  1) Step-by-step reasoning:\n- The question is:...
1        0.0           2.0  1) Let's evaluate the question, correct_answer...
2        0.0           3.0  1) Reasoning step by step:\n- The question ask...
3        0.0           4.0  1) Reasoning step by step:\n\n- The question a...
4        0.0           5.0  1) Let's analyze the question, which asks abou...
5        0.0           6.0  1) The question asks which tennis player, betw...
6        0.0           7.0  1) Step-by-step reasoning:\n- The question ask...
7        0.0           8.0  1) Reasoning:\n- The question asks for the nam...
8        0.0           9.0  1) Reasoning step-by-step:\n- The question ask...
9        0.0          10.0  1) Reasoning step by step:\n- The question ask...

In [53]:
# Extract is_correct from the answer_check_str
def extract_is_correct(row):
    # Regex pattern to find the final answer
    final_answer_pat = r'### FINAL_ANSWER\s*(TRUE|FALSE)'
    match = re.search(final_answer_pat, row['answer_check_str'], re.DOTALL)
    return match.group(1).strip() if match else False


# Merge the llm_answer_str_df with main_df to get the final answers
answer_check_df['is_correct'] = answer_check_df.apply(extract_is_correct, axis=1)
main_df = main_df.merge(answer_check_df, on=['batch_num', 'question_num'], how='left')
main_df

,batch_num,question_num,context,question,answer,graphs_str,context_reasoning,context_triples,questions_str,question_reasoning,question_triples,llm_answer_str,llm_answer,answer_check_str,is_correct
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted by identifying names o...,"[(radio_city, is, radio_station), (radio_city,...",### QUESTION_REASONING\nI identified two entit...,"I identified two entities in the question: ""Ar...","[(arthurs_magazine, started_in, x), (first_for...",Step-by-Step Reasoning:\n\n1. The question ask...,Arthur's Magazine was started first.,1) Step-by-step reasoning:\n- The question is:...,TRUE
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted based on clear mention...,"[(ritz-carlton_jakarta, is_a, hotel), (ritz-ca...",### QUESTION_REASONING\nThe question is asking...,The question is asking for the city where the ...,"[(oberoi_family, is_part_of, x), (x, has_head_...",Step-by-step reasoning:\n\n1. The question ask...,Delhi,"1) Let's evaluate the question, correct_answer...",TRUE
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,### CONTEXT_REASONING\nEntities are extracted ...,Entities are extracted by identifying unique n...,"[(lisa_simpson, is_fictional_character_in, the...","### QUESTION_REASONING\nFirst, identify the ma...","First, identify the main entities: Allie Goert...","[(allie_goertz, wrote_a_song_about, milhouse),...",Step-by-step reasoning:\n\n1. The question ask...,Richard Nixon's middle name,1) Reasoning step by step:\n- The question ask...,TRUE
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted from titles and paragr...,"[(moloch_or, this_gentile_world, written_by_he...",### QUESTION_REASONING\nThe question asks for ...,The question asks for the nationality of James...,"[(james_henry_miller, has_wife, x), (x, has_na...",Step-by-step reasoning:\n\n1. The question ask...,insufficient data,1) Reasoning step by step:\n\n- The question a...,FALSE
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted from each title and pa...,"[(cadmium_chloride, is_a, chemical_compound), ...","### QUESTION_REASONING\nFirst, identify entiti...","First, identify entities: ""Cadmium Chloride"" a...","[(cadmium_chloride, is_slightly_soluble_in, x)...",Step-by-step reasoning:\n\n1. The question ask...,ethyl alcohol (ethanol),"1) Let's analyze the question, which asks abou...",TRUE
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark,### CONTEXT_REASONING\nEntities were identifie...,Entities were identified as prominent individu...,"[(li_na, born_on, n26_february_1982), (li_na, ...","### QUESTION_REASONING\nFirst, identify the tw...","First, identify the two entities being compare...","[(henri_leconte, won_number_of_grand_slam_titl...",Step-by-step reasoning:\n\n1. The question ask...,Jonathan Stark,"1) The question asks which tennis player, betw...",TRUE
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae,### CONTEXT_REASONING\nEntities were extracted...,Entities were extracted by identifying country...,"[(india, official_name, republic_of_india), (i...",### QUESTION_REASONING\n1. The question asks f...,1. The question asks for a genus of moth (unkn...,"[(x, is_a_genus_of, moth), (x, located_in, y),...",Step-by-step reasoning:\n\n1. The question ask...,insufficient data,1) Step-by-step reasoning:\n- The question ask...,FALSE
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari,"### CONTEXT_REASONING\nFirst, I identified uni...","First, I identified unique entities from each ...","[(verano_de_escándalo_1998, held_on, september...","### QUESTION_REASONING\nFirst, I identify the ...","First, I identify the main subject of the ques...","[(x, was_considered_the_best_in, kick_boxing),...",Step-by-step reasoning:\n\n1. The question ask...,Badr Hari,1) Reasoning:\n- The question asks for the nam...,TRUE
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006,### CONTEXT_REASONING\nI identified television...,"I identified television series, people, organi...","[(house_of_anubis, is_a, television_series), (...","### QUESTION_REASONING\nFirst, identify that ""...","First, identify that ""House of Anubis"" is base...","[(house_of_anubis, is_based_on, x), (x, first_...",Step-by-step reasoning:\n\n1. The question ask...,September 2006,1) Reasoning step-by-step:\n- The question ask...,TRUE
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long,"### CONTEXT_REASONING\nFirst, I identified maj...","First, I identified major entities: Mount Pano...","[(mount_panorama_circuit, located_in, bathurst...","### QUESTION_REASONING\nFirst, identify the ma...","First, identify the main event: ""2013 Liqui Mo...","[(n2013_liqui_moly_bathurst_12_hour, was_stage...",Step-by-step reasoning:\n\n1. The question ask...,6.213 km,1) Reasoning step by step:\n- The question ask...,TRUE

In [54]:
# Calculate the accuracy
accuracy = main_df['is_correct'].value_counts(normalize=True).get('TRUE', 0) * 100
print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 80.00%

In [55]:
main_df.to_csv("outputs/hotpotqa_complex_entity_prediction_results.csv", index=False)

In [56]:
# GPT 4.1 - Accuracy: 80.00%
# GPT 4.1-mini - Accuracy: 80.00%