In [1]:
import pandas as pd
import json

In [2]:
three_file_path = r"C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\bbh\logical_deduction\logical_deduction_three_objects.json"
five_file_path = r"C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\bbh\logical_deduction\logical_deduction_five_objects.json"
seven_file_path = r"C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\bbh\logical_deduction\logical_deduction_seven_objects.json"

In [3]:
with open(three_file_path, 'r', encoding='utf-8') as f:
    three_data = json.load(f)

with open(five_file_path, 'r', encoding='utf-8') as f:
    five_data = json.load(f)

with open(seven_file_path, 'r', encoding='utf-8') as f:
    seven_data = json.load(f)

# for key, value in three_data.items():
#     print(key)

In [4]:
print(len(three_data['examples']))
print(len(five_data['examples']))
print(len(seven_data['examples']))

250
250
250

In [5]:
for i in range(len(three_data['examples'])):
    print(three_data['examples'][i]['input'])
    if i == 10:
        break

The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are three birds: a blue jay, a quail, and a falcon. The falcon is to the right of the blue jay. The blue jay is to the right of the quail.
Options:
(A) The blue jay is the second from the left
(B) The quail is the second from the left
(C) The falcon is the second from the left
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a motorcyle, a limousine, and a convertible. The motorcyle is newer than the limousine. The convertible is newer than the motorcyle.
Options:
(A) The motorcyle is the oldest
(B) The limousine is the oldest
(C) The convertible is the oldest
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a blue book, an orange book, and a red book. The blue book is the rightmost. The orange book is the leftmost.
Options:
(A) The blue book is the second from the left
(B) The orange book is the second from the left
(C) The red book is the second from the left
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are three birds: a robin, a blue jay, and a crow. The robin is to the right of the crow. The robin is to the left of the blue jay.
Options:
(A) The robin is the rightmost
(B) The blue jay is the rightmost
(C) The crow is the rightmost
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a green book, a red book, and a blue book. The red book is the rightmost. The blue book is to the right of the green book.
Options:
(A) The green book is the rightmost
(B) The red book is the rightmost
(C) The blue book is the rightmost
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: apples, peaches, and mangoes. The mangoes are less expensive than the peaches. The apples are less expensive than the mangoes.
Options:
(A) The apples are the second-most expensive
(B) The peaches are the second-most expensive
(C) The mangoes are the second-most expensive
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a tractor, a truck, and a minivan. The minivan is newer than the truck. The tractor is older than the truck.
Options:
(A) The tractor is the newest
(B) The truck is the newest
(C) The minivan is the newest
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were three golfers: Eve, Rob, and Mel. Rob finished below Mel. Mel finished below Eve.
Options:
(A) Eve finished first
(B) Rob finished first
(C) Mel finished first
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: an orange book, a yellow book, and a blue book. The blue book is to the right of the yellow book. The orange book is the second from the left.
Options:
(A) The orange book is the second from the left
(B) The yellow book is the second from the left
(C) The blue book is the second from the left
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a station wagon, a minivan, and a truck. The minivan is newer than the truck. The station wagon is newer than the minivan.
Options:
(A) The station wagon is the newest
(B) The minivan is the newest
(C) The truck is the newest
The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a gray book, a purple book, and a red book. The purple book is to the left of the red book. The gray book is to the left of the purple book.
Options:
(A) The gray book is the leftmost
(B) The purple book is the leftmost
(C) The red book is the leftmost

In [6]:
for i in range(len(seven_data['examples'])):
    print(seven_data['examples'][i]['input'])
    if i == 10:
        break

The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were seven golfers: Ana, Eve, Ada, Dan, Rob, Amy, and Joe. Dan finished third. Ana finished above Ada. Amy finished last. Dan finished below Rob. Eve finished below Ada. Rob finished below Joe.
Options:
(A) Ana finished third
(B) Eve finished third
(C) Ada finished third
(D) Dan finished third
(E) Rob finished third
(F) Amy finished third
(G) Joe finished third
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are seven vehicles: a bus, a motorcyle, a hatchback, a station wagon, a minivan, a truck, and a limousine. The station wagon is the fourth-newest. The motorcyle is newer than the truck. The station wagon is older than the hatchback. The minivan is newer than the hatchback. The bus is newer than the minivan. The truck is newer than the limousine.
Options:
(A) The bus is the third-oldest
(B) The motorcyle is the third-oldest
(C) The hatchback is the third-oldest
(D) The station wagon is the third-oldest
(E) The minivan is the third-oldest
(F) The truck is the third-oldest
(G) The limousine is the third-oldest
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are seven birds: a hummingbird, a cardinal, a blue jay, an owl, a raven, a quail, and a robin. The hummingbird is to the left of the quail. The robin is to the left of the cardinal. The blue jay is the leftmost. The cardinal is the fourth from the left. The raven is the third from the right. The owl is the third from the left.
Options:
(A) The hummingbird is the second from the right
(B) The cardinal is the second from the right
(C) The blue jay is the second from the right
(D) The owl is the second from the right
(E) The raven is the second from the right
(F) The quail is the second from the right
(G) The robin is the second from the right
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are seven birds: a robin, an owl, a quail, a falcon, a hummingbird, a cardinal, and a crow. The hummingbird is to the left of the falcon. The crow is to the right of the cardinal. The cardinal is the second from the right. The quail is the third from the right. The falcon is to the left of the robin. The owl is the second from the left.
Options:
(A) The robin is the fourth from the left
(B) The owl is the fourth from the left
(C) The quail is the fourth from the left
(D) The falcon is the fourth from the left
(E) The hummingbird is the fourth from the left
(F) The cardinal is the fourth from the left
(G) The crow is the fourth from the left
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells seven fruits: kiwis, plums, mangoes, watermelons, pears, peaches, and oranges. The pears are the third-cheapest. The kiwis are the second-most expensive. The pears are more expensive than the plums. The oranges are less expensive than the kiwis. The mangoes are the third-most expensive. The peaches are the second-cheapest.
Options:
(A) The kiwis are the second-cheapest
(B) The plums are the second-cheapest
(C) The mangoes are the second-cheapest
(D) The watermelons are the second-cheapest
(E) The pears are the second-cheapest
(F) The peaches are the second-cheapest
(G) The oranges are the second-cheapest
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were seven golfers: Eli, Eve, Mel, Joe, Mya, Rob, and Ada. Ada finished above Mya. Eli finished below Joe. Eli finished above Eve. Ada finished second-to-last. Mel finished third. Rob finished fourth.
Options:
(A) Eli finished third-to-last
(B) Eve finished third-to-last
(C) Mel finished third-to-last
(D) Joe finished third-to-last
(E) Mya finished third-to-last
(F) Rob finished third-to-last
(G) Ada finished third-to-last
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were seven golfers: Amy, Eve, Ada, Rob, Dan, Mel, and Joe. Joe finished third. Dan finished last. Eve finished first. Mel finished below Rob. Ada finished above Joe. Rob finished third-to-last.
Options:
(A) Amy finished last
(B) Eve finished last
(C) Ada finished last
(D) Rob finished last
(E) Dan finished last
(F) Mel finished last
(G) Joe finished last
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells seven fruits: oranges, loquats, apples, kiwis, mangoes, plums, and peaches. The apples are the second-cheapest. The peaches are the cheapest. The plums are the fourth-most expensive. The loquats are the third-cheapest. The kiwis are more expensive than the mangoes. The oranges are less expensive than the mangoes.
Options:
(A) The oranges are the third-cheapest
(B) The loquats are the third-cheapest
(C) The apples are the third-cheapest
(D) The kiwis are the third-cheapest
(E) The mangoes are the third-cheapest
(F) The plums are the third-cheapest
(G) The peaches are the third-cheapest
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are seven vehicles: a limousine, a truck, a minivan, a tractor, a hatchback, a bus, and a convertible. The convertible is the second-oldest. The tractor is the fourth-newest. The minivan is older than the truck. The truck is older than the limousine. The hatchback is the third-oldest. The bus is newer than the limousine.
Options:
(A) The limousine is the oldest
(B) The truck is the oldest
(C) The minivan is the oldest
(D) The tractor is the oldest
(E) The hatchback is the oldest
(F) The bus is the oldest
(G) The convertible is the oldest
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are seven books: a brown book, a yellow book, a black book, a white book, a green book, an orange book, and a purple book. The purple book is the rightmost. The yellow book is the leftmost. The orange book is the second from the right. The brown book is to the left of the green book. The brown book is to the right of the black book. The white book is the fourth from the left.
Options:
(A) The brown book is the leftmost
(B) The yellow book is the leftmost
(C) The black book is the leftmost
(D) The white book is the leftmost
(E) The green book is the leftmost
(F) The orange book is the leftmost
(G) The purple book is the leftmost
The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells seven fruits: mangoes, watermelons, peaches, kiwis, oranges, cantaloupes, and plums. The watermelons are the cheapest. The peaches are more expensive than the mangoes. The cantaloupes are the second-most expensive. The oranges are more expensive than the cantaloupes. The peaches are less expensive than the plums. The kiwis are the third-cheapest.
Options:
(A) The mangoes are the third-most expensive
(B) The watermelons are the third-most expensive
(C) The peaches are the third-most expensive
(D) The kiwis are the third-most expensive
(E) The oranges are the third-most expensive
(F) The cantaloupes are the third-most expensive
(G) The plums are the third-most expensive

In [7]:
for i in range(len(five_data['examples'])):
    print(five_data['examples'][i]['input'])
    if i == 10:
        break

The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are five birds: a quail, an owl, a raven, a falcon, and a robin. The owl is the leftmost. The robin is to the left of the raven. The quail is the rightmost. The raven is the third from the left.
Options:
(A) The quail is the rightmost
(B) The owl is the rightmost
(C) The raven is the rightmost
(D) The falcon is the rightmost
(E) The robin is the rightmost
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are five vehicles: a hatchback, a bus, a convertible, a tractor, and a minivan. The tractor is older than the bus. The minivan is newer than the bus. The hatchback is the second-newest. The minivan is older than the convertible.
Options:
(A) The hatchback is the second-oldest
(B) The bus is the second-oldest
(C) The convertible is the second-oldest
(D) The tractor is the second-oldest
(E) The minivan is the second-oldest
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are five books: a yellow book, a green book, a gray book, a blue book, and an orange book. The gray book is to the left of the green book. The gray book is the second from the right. The yellow book is to the right of the orange book. The blue book is the second from the left.
Options:
(A) The yellow book is the leftmost
(B) The green book is the leftmost
(C) The gray book is the leftmost
(D) The blue book is the leftmost
(E) The orange book is the leftmost
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are five birds: a raven, an owl, a cardinal, a hummingbird, and a robin. The cardinal is the rightmost. The raven is to the left of the owl. The robin is to the right of the hummingbird. The hummingbird is the third from the left.
Options:
(A) The raven is the second from the left
(B) The owl is the second from the left
(C) The cardinal is the second from the left
(D) The hummingbird is the second from the left
(E) The robin is the second from the left
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are five books: a green book, an orange book, a gray book, a yellow book, and a purple book. The green book is the rightmost. The gray book is to the right of the orange book. The purple book is to the left of the yellow book. The purple book is to the right of the gray book.
Options:
(A) The green book is the second from the right
(B) The orange book is the second from the right
(C) The gray book is the second from the right
(D) The yellow book is the second from the right
(E) The purple book is the second from the right
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are five books: a white book, a green book, a brown book, a gray book, and an orange book. The gray book is to the right of the orange book. The green book is the second from the right. The brown book is to the right of the white book. The brown book is to the left of the orange book.
Options:
(A) The white book is the third from the left
(B) The green book is the third from the left
(C) The brown book is the third from the left
(D) The gray book is the third from the left
(E) The orange book is the third from the left
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are five vehicles: a convertible, a bus, a minivan, a truck, and a sedan. The convertible is newer than the truck. The minivan is the newest. The bus is the third-newest. The truck is newer than the sedan.
Options:
(A) The convertible is the newest
(B) The bus is the newest
(C) The minivan is the newest
(D) The truck is the newest
(E) The sedan is the newest
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were five golfers: Rob, Ada, Dan, Joe, and Mel. Ada finished above Mel. Mel finished above Dan. Joe finished below Dan. Ada finished second.
Options:
(A) Rob finished last
(B) Ada finished last
(C) Dan finished last
(D) Joe finished last
(E) Mel finished last
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are five books: a white book, a green book, a brown book, a gray book, and an orange book. The gray book is to the right of the orange book. The green book is the second from the right. The brown book is to the right of the white book. The brown book is to the left of the orange book.
Options:
(A) The white book is the rightmost
(B) The green book is the rightmost
(C) The brown book is the rightmost
(D) The gray book is the rightmost
(E) The orange book is the rightmost
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are five vehicles: a convertible, a sedan, a tractor, a minivan, and a limousine. The tractor is newer than the minivan. The tractor is older than the limousine. The convertible is older than the sedan. The convertible is the second-newest.
Options:
(A) The convertible is the second-oldest
(B) The sedan is the second-oldest
(C) The tractor is the second-oldest
(D) The minivan is the second-oldest
(E) The limousine is the second-oldest
The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells five fruits: kiwis, pears, peaches, loquats, and apples. The loquats are more expensive than the kiwis. The pears are more expensive than the peaches. The apples are more expensive than the loquats. The apples are less expensive than the peaches.
Options:
(A) The kiwis are the second-cheapest
(B) The pears are the second-cheapest
(C) The peaches are the second-cheapest
(D) The loquats are the second-cheapest
(E) The apples are the second-cheapest

In [8]:
questions = []
options = []
targets = []

sample_num_questions = 250  # Limit to first 5 items from each dataset

i = 0
for item in three_data['examples']:
    input_text = item['input']
    q, o = input_text.split("Options:\n", 1)
    questions.append(q.strip())
    options.append(o.strip())
    targets.append(item['target'].strip())
    if i == sample_num_questions-1:  # Limit to first 5 items
        break
    i += 1

i = 0
for item in five_data['examples']:
    input_text = item['input']
    q, o = input_text.split("Options:\n", 1)
    questions.append(q.strip())
    options.append(o.strip())
    targets.append(item['target'].strip())
    if i == sample_num_questions-1:  # Limit to first 5 items
        break
    i += 1

i = 0
for item in seven_data['examples']:
    input_text = item['input']
    q, o = input_text.split("Options:\n", 1)
    questions.append(q.strip())
    options.append(o.strip())
    targets.append(item['target'].strip())
    if i == sample_num_questions-1:  # Limit to first 5 items
        break
    i += 1

for i in range(len(questions)):
    print(f"Question {i + 1}: {questions[i]}")
    print(f"Options {i + 1}: {options[i]}")
    print(f"Target {i + 1}: {targets[i]}")
    print("-" * 40)

Question 1: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are three birds: a blue jay, a quail, and a falcon. The falcon is to the right of the blue jay. The blue jay is to the right of the quail.
Options 1: (A) The blue jay is the second from the left
(B) The quail is the second from the left
(C) The falcon is the second from the left
Target 1: (A)
----------------------------------------
Question 2: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a motorcyle, a limousine, and a convertible. The motorcyle is newer than the limousine. The convertible is newer than the motorcyle.
Options 2: (A) The motorcyle is the oldest
(B) The limousine is the oldest
(C) The convertible is the oldest
Target 2: (B)
----------------------------------------
Question 3: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a blue book, an orange book, and a red book. The blue book is the rightmost. The orange book is the leftmost.
Options 3: (A) The blue book is the second from the left
(B) The orange book is the second from the left
(C) The red book is the second from the left
Target 3: (C)
----------------------------------------
Question 4: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are three birds: a robin, a blue jay, and a crow. The robin is to the right of the crow. The robin is to the left of the blue jay.
Options 4: (A) The robin is the rightmost
(B) The blue jay is the rightmost
(C) The crow is the rightmost
Target 4: (B)
----------------------------------------
Question 5: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a green book, a red book, and a blue book. The red book is the rightmost. The blue book is to the right of the green book.
Options 5: (A) The green book is the rightmost
(B) The red book is the rightmost
(C) The blue book is the rightmost
Target 5: (B)
----------------------------------------
Question 6: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: apples, peaches, and mangoes. The mangoes are less expensive than the peaches. The apples are less expensive than the mangoes.
Options 6: (A) The apples are the second-most expensive
(B) The peaches are the second-most expensive
(C) The mangoes are the second-most expensive
Target 6: (C)
----------------------------------------
Question 7: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a tractor, a truck, and a minivan. The minivan is newer than the truck. The tractor is older than the truck.
Options 7: (A) The tractor is the newest
(B) The truck is the newest
(C) The minivan is the newest
Target 7: (C)
----------------------------------------
Question 8: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were three golfers: Eve, Rob, and Mel. Rob finished below Mel. Mel finished below Eve.
Options 8: (A) Eve finished first
(B) Rob finished first
(C) Mel finished first
Target 8: (A)
----------------------------------------
Question 9: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: an orange book, a yellow book, and a blue book. The blue book is to the right of the yellow book. The orange book is the second from the left.
Options 9: (A) The orange book is the second from the left
(B) The yellow book is the second from the left
(C) The blue book is the second from the left
Target 9: (A)
----------------------------------------
Question 10: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a station wagon, a minivan, and a truck. The minivan is newer than the truck. The station wagon is newer than the minivan.
Options 10: (A) The station wagon is the newest
(B) The minivan is the newest
(C) The truck is the newest
Target 10: (A)
----------------------------------------
Question 11: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a gray book, a purple book, and a red book. The purple book is to the left of the red book. The gray book is to the left of the purple book.
Options 11: (A) The gray book is the leftmost
(B) The purple book is the leftmost
(C) The red book is the leftmost
Target 11: (A)
----------------------------------------
Question 12: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: peaches, mangoes, and apples. The peaches are more expensive than the apples. The mangoes are the cheapest.
Options 12: (A) The peaches are the second-most expensive
(B) The mangoes are the second-most expensive
(C) The apples are the second-most expensive
Target 12: (C)
----------------------------------------
Question 13: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are three birds: a blue jay, a falcon, and a hummingbird. The blue jay is to the right of the falcon. The hummingbird is to the left of the falcon.
Options 13: (A) The blue jay is the second from the left
(B) The falcon is the second from the left
(C) The hummingbird is the second from the left
Target 13: (B)
----------------------------------------
Question 14: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a minivan, a bus, and a sedan. The minivan is newer than the sedan. The minivan is older than the bus.
Options 14: (A) The minivan is the second-newest
(B) The bus is the second-newest
(C) The sedan is the second-newest
Target 14: (A)
----------------------------------------
Question 15: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a hatchback, a convertible, and a tractor. The convertible is older than the tractor. The hatchback is the second-newest.
Options 15: (A) The hatchback is the second-newest
(B) The convertible is the second-newest
(C) The tractor is the second-newest
Target 15: (A)
----------------------------------------
Question 16: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: loquats, watermelons, and cantaloupes. The watermelons are the second-most expensive. The loquats are more expensive than the cantaloupes.
Options 16: (A) The loquats are the most expensive
(B) The watermelons are the most expensive
(C) The cantaloupes are the most expensive
Target 16: (A)
----------------------------------------
Question 17: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: mangoes, watermelons, and kiwis. The watermelons are less expensive than the kiwis. The kiwis are the second-most expensive.
Options 17: (A) The mangoes are the most expensive
(B) The watermelons are the most expensive
(C) The kiwis are the most expensive
Target 17: (A)
----------------------------------------
Question 18: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a blue book, an orange book, and a red book. The blue book is the rightmost. The orange book is the leftmost.
Options 18: (A) The blue book is the rightmost
(B) The orange book is the rightmost
(C) The red book is the rightmost
Target 18: (A)
----------------------------------------
Question 19: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were three golfers: Ada, Mel, and Mya. Mya finished below Ada. Mel finished above Ada.
Options 19: (A) Ada finished last
(B) Mel finished last
(C) Mya finished last
Target 19: (C)
----------------------------------------
Question 20: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were three golfers: Mel, Ada, and Ana. Mel finished last. Ana finished second.
Options 20: (A) Mel finished last
(B) Ada finished last
(C) Ana finished last
Target 20: (A)
----------------------------------------
Question 21: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: plums, apples, and loquats. The loquats are the cheapest. The plums are less expensive than the apples.
Options 21: (A) The plums are the cheapest
(B) The apples are the cheapest
(C) The loquats are the cheapest
Target 21: (C)
----------------------------------------
Question 22: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a black book, an orange book, and a blue book. The blue book is to the right of the orange book. The orange book is to the right of the black book.
Options 22: (A) The black book is the second from the left
(B) The orange book is the second from the left
(C) The blue book is the second from the left
Target 22: (B)
----------------------------------------
Question 23: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a convertible, a motorcyle, and a truck. The motorcyle is newer than the convertible. The convertible is newer than the truck.
Options 23: (A) The convertible is the oldest
(B) The motorcyle is the oldest
(C) The truck is the oldest
Target 23: (C)
----------------------------------------
Question 24: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: apples, peaches, and mangoes. The mangoes are less expensive than the peaches. The apples are less expensive than the mangoes.
Options 24: (A) The apples are the cheapest
(B) The peaches are the cheapest
(C) The mangoes are the cheapest
Target 24: (A)
----------------------------------------
Question 25: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were three golfers: Eve, Joe, and Amy. Eve finished below Amy. Eve finished above Joe.
Options 25: (A) Eve finished first
(B) Joe finished first
(C) Amy finished first
Target 25: (C)
----------------------------------------
Question 26: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were three golfers: Eli, Mya, and Eve. Eve finished below Eli. Eve finished above Mya.
Options 26: (A) Eli finished second
(B) Mya finished second
(C) Eve finished second
Target 26: (C)
----------------------------------------
Question 27: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: peaches, pears, and mangoes. The mangoes are less expensive than the peaches. The mangoes are more expensive than the pears.
Options 27: (A) The peaches are the most expensive
(B) The pears are the most expensive
(C) The mangoes are the most expensive
Target 27: (A)
----------------------------------------
Question 28: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a hatchback, a convertible, and a tractor. The convertible is older than the tractor. The hatchback is the second-newest.
Options 28: (A) The hatchback is the oldest
(B) The convertible is the oldest
(C) The tractor is the oldest
Target 28: (B)
----------------------------------------
Question 29: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are three birds: a hummingbird, a blue jay, and a raven. The blue jay is to the right of the hummingbird. The raven is the second from the left.
Options 29: (A) The hummingbird is the rightmost
(B) The blue jay is the rightmost
(C) The raven is the rightmost
Target 29: (B)
----------------------------------------
Question 30: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a purple book, a red book, and a yellow book. The purple book is to the right of the yellow book. The yellow book is to the right of the red book.
Options 30: (A) The purple book is the rightmost
(B) The red book is the rightmost
(C) The yellow book is the rightmost
Target 30: (A)
----------------------------------------
Question 31: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: watermelons, apples, and mangoes. The apples are less expensive than the mangoes. The mangoes are less expensive than the watermelons.
Options 31: (A) The watermelons are the second-most expensive
(B) The apples are the second-most expensive
(C) The mangoes are the second-most expensive
Target 31: (C)
----------------------------------------
Question 32: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In a golf tournament, there were three golfers: Amy, Dan, and Mel. Mel finished above Amy. Dan finished below Amy.
Options 32: (A) Amy finished first
(B) Dan finished first
(C) Mel finished first
Target 32: (C)
----------------------------------------
Question 33: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a motorcyle, a bus, and a tractor. The motorcyle is the oldest. The bus is newer than the tractor.
Options 33: (A) The motorcyle is the second-newest
(B) The bus is the second-newest
(C) The tractor is the second-newest
Target 33: (C)
----------------------------------------
Question 34: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a red book, a blue book, and an orange book. The red book is to the left of the orange book. The orange book is the second from the left.
Options 34: (A) The red book is the second from the left
(B) The blue book is the second from the left
(C) The orange book is the second from the left
Target 34: (C)
----------------------------------------
Question 35: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a motorcyle, a minivan, and a tractor. The minivan is older than the tractor. The minivan is the second-newest.
Options 35: (A) The motorcyle is the newest
(B) The minivan is the newest
(C) The tractor is the newest
Target 35: (C)
----------------------------------------
Question 36: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. In an antique car show, there are three vehicles: a bus, a sedan, and a truck. The truck is older than the bus. The bus is older than the sedan.
Options 36: (A) The bus is the second-newest
(B) The sedan is the second-newest
(C) The truck is the second-newest
Target 36: (A)
----------------------------------------
Question 37: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. A fruit stand sells three fruits: loquats, mangoes, and apples. The mangoes are more expensive than the apples. The loquats are more expensive than the mangoes.
Options 37: (A) The loquats are the most expensive
(B) The mangoes are the most expensive
(C) The apples are the most expensive
Target 37: (A)
----------------------------------------
Question 38: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are three birds: a blue jay, a quail, and a falcon. The falcon is to the right of the blue jay. The blue jay is to the right of the quail.
Options 38: (A) The blue jay is the rightmost
(B) The quail is the rightmost
(C) The falcon is the rightmost
Target 38: (C)
----------------------------------------
Question 39: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a branch, there are three birds: a hawk, a crow, and a raven. The raven is to the right of the hawk. The crow is the rightmost.
Options 39: (A) The hawk is the second from the left
(B) The crow is the second from the left
(C) The raven is the second from the left
Target 39: (C)
----------------------------------------
Question 40: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph. On a shelf, there are three books: a brown book, a yellow book, and an orange book. The yellow book is the leftmost. The orange book is to the right of the brown book.
Options 40: (A) The brown book is the leftmost
(B) The yellow book is the leftmost
(C) The orange book is the leftmost
Target 40: (B)
----------------------------------------

In [9]:
from dotenv import load_dotenv
import os

load_dotenv()
openai_api_key = os.getenv("OPENAI_API_KEY")

In [10]:
from langchain_openai import ChatOpenAI
from langchain_core.globals import set_debug, set_verbose, set_llm_cache
from langchain_community.cache import InMemoryCache
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

set_debug(False)
set_verbose(False)
set_llm_cache(InMemoryCache())

llm_model = ChatOpenAI(model="gpt-4o", api_key=openai_api_key)

In [11]:
relationships = ["has_position_number", "precedes", "follows"]

system_msg = """
<role>
  You are an expert in natural-language understanding and information extraction.
  Your job is to read a user-provided statement that describes the order of a set of items
  (people, vehicles, birds, fruits, etc.) and convert every directly stated fact
  into relationship triples drawn from this fixed vocabulary:
  "has_position_number", "precedes", "follows".
</role>

<behavior>

  <rule name="List-items">
    Before extracting any relationships, identify and list all of the distinct items, people, vehicles, or entities whose order is being described in the user statement.
    Output their names exactly as they appear in the text (case-insensitive, no quotes or articles), replacing internal spaces with a single underscore.
    List them in the order they appear in the source text, separated by commas, with no extra spaces.
  </rule>

  <rule name="Select-quality">
    Carefully read the user-provided statement and identify the single quality or dimension being used to order the items (e.g., "left to right", "oldest to newest", "cheapest to most expensive", "highest to lowest rank", etc.). You must select and state this quality before any reasoning or extraction.
  </rule>

  <rule name="Absolute-position">
    If a sentence gives an explicit ordinal position (e.g. “third”, “leftmost”, “last”, “second-most expensive”):
      • Determine the correct position number for the entity based on BOTH the ordinal word and the total number of items in the list.
      • For a quality worded "cheapest to most expensive" (where 1 is "cheapest" and N is "most expensive" for N items):
          - "second-most expensive" means position N-1.
          - "third-most expensive" means position N-2, and so on.
          - "k-th most expensive" means position (N + 1 - k).
          - "k-th cheapest" means position k.
      • Always calculate and assign the correct position number based on this logic.
      • Emit (Entity, has_position_number, k) using the computed value.
  </rule>

  <rule name="Relative-order">
    For every comparative statement indicating order between two entities (such as “A is more expensive than B”, “A is newer than B”, “A is to the left of B”):

    1. Identify the ordering direction selected (e.g., "newest to oldest").
    2. Based on this direction, determine which end of the ordering is considered position 1.
       • For example:
         - "cheapest to most expensive" → position 1 is cheapest
         - "newest to oldest" → position 1 is newest
         - "left to right" → position 1 is leftmost
    3. Then, for any comparison (e.g., "A is newer than B"):
       • Determine which entity should come first (closer to position 1).
       • Emit both:
         (FirstEntity, precedes, SecondEntity)
         (SecondEntity, follows, FirstEntity)
    4. Use the semantics of the comparison AND the selected quality to decide the correct direction.

    Examples:
      - If the quality is "newest to oldest", then "A is newer than B" → A precedes B.
      - If the quality is "oldest to newest", then "A is newer than B" → B precedes A.
      - If the quality is "most expensive to cheapest", then "A is more expensive than B" → A precedes B.
      - If the quality is "left to right", then "A is to the right of B" → A follows B.

    Always emit both triples for each comparison.
  </rule>

  <rule name="Entity-spelling">
    Preserve the surface form of each entity exactly as it appears in the text (case-insensitive, no quotes or articles). Replace internal spaces with a single underscore.
  </rule>

  <rule name="No-inference">
    Record only facts stated explicitly. Do not infer unstated positions or transitive relations.
  </rule>

  <rule name="No-duplicates">
    Output each triple at most once.
  </rule>

</behavior>

<format>
  1. First, print exactly this heading on its own line (no extra spaces or text):
     ### LIST_TO_ORDER
  2. On the next line, print a single, comma-separated list of all the items/entities being ordered, with no extra spaces.
  3. Then, print exactly this heading on its own line (no extra spaces or text):
     ### LEFT_TO_RIGHT_ORDER_QUALITY
  4. On the next line, print only the ordering quality you identified (e.g. "left to right", "oldest to newest", "cheapest to most expensive", etc.).
  5. Then, print exactly this heading on its own line (no extra spaces or text):
     ### STEP_BY_STEP_REASONING
  6. Then, write out your step-by-step reasoning, explaining how each triple was derived, based on the selected ordering quality.
  7. After the reasoning, print exactly this heading on its own line (no extra spaces or text):
     ### TRIPLES_START
  8. Immediately after the heading, output one triple per line in this form:
     (Subject, relation, Object)
     with a single space after each comma.
  9. Use integers for has_position_number triples; use other entity names for follows/precedes triples.
 10. List triples in the order the corresponding facts appear in the paragraph.
 11. Do not add blank lines, commentary, or any text after the final triple.
</format>
"""

human_msg = "{statement}"

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [12]:
chain = prompt | llm_model | StrOutputParser()

In [13]:
list_questions = []

for i in range(len(questions)):
    question = questions[i]
    list_questions.append({
        "statement": question
    })

In [14]:
graphs_str_list = chain.batch(list_questions)

In [15]:
from pydantic import BaseModel, Field
from typing import List
import re


class GraphEntry(BaseModel):
    """A single relationship in the knowledge graph"""
    entity_1: str = Field(description="First entity in the relationship.")
    entity_2: str = Field(description="Second entity in the relationship.")
    edge: str = Field(description="The relationship between entity_1 and entity_2.")


class EntityEntry(BaseModel):
    """A single entity in the knowledge graph"""
    entity: str = Field(description="The entity.")
    classes: List[str] = Field(description="Classes of the entity.")


class KnowledgeGraph(BaseModel):
    """Graph representation of the statement and the question asked by the user"""

    graph: List[GraphEntry] = Field(
        description="Graph representation of the statement. "
                    "Each entry should define a relationship with 'entity_1', 'entity_2', and 'edge'."
    )


def sanitize_entity_name(name: str) -> str:
    """
    Sanitize entity names to make them valid for URIs.

    Args:
        name: The entity name to sanitize

    Returns:
        Sanitized entity name
    """
    # Replace apostrophes with empty string
    name = name.replace("'s", "s")
    name = name.replace("'", "")

    # Replace spaces with underscores
    name = name.replace(" ", "_")

    # Remove any other problematic characters
    name = re.sub(r'[^\w\-_]', '', name)

    return name


def extract_triples_from_llm_str_output(text: str) -> KnowledgeGraph:
    # 1) Split off everything before "### TRIPLES_START"
    if "### TRIPLES_START" in text:
        _, triples_part = text.split("### TRIPLES_START", 1)
    else:
        # fallback: run on entire text
        triples_part = text

    # 2) Only run the regex on triples_part
    # triple_pattern = r'^\(\s*([A-Za-z]+)\s*,\s*([a-z_]+)\s*,\s*([A-Za-z]+)\s*\)$'
    triple_pattern = r'^\(\s*([\w]+)\s*,\s*([\w]+)\s*,\s*([\w]+)\s*\)$'
    graph_entries = []
    for line in triples_part.splitlines():
        line = line.strip()
        m = re.match(triple_pattern, line)
        if not m:
            continue
        e1, rel, e2 = m.groups()
        graph_entries.append(
            GraphEntry(
                entity_1=sanitize_entity_name(e1),
                entity_2=sanitize_entity_name(e2),
                edge=sanitize_entity_name(rel)
            )
        )

    return KnowledgeGraph(graph=graph_entries)

In [16]:
kg_list = []

for i in range(len(graphs_str_list)):
    graph_str = graphs_str_list[i]
    kg = extract_triples_from_llm_str_output(graph_str)
    kg_list.append(kg)

In [17]:
# Print the first all knowledge graphs
for i, kg in enumerate(kg_list):
    print(f"Knowledge Graph {i + 1}:")
    for entry in kg.graph:
        print(f"({entry.entity_1}, {entry.edge}, {entry.entity_2})")
    print("-" * 40)

Knowledge Graph 1:
(blue_jay, precedes, falcon)
(falcon, follows, blue_jay)
(quail, precedes, blue_jay)
(blue_jay, follows, quail)
----------------------------------------
Knowledge Graph 2:
(motorcyle, precedes, limousine)
(limousine, follows, motorcyle)
(convertible, precedes, motorcyle)
(motorcyle, follows, convertible)
----------------------------------------
Knowledge Graph 3:
(blue_book, has_position_number, 3)
(orange_book, has_position_number, 1)
----------------------------------------
Knowledge Graph 4:
(crow, precedes, robin)
(robin, follows, crow)
(robin, precedes, blue_jay)
(blue_jay, follows, robin)
----------------------------------------
Knowledge Graph 5:
(red_book, has_position_number, 3)
(green_book, precedes, blue_book)
(blue_book, follows, green_book)
----------------------------------------
Knowledge Graph 6:
(mangoes, precedes, peaches)
(peaches, follows, mangoes)
(apples, precedes, mangoes)
(mangoes, follows, apples)
----------------------------------------
Knowledge Graph 7:
(minivan, precedes, truck)
(truck, follows, minivan)
(truck, precedes, tractor)
(tractor, follows, truck)
----------------------------------------
Knowledge Graph 8:
(Mel, precedes, Rob)
(Rob, follows, Mel)
(Eve, precedes, Mel)
(Mel, follows, Eve)
----------------------------------------
Knowledge Graph 9:
(yellow_book, precedes, blue_book)
(blue_book, follows, yellow_book)
(orange_book, has_position_number, 2)
----------------------------------------
Knowledge Graph 10:
(minivan, precedes, truck)
(truck, follows, minivan)
(station_wagon, precedes, minivan)
(minivan, follows, station_wagon)
----------------------------------------
Knowledge Graph 11:
(purple_book, precedes, red_book)
(red_book, follows, purple_book)
(gray_book, precedes, purple_book)
(purple_book, follows, gray_book)
----------------------------------------
Knowledge Graph 12:
(mangoes, has_position_number, 1)
(apples, precedes, peaches)
(peaches, follows, apples)
----------------------------------------
Knowledge Graph 13:
(falcon, precedes, blue_jay)
(blue_jay, follows, falcon)
(hummingbird, precedes, falcon)
(falcon, follows, hummingbird)
----------------------------------------
Knowledge Graph 14:
(minivan, precedes, sedan)
(sedan, follows, minivan)
(bus, precedes, minivan)
(minivan, follows, bus)
----------------------------------------
Knowledge Graph 15:
(convertible, precedes, tractor)
(tractor, follows, convertible)
(hatchback, has_position_number, 2)
----------------------------------------
Knowledge Graph 16:
(watermelons, has_position_number, 2)
(loquats, follows, cantaloupes)
(cantaloupes, precedes, loquats)
----------------------------------------
Knowledge Graph 17:
(watermelons, precedes, kiwis)
(kiwis, follows, watermelons)
(kiwis, has_position_number, 2)
----------------------------------------
Knowledge Graph 18:
(blue_book, has_position_number, 3)
(orange_book, has_position_number, 1)
(orange_book, precedes, red_book)
(red_book, follows, orange_book)
(red_book, precedes, blue_book)
(blue_book, follows, red_book)
----------------------------------------
Knowledge Graph 19:
(Ada, precedes, Mya)
(Mya, follows, Ada)
(Mel, precedes, Ada)
(Ada, follows, Mel)
----------------------------------------
Knowledge Graph 20:
(Mel, has_position_number, 3)
(Ana, has_position_number, 2)
----------------------------------------
Knowledge Graph 21:
(loquats, has_position_number, 1)
(plums, precedes, apples)
(apples, follows, plums)
----------------------------------------
Knowledge Graph 22:
(orange_book, precedes, blue_book)
(blue_book, follows, orange_book)
(black_book, precedes, orange_book)
(orange_book, follows, black_book)
----------------------------------------
Knowledge Graph 23:
(motorcyle, precedes, convertible)
(convertible, follows, motorcyle)
(convertible, precedes, truck)
(truck, follows, convertible)
----------------------------------------
Knowledge Graph 24:
(mangoes, precedes, peaches)
(peaches, follows, mangoes)
(apples, precedes, mangoes)
(mangoes, follows, apples)
----------------------------------------
Knowledge Graph 25:
(Amy, precedes, Eve)
(Eve, follows, Amy)
(Eve, precedes, Joe)
(Joe, follows, Eve)
----------------------------------------
Knowledge Graph 26:
(Eli, precedes, Eve)
(Eve, follows, Eli)
(Eve, precedes, Mya)
(Mya, follows, Eve)
----------------------------------------
Knowledge Graph 27:
(mangoes, precedes, peaches)
(peaches, follows, mangoes)
(pears, precedes, mangoes)
(mangoes, follows, pears)
----------------------------------------
Knowledge Graph 28:
(convertible, precedes, tractor)
(tractor, follows, convertible)
(hatchback, has_position_number, 2)
----------------------------------------
Knowledge Graph 29:
(hummingbird, precedes, blue_jay)
(blue_jay, follows, hummingbird)
(raven, has_position_number, 2)
----------------------------------------
Knowledge Graph 30:
(yellow_book, precedes, purple_book)
(purple_book, follows, yellow_book)
(red_book, precedes, yellow_book)
(yellow_book, follows, red_book)
----------------------------------------
Knowledge Graph 31:
(apples, precedes, mangoes)
(mangoes, follows, apples)
(mangoes, precedes, watermelons)
(watermelons, follows, mangoes)
----------------------------------------
Knowledge Graph 32:
(Mel, precedes, Amy)
(Amy, follows, Mel)
(Amy, precedes, Dan)
(Dan, follows, Amy)
----------------------------------------
Knowledge Graph 33:
(motorcyle, has_position_number, 1)
(bus, precedes, tractor)
(tractor, follows, bus)
----------------------------------------
Knowledge Graph 34:
(red_book, precedes, orange_book)
(orange_book, follows, red_book)
(orange_book, has_position_number, 2)
----------------------------------------
Knowledge Graph 35:
(minivan, precedes, tractor)
(tractor, follows, minivan)
(minivan, has_position_number, 2)
----------------------------------------
Knowledge Graph 36:
(truck, precedes, bus)
(bus, follows, truck)
(bus, precedes, sedan)
(sedan, follows, bus)
----------------------------------------
Knowledge Graph 37:
(apples, precedes, mangoes)
(mangoes, follows, apples)
(mangoes, precedes, loquats)
(loquats, follows, mangoes)
----------------------------------------
Knowledge Graph 38:
(blue_jay, precedes, falcon)
(falcon, follows, blue_jay)
(quail, precedes, blue_jay)
(blue_jay, follows, quail)
----------------------------------------
Knowledge Graph 39:
(hawk, precedes, raven)
(raven, follows, hawk)
(crow, has_position_number, 3)
----------------------------------------
Knowledge Graph 40:
(yellow_book, has_position_number, 1)
(brown_book, precedes, orange_book)
(orange_book, follows, brown_book)
----------------------------------------
Knowledge Graph 41:
(mangoes, precedes, apples)
(apples, follows, mangoes)
(loquats, precedes, mangoes)
(mangoes, follows, loquats)
----------------------------------------
Knowledge Graph 42:
(oranges, has_position_number, 3)
(cantaloupes, precedes, oranges)
(watermelons, precedes, cantaloupes)
(cantaloupes, follows, watermelons)
(cantaloupes, follows, watermelons)
----------------------------------------
Knowledge Graph 43:
(loquats, precedes, apples)
(apples, follows, loquats)
(apples, precedes, peaches)
(peaches, follows, apples)
----------------------------------------
Knowledge Graph 44:
(owl, has_position_number, 2)
(crow, precedes, owl)
(owl, follows, crow)
(cardinal, follows, owl)
(owl, precedes, cardinal)
(crow, has_position_number, 1)
(cardinal, has_position_number, 3)
----------------------------------------
Knowledge Graph 45:
(oranges, precedes, plums)
(plums, follows, oranges)
(plums, precedes, mangoes)
(mangoes, follows, plums)
----------------------------------------
Knowledge Graph 46:
(quail, precedes, owl)
(owl, follows, quail)
(owl, precedes, hummingbird)
(hummingbird, follows, owl)
----------------------------------------
Knowledge Graph 47:
(oranges, has_position_number, 2)
(watermelons, precedes, pears)
(pears, follows, watermelons)
----------------------------------------
Knowledge Graph 48:
(Ada, precedes, Ana)
(Ana, follows, Ada)
(Ana, precedes, Mel)
(Mel, follows, Ana)
----------------------------------------
Knowledge Graph 49:
(sedan, precedes, tractor)
(tractor, follows, sedan)
(bus, precedes, sedan)
(sedan, follows, bus)
----------------------------------------
Knowledge Graph 50:
(brown_book, precedes, orange_book)
(orange_book, follows, brown_book)
(green_book, precedes, brown_book)
(brown_book, follows, green_book)
----------------------------------------
Knowledge Graph 51:
(orange_book, precedes, blue_book)
(blue_book, follows, orange_book)
(blue_book, precedes, yellow_book)
(yellow_book, follows, blue_book)
----------------------------------------
Knowledge Graph 52:
(plums, precedes, mangoes)
(mangoes, follows, plums)
(oranges, precedes, plums)
(plums, follows, oranges)
----------------------------------------
Knowledge Graph 53:
(purple_book, precedes, red_book)
(red_book, follows, purple_book)
(gray_book, precedes, purple_book)
(purple_book, follows, gray_book)
----------------------------------------
Knowledge Graph 54:
(minivan, has_position_number, 2)
(minivan, precedes, tractor)
(tractor, follows, minivan)
----------------------------------------
Knowledge Graph 55:
(quail, precedes, cardinal)
(cardinal, follows, quail)
(blue_jay, precedes, quail)
(quail, follows, blue_jay)
----------------------------------------
Knowledge Graph 56:
(Eve, precedes, Amy)
(Amy, follows, Eve)
(Amy, precedes, Eli)
(Eli, follows, Amy)
----------------------------------------
Knowledge Graph 57:
(Eve, precedes, Dan)
(Dan, follows, Eve)
(Dan, precedes, Joe)
(Joe, follows, Dan)
----------------------------------------
Knowledge Graph 58:
(blue_jay, precedes, falcon)
(falcon, follows, blue_jay)
(quail, precedes, blue_jay)
(blue_jay, follows, quail)
----------------------------------------
Knowledge Graph 59:
(apples, precedes, mangoes)
(mangoes, follows, apples)
(mangoes, precedes, watermelons)
(watermelons, follows, mangoes)
----------------------------------------
Knowledge Graph 60:
(motorcyle, has_position_number, 1)
(bus, precedes, tractor)
(tractor, follows, bus)
----------------------------------------
Knowledge Graph 61:
(minivan, has_position_number, 2)
(minivan, precedes, tractor)
(tractor, follows, minivan)
----------------------------------------
Knowledge Graph 62:
(loquats, has_position_number, 1)
(plums, precedes, apples)
(apples, follows, plums)
----------------------------------------
Knowledge Graph 63:
(orange_book, has_position_number, 1)
(brown_book, precedes, gray_book)
(gray_book, follows, brown_book)
----------------------------------------
Knowledge Graph 64:
(pears, precedes, plums)
(plums, follows, pears)
(kiwis, precedes, pears)
(pears, follows, kiwis)
----------------------------------------
Knowledge Graph 65:
(convertible, precedes, hatchback)
(hatchback, follows, convertible)
(tractor, has_position_number, 1)
----------------------------------------
Knowledge Graph 66:
(tractor, has_position_number, 2)
(minivan, precedes, convertible)
(convertible, follows, minivan)
----------------------------------------
Knowledge Graph 67:
(station_wagon, has_position_number, 1)
(tractor, precedes, limousine)
(limousine, follows, tractor)
----------------------------------------
Knowledge Graph 68:
(Eli, precedes, Eve)
(Eve, follows, Eli)
(Eve, precedes, Mya)
(Mya, follows, Eve)
----------------------------------------
Knowledge Graph 69:
(hawk, precedes, hummingbird)
(hummingbird, follows, hawk)
(cardinal, precedes, hawk)
(hawk, follows, cardinal)
----------------------------------------
Knowledge Graph 70:
(sedan, precedes, tractor)
(tractor, follows, sedan)
(bus, precedes, sedan)
(sedan, follows, bus)
----------------------------------------
Knowledge Graph 71:
(green_book, has_position_number, 1)
(orange_book, precedes, blue_book)
(blue_book, follows, orange_book)
----------------------------------------
Knowledge Graph 72:
(Joe, has_position_number, 1)
(Amy, precedes, Eve)
(Eve, follows, Amy)
----------------------------------------
Knowledge Graph 73:
(kiwis, precedes, loquats)
(loquats, follows, kiwis)
(cantaloupes, precedes, kiwis)
(kiwis, follows, cantaloupes)
----------------------------------------
Knowledge Graph 74:
(kiwis, precedes, loquats)
(loquats, follows, kiwis)
(cantaloupes, precedes, kiwis)
(kiwis, follows, cantaloupes)
----------------------------------------
Knowledge Graph 75:
(minivan, precedes, truck)
(truck, follows, minivan)
(station_wagon, precedes, minivan)
(minivan, follows, station_wagon)
----------------------------------------
Knowledge Graph 76:
(black_book, precedes, purple_book)
(purple_book, follows, black_book)
(purple_book, precedes, white_book)
(white_book, follows, purple_book)
----------------------------------------
Knowledge Graph 77:
(Eli, precedes, Eve)
(Eve, follows, Eli)
(Eve, precedes, Mya)
(Mya, follows, Eve)
----------------------------------------
Knowledge Graph 78:
(quail, precedes, owl)
(owl, follows, quail)
(owl, precedes, hummingbird)
(hummingbird, follows, owl)
----------------------------------------
Knowledge Graph 79:
(pears, precedes, plums)
(plums, follows, pears)
(apples, precedes, pears)
(pears, follows, apples)
----------------------------------------
Knowledge Graph 80:
(Ada, precedes, Mya)
(Mya, follows, Ada)
(Mel, precedes, Ada)
(Ada, follows, Mel)
----------------------------------------
Knowledge Graph 81:
(mangoes, has_position_number, 1)
(cantaloupes, has_position_number, 2)
----------------------------------------
Knowledge Graph 82:
(Ana, precedes, Amy)
(Amy, follows, Ana)
(Joe, precedes, Ana)
(Ana, follows, Joe)
----------------------------------------
Knowledge Graph 83:
(Ada, precedes, Mya)
(Mya, follows, Ada)
(Mel, precedes, Ada)
(Ada, follows, Mel)
----------------------------------------
Knowledge Graph 84:
(motorcyle, precedes, convertible)
(convertible, follows, motorcyle)
(convertible, precedes, truck)
(truck, follows, convertible)
----------------------------------------
Knowledge Graph 85:
(Mel, has_position_number, 1)
(Dan, has_position_number, 2)
(Mel, precedes, Dan)
(Dan, follows, Mel)
----------------------------------------
Knowledge Graph 86:
(limousine, precedes, bus)
(bus, follows, limousine)
(bus, precedes, convertible)
(convertible, follows, bus)
----------------------------------------
Knowledge Graph 87:
(red_book, has_position_number, 3)
(green_book, precedes, blue_book)
(blue_book, follows, green_book)
----------------------------------------
Knowledge Graph 88:
(peaches, has_position_number, 1)
(mangoes, precedes, pears)
(pears, follows, mangoes)
----------------------------------------
Knowledge Graph 89:
(watermelons, has_position_number, 2)
(loquats, follows, cantaloupes)
(cantaloupes, precedes, loquats)
----------------------------------------
Knowledge Graph 90:
(owl, has_position_number, 1)
(hawk, precedes, robin)
(robin, follows, hawk)
----------------------------------------
Knowledge Graph 91:
(Eli, has_position_number, 3)
(Mya, has_position_number, 2)
(Eve, has_position_number, 1)
(Eve, precedes, Mya)
(Mya, follows, Eve)
(Mya, precedes, Eli)
(Eli, follows, Mya)
----------------------------------------
Knowledge Graph 92:
(oranges, precedes, plums)
(plums, follows, oranges)
(plums, precedes, mangoes)
(mangoes, follows, plums)
----------------------------------------
Knowledge Graph 93:
(sedan, precedes, tractor)
(tractor, follows, sedan)
(bus, precedes, sedan)
(sedan, follows, bus)
----------------------------------------
Knowledge Graph 94:
(hummingbird, precedes, blue_jay)
(blue_jay, follows, hummingbird)
(raven, has_position_number, 2)
----------------------------------------
Knowledge Graph 95:
(orange_book, precedes, white_book)
(white_book, follows, orange_book)
(purple_book, has_position_number, 3)
----------------------------------------
Knowledge Graph 96:
(Eve, precedes, Amy)
(Amy, follows, Eve)
(Amy, precedes, Eli)
(Eli, follows, Amy)
----------------------------------------
Knowledge Graph 97:
(hawk, precedes, cardinal)
(cardinal, follows, hawk)
(hawk, has_position_number, 2)
----------------------------------------
Knowledge Graph 98:
(oranges, has_position_number, 3)
(cantaloupes, precedes, oranges)
(watermelons, precedes, cantaloupes)
(cantaloupes, follows, watermelons)
(cantaloupes, follows, watermelons)
----------------------------------------
Knowledge Graph 99:
(crow, precedes, robin)
(robin, follows, crow)
(robin, precedes, blue_jay)
(blue_jay, follows, robin)
----------------------------------------
Knowledge Graph 100:
(Ada, precedes, Ana)
(Ana, follows, Ada)
(Ana, precedes, Mel)
(Mel, follows, Ana)
----------------------------------------
Knowledge Graph 101:
(owl, precedes, falcon)
(falcon, follows, owl)
(hummingbird, precedes, owl)
(owl, follows, hummingbird)
----------------------------------------
Knowledge Graph 102:
(motorcyle, has_position_number, 2)
(minivan, precedes, motorcyle)
(motorcyle, follows, minivan)
----------------------------------------
Knowledge Graph 103:
(limousine, precedes, bus)
(bus, follows, limousine)
(bus, precedes, convertible)
(convertible, follows, bus)
----------------------------------------
Knowledge Graph 104:
(truck, precedes, minivan)
(minivan, follows, truck)
(minivan, precedes, tractor)
(tractor, follows, minivan)
----------------------------------------
Knowledge Graph 105:
(cardinal, precedes, owl)
(owl, follows, cardinal)
(crow, precedes, cardinal)
(cardinal, follows, crow)
----------------------------------------
Knowledge Graph 106:
(Amy, precedes, Eve)
(Eve, follows, Amy)
(Eve, precedes, Joe)
(Joe, follows, Eve)
----------------------------------------
Knowledge Graph 107:
(red_book, precedes, orange_book)
(orange_book, follows, red_book)
(orange_book, has_position_number, 2)
----------------------------------------
Knowledge Graph 108:
(blue_book, precedes, purple_book)
(purple_book, follows, blue_book)
(black_book, has_position_number, 2)
----------------------------------------
Knowledge Graph 109:
(quail, has_position_number, 1)
(raven, has_position_number, 3)
(crow, has_position_number, 2)
----------------------------------------
Knowledge Graph 110:
(quail, precedes, robin)
(robin, follows, quail)
(robin, has_position_number, 2)
----------------------------------------
Knowledge Graph 111:
(hummingbird, precedes, blue_jay)
(blue_jay, follows, hummingbird)
(raven, has_position_number, 2)
----------------------------------------
Knowledge Graph 112:
(Mel, precedes, Amy)
(Amy, follows, Mel)
(Amy, precedes, Dan)
(Dan, follows, Amy)
----------------------------------------
Knowledge Graph 113:
(minivan, precedes, truck)
(truck, follows, minivan)
(station_wagon, precedes, minivan)
(minivan, follows, station_wagon)
----------------------------------------
Knowledge Graph 114:
(motorcyle, has_position_number, 1)
(bus, precedes, tractor)
(tractor, follows, bus)
----------------------------------------
Knowledge Graph 115:
(Eve, precedes, Dan)
(Dan, follows, Eve)
(Dan, precedes, Joe)
(Joe, follows, Dan)
----------------------------------------
Knowledge Graph 116:
(loquats, precedes, pears)
(pears, follows, loquats)
(pears, precedes, apples)
(apples, follows, pears)
----------------------------------------
Knowledge Graph 117:
(convertible, precedes, tractor)
(tractor, follows, convertible)
(hatchback, has_position_number, 2)
----------------------------------------
Knowledge Graph 118:
(falcon, precedes, blue_jay)
(blue_jay, follows, falcon)
(hummingbird, precedes, falcon)
(falcon, follows, hummingbird)
----------------------------------------
Knowledge Graph 119:
(minivan, precedes, sedan)
(sedan, follows, minivan)
(bus, precedes, minivan)
(minivan, follows, bus)
----------------------------------------
Knowledge Graph 120:
(apples, precedes, loquats)
(loquats, follows, apples)
(cantaloupes, precedes, apples)
(apples, follows, cantaloupes)
----------------------------------------
Knowledge Graph 121:
(Mel, precedes, Rob)
(Rob, follows, Mel)
(Eve, precedes, Mel)
(Mel, follows, Eve)

In [19]:
for response in graphs_str_list:
    print(response)
    print("-" * 40)

### LIST_TO_ORDER
blue_jay,quail,falcon
### LEFT_TO_RIGHT_ORDER_QUALITY
left to right
### STEP_BY_STEP_REASONING
- The falcon is to the right of the blue jay. In a "left to right" order, this means the blue jay precedes the falcon.
- So, (blue_jay, precedes, falcon) and (falcon, follows, blue_jay) are derived.
- The blue jay is to the right of the quail. In a "left to right" order, this means the quail precedes the blue jay.
- So, (quail, precedes, blue_jay) and (blue_jay, follows, quail) are derived.
### TRIPLES_START
(blue_jay, precedes, falcon)
(falcon, follows, blue_jay)
(quail, precedes, blue_jay)
(blue_jay, follows, quail)
----------------------------------------
### LIST_TO_ORDER
motorcyle,limousine,convertible
### LEFT_TO_RIGHT_ORDER_QUALITY
newest to oldest
### STEP_BY_STEP_REASONING
1. The quality used for ordering is "newest to oldest", where position 1 is the newest and position 3 is the oldest.
2. The sentence "The motorcyle is newer than the limousine" implies that the motorcyle should come before the limousine. Thus, (motorcyle, precedes, limousine) and (limousine, follows, motorcyle).
3. The sentence "The convertible is newer than the motorcyle" implies that the convertible should come before the motorcyle. Thus, (convertible, precedes, motorcyle) and (motorcyle, follows, convertible).
### TRIPLES_START
(motorcyle, precedes, limousine)
(limousine, follows, motorcyle)
(convertible, precedes, motorcyle)
(motorcyle, follows, convertible)
----------------------------------------
### LIST_TO_ORDER
blue_book,orange_book,red_book
### LEFT_TO_RIGHT_ORDER_QUALITY
left to right
### STEP_BY_STEP_REASONING
1. Three books are mentioned: blue book, orange book, and red book.
2. The ordering dimension is "left to right."
3. It is stated that the blue book is the rightmost, meaning it is in the last position when arranged left to right. There are three books, so the blue book has position number 3.
4. It is also stated that the orange book is the leftmost, meaning it is in the first position when arranged left to right. Hence, the orange book has position number 1.
### TRIPLES_START
(blue_book, has_position_number, 3)
(orange_book, has_position_number, 1)
----------------------------------------
### LIST_TO_ORDER
robin,blue_jay,crow
### LEFT_TO_RIGHT_ORDER_QUALITY
left to right
### STEP_BY_STEP_REASONING
1. The statement "The robin is to the right of the crow" indicates that in a left-to-right order, the crow precedes the robin. Hence, we have: (crow, precedes, robin) and (robin, follows, crow).
2. The statement "The robin is to the left of the blue jay" indicates that in a left-to-right order, the robin precedes the blue jay. Hence, we have: (robin, precedes, blue_jay) and (blue_jay, follows, robin).
### TRIPLES_START
(crow, precedes, robin)
(robin, follows, crow)
(robin, precedes, blue_jay)
(blue_jay, follows, robin)
----------------------------------------
### LIST_TO_ORDER
green_book,red_book,blue_book
### LEFT_TO_RIGHT_ORDER_QUALITY
left to right
### STEP_BY_STEP_REASONING
1. The paragraph mentions three books: green book, red book, and blue book.
2. The ordering quality is identified as "left to right."
3. The second sentence states that "The red book is the rightmost," which means the red book is in position 3 (last/rightmost) in a list of 3 books.
   - Therefore, the triple is: (red_book, has_position_number, 3).
4. The third sentence states "The blue book is to the right of the green book," implying the green book precedes the blue book.
   - Using the “left to right” order, this means the green book precedes the blue book.
   - Emit both triples: (green_book, precedes, blue_book) and (blue_book, follows, green_book).
### TRIPLES_START
(red_book, has_position_number, 3)
(green_book, precedes, blue_book)
(blue_book, follows, green_book)
----------------------------------------
### LIST_TO_ORDER
apples,peaches,mangoes
### LEFT_TO_RIGHT_ORDER_QUALITY
cheapest to most expensive
### STEP_BY_STEP_REASONING
1. The sentence "The mangoes are less expensive than the peaches" indicates that mangoes precede peaches in the ordering "cheapest to most expensive". Therefore, mangoes are cheaper than peaches: (mangoes, precedes, peaches) and (peaches, follows, mangoes).
2. The sentence "The apples are less expensive than the mangoes" indicates that apples precede mangoes in the ordering "cheapest to most expensive". Therefore, apples are cheaper than mangoes: (apples, precedes, mangoes) and (mangoes, follows, apples).
### TRIPLES_START
(mangoes, precedes, peaches)
(peaches, follows, mangoes)
(apples, precedes, mangoes)
(mangoes, follows, apples)
----------------------------------------
### LIST_TO_ORDER
tractor,truck,minivan
### LEFT_TO_RIGHT_ORDER_QUALITY
newest to oldest
### STEP_BY_STEP_REASONING
- The ordering quality is "newest to oldest", meaning position 1 is the newest.
- "The minivan is newer than the truck" implies that the minivan precedes the truck in the order.
- Therefore, The minivan precedes the truck and the truck follows the minivan.
- "The tractor is older than the truck" implies that the truck precedes the tractor in the order.
- Therefore, The truck precedes the tractor and the tractor follows the truck.
### TRIPLES_START
(minivan, precedes, truck)
(truck, follows, minivan)
(truck, precedes, tractor)
(tractor, follows, truck)
----------------------------------------
### LIST_TO_ORDER
Eve,Rob,Mel
### LEFT_TO_RIGHT_ORDER_QUALITY
highest to lowest rank
### STEP_BY_STEP_REASONING
- The quality is "highest to lowest rank", so position 1 is the highest rank and position 3 is the lowest rank.
- "Rob finished below Mel" indicates Mel precedes Rob, meaning Mel has a higher rank.
- Thus, (Mel, precedes, Rob) and (Rob, follows, Mel).
- "Mel finished below Eve" indicates Eve precedes Mel, meaning Eve has a higher rank than Mel.
- Thus, (Eve, precedes, Mel) and (Mel, follows, Eve).
### TRIPLES_START
(Mel, precedes, Rob)
(Rob, follows, Mel)
(Eve, precedes, Mel)
(Mel, follows, Eve)
----------------------------------------
### LIST_TO_ORDER
orange_book,yellow_book,blue_book
### LEFT_TO_RIGHT_ORDER_QUALITY
left to right
### STEP_BY_STEP_REASONING
1. The ordering quality is "left to right", meaning the leftmost position is 1, and the rightmost is N (3 in this case).
2. The statement "The blue book is to the right of the yellow book" implies that the blue book follows the yellow book. This yields:
   - (yellow_book, precedes, blue_book)
   - (blue_book, follows, yellow_book)
3. "The orange book is the second from the left" informs us that the orange book is in position 2 in this "left to right" order.
   - (orange_book, has_position_number, 2)
### TRIPLES_START
(yellow_book, precedes, blue_book)
(blue_book, follows, yellow_book)
(orange_book, has_position_number, 2)
----------------------------------------
### LIST_TO_ORDER
station_wagon,minivan,truck
### LEFT_TO_RIGHT_ORDER_QUALITY
newest to oldest
### STEP_BY_STEP_REASONING
1. The quality for ordering is "newest to oldest."
2. The sentence "The minivan is newer than the truck" implies that the minivan precedes the truck in this order. Therefore, (minivan, precedes, truck) and (truck, follows, minivan).
3. The sentence "The station wagon is newer than the minivan" implies that the station wagon precedes the minivan in this order. Therefore, (station_wagon, precedes, minivan) and (minivan, follows, station_wagon).
### TRIPLES_START
(minivan, precedes, truck)
(truck, follows, minivan)
(station_wagon, precedes, minivan)
(minivan, follows, station_wagon)
----------------------------------------
### LIST_TO_ORDER
gray_book,purple_book,red_book
### LEFT_TO_RIGHT_ORDER_QUALITY
left to right
### STEP_BY_STEP_REASONING
1. "The purple book is to the left of the red book." In a left-to-right order, this means the purple book precedes the red book. Therefore, we have (purple_book, precedes, red_book) and (red_book, follows, purple_book).
2. "The gray book is to the left of the purple book." In a left-to-right order, this means the gray book precedes the purple book. Therefore, we have (gray_book, precedes, purple_book) and (purple_book, follows, gray_book).
### TRIPLES_START
(purple_book, precedes, red_book)
(red_book, follows, purple_book)
(gray_book, precedes, purple_book)
(purple_book, follows, gray_book)
----------------------------------------
### LIST_TO_ORDER
peaches,mangoes,apples
### LEFT_TO_RIGHT_ORDER_QUALITY
cheapest to most expensive
### STEP_BY_STEP_REASONING
1. The ordering quality is "cheapest to most expensive", meaning position 1 is the cheapest and position 3 is the most expensive.
2. "The mangoes are the cheapest" implies mangoes are in position 1.
   - Emit: (mangoes, has_position_number, 1)
3. "The peaches are more expensive than the apples" suggests peaches follow apples for "cheapest to most expensive".
   - Therefore, apples precede peaches.
   - Emit: (apples, precedes, peaches)
   - Emit: (peaches, follows, apples)
### TRIPLES_START
(mangoes, has_position_number, 1)
(apples, precedes, peaches)
(peaches, follows, apples)
----------------------------------------
### LIST_TO_ORDER
blue_jay,falcon,hummingbird
### LEFT_TO_RIGHT_ORDER_QUALITY
left to right
### STEP_BY_STEP_REASONING
1. The quality selected for ordering is "left to right".
2. The statement "the blue jay is to the right of the falcon" implies that the falcon precedes the blue jay. Therefore, we derive the following two triples:
   - (falcon, precedes, blue_jay)
   - (blue_jay, follows, falcon)
3. The statement "the hummingbird is to the left of the falcon" implies that the hummingbird precedes the falcon. Therefore, we derive the following two triples:
   - (hummingbird, precedes, falcon)
   - (falcon, follows, hummingbird)
### TRIPLES_START
(falcon, precedes, blue_jay)
(blue_jay, follows, falcon)
(hummingbird, precedes, falcon)
(falcon, follows, hummingbird)
----------------------------------------
### LIST_TO_ORDER
minivan,bus,sedan
### LEFT_TO_RIGHT_ORDER_QUALITY
newest to oldest
### STEP_BY_STEP_REASONING
1. The quality of order is "newest to oldest", meaning the newest vehicle is at position 1.
2. "The minivan is newer than the sedan": Based on this quality, the minivan precedes the sedan.
3. "The minivan is older than the bus": Based on this quality, the bus precedes the minivan.
4. From these comparisons, we have:
   - The bus precedes the minivan, and the minivan precedes the sedan.
### TRIPLES_START
(minivan, precedes, sedan)
(sedan, follows, minivan)
(bus, precedes, minivan)
(minivan, follows, bus)
----------------------------------------
### LIST_TO_ORDER
hatchback,convertible,tractor
### LEFT_TO_RIGHT_ORDER_QUALITY
oldest to newest
### STEP_BY_STEP_REASONING
1. The order is from "oldest to newest", meaning position 1 is the oldest and position 3 is the newest.
2. The convertible is older than the tractor. This implies in the "oldest to newest" order, the convertible precedes the tractor, and the tractor follows the convertible.
3. The hatchback is the second-newest. Since there are three vehicles, this means the hatchback is in position 2.
### TRIPLES_START
(convertible, precedes, tractor)
(tractor, follows, convertible)
(hatchback, has_position_number, 2)
----------------------------------------
### LIST_TO_ORDER
loquats,watermelons,cantaloupes
### LEFT_TO_RIGHT_ORDER_QUALITY
cheapest to most expensive
### STEP_BY_STEP_REASONING
1. The watermelons are stated to be the second-most expensive in a list of three items. Since "second-most expensive" corresponds to position (N - 1) in a "cheapest to most expensive" order, where N is the total number of items (3 in this case), watermelons have position 2.
2. The statement "loquats are more expensive than cantaloupes" means that loquats precede cantaloupes in a "cheapest to most expensive" order because the more expensive item comes later.
3. Based on this comparative statement, loquats precede cantaloupes implies loquats follow and cantaloupes precedes.
### TRIPLES_START
(watermelons, has_position_number, 2)
(loquats, follows, cantaloupes)
(cantaloupes, precedes, loquats)
----------------------------------------
### LIST_TO_ORDER
mangoes,watermelons,kiwis
### LEFT_TO_RIGHT_ORDER_QUALITY
cheapest to most expensive
### STEP_BY_STEP_REASONING
1. We have three items: mangoes, watermelons, and kiwis.
2. The quality being used to order them is "cheapest to most expensive".
3. The watermelons are stated as being less expensive than the kiwis, which means in a "cheapest to most expensive" order, watermelons precede kiwis. Thus, we can write: (watermelons, precedes, kiwis) and (kiwis, follows, watermelons).
4. The kiwis are identified as the second-most expensive fruit. Since there are three fruits in total, "second-most expensive" translates to being in position 2. Thus, we can write: (kiwis, has_position_number, 2).
### TRIPLES_START
(watermelons, precedes, kiwis)
(kiwis, follows, watermelons)
(kiwis, has_position_number, 2)
----------------------------------------
### LIST_TO_ORDER
blue_book,orange_book,red_book
### LEFT_TO_RIGHT_ORDER_QUALITY
left to right
### STEP_BY_STEP_REASONING
1. The statement "The blue book is the rightmost" indicates that the blue book is in position 3 from left to right.
2. The statement "The orange book is the leftmost" indicates that the orange book is in position 1 from left to right.
3. With these positions established, the only remaining position (position 2) must be occupied by the red book.
4. By confirming the positions, the order is established as orange book, red book, and blue book from left to right.
5. Given the left to right order:
   - The orange book precedes the red book, and the red book follows the orange book.
   - The red book precedes the blue book, and the blue book follows the red book.
### TRIPLES_START
(blue_book, has_position_number, 3)
(orange_book, has_position_number, 1)
(orange_book, precedes, red_book)
(red_book, follows, orange_book)
(red_book, precedes, blue_book)
(blue_book, follows, red_book)
----------------------------------------
### LIST_TO_ORDER
Ada,Mel,Mya
### LEFT_TO_RIGHT_ORDER_QUALITY
highest to lowest finish
### STEP_BY_STEP_REASONING
1. "Mya finished below Ada" means Mya had a worse finish than Ada in the tournament. Given the order "highest to lowest finish", Ada precedes Mya.
2. "Mel finished above Ada" means Mel had a better finish than Ada in the tournament. Given the order "highest to lowest finish", Mel precedes Ada.
### TRIPLES_START
(Ada, precedes, Mya)
(Mya, follows, Ada)
(Mel, precedes, Ada)
(Ada, follows, Mel)
----------------------------------------
### LIST_TO_ORDER
Mel,Ada,Ana
### LEFT_TO_RIGHT_ORDER_QUALITY
first to last
### STEP_BY_STEP_REASONING
1. The statement "Mel finished last" directly tells us that Mel is in position 3. This establishes Mel's position.
2. The statement "Ana finished second" directly tells us that Ana is in position 2. This gives us Ana's position.
3. Since Mel is last (position 3) and Ana is second (position 2), Ada must be in position 1, as the only remaining position for the three golfers is the first.

### TRIPLES_START
(Mel, has_position_number, 3)
(Ana, has_position_number, 2)
----------------------------------------
### LIST_TO_ORDER
plums,apples,loquats
### LEFT_TO_RIGHT_ORDER_QUALITY
cheapest to most expensive
### STEP_BY_STEP_REASONING
1. The statement "The loquats are the cheapest" directly provides the information that loquats have the lowest price. Therefore, loquats have the position 1.
2. The statement "The plums are less expensive than the apples" tells us that plums are cheaper than apples. In the "cheapest to most expensive" ordering, plums therefore precede apples. Accordingly, apples follow plums.
### TRIPLES_START
(loquats, has_position_number, 1)
(plums, precedes, apples)
(apples, follows, plums)
----------------------------------------
### LIST_TO_ORDER
black_book,orange_book,blue_book
### LEFT_TO_RIGHT_ORDER_QUALITY
left to right
### STEP_BY_STEP_REASONING
- The statement "The blue book is to the right of the orange book" implies that in a "left to right" order, the orange book precedes the blue book. Therefore, (orange_book, precedes, blue_book) and (blue_book, follows, orange_book) are derived.
- The statement "The orange book is to the right of the black book" implies that in a "left to right" order, the black book precedes the orange book. Therefore, (black_book, precedes, orange_book) and (orange_book, follows, black_book) are derived.
### TRIPLES_START
(orange_book, precedes, blue_book)
(blue_book, follows, orange_book)
(black_book, precedes, orange_book)
(orange_book, follows, black_book)
----------------------------------------
### LIST_TO_ORDER
convertible,motorcyle,truck
### LEFT_TO_RIGHT_ORDER_QUALITY
newest to oldest
### STEP_BY_STEP_REASONING
1. The ordering quality is "newest to oldest", meaning position 1 is assigned to the newest.
2. The statement "The motorcyle is newer than the convertible" indicates that the motorcyle should precede the convertible in the "newest to oldest" ordering. Therefore, (motorcyle, precedes, convertible) and (convertible, follows, motorcyle).
3. The statement "The convertible is newer than the truck" indicates that the convertible should precede the truck in the "newest to oldest" ordering. Therefore, (convertible, precedes, truck) and (truck, follows, convertible).
### TRIPLES_START
(motorcyle, precedes, convertible)
(convertible, follows, motorcyle)
(convertible, precedes, truck)
(truck, follows, convertible)
----------------------------------------
### LIST_TO_ORDER
apples,peaches,mangoes
### LEFT_TO_RIGHT_ORDER_QUALITY
cheapest to most expensive
### STEP_BY_STEP_REASONING
1. We start by identifying the ordering quality: "cheapest to most expensive." This means the least expensive item is in position 1.
2. The statement "The mangoes are less expensive than the peaches" indicates that mangoes precede peaches in terms of cost. Therefore, mangoes are cheaper than peaches.
3. Based on this, we determine:
   - (mangoes, precedes, peaches)
   - (peaches, follows, mangoes)
4. The statement "The apples are less expensive than the mangoes" indicates that apples precede mangoes, meaning apples are cheaper than mangoes.
5. Based on this, we determine:
   - (apples, precedes, mangoes)
   - (mangoes, follows, apples)
### TRIPLES_START
(mangoes, precedes, peaches)
(peaches, follows, mangoes)
(apples, precedes, mangoes)
(mangoes, follows, apples)
----------------------------------------
### LIST_TO_ORDER
Eve,Joe,Amy
### LEFT_TO_RIGHT_ORDER_QUALITY
highest to lowest rank
### STEP_BY_STEP_REASONING
1. Identify that we are dealing with a ranking based on performance in a golf tournament, interpreted as "highest to lowest rank" where position 1 is the highest rank.
2. "Eve finished below Amy" means Amy's rank is higher than Eve. Interpret this as Amy precedes Eve.
3. Therefore, emit (Amy, precedes, Eve) and (Eve, follows, Amy).
4. "Eve finished above Joe" means Eve's rank is higher than Joe. Interpret this as Eve precedes Joe.
5. Therefore, emit (Eve, precedes, Joe) and (Joe, follows, Eve).
### TRIPLES_START
(Amy, precedes, Eve)
(Eve, follows, Amy)
(Eve, precedes, Joe)
(Joe, follows, Eve)
----------------------------------------
### LIST_TO_ORDER
Eli,Mya,Eve
### LEFT_TO_RIGHT_ORDER_QUALITY
highest to lowest rank
### STEP_BY_STEP_REASONING
1. The quality is "highest to lowest rank", meaning position 1 is the highest rank.
2. Eve finished below Eli. In a "highest to lowest rank" order, this means Eli precedes Eve.
3. Therefore, the triple (Eli, precedes, Eve) is correct.
4. Conversely, Eve follows Eli, so the triple (Eve, follows, Eli) is correct.
5. Eve finished above Mya, which means in "highest to lowest rank" Eve precedes Mya.
6. Thus, the triple (Eve, precedes, Mya) is correct.
7. Conversely, Mya follows Eve, so the triple (Mya, follows, Eve) is correct.
### TRIPLES_START
(Eli, precedes, Eve)
(Eve, follows, Eli)
(Eve, precedes, Mya)
(Mya, follows, Eve)

In [20]:
def extract_ordering_quality(text):
    marker = "### LEFT_TO_RIGHT_ORDER_QUALITY"
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == marker:
            # Return the very next non-empty line (in case there are blank lines)
            for next_line in lines[i+1:]:
                if next_line.strip():
                    return next_line.strip()
    return None  # If marker or value not found

ordering_quality_list = []

for i in range(len(graphs_str_list)):
    graph_str = graphs_str_list[i]
    ordering_quality = extract_ordering_quality(graph_str)
    print(f"Ordering Quality {i + 1}: {ordering_quality}")
    ordering_quality_list.append(ordering_quality)

Ordering Quality 1: left to right
Ordering Quality 2: newest to oldest
Ordering Quality 3: left to right
Ordering Quality 4: left to right
Ordering Quality 5: left to right
Ordering Quality 6: cheapest to most expensive
Ordering Quality 7: newest to oldest
Ordering Quality 8: highest to lowest rank
Ordering Quality 9: left to right
Ordering Quality 10: newest to oldest
Ordering Quality 11: left to right
Ordering Quality 12: cheapest to most expensive
Ordering Quality 13: left to right
Ordering Quality 14: newest to oldest
Ordering Quality 15: oldest to newest
Ordering Quality 16: cheapest to most expensive
Ordering Quality 17: cheapest to most expensive
Ordering Quality 18: left to right
Ordering Quality 19: highest to lowest finish
Ordering Quality 20: first to last
Ordering Quality 21: cheapest to most expensive
Ordering Quality 22: left to right
Ordering Quality 23: newest to oldest
Ordering Quality 24: cheapest to most expensive
Ordering Quality 25: highest to lowest rank
Ordering Quality 26: highest to lowest rank
Ordering Quality 27: cheapest to most expensive
Ordering Quality 28: oldest to newest
Ordering Quality 29: left to right
Ordering Quality 30: left to right
Ordering Quality 31: cheapest to most expensive
Ordering Quality 32: highest to lowest rank
Ordering Quality 33: oldest to newest
Ordering Quality 34: left to right
Ordering Quality 35: oldest to newest
Ordering Quality 36: oldest to newest
Ordering Quality 37: cheapest to most expensive
Ordering Quality 38: left to right
Ordering Quality 39: left to right
Ordering Quality 40: left to right
Ordering Quality 41: cheapest to most expensive
Ordering Quality 42: cheapest to most expensive
Ordering Quality 43: cheapest to most expensive
Ordering Quality 44: left to right
Ordering Quality 45: cheapest to most expensive
Ordering Quality 46: left to right
Ordering Quality 47: cheapest to most expensive
Ordering Quality 48: highest to lowest rank
Ordering Quality 49: oldest to newest
Ordering Quality 50: left to right
Ordering Quality 51: left to right
Ordering Quality 52: cheapest to most expensive
Ordering Quality 53: left to right
Ordering Quality 54: oldest to newest
Ordering Quality 55: left to right
Ordering Quality 56: highest to lowest finish
Ordering Quality 57: highest to lowest rank
Ordering Quality 58: left to right
Ordering Quality 59: cheapest to most expensive
Ordering Quality 60: oldest to newest
Ordering Quality 61: oldest to newest
Ordering Quality 62: cheapest to most expensive
Ordering Quality 63: left to right
Ordering Quality 64: cheapest to most expensive
Ordering Quality 65: newest to oldest
Ordering Quality 66: newest to oldest
Ordering Quality 67: newest to oldest
Ordering Quality 68: highest to lowest rank
Ordering Quality 69: left to right
Ordering Quality 70: oldest to newest
Ordering Quality 71: left to right
Ordering Quality 72: first to last
Ordering Quality 73: cheapest to most expensive
Ordering Quality 74: cheapest to most expensive
Ordering Quality 75: newest to oldest
Ordering Quality 76: left to right
Ordering Quality 77: highest to lowest rank
Ordering Quality 78: left to right
Ordering Quality 79: cheapest to most expensive
Ordering Quality 80: highest to lowest finish
Ordering Quality 81: cheapest to most expensive
Ordering Quality 82: highest to lowest position
Ordering Quality 83: highest to lowest finish
Ordering Quality 84: newest to oldest
Ordering Quality 85: first to last
Ordering Quality 86: oldest to newest
Ordering Quality 87: left to right
Ordering Quality 88: cheapest to most expensive
Ordering Quality 89: cheapest to most expensive
Ordering Quality 90: left to right
Ordering Quality 91: first to last
Ordering Quality 92: cheapest to most expensive
Ordering Quality 93: oldest to newest
Ordering Quality 94: left to right
Ordering Quality 95: left to right
Ordering Quality 96: highest to lowest finish
Ordering Quality 97: left to right
Ordering Quality 98: cheapest to most expensive
Ordering Quality 99: left to right
Ordering Quality 100: highest to lowest rank
Ordering Quality 101: left to right
Ordering Quality 102: newest to oldest
Ordering Quality 103: oldest to newest
Ordering Quality 104: newest to oldest
Ordering Quality 105: left to right
Ordering Quality 106: highest to lowest rank
Ordering Quality 107: left to right
Ordering Quality 108: left to right
Ordering Quality 109: left to right
Ordering Quality 110: left to right
Ordering Quality 111: left to right
Ordering Quality 112: highest to lowest rank
Ordering Quality 113: newest to oldest
Ordering Quality 114: oldest to newest
Ordering Quality 115: highest to lowest rank
Ordering Quality 116: cheapest to most expensive
Ordering Quality 117: oldest to newest
Ordering Quality 118: left to right
Ordering Quality 119: newest to oldest
Ordering Quality 120: cheapest to most expensive
Ordering Quality 121: highest to lowest rank
Ordering Quality 122: left to right
Ordering Quality 123: highest to lowest rank
Ordering Quality 124: left to right
Ordering Quality 125: cheapest to most expensive
Ordering Quality 126: left to right
Ordering Quality 127: left to right
Ordering Quality 128: left to right
Ordering Quality 129: left to right
Ordering Quality 130: first to last
Ordering Quality 131: newest to oldest
Ordering Quality 132: left to right
Ordering Quality 133: cheapest to most expensive
Ordering Quality 134: left to right
Ordering Quality 135: cheapest to most expensive
Ordering Quality 136: cheapest to most expensive
Ordering Quality 137: cheapest to most expensive
Ordering Quality 138: left to right
Ordering Quality 139: highest to lowest rank
Ordering Quality 140: left to right
Ordering Quality 141: cheapest to most expensive
Ordering Quality 142: left to right
Ordering Quality 143: left to right
Ordering Quality 144: first to last
Ordering Quality 145: left to right
Ordering Quality 146: highest to lowest rank
Ordering Quality 147: cheapest to most expensive
Ordering Quality 148: left to right
Ordering Quality 149: newest to oldest
Ordering Quality 150: highest to lowest rank
Ordering Quality 151: cheapest to most expensive
Ordering Quality 152: left to right
Ordering Quality 153: newest to oldest
Ordering Quality 154: left to right
Ordering Quality 155: newest to oldest
Ordering Quality 156: oldest to newest
Ordering Quality 157: left to right
Ordering Quality 158: left to right
Ordering Quality 159: highest to lowest finish
Ordering Quality 160: left to right
Ordering Quality 161: cheapest to most expensive
Ordering Quality 162: cheapest to most expensive
Ordering Quality 163: 1st to last in a tournament
Ordering Quality 164: cheapest to most expensive
Ordering Quality 165: left to right
Ordering Quality 166: newest to oldest
Ordering Quality 167: highest to lowest position
Ordering Quality 168: left to right
Ordering Quality 169: cheapest to most expensive
Ordering Quality 170: highest to lowest rank
Ordering Quality 171: left to right
Ordering Quality 172: left to right
Ordering Quality 173: cheapest to most expensive
Ordering Quality 174: left to right
Ordering Quality 175: highest to lowest finish
Ordering Quality 176: first to last
Ordering Quality 177: newest to oldest
Ordering Quality 178: oldest to newest
Ordering Quality 179: left to right
Ordering Quality 180: oldest to newest
Ordering Quality 181: oldest to newest
Ordering Quality 182: left to right
Ordering Quality 183: first to last
Ordering Quality 184: newest to oldest
Ordering Quality 185: highest to lowest rank
Ordering Quality 186: highest to lowest rank
Ordering Quality 187: cheapest to most expensive
Ordering Quality 188: left to right
Ordering Quality 189: left to right
Ordering Quality 190: left to right
Ordering Quality 191: left to right
Ordering Quality 192: best finish to worst finish
Ordering Quality 193: cheapest to most expensive
Ordering Quality 194: highest to lowest rank
Ordering Quality 195: 1st to last in a tournament
Ordering Quality 196: newest to oldest
Ordering Quality 197: newest to oldest
Ordering Quality 198: cheapest to most expensive
Ordering Quality 199: highest to lowest rank
Ordering Quality 200: left to right
Ordering Quality 201: cheapest to most expensive
Ordering Quality 202: cheapest to most expensive
Ordering Quality 203: left to right
Ordering Quality 204: left to right
Ordering Quality 205: left to right
Ordering Quality 206: cheapest to most expensive
Ordering Quality 207: left to right
Ordering Quality 208: newest to oldest
Ordering Quality 209: newest to oldest
Ordering Quality 210: left to right
Ordering Quality 211: first to last place
Ordering Quality 212: left to right
Ordering Quality 213: cheapest to most expensive
Ordering Quality 214: cheapest to most expensive
Ordering Quality 215: highest to lowest rank
Ordering Quality 216: left to right
Ordering Quality 217: cheapest to most expensive
Ordering Quality 218: left to right
Ordering Quality 219: newest to oldest
Ordering Quality 220: left to right
Ordering Quality 221: newest to oldest
Ordering Quality 222: highest to lowest rank
Ordering Quality 223: left to right
Ordering Quality 224: newest to oldest
Ordering Quality 225: highest to lowest rank
Ordering Quality 226: left to right
Ordering Quality 227: 1st to last in a tournament
Ordering Quality 228: cheapest to most expensive
Ordering Quality 229: first to last
Ordering Quality 230: left to right
Ordering Quality 231: first to last
Ordering Quality 232: left to right
Ordering Quality 233: left to right
Ordering Quality 234: left to right
Ordering Quality 235: left to right
Ordering Quality 236: left to right
Ordering Quality 237: newest to oldest
Ordering Quality 238: highest to lowest rank
Ordering Quality 239: left to right
Ordering Quality 240: cheapest to most expensive
Ordering Quality 241: left to right
Ordering Quality 242: left to right
Ordering Quality 243: newest to oldest
Ordering Quality 244: left to right
Ordering Quality 245: newest to oldest
Ordering Quality 246: left to right
Ordering Quality 247: left to right
Ordering Quality 248: newest to oldest
Ordering Quality 249: left to right
Ordering Quality 250: highest to lowest rank
Ordering Quality 251: left to right
Ordering Quality 252: oldest to newest
Ordering Quality 253: left to right
Ordering Quality 254: left to right
Ordering Quality 255: left to right
Ordering Quality 256: left to right
Ordering Quality 257: newest to oldest
Ordering Quality 258: highest to lowest rank
Ordering Quality 259: left to right
Ordering Quality 260: oldest to newest
Ordering Quality 261: cheapest to most expensive
Ordering Quality 262: cheapest to most expensive
Ordering Quality 263: left to right
Ordering Quality 264: best performance to worst performance
Ordering Quality 265: cheapest to most expensive
Ordering Quality 266: left to right
Ordering Quality 267: newest to oldest
Ordering Quality 268: left to right
Ordering Quality 269: first to last
Ordering Quality 270: first to fifth position
Ordering Quality 271: cheapest to most expensive
Ordering Quality 272: newest to oldest
Ordering Quality 273: best to worst finish
Ordering Quality 274: oldest to newest
Ordering Quality 275: left to right
Ordering Quality 276: cheapest to most expensive
Ordering Quality 277: first to last
Ordering Quality 278: first to last
Ordering Quality 279: highest to lowest rank
Ordering Quality 280: first to last
Ordering Quality 281: left to right
Ordering Quality 282: left to right
Ordering Quality 283: highest to lowest rank
Ordering Quality 284: left to right
Ordering Quality 285: highest to lowest rank
Ordering Quality 286: left to right
Ordering Quality 287: cheapest to most expensive
Ordering Quality 288: left to right
Ordering Quality 289: first to last in a golf tournament
Ordering Quality 290: left to right
Ordering Quality 291: newest to oldest
Ordering Quality 292: best performance to worst performance
Ordering Quality 293: left to right
Ordering Quality 294: left to right
Ordering Quality 295: newest to oldest
Ordering Quality 296: left to right
Ordering Quality 297: left to right
Ordering Quality 298: newest to oldest
Ordering Quality 299: left to right
Ordering Quality 300: left to right
Ordering Quality 301: left to right
Ordering Quality 302: left to right
Ordering Quality 303: cheapest to most expensive
Ordering Quality 304: oldest to newest
Ordering Quality 305: left to right
Ordering Quality 306: left to right
Ordering Quality 307: best score to worst score
Ordering Quality 308: left to right
Ordering Quality 309: left to right
Ordering Quality 310: newest to oldest
Ordering Quality 311: left to right
Ordering Quality 312: newest to oldest
Ordering Quality 313: left to right
Ordering Quality 314: left to right
Ordering Quality 315: left to right
Ordering Quality 316: left to right
Ordering Quality 317: oldest to newest
Ordering Quality 318: left to right
Ordering Quality 319: newest to oldest
Ordering Quality 320: cheapest to most expensive
Ordering Quality 321: left to right
Ordering Quality 322: cheapest to most expensive
Ordering Quality 323: first to last
Ordering Quality 324: newest to oldest
Ordering Quality 325: cheapest to most expensive
Ordering Quality 326: cheapest to most expensive
Ordering Quality 327: left to right
Ordering Quality 328: oldest to newest
Ordering Quality 329: first to last
Ordering Quality 330: left to right
Ordering Quality 331: left to right
Ordering Quality 332: left to right
Ordering Quality 333: cheapest to most expensive
Ordering Quality 334: first to last
Ordering Quality 335: newest to oldest
Ordering Quality 336: cheapest to most expensive
Ordering Quality 337: newest to oldest
Ordering Quality 338: left to right
Ordering Quality 339: cheapest to most expensive
Ordering Quality 340: left to right
Ordering Quality 341: left to right
Ordering Quality 342: left to right
Ordering Quality 343: highest to lowest rank
Ordering Quality 344: highest to lowest rank
Ordering Quality 345: left to right
Ordering Quality 346: left to right
Ordering Quality 347: left to right
Ordering Quality 348: cheapest to most expensive
Ordering Quality 349: newest to oldest
Ordering Quality 350: left to right
Ordering Quality 351: highest to lowest rank
Ordering Quality 352: newest to oldest
Ordering Quality 353: last to first
Ordering Quality 354: oldest to newest
Ordering Quality 355: left to right
Ordering Quality 356: newest to oldest
Ordering Quality 357: left to right
Ordering Quality 358: newest to oldest
Ordering Quality 359: left to right
Ordering Quality 360: newest to oldest
Ordering Quality 361: left to right
Ordering Quality 362: newest to oldest
Ordering Quality 363: left to right
Ordering Quality 364: left to right
Ordering Quality 365: newest to oldest
Ordering Quality 366: cheapest to most expensive
Ordering Quality 367: cheapest to most expensive
Ordering Quality 368: left to right
Ordering Quality 369: left to right
Ordering Quality 370: best to worst finish
Ordering Quality 371: left to right
Ordering Quality 372: highest to lowest finish
Ordering Quality 373: cheapest to most expensive
Ordering Quality 374: first to last
Ordering Quality 375: highest to lowest rank
Ordering Quality 376: cheapest to most expensive
Ordering Quality 377: first to last
Ordering Quality 378: left to right
Ordering Quality 379: left to right
Ordering Quality 380: newest to oldest
Ordering Quality 381: newest to oldest
Ordering Quality 382: left to right
Ordering Quality 383: left to right
Ordering Quality 384: cheapest to most expensive
Ordering Quality 385: highest to lowest finish
Ordering Quality 386: left to right
Ordering Quality 387: first to fifth position
Ordering Quality 388: newest to oldest
Ordering Quality 389: oldest to newest
Ordering Quality 390: cheapest to most expensive
Ordering Quality 391: left to right
Ordering Quality 392: cheapest to most expensive
Ordering Quality 393: left to right
Ordering Quality 394: left to right
Ordering Quality 395: left to right
Ordering Quality 396: left to right
Ordering Quality 397: cheapest to most expensive
Ordering Quality 398: highest to lowest rank
Ordering Quality 399: highest to lowest rank
Ordering Quality 400: cheapest to most expensive
Ordering Quality 401: highest to lowest rank
Ordering Quality 402: left to right
Ordering Quality 403: cheapest to most expensive
Ordering Quality 404: highest to lowest rank
Ordering Quality 405: newest to oldest
Ordering Quality 406: cheapest to most expensive
Ordering Quality 407: newest to oldest
Ordering Quality 408: left to right
Ordering Quality 409: cheapest to most expensive
Ordering Quality 410: left to right
Ordering Quality 411: left to right
Ordering Quality 412: last to first
Ordering Quality 413: best score to worst score
Ordering Quality 414: best to worst finish
Ordering Quality 415: oldest to newest
Ordering Quality 416: oldest to newest
Ordering Quality 417: left to right
Ordering Quality 418: highest to lowest rank
Ordering Quality 419: oldest to newest
Ordering Quality 420: newest to oldest
Ordering Quality 421: left to right
Ordering Quality 422: highest to lowest finish position
Ordering Quality 423: cheapest to most expensive
Ordering Quality 424: left to right
Ordering Quality 425: left to right
Ordering Quality 426: left to right
Ordering Quality 427: highest to lowest rank
Ordering Quality 428: left to right
Ordering Quality 429: newest to oldest
Ordering Quality 430: cheapest to most expensive
Ordering Quality 431: highest to lowest rank
Ordering Quality 432: left to right
Ordering Quality 433: first to last
Ordering Quality 434: cheapest to most expensive
Ordering Quality 435: cheapest to most expensive
Ordering Quality 436: left to right
Ordering Quality 437: left to right
Ordering Quality 438: cheapest to most expensive
Ordering Quality 439: left to right
Ordering Quality 440: left to right
Ordering Quality 441: oldest to newest
Ordering Quality 442: best to worst finish
Ordering Quality 443: newest to oldest
Ordering Quality 444: cheapest to most expensive
Ordering Quality 445: left to right
Ordering Quality 446: best to worst finish
Ordering Quality 447: left to right
Ordering Quality 448: left to right
Ordering Quality 449: left to right
Ordering Quality 450: cheapest to most expensive
Ordering Quality 451: highest to lowest finish
Ordering Quality 452: first to fifth position
Ordering Quality 453: oldest to newest
Ordering Quality 454: cheapest to most expensive
Ordering Quality 455: first to last in a golf tournament
Ordering Quality 456: cheapest to most expensive
Ordering Quality 457: left to right
Ordering Quality 458: left to right
Ordering Quality 459: best performance to worst performance
Ordering Quality 460: left to right
Ordering Quality 461: newest to oldest
Ordering Quality 462: oldest to newest
Ordering Quality 463: cheapest to most expensive
Ordering Quality 464: first to last
Ordering Quality 465: cheapest to most expensive
Ordering Quality 466: newest to oldest
Ordering Quality 467: best to worst finish
Ordering Quality 468: cheapest to most expensive
Ordering Quality 469: cheapest to most expensive
Ordering Quality 470: left to right
Ordering Quality 471: highest to lowest rank
Ordering Quality 472: cheapest to most expensive
Ordering Quality 473: left to right
Ordering Quality 474: newest to oldest
Ordering Quality 475: left to right
Ordering Quality 476: cheapest to most expensive
Ordering Quality 477: left to right
Ordering Quality 478: newest to oldest
Ordering Quality 479: left to right
Ordering Quality 480: cheapest to most expensive
Ordering Quality 481: cheapest to most expensive
Ordering Quality 482: cheapest to most expensive
Ordering Quality 483: highest to lowest rank
Ordering Quality 484: cheapest to most expensive
Ordering Quality 485: left to right
Ordering Quality 486: newest to oldest
Ordering Quality 487: left to right
Ordering Quality 488: cheapest to most expensive
Ordering Quality 489: left to right
Ordering Quality 490: best to worst finish
Ordering Quality 491: cheapest to most expensive

In [21]:
def extract_entities(text):
    marker = "### LIST_TO_ORDER"
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == marker:
            # Return the very next non-empty line (in case there are blank lines)
            for next_line in lines[i+1:]:
                if next_line.strip():
                    return next_line.strip().split(",")
    return []  # If marker or value not found

entities_list = []

for i in range(len(graphs_str_list)):
    graph_str = graphs_str_list[i]
    entities = extract_entities(graph_str)
    print(f"Entities {i + 1}: {entities}")
    entities_list.append(entities)

Entities 1: ['blue_jay', 'quail', 'falcon']
Entities 2: ['motorcyle', 'limousine', 'convertible']
Entities 3: ['blue_book', 'orange_book', 'red_book']
Entities 4: ['robin', 'blue_jay', 'crow']
Entities 5: ['green_book', 'red_book', 'blue_book']
Entities 6: ['apples', 'peaches', 'mangoes']
Entities 7: ['tractor', 'truck', 'minivan']
Entities 8: ['Eve', 'Rob', 'Mel']
Entities 9: ['orange_book', 'yellow_book', 'blue_book']
Entities 10: ['station_wagon', 'minivan', 'truck']
Entities 11: ['gray_book', 'purple_book', 'red_book']
Entities 12: ['peaches', 'mangoes', 'apples']
Entities 13: ['blue_jay', 'falcon', 'hummingbird']
Entities 14: ['minivan', 'bus', 'sedan']
Entities 15: ['hatchback', 'convertible', 'tractor']
Entities 16: ['loquats', 'watermelons', 'cantaloupes']
Entities 17: ['mangoes', 'watermelons', 'kiwis']
Entities 18: ['blue_book', 'orange_book', 'red_book']
Entities 19: ['Ada', 'Mel', 'Mya']
Entities 20: ['Mel', 'Ada', 'Ana']
Entities 21: ['plums', 'apples', 'loquats']
Entities 22: ['black_book', 'orange_book', 'blue_book']
Entities 23: ['convertible', 'motorcyle', 'truck']
Entities 24: ['apples', 'peaches', 'mangoes']
Entities 25: ['Eve', 'Joe', 'Amy']
Entities 26: ['Eli', 'Mya', 'Eve']
Entities 27: ['peaches', 'pears', 'mangoes']
Entities 28: ['hatchback', 'convertible', 'tractor']
Entities 29: ['hummingbird', 'blue_jay', 'raven']
Entities 30: ['purple_book', 'red_book', 'yellow_book']
Entities 31: ['watermelons', 'apples', 'mangoes']
Entities 32: ['Amy', 'Dan', 'Mel']
Entities 33: ['motorcyle', 'bus', 'tractor']
Entities 34: ['red_book', 'blue_book', 'orange_book']
Entities 35: ['motorcyle', 'minivan', 'tractor']
Entities 36: ['bus', 'sedan', 'truck']
Entities 37: ['loquats', 'mangoes', 'apples']
Entities 38: ['blue_jay', 'quail', 'falcon']
Entities 39: ['hawk', 'crow', 'raven']
Entities 40: ['brown_book', 'yellow_book', 'orange_book']
Entities 41: ['loquats', 'mangoes', 'apples']
Entities 42: ['cantaloupes', 'oranges', 'watermelons']
Entities 43: ['apples', 'peaches', 'loquats']
Entities 44: ['owl', 'crow', 'cardinal']
Entities 45: ['oranges', 'mangoes', 'plums']
Entities 46: ['quail', 'owl', 'hummingbird']
Entities 47: ['oranges', 'watermelons', 'pears']
Entities 48: ['Ana', 'Mel', 'Ada']
Entities 49: ['sedan', 'tractor', 'bus']
Entities 50: ['green_book', 'brown_book', 'orange_book']
Entities 51: ['orange_book', 'blue_book', 'yellow_book']
Entities 52: ['oranges', 'mangoes', 'plums']
Entities 53: ['gray_book', 'purple_book', 'red_book']
Entities 54: ['motorcyle', 'minivan', 'tractor']
Entities 55: ['blue_jay', 'cardinal', 'quail']
Entities 56: ['Amy', 'Eli', 'Eve']
Entities 57: ['Joe', 'Dan', 'Eve']
Entities 58: ['blue_jay', 'quail', 'falcon']
Entities 59: ['watermelons', 'apples', 'mangoes']
Entities 60: ['motorcyle', 'bus', 'tractor']
Entities 61: ['motorcyle', 'minivan', 'tractor']
Entities 62: ['plums', 'apples', 'loquats']
Entities 63: ['gray_book', 'orange_book', 'brown_book']
Entities 64: ['pears', 'plums', 'kiwis']
Entities 65: ['convertible', 'tractor', 'hatchback']
Entities 66: ['tractor', 'convertible', 'minivan']
Entities 67: ['tractor', 'station_wagon', 'limousine']
Entities 68: ['Eli', 'Mya', 'Eve']
Entities 69: ['cardinal', 'hawk', 'hummingbird']
Entities 70: ['sedan', 'tractor', 'bus']
Entities 71: ['blue_book', 'orange_book', 'green_book']
Entities 72: ['Joe', 'Eve', 'Amy']
Entities 73: ['kiwis', 'loquats', 'cantaloupes']
Entities 74: ['kiwis', 'loquats', 'cantaloupes']
Entities 75: ['station_wagon', 'minivan', 'truck']
Entities 76: ['white_book', 'black_book', 'purple_book']
Entities 77: ['Eli', 'Mya', 'Eve']
Entities 78: ['quail', 'owl', 'hummingbird']
Entities 79: ['apples', 'pears', 'plums']
Entities 80: ['Ada', 'Mel', 'Mya']
Entities 81: ['cantaloupes', 'watermelons', 'mangoes']
Entities 82: ['Amy', 'Ana', 'Joe']
Entities 83: ['Ada', 'Mel', 'Mya']
Entities 84: ['convertible', 'motorcyle', 'truck']
Entities 85: ['Ana', 'Dan', 'Mel']
Entities 86: ['convertible', 'limousine', 'bus']
Entities 87: ['green_book', 'red_book', 'blue_book']
Entities 88: ['peaches', 'pears', 'mangoes']
Entities 89: ['loquats', 'watermelons', 'cantaloupes']
Entities 90: ['robin', 'owl', 'hawk']
Entities 91: ['Eli', 'Mya', 'Eve']
Entities 92: ['oranges', 'mangoes', 'plums']
Entities 93: ['sedan', 'tractor', 'bus']
Entities 94: ['hummingbird', 'blue_jay', 'raven']
Entities 95: ['orange_book', 'white_book', 'purple_book']
Entities 96: ['Amy', 'Eli', 'Eve']
Entities 97: ['hawk', 'cardinal', 'falcon']
Entities 98: ['cantaloupes', 'oranges', 'watermelons']
Entities 99: ['robin', 'blue_jay', 'crow']
Entities 100: ['Ana', 'Mel', 'Ada']
Entities 101: ['hummingbird', 'owl', 'falcon']
Entities 102: ['sedan', 'minivan', 'motorcyle']
Entities 103: ['convertible', 'limousine', 'bus']
Entities 104: ['truck', 'minivan', 'tractor']
Entities 105: ['owl', 'crow', 'cardinal']
Entities 106: ['Eve', 'Joe', 'Amy']
Entities 107: ['red_book', 'blue_book', 'orange_book']
Entities 108: ['purple_book', 'black_book', 'blue_book']
Entities 109: ['raven', 'quail', 'crow']
Entities 110: ['robin', 'raven', 'quail']
Entities 111: ['hummingbird', 'blue_jay', 'raven']
Entities 112: ['Amy', 'Dan', 'Mel']
Entities 113: ['station_wagon', 'minivan', 'truck']
Entities 114: ['motorcyle', 'bus', 'tractor']
Entities 115: ['Joe', 'Dan', 'Eve']
Entities 116: ['apples', 'pears', 'loquats']
Entities 117: ['hatchback', 'convertible', 'tractor']
Entities 118: ['blue_jay', 'falcon', 'hummingbird']
Entities 119: ['minivan', 'bus', 'sedan']
Entities 120: ['cantaloupes', 'apples', 'loquats']
Entities 121: ['Eve', 'Rob', 'Mel']
Entities 122: ['white_book', 'black_book', 'purple_book']
Entities 123: ['Eve', 'Rob', 'Mel']
Entities 124: ['owl', 'crow', 'cardinal']
Entities 125: ['apples', 'pears', 'loquats']
Entities 126: ['green_book', 'red_book', 'blue_book']
Entities 127: ['orange_book', 'blue_book', 'yellow_book']
Entities 128: ['robin', 'raven', 'quail']
Entities 129: ['crow', 'falcon', 'raven']
Entities 130: ['Eli', 'Mya', 'Eve']
Entities 131: ['convertible', 'motorcyle', 'truck']
Entities 132: ['purple_book', 'red_book', 'yellow_book']
Entities 133: ['peaches', 'mangoes', 'apples']
Entities 134: ['blue_jay', 'falcon', 'raven']
Entities 135: ['loquats', 'mangoes', 'apples']
Entities 136: ['apples', 'peaches', 'mangoes']
Entities 137: ['plums', 'apples', 'loquats']
Entities 138: ['hummingbird', 'quail', 'crow']
Entities 139: ['Ana', 'Rob', 'Joe']
Entities 140: ['brown_book', 'yellow_book', 'orange_book']
Entities 141: ['pears', 'plums', 'kiwis']
Entities 142: ['owl', 'crow', 'cardinal']
Entities 143: ['yellow_book', 'brown_book', 'red_book']
Entities 144: ['Joe', 'Eve', 'Amy']
Entities 145: ['gray_book', 'orange_book', 'brown_book']
Entities 146: ['Amy', 'Ada', 'Joe']
Entities 147: ['peaches', 'pears', 'mangoes']
Entities 148: ['black_book', 'orange_book', 'blue_book']
Entities 149: ['motorcyle', 'limousine', 'convertible']
Entities 150: ['Ana', 'Rob', 'Joe']
Entities 151: ['kiwis', 'oranges', 'watermelons']
Entities 152: ['owl', 'crow', 'cardinal']
Entities 153: ['convertible', 'tractor', 'hatchback']
Entities 154: ['robin', 'blue_jay', 'crow']
Entities 155: ['limousine', 'truck', 'minivan']
Entities 156: ['hatchback', 'limousine', 'station_wagon']
Entities 157: ['yellow_book', 'brown_book', 'red_book']
Entities 158: ['black_book', 'orange_book', 'blue_book']
Entities 159: ['Eve', 'Amy', 'Rob']
Entities 160: ['cardinal', 'hawk', 'hummingbird']
Entities 161: ['oranges', 'watermelons', 'pears']
Entities 162: ['kiwis', 'oranges', 'watermelons']
Entities 163: ['Ana', 'Amy', 'Eli']
Entities 164: ['apples', 'pears', 'plums']
Entities 165: ['hummingbird', 'owl', 'falcon']
Entities 166: ['sedan', 'convertible', 'truck']
Entities 167: ['Amy', 'Ana', 'Joe']
Entities 168: ['crow', 'falcon', 'hummingbird']
Entities 169: ['pears', 'plums', 'kiwis']
Entities 170: ['Ana', 'Mel', 'Ada']
Entities 171: ['yellow_book', 'green_book', 'red_book']
Entities 172: ['yellow_book', 'brown_book', 'red_book']
Entities 173: ['loquats', 'watermelons', 'cantaloupes']
Entities 174: ['purple_book', 'black_book', 'blue_book']
Entities 175: ['Amy', 'Ada', 'Joe']
Entities 176: ['Joe', 'Eve', 'Amy']
Entities 177: ['station_wagon', 'truck', 'motorcyle']
Entities 178: ['convertible', 'limousine', 'bus']
Entities 179: ['hawk', 'cardinal', 'falcon']
Entities 180: ['limousine', 'truck', 'minivan']
Entities 181: ['bus', 'sedan', 'truck']
Entities 182: ['crow', 'falcon', 'hummingbird']
Entities 183: ['Ana', 'Dan', 'Mel']
Entities 184: ['station_wagon', 'truck', 'motorcyle']
Entities 185: ['Dan', 'Mel', 'Amy']
Entities 186: ['Eve', 'Amy', 'Rob']
Entities 187: ['cantaloupes', 'apples', 'loquats']
Entities 188: ['red_book', 'blue_book', 'orange_book']
Entities 189: ['robin', 'owl', 'hawk']
Entities 190: ['blue_book', 'orange_book', 'red_book']
Entities 191: ['falcon', 'owl', 'raven']
Entities 192: ['Rob', 'Mel', 'Joe']
Entities 193: ['watermelons', 'apples', 'mangoes']
Entities 194: ['Amy', 'Ada', 'Joe']
Entities 195: ['Ana', 'Amy', 'Eli']
Entities 196: ['sedan', 'convertible', 'truck']
Entities 197: ['limousine', 'truck', 'minivan']
Entities 198: ['cantaloupes', 'watermelons', 'mangoes']
Entities 199: ['Eve', 'Joe', 'Amy']
Entities 200: ['green_book', 'brown_book', 'orange_book']
Entities 201: ['peaches', 'pears', 'mangoes']
Entities 202: ['apples', 'peaches', 'loquats']
Entities 203: ['blue_jay', 'falcon', 'hummingbird']
Entities 204: ['crow', 'falcon', 'raven']
Entities 205: ['orange_book', 'blue_book', 'yellow_book']
Entities 206: ['peaches', 'pears', 'mangoes']
Entities 207: ['white_book', 'green_book', 'orange_book']
Entities 208: ['sedan', 'convertible', 'truck']
Entities 209: ['truck', 'minivan', 'tractor']
Entities 210: ['blue_jay', 'falcon', 'raven']
Entities 211: ['Ana', 'Rob', 'Joe']
Entities 212: ['green_book', 'brown_book', 'orange_book']
Entities 213: ['kiwis', 'loquats', 'cantaloupes']
Entities 214: ['oranges', 'watermelons', 'pears']
Entities 215: ['Rob', 'Mel', 'Joe']
Entities 216: ['raven', 'quail', 'crow']
Entities 217: ['cantaloupes', 'oranges', 'watermelons']
Entities 218: ['falcon', 'owl', 'raven']
Entities 219: ['tractor', 'station_wagon', 'limousine']
Entities 220: ['robin', 'raven', 'quail']
Entities 221: ['station_wagon', 'truck', 'motorcyle']
Entities 222: ['Dan', 'Mel', 'Amy']
Entities 223: ['blue_book', 'orange_book', 'green_book']
Entities 224: ['motorcyle', 'limousine', 'convertible']
Entities 225: ['Joe', 'Dan', 'Eve']
Entities 226: ['orange_book', 'yellow_book', 'blue_book']
Entities 227: ['Ana', 'Amy', 'Eli']
Entities 228: ['apples', 'pears', 'plums']
Entities 229: ['Eli', 'Mya', 'Eve']
Entities 230: ['robin', 'owl', 'hawk']
Entities 231: ['Mel', 'Ada', 'Ana']
Entities 232: ['orange_book', 'white_book', 'purple_book']
Entities 233: ['hawk', 'cardinal', 'falcon']
Entities 234: ['hummingbird', 'quail', 'crow']
Entities 235: ['yellow_book', 'green_book', 'red_book']
Entities 236: ['hummingbird', 'quail', 'crow']
Entities 237: ['sedan', 'minivan', 'motorcyle']
Entities 238: ['Rob', 'Mel', 'Joe']
Entities 239: ['hawk', 'crow', 'raven']
Entities 240: ['peaches', 'mangoes', 'apples']
Entities 241: ['hummingbird', 'owl', 'falcon']
Entities 242: ['gray_book', 'purple_book', 'red_book']
Entities 243: ['minivan', 'bus', 'sedan']
Entities 244: ['red_book', 'gray_book', 'white_book']
Entities 245: ['tractor', 'convertible', 'minivan']
Entities 246: ['orange_book', 'yellow_book', 'blue_book']
Entities 247: ['owl', 'crow', 'cardinal']
Entities 248: ['truck', 'minivan', 'tractor']
Entities 249: ['red_book', 'gray_book', 'white_book']
Entities 250: ['Ana', 'Rob', 'Joe']
Entities 251: ['quail', 'owl', 'raven', 'falcon', 'robin']
Entities 252: ['hatchback', 'bus', 'convertible', 'tractor', 'minivan']
Entities 253: ['yellow_book', 'green_book', 'gray_book', 'blue_book', 'orange_book']
Entities 254: ['raven', 'owl', 'cardinal', 'hummingbird', 'robin']
Entities 255: ['green_book', 'orange_book', 'gray_book', 'yellow_book', 'purple_book']
Entities 256: ['white_book', 'green_book', 'brown_book', 'gray_book', 'orange_book']
Entities 257: ['convertible', 'bus', 'minivan', 'truck', 'sedan']
Entities 258: ['Rob', 'Ada', 'Dan', 'Joe', 'Mel']
Entities 259: ['white_book', 'green_book', 'brown_book', 'gray_book', 'orange_book']
Entities 260: ['convertible', 'sedan', 'tractor', 'minivan', 'limousine']
Entities 261: ['kiwis', 'pears', 'peaches', 'loquats', 'apples']
Entities 262: ['oranges', 'cantaloupes', 'peaches', 'loquats', 'kiwis']
Entities 263: ['brown_book', 'yellow_book', 'orange_book', 'green_book', 'gray_book']
Entities 264: ['Ada', 'Eli', 'Amy', 'Joe', 'Mel']
Entities 265: ['watermelons', 'oranges', 'loquats', 'plums', 'kiwis']
Entities 266: ['yellow_book', 'gray_book', 'red_book', 'black_book', 'white_book']
Entities 267: ['hatchback', 'convertible', 'tractor', 'truck', 'limousine']
Entities 268: ['quail', 'owl', 'raven', 'falcon', 'robin']
Entities 269: ['Mel', 'Dan', 'Amy', 'Joe', 'Eve']
Entities 270: ['Rob', 'Amy', 'Joe', 'Eve', 'Dan']
Entities 271: ['watermelons', 'apples', 'mangoes', 'pears', 'cantaloupes']
Entities 272: ['truck', 'station_wagon', 'motorcycle', 'convertible', 'hatchback']
Entities 273: ['Ana', 'Rob', 'Amy', 'Dan', 'Joe']
Entities 274: ['bus', 'truck', 'motorcyle', 'sedan', 'hatchback']
Entities 275: ['yellow_book', 'brown_book', 'gray_book', 'black_book', 'purple_book']
Entities 276: ['watermelons', 'loquats', 'pears', 'plums', 'apples']
Entities 277: ['Amy', 'Mel', 'Rob', 'Joe', 'Ada']
Entities 278: ['Joe', 'Eve', 'Mya', 'Rob', 'Dan']
Entities 279: ['Amy', 'Mel', 'Rob', 'Joe', 'Ada']
Entities 280: ['Mel', 'Dan', 'Amy', 'Joe', 'Eve']
Entities 281: ['quail', 'hummingbird', 'blue_jay', 'hawk', 'robin']
Entities 282: ['quail', 'owl', 'raven', 'falcon', 'robin']
Entities 283: ['Dan', 'Mel', 'Ana', 'Eli', 'Rob']
Entities 284: ['gray_book', 'red_book', 'yellow_book', 'blue_book', 'orange_book']
Entities 285: ['Eve', 'Eli', 'Joe', 'Rob', 'Mya']
Entities 286: ['green_book', 'blue_book', 'brown_book', 'gray_book', 'red_book']
Entities 287: ['pears', 'mangoes', 'kiwis', 'oranges', 'peaches']
Entities 288: ['black_book', 'purple_book', 'yellow_book', 'orange_book', 'red_book']
Entities 289: ['Joe', 'Eve', 'Mya', 'Rob', 'Dan']
Entities 290: ['owl', 'cardinal', 'robin', 'hummingbird', 'crow']
Entities 291: ['hatchback', 'convertible', 'tractor', 'truck', 'limousine']
Entities 292: ['Ada', 'Eli', 'Amy', 'Joe', 'Mel']
Entities 293: ['owl', 'cardinal', 'robin', 'hummingbird', 'crow']
Entities 294: ['owl', 'crow', 'raven', 'robin', 'cardinal']
Entities 295: ['tractor', 'station_wagon', 'bus', 'motorcyle', 'minivan']
Entities 296: ['cardinal', 'crow', 'falcon', 'robin', 'blue_jay']
Entities 297: ['blue_jay', 'cardinal', 'hawk', 'hummingbird', 'quail']
Entities 298: ['convertible', 'truck', 'bus', 'sedan', 'motorcyle']
Entities 299: ['owl', 'crow', 'raven', 'robin', 'cardinal']
Entities 300: ['crow', 'falcon', 'hawk', 'robin', 'quail']
Entities 301: ['blue_book', 'red_book', 'purple_book', 'gray_book', 'white_book']
Entities 302: ['blue_book', 'purple_book', 'yellow_book', 'black_book', 'green_book']
Entities 303: ['apples', 'loquats', 'cantaloupes', 'watermelons', 'kiwis']
Entities 304: ['tractor', 'station_wagon', 'minivan', 'sedan', 'hatchback']
Entities 305: ['green_book', 'orange_book', 'gray_book', 'yellow_book', 'purple_book']
Entities 306: ['owl', 'hawk', 'robin', 'crow', 'raven']
Entities 307: ['Amy', 'Dan', 'Mya', 'Eli', 'Mel']
Entities 308: ['owl', 'hummingbird', 'crow', 'hawk', 'robin']
Entities 309: ['robin', 'quail', 'owl', 'crow', 'hawk']
Entities 310: ['hatchback', 'limousine', 'sedan', 'bus', 'tractor']
Entities 311: ['cardinal', 'robin', 'blue_jay', 'quail', 'raven']
Entities 312: ['sedan', 'convertible', 'station_wagon', 'bus', 'motorcyle']
Entities 313: ['green_book', 'blue_book', 'white_book', 'purple_book', 'yellow_book']
Entities 314: ['quail', 'owl', 'raven', 'falcon', 'robin']
Entities 315: ['gray_book', 'red_book', 'purple_book', 'blue_book', 'black_book']
Entities 316: ['brown_book', 'yellow_book', 'orange_book', 'green_book', 'gray_book']
Entities 317: ['tractor', 'station_wagon', 'minivan', 'sedan', 'hatchback']
Entities 318: ['owl', 'robin', 'blue_jay', 'hawk', 'hummingbird']
Entities 319: ['sedan', 'convertible', 'station_wagon', 'bus', 'motorcyle']
Entities 320: ['apples', ' mangoes', ' oranges', ' plums', ' pears']
Entities 321: ['brown_book', 'yellow_book', 'orange_book', 'green_book', 'gray_book']
Entities 322: ['oranges', 'apples', 'peaches', 'cantaloupes', 'loquats']
Entities 323: ['Amy', 'Eve', 'Mel', 'Mya', 'Rob']
Entities 324: ['convertible', 'sedan', 'station_wagon', 'bus', 'limousine']
Entities 325: ['mangoes', 'pears', 'cantaloupes', 'watermelons', 'loquats']
Entities 326: ['mangoes', 'pears', 'cantaloupes', 'watermelons', 'loquats']
Entities 327: ['owl', 'robin', 'blue_jay', 'hawk', 'hummingbird']
Entities 328: ['convertible', 'sedan', 'tractor', 'minivan', 'limousine']
Entities 329: ['Mel', 'Dan', 'Amy', 'Joe', 'Eve']
Entities 330: ['quail', 'hummingbird', 'blue_jay', 'hawk', 'robin']
Entities 331: ['blue_book', 'red_book', 'brown_book', 'yellow_book', 'orange_book']
Entities 332: ['yellow_book', 'brown_book', 'gray_book', 'black_book', 'purple_book']
Entities 333: ['watermelons', 'apples', 'mangoes', 'pears', 'cantaloupes']
Entities 334: ['Amy', 'Mel', 'Rob', 'Joe', 'Ada']
Entities 335: ['tractor', 'station_wagon', 'bus', 'motorcyle', 'minivan']
Entities 336: ['apples', 'oranges', 'watermelons', 'pears', 'mangoes']
Entities 337: ['station_wagon', 'sedan', 'tractor', 'motorcyle', 'limousine']
Entities 338: ['blue_book', 'red_book', 'purple_book', 'gray_book', 'white_book']
Entities 339: ['apples', 'oranges', 'watermelons', 'pears', 'mangoes']
Entities 340: ['green_book', 'orange_book', 'brown_book', 'yellow_book', 'blue_book']
Entities 341: ['black_book', 'brown_book', 'yellow_book', 'orange_book', 'red_book']
Entities 342: ['cardinal', 'robin', 'blue_jay', 'quail', 'raven']
Entities 343: ['Dan', 'Ana', 'Eli', 'Mya', 'Amy']
Entities 344: ['Rob', 'Ada', 'Dan', 'Joe', 'Mel']
Entities 345: ['cardinal', 'robin', 'blue_jay', 'quail', 'raven']
Entities 346: ['blue_book', 'purple_book', 'yellow_book', 'black_book', 'green_book']
Entities 347: ['falcon', 'raven', 'cardinal', 'hawk', 'crow']
Entities 348: ['oranges', 'cantaloupes', 'peaches', 'loquats', 'kiwis']
Entities 349: ['minivan', ' hatchback', ' bus', ' convertible', ' motorcyle']
Entities 350: ['raven', 'owl', 'cardinal', 'hummingbird', 'robin']
Entities 351: ['Eve', ' Rob', ' Ana', ' Eli', ' Mya']
Entities 352: ['truck', 'station_wagon', 'motorcyle', 'limousine', 'hatchback']
Entities 353: ['Joe', 'Ana', 'Amy', 'Mya', 'Eve']
Entities 354: ['limousine', 'sedan', 'bus', 'hatchback', 'motorcyle']
Entities 355: ['blue_book', 'red_book', 'purple_book', 'gray_book', 'white_book']
Entities 356: ['truck', 'station_wagon', 'motorcycle', 'convertible', 'hatchback']
Entities 357: ['crow', 'falcon', 'hawk', 'robin', 'quail']
Entities 358: ['minivan', ' hatchback', ' bus', ' convertible', ' motorcyle']
Entities 359: ['owl', 'cardinal', 'robin', 'hummingbird', 'crow']
Entities 360: ['station_wagon', 'tractor', 'truck', 'hatchback', 'minivan']
Entities 361: ['green_book', 'blue_book', 'white_book', 'purple_book', 'yellow_book']
Entities 362: ['minivan', ' hatchback', ' bus', ' convertible', ' motorcyle']
Entities 363: ['black_book', 'purple_book', 'yellow_book', 'orange_book', 'red_book']
Entities 364: ['crow', 'robin', 'quail', 'blue_jay', 'falcon']
Entities 365: ['station_wagon', 'sedan', 'tractor', 'motorcyle', 'limousine']
Entities 366: ['loquats', 'peaches', 'pears', 'plums', 'watermelons']
Entities 367: ['apples', 'oranges', 'watermelons', 'pears', 'mangoes']
Entities 368: ['raven', 'owl', 'cardinal', 'hummingbird', 'robin']
Entities 369: ['white_book', 'gray_book', 'purple_book', 'yellow_book', 'black_book']
Entities 370: ['Eve', 'Amy', 'Ada', 'Rob', 'Joe']

## 2. Comparing Generated Graphs with Ground Truths

In [22]:
ground_truths = pd.read_csv(r'C:\Users\Sudheera\OneDrive - University of Moratuwa\PhD\7.1. Dynamic graph buidling - final project\sample_questions_with_ground_truth.csv')
ground_truths

    sample_question_number                                 ground_truth_graph
0                        1  (blue_jay, precedes, falcon),(falcon, follows,...
1                        2  (limousine, precedes, motorcyle),(motorcyle, f...
2                        3  (blue_book, has_position_number, 3),(orange_bo...
3                        4  (crow, precedes, robin),(robin, follows, crow)...
4                        5  (red_book, has_position_number, 3),(green_book...
5                        6  (owl, has_position_number, 1),(robin, precedes...
6                        7  (tractor, precedes, bus),(bus, follows, tracto...
7                        8  (gray_book, precedes, green_book),(green_book,...
8                        9  (cardinal, has_position_number, 5),(raven, pre...
9                       10  (green_book, has_position_number, 5),(gray_boo...
10                      11  (Dan, has_position_number, 3),(Ana, precedes, ...
11                      12  (station_wagon, has_position_number, 4),(motor...
12                      13  (hummingbird, precedes, quail),(quail, follows...
13                      14  (hummingbird, precedes, falcon),(falcon, follo...
14                      15  (pears, has_position_number, 3),(kiwis, has_po...

In [23]:
def convert_string_to_triples(triples_string):
    # Use regex to find all patterns like (X, Y, Z)
    pattern = r'\(([^,]+),\s*([^,]+),\s*([^)]+)\)'
    matches = re.findall(pattern, triples_string)

    # Convert matches to list of tuples, stripping whitespace
    result = [(s.strip(), p.strip(), o.strip()) for s, p, o in matches]

    return result

ground_truths.loc[:, 'ground_truth_graph'] = ground_truths['ground_truth_graph'].apply(convert_string_to_triples)

ground_truths

    sample_question_number                                 ground_truth_graph
0                        1  [(blue_jay, precedes, falcon), (falcon, follow...
1                        2  [(limousine, precedes, motorcyle), (motorcyle,...
2                        3  [(blue_book, has_position_number, 3), (orange_...
3                        4  [(crow, precedes, robin), (robin, follows, cro...
4                        5  [(red_book, has_position_number, 3), (green_bo...
5                        6  [(owl, has_position_number, 1), (robin, preced...
6                        7  [(tractor, precedes, bus), (bus, follows, trac...
7                        8  [(gray_book, precedes, green_book), (green_boo...
8                        9  [(cardinal, has_position_number, 5), (raven, p...
9                       10  [(green_book, has_position_number, 5), (gray_b...
10                      11  [(Dan, has_position_number, 3), (Ana, precedes...
11                      12  [(station_wagon, has_position_number, 4), (mot...
12                      13  [(hummingbird, precedes, quail), (quail, follo...
13                      14  [(hummingbird, precedes, falcon), (falcon, fol...
14                      15  [(pears, has_position_number, 3), (kiwis, has_...

In [24]:
generated_graphs_list = []

for i, kg in enumerate(kg_list):
    triples_list = []
    for entry in kg.graph:
        triples_list.append((entry.entity_1, entry.edge, entry.entity_2))

    generated_graphs_list.append(
        {
            'question_number': i + 1,
            'generated_triples': triples_list,
        }
    )

generated_graphs_df = pd.DataFrame(generated_graphs_list)
generated_graphs_df

     question_number                                  generated_triples
0                  1  [(blue_jay, precedes, falcon), (falcon, follow...
1                  2  [(motorcyle, precedes, limousine), (limousine,...
2                  3  [(blue_book, has_position_number, 3), (orange_...
3                  4  [(crow, precedes, robin), (robin, follows, cro...
4                  5  [(red_book, has_position_number, 3), (green_bo...
..               ...                                                ...
745              746  [(Rob, has_position_number, 1), (Eve, has_posi...
746              747  [(cardinal, has_position_number, 6), (hawk, ha...
747              748  [(black_book, has_position_number, 6), (red_bo...
748              749  [(blue_jay, precedes, falcon), (falcon, follow...
749              750  [(truck, has_position_number, 1), (tractor, ha...

[750 rows x 2 columns]

In [25]:
merged_df = pd.merge(ground_truths, generated_graphs_df, left_on='sample_question_number', right_on='question_number', how='inner')
merged_df

,sample_question_number,ground_truth_graph,question_number,generated_triples
0,1,"[(blue_jay, precedes, falcon), (falcon, follow...",1,"[(blue_jay, precedes, falcon), (falcon, follow..."
1,2,"[(limousine, precedes, motorcyle), (motorcyle,...",2,"[(motorcyle, precedes, limousine), (limousine,..."
2,3,"[(blue_book, has_position_number, 3), (orange_...",3,"[(blue_book, has_position_number, 3), (orange_..."
3,4,"[(crow, precedes, robin), (robin, follows, cro...",4,"[(crow, precedes, robin), (robin, follows, cro..."
4,5,"[(red_book, has_position_number, 3), (green_bo...",5,"[(red_book, has_position_number, 3), (green_bo..."
5,6,"[(owl, has_position_number, 1), (robin, preced...",6,"[(mangoes, precedes, peaches), (peaches, follo..."
6,7,"[(tractor, precedes, bus), (bus, follows, trac...",7,"[(minivan, precedes, truck), (truck, follows, ..."
7,8,"[(gray_book, precedes, green_book), (green_boo...",8,"[(Mel, precedes, Rob), (Rob, follows, Mel), (E..."
8,9,"[(cardinal, has_position_number, 5), (raven, p...",9,"[(yellow_book, precedes, blue_book), (blue_boo..."
9,10,"[(green_book, has_position_number, 5), (gray_b...",10,"[(minivan, precedes, truck), (truck, follows, ..."
10,11,"[(Dan, has_position_number, 3), (Ana, precedes...",11,"[(purple_book, precedes, red_book), (red_book,..."
11,12,"[(station_wagon, has_position_number, 4), (mot...",12,"[(mangoes, has_position_number, 1), (apples, p..."
12,13,"[(hummingbird, precedes, quail), (quail, follo...",13,"[(falcon, precedes, blue_jay), (blue_jay, foll..."
13,14,"[(hummingbird, precedes, falcon), (falcon, fol...",14,"[(minivan, precedes, sedan), (sedan, follows, ..."
14,15,"[(pears, has_position_number, 3), (kiwis, has_...",15,"[(convertible, precedes, tractor), (tractor, f..."

In [26]:
def compare_triples(df):
    """
    Compare if all ground truth triples are present in the generated triples.

    Args:
        df: DataFrame containing 'ground_truth_graph' and 'generated_triples' columns

    Returns:
        DataFrame with new 'is_pass_graph' column (1 if passing, 0 if failing)
    """
    def check_if_all_triples_found(row):
        ground_truth = row['ground_truth_graph']
        generated = row['generated_triples']

        # Check if all ground truth triples exist in generated triples
        all_found = all(triple in generated for triple in ground_truth)

        return 1 if all_found else 0

    # Create a copy to avoid SettingWithCopyWarning
    result_df = df.copy()

    # Add the new column
    result_df['is_pass_graph'] = result_df.apply(check_if_all_triples_found, axis=1)

    return result_df

# Apply the function to your merged dataframe
graph_merged_df = compare_triples(merged_df)
graph_merged_df

,sample_question_number,ground_truth_graph,question_number,generated_triples,is_pass_graph
0,1,"[(blue_jay, precedes, falcon), (falcon, follow...",1,"[(blue_jay, precedes, falcon), (falcon, follow...",1
1,2,"[(limousine, precedes, motorcyle), (motorcyle,...",2,"[(motorcyle, precedes, limousine), (limousine,...",0
2,3,"[(blue_book, has_position_number, 3), (orange_...",3,"[(blue_book, has_position_number, 3), (orange_...",1
3,4,"[(crow, precedes, robin), (robin, follows, cro...",4,"[(crow, precedes, robin), (robin, follows, cro...",1
4,5,"[(red_book, has_position_number, 3), (green_bo...",5,"[(red_book, has_position_number, 3), (green_bo...",1
5,6,"[(owl, has_position_number, 1), (robin, preced...",6,"[(mangoes, precedes, peaches), (peaches, follo...",0
6,7,"[(tractor, precedes, bus), (bus, follows, trac...",7,"[(minivan, precedes, truck), (truck, follows, ...",0
7,8,"[(gray_book, precedes, green_book), (green_boo...",8,"[(Mel, precedes, Rob), (Rob, follows, Mel), (E...",0
8,9,"[(cardinal, has_position_number, 5), (raven, p...",9,"[(yellow_book, precedes, blue_book), (blue_boo...",0
9,10,"[(green_book, has_position_number, 5), (gray_b...",10,"[(minivan, precedes, truck), (truck, follows, ...",0
10,11,"[(Dan, has_position_number, 3), (Ana, precedes...",11,"[(purple_book, precedes, red_book), (red_book,...",0
11,12,"[(station_wagon, has_position_number, 4), (mot...",12,"[(mangoes, has_position_number, 1), (apples, p...",0
12,13,"[(hummingbird, precedes, quail), (quail, follo...",13,"[(falcon, precedes, blue_jay), (blue_jay, foll...",0
13,14,"[(hummingbird, precedes, falcon), (falcon, fol...",14,"[(minivan, precedes, sedan), (sedan, follows, ...",0
14,15,"[(pears, has_position_number, 3), (kiwis, has_...",15,"[(convertible, precedes, tractor), (tractor, f...",0

## 3. Enriching Generated Graphs by adding missing 'has_position_number'

In [27]:
def infer_missing_positions(triples, entities):
    from collections import defaultdict, deque
    from itertools import permutations

    # Normalization helper
    def norm(e):
        return e.strip().replace(" ", "_").lower()

    # Normalize all entity names
    entities = [norm(e) for e in entities]
    triples = [(norm(e1), rel, norm(e2)) for e1, rel, e2 in triples]

    # Parse anchors and order constraints
    precedes = defaultdict(list)
    follows = defaultdict(list)
    anchor_pos = {}
    for e1, rel, e2 in triples:
        if rel == "precedes":
            precedes[e1].append(e2)
            follows[e2].append(e1)
        elif rel == "follows":
            follows[e1].append(e2)
            precedes[e2].append(e1)
        elif rel == "has_position_number":
            anchor_pos[e1] = int(e2)

    n = len(entities)
    positions = list(range(1, n + 1))
    used_positions = set(anchor_pos.values())

    # Build directed graph for topological sorting
    indegree = {e: 0 for e in entities}
    for e in entities:
        for succ in precedes[e]:
            indegree[succ] += 1

    # Topological sort to get one valid ordering
    queue = deque([e for e in entities if indegree[e] == 0])
    topo_order = []
    seen = set()
    while queue:
        e = queue.popleft()
        if e in seen:
            continue
        seen.add(e)
        topo_order.append(e)
        for succ in precedes[e]:
            indegree[succ] -= 1
            if indegree[succ] == 0:
                queue.append(succ)
    for e in entities:
        if e not in seen:
            topo_order.append(e)

    # Place anchors in a slot array; None for missing
    slots = [None] * n
    entity_to_slot = {}
    for ent, pos in anchor_pos.items():
        slots[pos - 1] = ent
        entity_to_slot[ent] = pos - 1

    # Fill in the rest (try every permutation that fits)
    unanchored = [e for e in topo_order if e not in anchor_pos]
    unassigned_positions = [i for i in range(n) if slots[i] is None]

    # Brute-force search is feasible for small N; for large N, use backtracking.
    for perm in permutations(unanchored):
        test_slots = slots[:]
        for idx, e in zip(unassigned_positions, perm):
            test_slots[idx] = e
        # Now, verify all constraints
        valid = True
        pos_of = {e: i + 1 for i, e in enumerate(test_slots)}
        for a in entities:
            for b in precedes[a]:
                if pos_of[a] >= pos_of[b]:  # a must come before b
                    valid = False
                    break
            for b in follows[a]:
                if pos_of[a] <= pos_of[b]:  # a must come after b
                    valid = False
                    break
            if not valid:
                break
        if valid:
            # Found a valid assignment!
            final = [(e, "has_position_number", str(pos_of[e])) for e in entities]
            out_triples = [t for t in triples if t[1] != "has_position_number"] + final
            return out_triples
    raise ValueError("No valid assignment possible (conflicting anchors or edges)")

In [29]:
# Loop through the generated_triples in the merged_df and apply infer_missing_positions function
enriched_graphs_list = []

for i in range(len(kg_list)):
    generated_graph_object = kg_list[i]
    entities = entities_list[i]
    generated_triples = []
    for entry in generated_graph_object.graph:
        generated_triples.append((entry.entity_1, entry.edge, entry.entity_2))

    print(f"triples :- {generated_triples}")
    print(f"entities :- {entities}")
    try:
        enriched_triples = infer_missing_positions(generated_triples, entities)
    except:
        enriched_triples = generated_triples
    enriched_position_triples = []

    for j, (e1, rel, e2) in enumerate(enriched_triples):
        if rel in ['has_position_number']:
            enriched_position_triples.append((e1, rel, e2))

    enriched_graphs_list.append({
        'question_number': i+1,
        'enriched_triples': enriched_position_triples
    })

    print(f"Enriched Graph for Question {i+1}:")
    for triple in enriched_position_triples:
        print(f"({triple[0]}, {triple[1]}, {triple[2]})")
    print("-" * 40)

triples :- [('blue_jay', 'precedes', 'falcon'), ('falcon', 'follows', 'blue_jay'), ('quail', 'precedes', 'blue_jay'), ('blue_jay', 'follows', 'quail')]
entities :- ['blue_jay', 'quail', 'falcon']
Enriched Graph for Question 1:
(blue_jay, has_position_number, 2)
(quail, has_position_number, 1)
(falcon, has_position_number, 3)
----------------------------------------
triples :- [('motorcyle', 'precedes', 'limousine'), ('limousine', 'follows', 'motorcyle'), ('convertible', 'precedes', 'motorcyle'), ('motorcyle', 'follows', 'convertible')]
entities :- ['motorcyle', 'limousine', 'convertible']
Enriched Graph for Question 2:
(motorcyle, has_position_number, 2)
(limousine, has_position_number, 3)
(convertible, has_position_number, 1)
----------------------------------------
triples :- [('blue_book', 'has_position_number', '3'), ('orange_book', 'has_position_number', '1')]
entities :- ['blue_book', 'orange_book', 'red_book']
Enriched Graph for Question 3:
(blue_book, has_position_number, 3)
(orange_book, has_position_number, 1)
(red_book, has_position_number, 2)
----------------------------------------
triples :- [('crow', 'precedes', 'robin'), ('robin', 'follows', 'crow'), ('robin', 'precedes', 'blue_jay'), ('blue_jay', 'follows', 'robin')]
entities :- ['robin', 'blue_jay', 'crow']
Enriched Graph for Question 4:
(robin, has_position_number, 2)
(blue_jay, has_position_number, 3)
(crow, has_position_number, 1)
----------------------------------------
triples :- [('red_book', 'has_position_number', '3'), ('green_book', 'precedes', 'blue_book'), ('blue_book', 'follows', 'green_book')]
entities :- ['green_book', 'red_book', 'blue_book']
Enriched Graph for Question 5:
(green_book, has_position_number, 1)
(red_book, has_position_number, 3)
(blue_book, has_position_number, 2)
----------------------------------------
triples :- [('mangoes', 'precedes', 'peaches'), ('peaches', 'follows', 'mangoes'), ('apples', 'precedes', 'mangoes'), ('mangoes', 'follows', 'apples')]
entities :- ['apples', 'peaches', 'mangoes']
Enriched Graph for Question 6:
(apples, has_position_number, 1)
(peaches, has_position_number, 3)
(mangoes, has_position_number, 2)
----------------------------------------
triples :- [('minivan', 'precedes', 'truck'), ('truck', 'follows', 'minivan'), ('truck', 'precedes', 'tractor'), ('tractor', 'follows', 'truck')]
entities :- ['tractor', 'truck', 'minivan']
Enriched Graph for Question 7:
(tractor, has_position_number, 3)
(truck, has_position_number, 2)
(minivan, has_position_number, 1)
----------------------------------------
triples :- [('Mel', 'precedes', 'Rob'), ('Rob', 'follows', 'Mel'), ('Eve', 'precedes', 'Mel'), ('Mel', 'follows', 'Eve')]
entities :- ['Eve', 'Rob', 'Mel']
Enriched Graph for Question 8:
(eve, has_position_number, 1)
(rob, has_position_number, 3)
(mel, has_position_number, 2)
----------------------------------------
triples :- [('yellow_book', 'precedes', 'blue_book'), ('blue_book', 'follows', 'yellow_book'), ('orange_book', 'has_position_number', '2')]
entities :- ['orange_book', 'yellow_book', 'blue_book']
Enriched Graph for Question 9:
(orange_book, has_position_number, 2)
(yellow_book, has_position_number, 1)
(blue_book, has_position_number, 3)
----------------------------------------
triples :- [('minivan', 'precedes', 'truck'), ('truck', 'follows', 'minivan'), ('station_wagon', 'precedes', 'minivan'), ('minivan', 'follows', 'station_wagon')]
entities :- ['station_wagon', 'minivan', 'truck']
Enriched Graph for Question 10:
(station_wagon, has_position_number, 1)
(minivan, has_position_number, 2)
(truck, has_position_number, 3)
----------------------------------------
triples :- [('purple_book', 'precedes', 'red_book'), ('red_book', 'follows', 'purple_book'), ('gray_book', 'precedes', 'purple_book'), ('purple_book', 'follows', 'gray_book')]
entities :- ['gray_book', 'purple_book', 'red_book']
Enriched Graph for Question 11:
(gray_book, has_position_number, 1)
(purple_book, has_position_number, 2)
(red_book, has_position_number, 3)
----------------------------------------
triples :- [('mangoes', 'has_position_number', '1'), ('apples', 'precedes', 'peaches'), ('peaches', 'follows', 'apples')]
entities :- ['peaches', 'mangoes', 'apples']
Enriched Graph for Question 12:
(peaches, has_position_number, 3)
(mangoes, has_position_number, 1)
(apples, has_position_number, 2)
----------------------------------------
triples :- [('falcon', 'precedes', 'blue_jay'), ('blue_jay', 'follows', 'falcon'), ('hummingbird', 'precedes', 'falcon'), ('falcon', 'follows', 'hummingbird')]
entities :- ['blue_jay', 'falcon', 'hummingbird']
Enriched Graph for Question 13:
(blue_jay, has_position_number, 3)
(falcon, has_position_number, 2)
(hummingbird, has_position_number, 1)
----------------------------------------
triples :- [('minivan', 'precedes', 'sedan'), ('sedan', 'follows', 'minivan'), ('bus', 'precedes', 'minivan'), ('minivan', 'follows', 'bus')]
entities :- ['minivan', 'bus', 'sedan']
Enriched Graph for Question 14:
(minivan, has_position_number, 2)
(bus, has_position_number, 1)
(sedan, has_position_number, 3)
----------------------------------------
triples :- [('convertible', 'precedes', 'tractor'), ('tractor', 'follows', 'convertible'), ('hatchback', 'has_position_number', '2')]
entities :- ['hatchback', 'convertible', 'tractor']
Enriched Graph for Question 15:
(hatchback, has_position_number, 2)
(convertible, has_position_number, 1)
(tractor, has_position_number, 3)
----------------------------------------
triples :- [('watermelons', 'has_position_number', '2'), ('loquats', 'follows', 'cantaloupes'), ('cantaloupes', 'precedes', 'loquats')]
entities :- ['loquats', 'watermelons', 'cantaloupes']
Enriched Graph for Question 16:
(loquats, has_position_number, 3)
(watermelons, has_position_number, 2)
(cantaloupes, has_position_number, 1)
----------------------------------------
triples :- [('watermelons', 'precedes', 'kiwis'), ('kiwis', 'follows', 'watermelons'), ('kiwis', 'has_position_number', '2')]
entities :- ['mangoes', 'watermelons', 'kiwis']
Enriched Graph for Question 17:
(mangoes, has_position_number, 3)
(watermelons, has_position_number, 1)
(kiwis, has_position_number, 2)
----------------------------------------
triples :- [('blue_book', 'has_position_number', '3'), ('orange_book', 'has_position_number', '1'), ('orange_book', 'precedes', 'red_book'), ('red_book', 'follows', 'orange_book'), ('red_book', 'precedes', 'blue_book'), ('blue_book', 'follows', 'red_book')]
entities :- ['blue_book', 'orange_book', 'red_book']
Enriched Graph for Question 18:
(blue_book, has_position_number, 3)
(orange_book, has_position_number, 1)
(red_book, has_position_number, 2)
----------------------------------------
triples :- [('Ada', 'precedes', 'Mya'), ('Mya', 'follows', 'Ada'), ('Mel', 'precedes', 'Ada'), ('Ada', 'follows', 'Mel')]
entities :- ['Ada', 'Mel', 'Mya']
Enriched Graph for Question 19:
(ada, has_position_number, 2)
(mel, has_position_number, 1)
(mya, has_position_number, 3)
----------------------------------------
triples :- [('Mel', 'has_position_number', '3'), ('Ana', 'has_position_number', '2')]
entities :- ['Mel', 'Ada', 'Ana']
Enriched Graph for Question 20:
(mel, has_position_number, 3)
(ada, has_position_number, 1)
(ana, has_position_number, 2)
----------------------------------------
triples :- [('loquats', 'has_position_number', '1'), ('plums', 'precedes', 'apples'), ('apples', 'follows', 'plums')]
entities :- ['plums', 'apples', 'loquats']
Enriched Graph for Question 21:
(plums, has_position_number, 2)
(apples, has_position_number, 3)
(loquats, has_position_number, 1)
----------------------------------------
triples :- [('orange_book', 'precedes', 'blue_book'), ('blue_book', 'follows', 'orange_book'), ('black_book', 'precedes', 'orange_book'), ('orange_book', 'follows', 'black_book')]
entities :- ['black_book', 'orange_book', 'blue_book']
Enriched Graph for Question 22:
(black_book, has_position_number, 1)
(orange_book, has_position_number, 2)
(blue_book, has_position_number, 3)
----------------------------------------
triples :- [('motorcyle', 'precedes', 'convertible'), ('convertible', 'follows', 'motorcyle'), ('convertible', 'precedes', 'truck'), ('truck', 'follows', 'convertible')]
entities :- ['convertible', 'motorcyle', 'truck']
Enriched Graph for Question 23:
(convertible, has_position_number, 2)
(motorcyle, has_position_number, 1)
(truck, has_position_number, 3)
----------------------------------------
triples :- [('mangoes', 'precedes', 'peaches'), ('peaches', 'follows', 'mangoes'), ('apples', 'precedes', 'mangoes'), ('mangoes', 'follows', 'apples')]
entities :- ['apples', 'peaches', 'mangoes']
Enriched Graph for Question 24:
(apples, has_position_number, 1)
(peaches, has_position_number, 3)
(mangoes, has_position_number, 2)
----------------------------------------
triples :- [('Amy', 'precedes', 'Eve'), ('Eve', 'follows', 'Amy'), ('Eve', 'precedes', 'Joe'), ('Joe', 'follows', 'Eve')]
entities :- ['Eve', 'Joe', 'Amy']
Enriched Graph for Question 25:
(eve, has_position_number, 2)
(joe, has_position_number, 3)
(amy, has_position_number, 1)
----------------------------------------
triples :- [('Eli', 'precedes', 'Eve'), ('Eve', 'follows', 'Eli'), ('Eve', 'precedes', 'Mya'), ('Mya', 'follows', 'Eve')]
entities :- ['Eli', 'Mya', 'Eve']
Enriched Graph for Question 26:
(eli, has_position_number, 1)
(mya, has_position_number, 3)
(eve, has_position_number, 2)
----------------------------------------
triples :- [('mangoes', 'precedes', 'peaches'), ('peaches', 'follows', 'mangoes'), ('pears', 'precedes', 'mangoes'), ('mangoes', 'follows', 'pears')]
entities :- ['peaches', 'pears', 'mangoes']
Enriched Graph for Question 27:
(peaches, has_position_number, 3)
(pears, has_position_number, 1)
(mangoes, has_position_number, 2)
----------------------------------------
triples :- [('convertible', 'precedes', 'tractor'), ('tractor', 'follows', 'convertible'), ('hatchback', 'has_position_number', '2')]
entities :- ['hatchback', 'convertible', 'tractor']
Enriched Graph for Question 28:
(hatchback, has_position_number, 2)
(convertible, has_position_number, 1)
(tractor, has_position_number, 3)
----------------------------------------
triples :- [('hummingbird', 'precedes', 'blue_jay'), ('blue_jay', 'follows', 'hummingbird'), ('raven', 'has_position_number', '2')]
entities :- ['hummingbird', 'blue_jay', 'raven']
Enriched Graph for Question 29:
(hummingbird, has_position_number, 1)
(blue_jay, has_position_number, 3)
(raven, has_position_number, 2)
----------------------------------------
triples :- [('yellow_book', 'precedes', 'purple_book'), ('purple_book', 'follows', 'yellow_book'), ('red_book', 'precedes', 'yellow_book'), ('yellow_book', 'follows', 'red_book')]
entities :- ['purple_book', 'red_book', 'yellow_book']
Enriched Graph for Question 30:
(purple_book, has_position_number, 3)
(red_book, has_position_number, 1)
(yellow_book, has_position_number, 2)
----------------------------------------
triples :- [('apples', 'precedes', 'mangoes'), ('mangoes', 'follows', 'apples'), ('mangoes', 'precedes', 'watermelons'), ('watermelons', 'follows', 'mangoes')]
entities :- ['watermelons', 'apples', 'mangoes']
Enriched Graph for Question 31:
(watermelons, has_position_number, 3)
(apples, has_position_number, 1)
(mangoes, has_position_number, 2)
----------------------------------------
triples :- [('Mel', 'precedes', 'Amy'), ('Amy', 'follows', 'Mel'), ('Amy', 'precedes', 'Dan'), ('Dan', 'follows', 'Amy')]
entities :- ['Amy', 'Dan', 'Mel']
Enriched Graph for Question 32:
(amy, has_position_number, 2)
(dan, has_position_number, 3)
(mel, has_position_number, 1)
----------------------------------------
triples :- [('motorcyle', 'has_position_number', '1'), ('bus', 'precedes', 'tractor'), ('tractor', 'follows', 'bus')]
entities :- ['motorcyle', 'bus', 'tractor']
Enriched Graph for Question 33:
(motorcyle, has_position_number, 1)
(bus, has_position_number, 2)
(tractor, has_position_number, 3)
----------------------------------------
triples :- [('red_book', 'precedes', 'orange_book'), ('orange_book', 'follows', 'red_book'), ('orange_book', 'has_position_number', '2')]
entities :- ['red_book', 'blue_book', 'orange_book']
Enriched Graph for Question 34:
(red_book, has_position_number, 1)
(blue_book, has_position_number, 3)
(orange_book, has_position_number, 2)
----------------------------------------
triples :- [('minivan', 'precedes', 'tractor'), ('tractor', 'follows', 'minivan'), ('minivan', 'has_position_number', '2')]
entities :- ['motorcyle', 'minivan', 'tractor']
Enriched Graph for Question 35:
(motorcyle, has_position_number, 1)
(minivan, has_position_number, 2)
(tractor, has_position_number, 3)
----------------------------------------
triples :- [('truck', 'precedes', 'bus'), ('bus', 'follows', 'truck'), ('bus', 'precedes', 'sedan'), ('sedan', 'follows', 'bus')]
entities :- ['bus', 'sedan', 'truck']
Enriched Graph for Question 36:
(bus, has_position_number, 2)
(sedan, has_position_number, 3)
(truck, has_position_number, 1)
----------------------------------------
triples :- [('apples', 'precedes', 'mangoes'), ('mangoes', 'follows', 'apples'), ('mangoes', 'precedes', 'loquats'), ('loquats', 'follows', 'mangoes')]
entities :- ['loquats', 'mangoes', 'apples']
Enriched Graph for Question 37:
(loquats, has_position_number, 3)
(mangoes, has_position_number, 2)
(apples, has_position_number, 1)
----------------------------------------
triples :- [('blue_jay', 'precedes', 'falcon'), ('falcon', 'follows', 'blue_jay'), ('quail', 'precedes', 'blue_jay'), ('blue_jay', 'follows', 'quail')]
entities :- ['blue_jay', 'quail', 'falcon']
Enriched Graph for Question 38:
(blue_jay, has_position_number, 2)
(quail, has_position_number, 1)
(falcon, has_position_number, 3)
----------------------------------------
triples :- [('hawk', 'precedes', 'raven'), ('raven', 'follows', 'hawk'), ('crow', 'has_position_number', '3')]
entities :- ['hawk', 'crow', 'raven']
Enriched Graph for Question 39:
(hawk, has_position_number, 1)
(crow, has_position_number, 3)
(raven, has_position_number, 2)
----------------------------------------
triples :- [('yellow_book', 'has_position_number', '1'), ('brown_book', 'precedes', 'orange_book'), ('orange_book', 'follows', 'brown_book')]
entities :- ['brown_book', 'yellow_book', 'orange_book']
Enriched Graph for Question 40:
(brown_book, has_position_number, 2)
(yellow_book, has_position_number, 1)
(orange_book, has_position_number, 3)
----------------------------------------
triples :- [('mangoes', 'precedes', 'apples'), ('apples', 'follows', 'mangoes'), ('loquats', 'precedes', 'mangoes'), ('mangoes', 'follows', 'loquats')]
entities :- ['loquats', 'mangoes', 'apples']
Enriched Graph for Question 41:
(loquats, has_position_number, 1)
(mangoes, has_position_number, 2)
(apples, has_position_number, 3)
----------------------------------------
triples :- [('oranges', 'has_position_number', '3'), ('cantaloupes', 'precedes', 'oranges'), ('watermelons', 'precedes', 'cantaloupes'), ('cantaloupes', 'follows', 'watermelons'), ('cantaloupes', 'follows', 'watermelons')]
entities :- ['cantaloupes', 'oranges', 'watermelons']
Enriched Graph for Question 42:
(cantaloupes, has_position_number, 2)
(oranges, has_position_number, 3)
(watermelons, has_position_number, 1)
----------------------------------------
triples :- [('loquats', 'precedes', 'apples'), ('apples', 'follows', 'loquats'), ('apples', 'precedes', 'peaches'), ('peaches', 'follows', 'apples')]
entities :- ['apples', 'peaches', 'loquats']
Enriched Graph for Question 43:
(apples, has_position_number, 2)
(peaches, has_position_number, 3)
(loquats, has_position_number, 1)
----------------------------------------
triples :- [('owl', 'has_position_number', '2'), ('crow', 'precedes', 'owl'), ('owl', 'follows', 'crow'), ('cardinal', 'follows', 'owl'), ('owl', 'precedes', 'cardinal'), ('crow', 'has_position_number', '1'), ('cardinal', 'has_position_number', '3')]
entities :- ['owl', 'crow', 'cardinal']
Enriched Graph for Question 44:
(owl, has_position_number, 2)
(crow, has_position_number, 1)
(cardinal, has_position_number, 3)
----------------------------------------
triples :- [('oranges', 'precedes', 'plums'), ('plums', 'follows', 'oranges'), ('plums', 'precedes', 'mangoes'), ('mangoes', 'follows', 'plums')]
entities :- ['oranges', 'mangoes', 'plums']
Enriched Graph for Question 45:
(oranges, has_position_number, 1)
(mangoes, has_position_number, 3)
(plums, has_position_number, 2)
----------------------------------------
triples :- [('quail', 'precedes', 'owl'), ('owl', 'follows', 'quail'), ('owl', 'precedes', 'hummingbird'), ('hummingbird', 'follows', 'owl')]
entities :- ['quail', 'owl', 'hummingbird']
Enriched Graph for Question 46:
(quail, has_position_number, 1)
(owl, has_position_number, 2)
(hummingbird, has_position_number, 3)
----------------------------------------
triples :- [('oranges', 'has_position_number', '2'), ('watermelons', 'precedes', 'pears'), ('pears', 'follows', 'watermelons')]
entities :- ['oranges', 'watermelons', 'pears']
Enriched Graph for Question 47:
(oranges, has_position_number, 2)
(watermelons, has_position_number, 1)
(pears, has_position_number, 3)
----------------------------------------
triples :- [('Ada', 'precedes', 'Ana'), ('Ana', 'follows', 'Ada'), ('Ana', 'precedes', 'Mel'), ('Mel', 'follows', 'Ana')]
entities :- ['Ana', 'Mel', 'Ada']
Enriched Graph for Question 48:
(ana, has_position_number, 2)
(mel, has_position_number, 3)
(ada, has_position_number, 1)
----------------------------------------
triples :- [('sedan', 'precedes', 'tractor'), ('tractor', 'follows', 'sedan'), ('bus', 'precedes', 'sedan'), ('sedan', 'follows', 'bus')]
entities :- ['sedan', 'tractor', 'bus']
Enriched Graph for Question 49:
(sedan, has_position_number, 2)
(tractor, has_position_number, 3)
(bus, has_position_number, 1)
----------------------------------------
triples :- [('brown_book', 'precedes', 'orange_book'), ('orange_book', 'follows', 'brown_book'), ('green_book', 'precedes', 'brown_book'), ('brown_book', 'follows', 'green_book')]
entities :- ['green_book', 'brown_book', 'orange_book']
Enriched Graph for Question 50:
(green_book, has_position_number, 1)
(brown_book, has_position_number, 2)
(orange_book, has_position_number, 3)
----------------------------------------
triples :- [('orange_book', 'precedes', 'blue_book'), ('blue_book', 'follows', 'orange_book'), ('blue_book', 'precedes', 'yellow_book'), ('yellow_book', 'follows', 'blue_book')]
entities :- ['orange_book', 'blue_book', 'yellow_book']
Enriched Graph for Question 51:
(orange_book, has_position_number, 1)
(blue_book, has_position_number, 2)
(yellow_book, has_position_number, 3)
----------------------------------------
triples :- [('plums', 'precedes', 'mangoes'), ('mangoes', 'follows', 'plums'), ('oranges', 'precedes', 'plums'), ('plums', 'follows', 'oranges')]
entities :- ['oranges', 'mangoes', 'plums']
Enriched Graph for Question 52:
(oranges, has_position_number, 1)
(mangoes, has_position_number, 3)
(plums, has_position_number, 2)
----------------------------------------
triples :- [('purple_book', 'precedes', 'red_book'), ('red_book', 'follows', 'purple_book'), ('gray_book', 'precedes', 'purple_book'), ('purple_book', 'follows', 'gray_book')]
entities :- ['gray_book', 'purple_book', 'red_book']
Enriched Graph for Question 53:
(gray_book, has_position_number, 1)
(purple_book, has_position_number, 2)
(red_book, has_position_number, 3)
----------------------------------------
triples :- [('minivan', 'has_position_number', '2'), ('minivan', 'precedes', 'tractor'), ('tractor', 'follows', 'minivan')]
entities :- ['motorcyle', 'minivan', 'tractor']
Enriched Graph for Question 54:
(motorcyle, has_position_number, 1)
(minivan, has_position_number, 2)
(tractor, has_position_number, 3)
----------------------------------------

## 4. Getting the final answers

In [30]:
final_answer_prompt_system = """
<role>
    You are an expert in logical reasoning and information extraction for natural language questions about ordered entities.
    Your job is to analyze a list of position triples that describe how items are ranked or ordered according to a stated quality,
    and then select the correct natural language statement from a list of options that matches the ordering facts.
  </role>

  <behavior>
    <rule name="Map-positions">
      Interpret each triple of the form (item, has_position_number, k) using the provided quality.
      The meaning of position number k depends on the direction of the quality. For example, if the quality is "cheapest to most expensive", position 1 means "cheapest", 2 means "second-cheapest", etc.
    </rule>

    <rule name="Option-matching">
      For each option, compare the natural language statement with the entity's actual position from the triples, as defined by the quality used to order. Only one option will exactly match the information in the triples.
    </rule>

    <rule name="No-assumptions">
      Do not make any assumptions beyond the given position triples and the provided quality. Use only the explicit data.
    </rule>
  </behavior>

  <format>
    1. Produce a detailed, step-by-step reasoning section that:
       - Explains how each triple is interpreted given the quality used to order,
       - Walks through each option, comparing its claim to the relevant position from the triples,
       - Clearly identifies the option that is supported by the triples.
    2. Then print this heading on its own line (exactly as written):
       ### FINAL ANSWER
    3. On the very next line, output ONLY the correct option letter in parentheses, e.g. (F)
    4. End without adding anything after that word.
  </format>
"""

final_answer_prompt_human = """
<quality used to order>
{quality_used_to_order}
</quality used to order>

<position triples>
{position_triples}
</position triples>

<options>
{options}
</options>
"""

In [31]:
final_answer_prompt = ChatPromptTemplate(
    [("system", final_answer_prompt_system),
     ("human", final_answer_prompt_human)]
)

final_answers_list = []

final_answer_chain = final_answer_prompt | llm_model | StrOutputParser()

# batch questions to pass to the LLM
final_questions_batch = []

print(len(enriched_graphs_list))
print(len(options))

for i in range(len(enriched_graphs_list)):
    enriched_triples = enriched_graphs_list[i]['enriched_triples']

    final_questions_batch.append({
        "position_triples": "\n".join([f"({e1}, {rel}, {e2})" for e1, rel, e2 in enriched_triples]),
        "options": options[i],
        "quality_used_to_order": ordering_quality_list[i]
    })

i = 0
for batch in final_questions_batch:
    print(f"Batch Question : {i + 1}")
    print(f"Position Triples: {batch['position_triples']}")
    print("\n")
    print(f"Options: {batch['options']}")
    print("\n")
    print(f"Quality Used to Order: {batch['quality_used_to_order']}")
    print("-" * 40)
    i += 1

750
750
Batch Question : 1
Position Triples: (blue_jay, has_position_number, 2)
(quail, has_position_number, 1)
(falcon, has_position_number, 3)


Options: (A) The blue jay is the second from the left
(B) The quail is the second from the left
(C) The falcon is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 2
Position Triples: (motorcyle, has_position_number, 2)
(limousine, has_position_number, 3)
(convertible, has_position_number, 1)


Options: (A) The motorcyle is the oldest
(B) The limousine is the oldest
(C) The convertible is the oldest


Quality Used to Order: newest to oldest
----------------------------------------
Batch Question : 3
Position Triples: (blue_book, has_position_number, 3)
(orange_book, has_position_number, 1)
(red_book, has_position_number, 2)


Options: (A) The blue book is the second from the left
(B) The orange book is the second from the left
(C) The red book is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 4
Position Triples: (robin, has_position_number, 2)
(blue_jay, has_position_number, 3)
(crow, has_position_number, 1)


Options: (A) The robin is the rightmost
(B) The blue jay is the rightmost
(C) The crow is the rightmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 5
Position Triples: (green_book, has_position_number, 1)
(red_book, has_position_number, 3)
(blue_book, has_position_number, 2)


Options: (A) The green book is the rightmost
(B) The red book is the rightmost
(C) The blue book is the rightmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 6
Position Triples: (apples, has_position_number, 1)
(peaches, has_position_number, 3)
(mangoes, has_position_number, 2)


Options: (A) The apples are the second-most expensive
(B) The peaches are the second-most expensive
(C) The mangoes are the second-most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 7
Position Triples: (tractor, has_position_number, 3)
(truck, has_position_number, 2)
(minivan, has_position_number, 1)


Options: (A) The tractor is the newest
(B) The truck is the newest
(C) The minivan is the newest


Quality Used to Order: newest to oldest
----------------------------------------
Batch Question : 8
Position Triples: (eve, has_position_number, 1)
(rob, has_position_number, 3)
(mel, has_position_number, 2)


Options: (A) Eve finished first
(B) Rob finished first
(C) Mel finished first


Quality Used to Order: highest to lowest rank
----------------------------------------
Batch Question : 9
Position Triples: (orange_book, has_position_number, 2)
(yellow_book, has_position_number, 1)
(blue_book, has_position_number, 3)


Options: (A) The orange book is the second from the left
(B) The yellow book is the second from the left
(C) The blue book is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 10
Position Triples: (station_wagon, has_position_number, 1)
(minivan, has_position_number, 2)
(truck, has_position_number, 3)


Options: (A) The station wagon is the newest
(B) The minivan is the newest
(C) The truck is the newest


Quality Used to Order: newest to oldest
----------------------------------------
Batch Question : 11
Position Triples: (gray_book, has_position_number, 1)
(purple_book, has_position_number, 2)
(red_book, has_position_number, 3)


Options: (A) The gray book is the leftmost
(B) The purple book is the leftmost
(C) The red book is the leftmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 12
Position Triples: (peaches, has_position_number, 3)
(mangoes, has_position_number, 1)
(apples, has_position_number, 2)


Options: (A) The peaches are the second-most expensive
(B) The mangoes are the second-most expensive
(C) The apples are the second-most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 13
Position Triples: (blue_jay, has_position_number, 3)
(falcon, has_position_number, 2)
(hummingbird, has_position_number, 1)


Options: (A) The blue jay is the second from the left
(B) The falcon is the second from the left
(C) The hummingbird is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 14
Position Triples: (minivan, has_position_number, 2)
(bus, has_position_number, 1)
(sedan, has_position_number, 3)


Options: (A) The minivan is the second-newest
(B) The bus is the second-newest
(C) The sedan is the second-newest


Quality Used to Order: newest to oldest
----------------------------------------
Batch Question : 15
Position Triples: (hatchback, has_position_number, 2)
(convertible, has_position_number, 1)
(tractor, has_position_number, 3)


Options: (A) The hatchback is the second-newest
(B) The convertible is the second-newest
(C) The tractor is the second-newest


Quality Used to Order: oldest to newest
----------------------------------------
Batch Question : 16
Position Triples: (loquats, has_position_number, 3)
(watermelons, has_position_number, 2)
(cantaloupes, has_position_number, 1)


Options: (A) The loquats are the most expensive
(B) The watermelons are the most expensive
(C) The cantaloupes are the most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 17
Position Triples: (mangoes, has_position_number, 3)
(watermelons, has_position_number, 1)
(kiwis, has_position_number, 2)


Options: (A) The mangoes are the most expensive
(B) The watermelons are the most expensive
(C) The kiwis are the most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 18
Position Triples: (blue_book, has_position_number, 3)
(orange_book, has_position_number, 1)
(red_book, has_position_number, 2)


Options: (A) The blue book is the rightmost
(B) The orange book is the rightmost
(C) The red book is the rightmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 19
Position Triples: (ada, has_position_number, 2)
(mel, has_position_number, 1)
(mya, has_position_number, 3)


Options: (A) Ada finished last
(B) Mel finished last
(C) Mya finished last


Quality Used to Order: highest to lowest finish
----------------------------------------
Batch Question : 20
Position Triples: (mel, has_position_number, 3)
(ada, has_position_number, 1)
(ana, has_position_number, 2)


Options: (A) Mel finished last
(B) Ada finished last
(C) Ana finished last


Quality Used to Order: first to last
----------------------------------------
Batch Question : 21
Position Triples: (plums, has_position_number, 2)
(apples, has_position_number, 3)
(loquats, has_position_number, 1)


Options: (A) The plums are the cheapest
(B) The apples are the cheapest
(C) The loquats are the cheapest


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 22
Position Triples: (black_book, has_position_number, 1)
(orange_book, has_position_number, 2)
(blue_book, has_position_number, 3)


Options: (A) The black book is the second from the left
(B) The orange book is the second from the left
(C) The blue book is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 23
Position Triples: (convertible, has_position_number, 2)
(motorcyle, has_position_number, 1)
(truck, has_position_number, 3)


Options: (A) The convertible is the oldest
(B) The motorcyle is the oldest
(C) The truck is the oldest


Quality Used to Order: newest to oldest
----------------------------------------
Batch Question : 24
Position Triples: (apples, has_position_number, 1)
(peaches, has_position_number, 3)
(mangoes, has_position_number, 2)


Options: (A) The apples are the cheapest
(B) The peaches are the cheapest
(C) The mangoes are the cheapest


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 25
Position Triples: (eve, has_position_number, 2)
(joe, has_position_number, 3)
(amy, has_position_number, 1)


Options: (A) Eve finished first
(B) Joe finished first
(C) Amy finished first


Quality Used to Order: highest to lowest rank
----------------------------------------
Batch Question : 26
Position Triples: (eli, has_position_number, 1)
(mya, has_position_number, 3)
(eve, has_position_number, 2)


Options: (A) Eli finished second
(B) Mya finished second
(C) Eve finished second


Quality Used to Order: highest to lowest rank
----------------------------------------
Batch Question : 27
Position Triples: (peaches, has_position_number, 3)
(pears, has_position_number, 1)
(mangoes, has_position_number, 2)


Options: (A) The peaches are the most expensive
(B) The pears are the most expensive
(C) The mangoes are the most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 28
Position Triples: (hatchback, has_position_number, 2)
(convertible, has_position_number, 1)
(tractor, has_position_number, 3)


Options: (A) The hatchback is the oldest
(B) The convertible is the oldest
(C) The tractor is the oldest


Quality Used to Order: oldest to newest
----------------------------------------
Batch Question : 29
Position Triples: (hummingbird, has_position_number, 1)
(blue_jay, has_position_number, 3)
(raven, has_position_number, 2)


Options: (A) The hummingbird is the rightmost
(B) The blue jay is the rightmost
(C) The raven is the rightmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 30
Position Triples: (purple_book, has_position_number, 3)
(red_book, has_position_number, 1)
(yellow_book, has_position_number, 2)


Options: (A) The purple book is the rightmost
(B) The red book is the rightmost
(C) The yellow book is the rightmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 31
Position Triples: (watermelons, has_position_number, 3)
(apples, has_position_number, 1)
(mangoes, has_position_number, 2)


Options: (A) The watermelons are the second-most expensive
(B) The apples are the second-most expensive
(C) The mangoes are the second-most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 32
Position Triples: (amy, has_position_number, 2)
(dan, has_position_number, 3)
(mel, has_position_number, 1)


Options: (A) Amy finished first
(B) Dan finished first
(C) Mel finished first


Quality Used to Order: highest to lowest rank
----------------------------------------
Batch Question : 33
Position Triples: (motorcyle, has_position_number, 1)
(bus, has_position_number, 2)
(tractor, has_position_number, 3)


Options: (A) The motorcyle is the second-newest
(B) The bus is the second-newest
(C) The tractor is the second-newest


Quality Used to Order: oldest to newest
----------------------------------------
Batch Question : 34
Position Triples: (red_book, has_position_number, 1)
(blue_book, has_position_number, 3)
(orange_book, has_position_number, 2)


Options: (A) The red book is the second from the left
(B) The blue book is the second from the left
(C) The orange book is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 35
Position Triples: (motorcyle, has_position_number, 1)
(minivan, has_position_number, 2)
(tractor, has_position_number, 3)


Options: (A) The motorcyle is the newest
(B) The minivan is the newest
(C) The tractor is the newest


Quality Used to Order: oldest to newest
----------------------------------------
Batch Question : 36
Position Triples: (bus, has_position_number, 2)
(sedan, has_position_number, 3)
(truck, has_position_number, 1)


Options: (A) The bus is the second-newest
(B) The sedan is the second-newest
(C) The truck is the second-newest


Quality Used to Order: oldest to newest
----------------------------------------
Batch Question : 37
Position Triples: (loquats, has_position_number, 3)
(mangoes, has_position_number, 2)
(apples, has_position_number, 1)


Options: (A) The loquats are the most expensive
(B) The mangoes are the most expensive
(C) The apples are the most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 38
Position Triples: (blue_jay, has_position_number, 2)
(quail, has_position_number, 1)
(falcon, has_position_number, 3)


Options: (A) The blue jay is the rightmost
(B) The quail is the rightmost
(C) The falcon is the rightmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 39
Position Triples: (hawk, has_position_number, 1)
(crow, has_position_number, 3)
(raven, has_position_number, 2)


Options: (A) The hawk is the second from the left
(B) The crow is the second from the left
(C) The raven is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 40
Position Triples: (brown_book, has_position_number, 2)
(yellow_book, has_position_number, 1)
(orange_book, has_position_number, 3)


Options: (A) The brown book is the leftmost
(B) The yellow book is the leftmost
(C) The orange book is the leftmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 41
Position Triples: (loquats, has_position_number, 1)
(mangoes, has_position_number, 2)
(apples, has_position_number, 3)


Options: (A) The loquats are the second-most expensive
(B) The mangoes are the second-most expensive
(C) The apples are the second-most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 42
Position Triples: (cantaloupes, has_position_number, 2)
(oranges, has_position_number, 3)
(watermelons, has_position_number, 1)


Options: (A) The cantaloupes are the cheapest
(B) The oranges are the cheapest
(C) The watermelons are the cheapest


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 43
Position Triples: (apples, has_position_number, 2)
(peaches, has_position_number, 3)
(loquats, has_position_number, 1)


Options: (A) The apples are the most expensive
(B) The peaches are the most expensive
(C) The loquats are the most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 44
Position Triples: (owl, has_position_number, 2)
(crow, has_position_number, 1)
(cardinal, has_position_number, 3)


Options: (A) The owl is the second from the left
(B) The crow is the second from the left
(C) The cardinal is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 45
Position Triples: (oranges, has_position_number, 1)
(mangoes, has_position_number, 3)
(plums, has_position_number, 2)


Options: (A) The oranges are the second-most expensive
(B) The mangoes are the second-most expensive
(C) The plums are the second-most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 46
Position Triples: (quail, has_position_number, 1)
(owl, has_position_number, 2)
(hummingbird, has_position_number, 3)


Options: (A) The quail is the second from the left
(B) The owl is the second from the left
(C) The hummingbird is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 47
Position Triples: (oranges, has_position_number, 2)
(watermelons, has_position_number, 1)
(pears, has_position_number, 3)


Options: (A) The oranges are the most expensive
(B) The watermelons are the most expensive
(C) The pears are the most expensive


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 48
Position Triples: (ana, has_position_number, 2)
(mel, has_position_number, 3)
(ada, has_position_number, 1)


Options: (A) Ana finished first
(B) Mel finished first
(C) Ada finished first


Quality Used to Order: highest to lowest rank
----------------------------------------
Batch Question : 49
Position Triples: (sedan, has_position_number, 2)
(tractor, has_position_number, 3)
(bus, has_position_number, 1)


Options: (A) The sedan is the second-newest
(B) The tractor is the second-newest
(C) The bus is the second-newest


Quality Used to Order: oldest to newest
----------------------------------------
Batch Question : 50
Position Triples: (green_book, has_position_number, 1)
(brown_book, has_position_number, 2)
(orange_book, has_position_number, 3)


Options: (A) The green book is the second from the left
(B) The brown book is the second from the left
(C) The orange book is the second from the left


Quality Used to Order: left to right
----------------------------------------
Batch Question : 51
Position Triples: (orange_book, has_position_number, 1)
(blue_book, has_position_number, 2)
(yellow_book, has_position_number, 3)


Options: (A) The orange book is the leftmost
(B) The blue book is the leftmost
(C) The yellow book is the leftmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 52
Position Triples: (oranges, has_position_number, 1)
(mangoes, has_position_number, 3)
(plums, has_position_number, 2)


Options: (A) The oranges are the cheapest
(B) The mangoes are the cheapest
(C) The plums are the cheapest


Quality Used to Order: cheapest to most expensive
----------------------------------------
Batch Question : 53
Position Triples: (gray_book, has_position_number, 1)
(purple_book, has_position_number, 2)
(red_book, has_position_number, 3)


Options: (A) The gray book is the rightmost
(B) The purple book is the rightmost
(C) The red book is the rightmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 54
Position Triples: (motorcyle, has_position_number, 1)
(minivan, has_position_number, 2)
(tractor, has_position_number, 3)


Options: (A) The motorcyle is the oldest
(B) The minivan is the oldest
(C) The tractor is the oldest


Quality Used to Order: oldest to newest
----------------------------------------
Batch Question : 55
Position Triples: (blue_jay, has_position_number, 1)
(cardinal, has_position_number, 3)
(quail, has_position_number, 2)


Options: (A) The blue jay is the rightmost
(B) The cardinal is the rightmost
(C) The quail is the rightmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 56
Position Triples: (amy, has_position_number, 2)
(eli, has_position_number, 3)
(eve, has_position_number, 1)


Options: (A) Amy finished second
(B) Eli finished second
(C) Eve finished second


Quality Used to Order: highest to lowest finish
----------------------------------------
Batch Question : 57
Position Triples: (joe, has_position_number, 3)
(dan, has_position_number, 2)
(eve, has_position_number, 1)


Options: (A) Joe finished first
(B) Dan finished first
(C) Eve finished first


Quality Used to Order: highest to lowest rank
----------------------------------------
Batch Question : 58
Position Triples: (blue_jay, has_position_number, 2)
(quail, has_position_number, 1)
(falcon, has_position_number, 3)


Options: (A) The blue jay is the leftmost
(B) The quail is the leftmost
(C) The falcon is the leftmost


Quality Used to Order: left to right
----------------------------------------
Batch Question : 59
Position Triples: (watermelons, has_position_number, 3)
(apples, has_position_number, 1)

In [32]:
# Get the final answers from the LLM
final_answers_str_list = final_answer_chain.batch(final_questions_batch)

In [33]:
for i, answer_str in enumerate(final_answers_str_list):
    print(f"Final Answer for Question {i + 1}: {answer_str}")
    final_answers_list.append(answer_str)
    print("-" * 40)

Final Answer for Question 1: 1. **Interpreting the Triples**:
   - The quality used to order is "left to right". This means:
     - Position 1 is the leftmost.
     - Position 2 is the second from the left.
     - Position 3 is the third from the left.

   - Given the position triples:
     - (blue_jay, has_position_number, 2): The blue jay is positioned second from the left.
     - (quail, has_position_number, 1): The quail is positioned leftmost.
     - (falcon, has_position_number, 3): The falcon is positioned third from the left.

2. **Analyzing Each Option**:
   - **Option (A)**: "The blue jay is the second from the left."
     - According to the triples, the blue jay is indeed in position number 2, which means it is second from the left. This statement is correct.
   - **Option (B)**: "The quail is the second from the left."
     - The triples indicate that the quail is in position number 1, meaning it is the leftmost. Therefore, this statement is incorrect.
   - **Option (C)**: "The falcon is the second from the left."
     - The triples show that the falcon is in position number 3, meaning it is third from the left. This statement is incorrect.

3. **Correct Option**:
   - The only statement accurately matching the information in the triples is Option (A).

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 2: 1. **Interpreting the Triples:**

   Given the quality "newest to oldest," a position number of 1 indicates the "newest," and a higher number indicates progressively "older" items.

   - **(motorcyle, has_position_number, 2):** The motorcycle is the second newest.
   - **(limousine, has_position_number, 3):** The limousine is the third newest, hence the oldest among the listed vehicles.
   - **(convertible, has_position_number, 1):** The convertible is the newest.

2. **Analyzing the Options:**

   - **Option (A):** "The motorcycle is the oldest."
     - The motorcycle has position number 2, meaning it is the second newest. Therefore, it is not the oldest. This statement is incorrect.

   - **Option (B):** "The limousine is the oldest."
     - The limousine has position number 3, indicating it is the oldest in this ordering. This statement is correct.

   - **Option (C):** "The convertible is the oldest."
     - The convertible has position number 1, meaning it is the newest. Therefore, it is not the oldest. This statement is incorrect.

3. **Conclusion:**

   By comparing each option with the interpreted positions given the quality "newest to oldest," option (B) correctly describes the ordering.

### FINAL ANSWER
(B)
----------------------------------------
Final Answer for Question 3: 1. **Detailed Reasoning:**

   **Interpreting Each Triple:**

   - (blue_book, has_position_number, 3): According to the "left to right" ordering quality, this means the blue book is the third from the left.
   - (orange_book, has_position_number, 1): This means the orange book is the first from the left.
   - (red_book, has_position_number, 2): This indicates the red book is the second from the left.

   **Comparing Each Option:**

   - **Option (A):** "The blue book is the second from the left"
     - From the position triples, the blue book is at position 3, which means it is the third from the left.
     - This option is incorrect.

   - **Option (B):** "The orange book is the second from the left"
     - The position triples state the orange book is at position 1, indicating it is the first from the left.
     - This option is incorrect.

   - **Option (C):** "The red book is the second from the left"
     - According to the position triples, the red book is at position 2, meaning it is indeed the second from the left.
     - This option is correct.

2. Based on the above analysis, the option that is accurately supported by the triples is option (C).

### FINAL ANSWER
(C)
----------------------------------------
Final Answer for Question 4: 1. **Detailed Reasoning**:

   Given the quality used to order is "left to right", we map the position numbers to their respective descriptions:
   - Position 1 is "leftmost", Position 2 is "second from the left", and Position 3 is "rightmost".

   Interpreting the triples:
   - **(robin, has_position_number, 2)**: The robin is the second from the left.
   - **(blue_jay, has_position_number, 3)**: The blue jay is the rightmost.
   - **(crow, has_position_number, 1)**: The crow is the leftmost.

   Evaluating each option:
   - **Option (A)**: "The robin is the rightmost." This is incorrect. The robin is second from the left, not the rightmost.
   - **Option (B)**: "The blue jay is the rightmost." This is correct. The blue jay's position number is 3, indicating it is indeed the rightmost.
   - **Option (C)**: "The crow is the rightmost." This is incorrect. The crow is the leftmost.

   Thus, only option (B) accurately reflects the position described in the triples.

2. **Outcome**:

   ### FINAL ANSWER
   (B)
----------------------------------------
Final Answer for Question 5: 1. **Interpreting each triple:**
   - The order is given as "left to right."
   - **(green_book, has_position_number, 1):** The green book is in position 1, meaning it is the leftmost.
   - **(red_book, has_position_number, 3):** The red book is in position 3, meaning it is the rightmost.
   - **(blue_book, has_position_number, 2):** The blue book is in position 2, meaning it is in the middle.

2. **Walkthrough of each option:**

   - **Option (A): "The green book is the rightmost"**
     - According to the triples, the green book is in position 1 (leftmost). This contradicts option A, which claims it is the rightmost.

   - **Option (B): "The red book is the rightmost"**
     - The position triples state that the red book is in position 3, which means it is indeed the rightmost. This option matches the triples properly.

   - **Option (C): "The blue book is the rightmost"**
     - The blue book is in position 2, meaning it is in the middle. Thus, it is not the rightmost, contradicting option C.

3. **Conclusion:**
   - Option B correctly matches the data provided by the position triples as the red book is the rightmost.

### FINAL ANSWER
(B)
----------------------------------------
Final Answer for Question 6: 1. **Step-by-step Reasoning:**

   - We first interpret each item based on the provided quality "cheapest to most expensive".

   - **Triple 1:** (apples, has_position_number, 1) indicates that apples are in position 1, making them the cheapest item.

   - **Triple 2:** (peaches, has_position_number, 3) shows that peaches are in position 3, making them the most expensive item among the three items listed.

   - **Triple 3:** (mangoes, has_position_number, 2) places mangoes in position 2, which makes them the second-cheapest or equivalently, the second-most expensive item out of the three since there are only three items.

   - Now we compare each option against the above interpretations:

     **Option (A):** "The apples are the second-most expensive."
      - Apples are the cheapest, not the second-most expensive as per position 1. Therefore, this option is incorrect.

     **Option (B):** "The peaches are the second-most expensive."
      - Peaches are the most expensive, in position 3, not the second-most expensive. Thus, this option is incorrect.

     **Option (C):** "The mangoes are the second-most expensive."
      - Mangoes are indeed in position 2, which correlates with being the second-most expensive. Therefore, this option is correct.

2. After evaluating all options, Option (C) is the only statement that aligns with the given position triples.

### FINAL ANSWER
(C)
----------------------------------------
Final Answer for Question 7: 1. **Detailed Reasoning:**

   - **Interpreting the Position Triples:**

     Using the quality "newest to oldest," we determine:
     - For position 1, the item is the "newest."
     - For position 2, the item is "second newest."
     - For position 3, the item is "third newest" or "oldest" among the given items.

     Applying this to the triples:
     - (minivan, has_position_number, 1): Minivan is the newest.
     - (truck, has_position_number, 2): Truck is the second newest.
     - (tractor, has_position_number, 3): Tractor is the oldest.

   - **Option Comparison:**

     - **Option (A)**: "The tractor is the newest"
       - The position triples tell us the tractor is in position 3, which means it is the oldest. Thus, this statement is not true.

     - **Option (B)**: "The truck is the newest"
       - The position triples assign the truck position 2, indicating it is the second newest, not the newest. Thus, this statement is not true.

     - **Option (C)**: "The minivan is the newest"
       - According to the position triples, the minivan is in position 1, which indeed makes it the newest. Thus, this statement is true.

   Only one option correctly reflects the order information provided: Option (C).

3. **Identifying the Option Supported by the Triples:**

   Given the comparisons, only Option (C) matches the order indicated by the position triples.

### FINAL ANSWER
(C)
----------------------------------------
Final Answer for Question 8: 1. **Detailed Step-by-Step Reasoning:**

   - **Interpreting the Triples:**
     - Each triple is of the form (item, has_position_number, k) with the quality "highest to lowest rank".
     - The number 1 position means the highest rank, number 2 means the next highest, and number 3 means the third highest.
     - For (eve, has_position_number, 1): Eve is in the highest rank position.
     - For (rob, has_position_number, 3): Rob is in the third highest rank position.
     - For (mel, has_position_number, 2): Mel is in the second highest rank position.

   - **Comparing Each Option:**
     - **Option (A) "Eve finished first":**
       - This means Eve is in the highest rank position. According to the triples, Eve indeed has position number 1, which is the highest rank.
       - Therefore, Option (A) is correct.

     - **Option (B) "Rob finished first":**
       - This would require Rob to be in the highest rank position. The triple shows Rob in position number 3, which is not the highest.
       - Therefore, Option (B) is incorrect.

     - **Option (C) "Mel finished first":**
       - This would require Mel to be in the highest rank position. The triple shows Mel in position number 2, which is not the highest.
       - Therefore, Option (C) is incorrect.

   - After analyzing all options, only Option (A) aligns perfectly with the position triples given the order from highest to lowest rank.

2. **Conclusion:**
   - The correct statement that matches the ordering facts from the triples is Option (A).

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 9: 1. **Interpreting the Position Triples:**
   - We have the quality "left to right" given to order these items.
   - (orange_book, has_position_number, 2): The orange book is positioned as the second item from the left.
   - (yellow_book, has_position_number, 1): The yellow book is positioned as the first item from the left.
   - (blue_book, has_position_number, 3): The blue book is positioned as the third item from the left.

2. **Evaluating Each Option:**
   - **Option (A):** "The orange book is the second from the left"
     - This matches the triple (orange_book, has_position_number, 2), as the orange book is indeed the second item from the left according to the given position.
   - **Option (B):** "The yellow book is the second from the left"
     - The triple (yellow_book, has_position_number, 1) indicates that the yellow book is the first from the left, not the second. Hence, this option is incorrect.
   - **Option (C):** "The blue book is the second from the left"
     - The triple (blue_book, has_position_number, 3) indicates that the blue book is the third from the left. Thus, this option is also incorrect.

3. **Identifying the Correct Option:**
   - Option (A) is the only statement that accurately reflects the position described by the triples.

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 10: 1. **Interpreting Triples:**
   - The quality used is "newest to oldest", meaning position 1 is the newest and position 3 is the oldest.
   - The triple (station_wagon, has_position_number, 1) indicates that the station wagon is the newest.
   - The triple (minivan, has_position_number, 2) indicates that the minivan is the second newest.
   - The triple (truck, has_position_number, 3) indicates that the truck is the oldest.

2. **Evaluating Options:**
   - **Option (A):** "The station wagon is the newest."
     - This statement claims that the station wagon is in the newest position. According to the triples, the station wagon is indeed position 1, which is the newest. So this option matches the data.
   - **Option (B):** "The minivan is the newest."
     - This statement claims that the minivan is in the newest position. According to the triples, the minivan is in position 2, not position 1. This does not match the data.
   - **Option (C):** "The truck is the newest."
     - This statement claims that the truck is in the newest position. According to the triples, the truck is in position 3, which is the oldest, not the newest. This does not match the data.

3. **Correct Option:**
   - Option (A) is the only statement that correctly reflects the position information given in the triples with the quality "newest to oldest".

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 11: 1. **Step-by-Step Reasoning:**

   - **Interpretation of Triples:**
     - `(gray_book, has_position_number, 1)` means the gray book is positioned at the leftmost, as positions are ordered from left to right.
     - `(purple_book, has_position_number, 2)` means the purple book is second from the left.
     - `(red_book, has_position_number, 3)` means the red book is third from the left, or the rightmost in this context of three books.

   - **Option (A):** "The gray book is the leftmost"
     - According to the triples, the gray book is indeed at position 1, which is the leftmost position. This option is supported by the triples.

   - **Option (B):** "The purple book is the leftmost"
     - The triples list the purple book at position 2, which is not the leftmost. Therefore, this option is incorrect.

   - **Option (C):** "The red book is the leftmost"
     - The red book is in position 3, making it the rightmost, not the leftmost. So, this option is also incorrect.

2. **Selection of the Correct Option:**
   - From the analysis above, only Option (A) correctly reflects the information provided in the triples.

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 12: 1. **Interpretation of Triples:**
   - The given quality is "cheapest to most expensive". This means:
     - Position 1 is the cheapest,
     - Position 2 is the second-cheapest,
     - Position 3 is the third-cheapest or most expensive among the three.

   Applying this interpretation:
   - (peaches, has_position_number, 3): Peaches are ranked 3rd, meaning they are the most expensive.
   - (mangoes, has_position_number, 1): Mangoes are ranked 1st, meaning they are the cheapest.
   - (apples, has_position_number, 2): Apples are ranked 2nd, meaning they are the second-cheapest or the second-most expensive among the provided items.

2. **Analysis of Options:**
   - **Option (A): "The peaches are the second-most expensive."**
     - From the triples, peaches are ranked 3rd, which makes them the most expensive, not the second-most expensive. Therefore, this option is incorrect.

   - **Option (B): "The mangoes are the second-most expensive."**
     - From the triples, mangoes are ranked 1st, meaning they are the cheapest. Therefore, this option is incorrect.

   - **Option (C): "The apples are the second-most expensive."**
     - From the triples, apples are ranked 2nd. Since we are using the ordering "cheapest to most expensive", being in position 2 means apples are indeed the second-most expensive. Thus, this option is correct.

3. **Identification of the Correct Option:**
   - The interpretation of the triples reveals that option (C) is correct because it accurately states the position of the apples according to the ordering "cheapest to most expensive."

### FINAL ANSWER
(C)
----------------------------------------
Final Answer for Question 13: 1. **Interpreting the position triples:**
   - The quality used to order is "left to right."
   - The triple (blue_jay, has_position_number, 3) indicates that the blue jay is in position 3 when ordered from left to right, meaning it is third from the left.
   - The triple (falcon, has_position_number, 2) tells us that the falcon is in position 2, meaning it is the second from the left.
   - The triple (hummingbird, has_position_number, 1) shows that the hummingbird is in position 1, making it the first from the left.

2. **Analyzing and matching each option:**
   - **Option (A):** "The blue jay is the second from the left." This claim would require the blue_jay to be in position 2. However, the blue_jay is in position 3, so this option is incorrect.
   - **Option (B):** "The falcon is the second from the left." This claim requires the falcon to be in position 2. According to the triples, the falcon is indeed in position 2, which matches this statement exactly. Therefore, this option is correct.
   - **Option (C):** "The hummingbird is the second from the left." This statement would necessitate the hummingbird being in position 2. However, the hummingbird is in position 1, making this option incorrect.

3. **Identify the supported option:**
   - Based on the analysis, Option (B) is supported by the triples as it correctly identifies the falcon's position as second from the left.

### FINAL ANSWER
(B)
----------------------------------------
Final Answer for Question 14: 1. **Interpretation of the triples given the quality "newest to oldest":**
   - **(minivan, has_position_number, 2):** This means the minivan is the second-newest.
   - **(bus, has_position_number, 1):** This means the bus is the newest.
   - **(sedan, has_position_number, 3):** This means the sedan is the third-newest, or the oldest in this set.

2. **Walkthrough of each option:**

   (A) "The minivan is the second-newest":
   - The triples state that the minivan is in position 2, which corresponds to being the second-newest. Hence, this statement matches the information from the triples.

   (B) "The bus is the second-newest":
   - The triples state that the bus is in position 1, which means it is the newest, not the second-newest. This statement does not match the information from the triples.

   (C) "The sedan is the second-newest":
   - The triples state that the sedan is in position 3, which means it is the oldest. This statement does not match the information from the triples.

3. **Identify the option supported by the triples:**
   - Option (A) matches the correct position of the minivan as stated in the interpretation of triples.

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 15: 1. **Interpreting the Triples:**

   Given the quality "oldest to newest," the position number 1 corresponds to the oldest, position 2 to the second-oldest, and position 3 to the newest. Each vehicle's position in the triples gives the following order:
   - The convertible is in position 1: it is the oldest.
   - The hatchback is in position 2: it is the second-oldest.
   - The tractor is in position 3: it is the newest.

2. **Analyzing Each Option:**

   - **Option (A):** "The hatchback is the second-newest."
     - Given our interpretation, the hatchback is the second-oldest, which means it is indeed the second-newest because there are only three items, and being second-oldest implies second-newest.

In [34]:
for i in range(len(targets)):
    print(f"Answer for the question num {i + 1}: {targets[i]}")

Answer for the question num 1: (A)
Answer for the question num 2: (B)
Answer for the question num 3: (C)
Answer for the question num 4: (B)
Answer for the question num 5: (B)
Answer for the question num 6: (C)
Answer for the question num 7: (C)
Answer for the question num 8: (A)
Answer for the question num 9: (A)
Answer for the question num 10: (A)
Answer for the question num 11: (A)
Answer for the question num 12: (C)
Answer for the question num 13: (B)
Answer for the question num 14: (A)
Answer for the question num 15: (A)
Answer for the question num 16: (A)
Answer for the question num 17: (A)
Answer for the question num 18: (A)
Answer for the question num 19: (C)
Answer for the question num 20: (A)
Answer for the question num 21: (C)
Answer for the question num 22: (B)
Answer for the question num 23: (C)
Answer for the question num 24: (A)
Answer for the question num 25: (C)
Answer for the question num 26: (C)
Answer for the question num 27: (A)
Answer for the question num 28: (B)
Answer for the question num 29: (B)
Answer for the question num 30: (A)
Answer for the question num 31: (C)
Answer for the question num 32: (C)
Answer for the question num 33: (C)
Answer for the question num 34: (C)
Answer for the question num 35: (C)
Answer for the question num 36: (A)
Answer for the question num 37: (A)
Answer for the question num 38: (C)
Answer for the question num 39: (C)
Answer for the question num 40: (B)
Answer for the question num 41: (B)
Answer for the question num 42: (C)
Answer for the question num 43: (B)
Answer for the question num 44: (A)
Answer for the question num 45: (C)
Answer for the question num 46: (B)
Answer for the question num 47: (C)
Answer for the question num 48: (C)
Answer for the question num 49: (A)
Answer for the question num 50: (B)
Answer for the question num 51: (A)
Answer for the question num 52: (A)
Answer for the question num 53: (C)
Answer for the question num 54: (A)
Answer for the question num 55: (B)
Answer for the question num 56: (A)
Answer for the question num 57: (C)
Answer for the question num 58: (B)
Answer for the question num 59: (B)
Answer for the question num 60: (B)
Answer for the question num 61: (B)
Answer for the question num 62: (B)
Answer for the question num 63: (C)
Answer for the question num 64: (A)
Answer for the question num 65: (B)
Answer for the question num 66: (A)
Answer for the question num 67: (C)
Answer for the question num 68: (A)
Answer for the question num 69: (C)
Answer for the question num 70: (B)
Answer for the question num 71: (C)
Answer for the question num 72: (B)
Answer for the question num 73: (B)
Answer for the question num 74: (A)
Answer for the question num 75: (C)
Answer for the question num 76: (B)
Answer for the question num 77: (B)
Answer for the question num 78: (A)
Answer for the question num 79: (A)
Answer for the question num 80: (B)
Answer for the question num 81: (C)
Answer for the question num 82: (B)
Answer for the question num 83: (A)
Answer for the question num 84: (B)
Answer for the question num 85: (B)
Answer for the question num 86: (A)
Answer for the question num 87: (C)
Answer for the question num 88: (B)
Answer for the question num 89: (C)
Answer for the question num 90: (B)
Answer for the question num 91: (C)
Answer for the question num 92: (B)
Answer for the question num 93: (C)
Answer for the question num 94: (C)
Answer for the question num 95: (A)
Answer for the question num 96: (C)
Answer for the question num 97: (A)
Answer for the question num 98: (A)
Answer for the question num 99: (A)
Answer for the question num 100: (B)
Answer for the question num 101: (A)
Answer for the question num 102: (A)
Answer for the question num 103: (B)
Answer for the question num 104: (A)
Answer for the question num 105: (A)
Answer for the question num 106: (B)
Answer for the question num 107: (A)
Answer for the question num 108: (C)
Answer for the question num 109: (C)
Answer for the question num 110: (C)
Answer for the question num 111: (A)
Answer for the question num 112: (A)
Answer for the question num 113: (B)
Answer for the question num 114: (A)
Answer for the question num 115: (B)
Answer for the question num 116: (B)
Answer for the question num 117: (C)
Answer for the question num 118: (A)
Answer for the question num 119: (B)
Answer for the question num 120: (A)
Answer for the question num 121: (B)
Answer for the question num 122: (C)
Answer for the question num 123: (C)
Answer for the question num 124: (B)
Answer for the question num 125: (C)
Answer for the question num 126: (A)
Answer for the question num 127: (B)
Answer for the question num 128: (A)
Answer for the question num 129: (A)
Answer for the question num 130: (B)
Answer for the question num 131: (A)
Answer for the question num 132: (C)
Answer for the question num 133: (B)
Answer for the question num 134: (B)
Answer for the question num 135: (C)
Answer for the question num 136: (B)
Answer for the question num 137: (A)
Answer for the question num 138: (B)
Answer for the question num 139: (A)
Answer for the question num 140: (C)
Answer for the question num 141: (B)
Answer for the question num 142: (C)
Answer for the question num 143: (C)
Answer for the question num 144: (A)
Answer for the question num 145: (B)
Answer for the question num 146: (C)
Answer for the question num 147: (C)
Answer for the question num 148: (A)
Answer for the question num 149: (A)
Answer for the question num 150: (B)
Answer for the question num 151: (B)
Answer for the question num 152: (B)
Answer for the question num 153: (C)
Answer for the question num 154: (C)
Answer for the question num 155: (B)
Answer for the question num 156: (A)
Answer for the question num 157: (A)
Answer for the question num 158: (C)
Answer for the question num 159: (A)
Answer for the question num 160: (B)
Answer for the question num 161: (A)
Answer for the question num 162: (C)
Answer for the question num 163: (C)
Answer for the question num 164: (B)
Answer for the question num 165: (C)
Answer for the question num 166: (A)
Answer for the question num 167: (A)
Answer for the question num 168: (C)
Answer for the question num 169: (C)
Answer for the question num 170: (A)
Answer for the question num 171: (A)
Answer for the question num 172: (B)
Answer for the question num 173: (B)
Answer for the question num 174: (A)
Answer for the question num 175: (A)
Answer for the question num 176: (C)
Answer for the question num 177: (A)
Answer for the question num 178: (C)
Answer for the question num 179: (B)
Answer for the question num 180: (A)
Answer for the question num 181: (C)
Answer for the question num 182: (A)
Answer for the question num 183: (A)
Answer for the question num 184: (C)
Answer for the question num 185: (B)
Answer for the question num 186: (C)
Answer for the question num 187: (B)
Answer for the question num 188: (B)
Answer for the question num 189: (C)
Answer for the question num 190: (B)
Answer for the question num 191: (A)
Answer for the question num 192: (A)
Answer for the question num 193: (A)
Answer for the question num 194: (B)
Answer for the question num 195: (A)
Answer for the question num 196: (B)
Answer for the question num 197: (C)
Answer for the question num 198: (B)
Answer for the question num 199: (A)
Answer for the question num 200: (A)
Answer for the question num 201: (C)
Answer for the question num 202: (C)
Answer for the question num 203: (C)
Answer for the question num 204: (B)
Answer for the question num 205: (C)
Answer for the question num 206: (B)
Answer for the question num 207: (C)
Answer for the question num 208: (C)
Answer for the question num 209: (B)
Answer for the question num 210: (A)
Answer for the question num 211: (B)
Answer for the question num 212: (C)
Answer for the question num 213: (C)
Answer for the question num 214: (B)
Answer for the question num 215: (C)
Answer for the question num 216: (B)
Answer for the question num 217: (B)
Answer for the question num 218: (C)
Answer for the question num 219: (B)
Answer for the question num 220: (B)
Answer for the question num 221: (B)
Answer for the question num 222: (C)
Answer for the question num 223: (B)
Answer for the question num 224: (C)
Answer for the question num 225: (A)
Answer for the question num 226: (B)
Answer for the question num 227: (B)
Answer for the question num 228: (C)
Answer for the question num 229: (A)
Answer for the question num 230: (A)
Answer for the question num 231: (B)
Answer for the question num 232: (C)
Answer for the question num 233: (C)
Answer for the question num 234: (C)
Answer for the question num 235: (B)
Answer for the question num 236: (A)
Answer for the question num 237: (B)
Answer for the question num 238: (B)
Answer for the question num 239: (B)
Answer for the question num 240: (A)
Answer for the question num 241: (B)
Answer for the question num 242: (B)
Answer for the question num 243: (C)
Answer for the question num 244: (B)
Answer for the question num 245: (B)
Answer for the question num 246: (C)
Answer for the question num 247: (C)
Answer for the question num 248: (C)
Answer for the question num 249: (A)
Answer for the question num 250: (C)
Answer for the question num 251: (A)
Answer for the question num 252: (B)
Answer for the question num 253: (E)
Answer for the question num 254: (B)
Answer for the question num 255: (D)
Answer for the question num 256: (E)
Answer for the question num 257: (C)
Answer for the question num 258: (D)
Answer for the question num 259: (D)
Answer for the question num 260: (C)
Answer for the question num 261: (D)
Answer for the question num 262: (B)
Answer for the question num 263: (A)
Answer for the question num 264: (D)
Answer for the question num 265: (A)
Answer for the question num 266: (A)
Answer for the question num 267: (B)
Answer for the question num 268: (D)
Answer for the question num 269: (A)
Answer for the question num 270: (C)
Answer for the question num 271: (B)
Answer for the question num 272: (C)
Answer for the question num 273: (B)
Answer for the question num 274: (A)
Answer for the question num 275: (D)
Answer for the question num 276: (B)
Answer for the question num 277: (E)
Answer for the question num 278: (E)
Answer for the question num 279: (A)
Answer for the question num 280: (D)
Answer for the question num 281: (B)
Answer for the question num 282: (C)
Answer for the question num 283: (D)
Answer for the question num 284: (A)
Answer for the question num 285: (C)
Answer for the question num 286: (D)
Answer for the question num 287: (C)
Answer for the question num 288: (B)
Answer for the question num 289: (D)
Answer for the question num 290: (D)
Answer for the question num 291: (D)
Answer for the question num 292: (B)
Answer for the question num 293: (C)
Answer for the question num 294: (E)
Answer for the question num 295: (A)
Answer for the question num 296: (B)
Answer for the question num 297: (E)
Answer for the question num 298: (C)
Answer for the question num 299: (A)
Answer for the question num 300: (B)
Answer for the question num 301: (D)
Answer for the question num 302: (E)
Answer for the question num 303: (C)
Answer for the question num 304: (E)
Answer for the question num 305: (B)
Answer for the question num 306: (D)
Answer for the question num 307: (A)
Answer for the question num 308: (E)
Answer for the question num 309: (B)
Answer for the question num 310: (D)
Answer for the question num 311: (A)
Answer for the question num 312: (E)
Answer for the question num 313: (E)
Answer for the question num 314: (B)
Answer for the question num 315: (B)
Answer for the question num 316: (E)
Answer for the question num 317: (A)
Answer for the question num 318: (A)
Answer for the question num 319: (D)
Answer for the question num 320: (A)
Answer for the question num 321: (C)
Answer for the question num 322: (D)
Answer for the question num 323: (D)
Answer for the question num 324: (E)
Answer for the question num 325: (A)
Answer for the question num 326: (E)
Answer for the question num 327: (D)
Answer for the question num 328: (D)
Answer for the question num 329: (C)
Answer for the question num 330: (D)
Answer for the question num 331: (C)
Answer for the question num 332: (C)
Answer for the question num 333: (A)
Answer for the question num 334: (D)
Answer for the question num 335: (D)
Answer for the question num 336: (D)
Answer for the question num 337: (A)
Answer for the question num 338: (E)
Answer for the question num 339: (C)
Answer for the question num 340: (D)
Answer for the question num 341: (E)
Answer for the question num 342: (B)
Answer for the question num 343: (C)
Answer for the question num 344: (E)
Answer for the question num 345: (C)
Answer for the question num 346: (A)
Answer for the question num 347: (A)
Answer for the question num 348: (A)
Answer for the question num 349: (D)
Answer for the question num 350: (A)
Answer for the question num 351: (A)
Answer for the question num 352: (A)
Answer for the question num 353: (E)
Answer for the question num 354: (D)
Answer for the question num 355: (A)
Answer for the question num 356: (D)
Answer for the question num 357: (D)
Answer for the question num 358: (B)
Answer for the question num 359: (E)
Answer for the question num 360: (B)
Answer for the question num 361: (B)
Answer for the question num 362: (C)
Answer for the question num 363: (C)
Answer for the question num 364: (A)
Answer for the question num 365: (B)
Answer for the question num 366: (A)
Answer for the question num 367: (B)
Answer for the question num 368: (E)
Answer for the question num 369: (D)
Answer for the question num 370: (D)
Answer for the question num 371: (E)
Answer for the question num 372: (C)
Answer for the question num 373: (E)
Answer for the question num 374: (D)
Answer for the question num 375: (E)
Answer for the question num 376: (C)
Answer for the question num 377: (E)
Answer for the question num 378: (E)
Answer for the question num 379: (D)
Answer for the question num 380: (A)
Answer for the question num 381: (E)
Answer for the question num 382: (A)
Answer for the question num 383: (E)
Answer for the question num 384: (D)
Answer for the question num 385: (D)
Answer for the question num 386: (B)
Answer for the question num 387: (E)
Answer for the question num 388: (C)
Answer for the question num 389: (C)
Answer for the question num 390: (D)
Answer for the question num 391: (A)
Answer for the question num 392: (A)
Answer for the question num 393: (A)
Answer for the question num 394: (B)
Answer for the question num 395: (C)
Answer for the question num 396: (D)
Answer for the question num 397: (C)
Answer for the question num 398: (A)
Answer for the question num 399: (E)
Answer for the question num 400: (C)
Answer for the question num 401: (C)
Answer for the question num 402: (C)
Answer for the question num 403: (B)
Answer for the question num 404: (E)
Answer for the question num 405: (D)
Answer for the question num 406: (A)
Answer for the question num 407: (B)
Answer for the question num 408: (B)
Answer for the question num 409: (B)
Answer for the question num 410: (E)
Answer for the question num 411: (A)
Answer for the question num 412: (D)
Answer for the question num 413: (D)
Answer for the question num 414: (E)
Answer for the question num 415: (C)
Answer for the question num 416: (D)
Answer for the question num 417: (D)
Answer for the question num 418: (D)
Answer for the question num 419: (C)
Answer for the question num 420: (B)
Answer for the question num 421: (C)
Answer for the question num 422: (B)
Answer for the question num 423: (D)
Answer for the question num 424: (A)
Answer for the question num 425: (E)
Answer for the question num 426: (A)
Answer for the question num 427: (C)
Answer for the question num 428: (A)
Answer for the question num 429: (E)
Answer for the question num 430: (A)
Answer for the question num 431: (D)
Answer for the question num 432: (D)
Answer for the question num 433: (B)
Answer for the question num 434: (C)
Answer for the question num 435: (B)
Answer for the question num 436: (D)
Answer for the question num 437: (D)
Answer for the question num 438: (C)
Answer for the question num 439: (B)
Answer for the question num 440: (A)
Answer for the question num 441: (D)
Answer for the question num 442: (D)
Answer for the question num 443: (D)
Answer for the question num 444: (A)
Answer for the question num 445: (A)
Answer for the question num 446: (A)
Answer for the question num 447: (B)
Answer for the question num 448: (B)
Answer for the question num 449: (E)
Answer for the question num 450: (E)
Answer for the question num 451: (A)
Answer for the question num 452: (A)
Answer for the question num 453: (D)
Answer for the question num 454: (D)
Answer for the question num 455: (B)
Answer for the question num 456: (B)
Answer for the question num 457: (D)
Answer for the question num 458: (C)
Answer for the question num 459: (E)
Answer for the question num 460: (E)
Answer for the question num 461: (E)
Answer for the question num 462: (B)
Answer for the question num 463: (B)
Answer for the question num 464: (C)
Answer for the question num 465: (B)
Answer for the question num 466: (E)
Answer for the question num 467: (E)
Answer for the question num 468: (C)
Answer for the question num 469: (E)
Answer for the question num 470: (B)
Answer for the question num 471: (E)
Answer for the question num 472: (E)
Answer for the question num 473: (C)
Answer for the question num 474: (C)
Answer for the question num 475: (C)
Answer for the question num 476: (B)
Answer for the question num 477: (E)
Answer for the question num 478: (C)
Answer for the question num 479: (E)
Answer for the question num 480: (E)
Answer for the question num 481: (B)
Answer for the question num 482: (A)
Answer for the question num 483: (B)
Answer for the question num 484: (C)
Answer for the question num 485: (D)
Answer for the question num 486: (A)
Answer for the question num 487: (B)
Answer for the question num 488: (B)
Answer for the question num 489: (B)
Answer for the question num 490: (C)
Answer for the question num 491: (E)
Answer for the question num 492: (C)
Answer for the question num 493: (E)
Answer for the question num 494: (B)
Answer for the question num 495: (C)
Answer for the question num 496: (C)
Answer for the question num 497: (A)
Answer for the question num 498: (E)
Answer for the question num 499: (E)
Answer for the question num 500: (B)
Answer for the question num 501: (D)
Answer for the question num 502: (B)
Answer for the question num 503: (A)
Answer for the question num 504: (A)
Answer for the question num 505: (F)
Answer for the question num 506: (B)
Answer for the question num 507: (E)
Answer for the question num 508: (B)
Answer for the question num 509: (C)
Answer for the question num 510: (B)
Answer for the question num 511: (G)
Answer for the question num 512: (C)
Answer for the question num 513: (D)
Answer for the question num 514: (F)
Answer for the question num 515: (A)
Answer for the question num 516: (E)
Answer for the question num 517: (B)
Answer for the question num 518: (E)
Answer for the question num 519: (G)
Answer for the question num 520: (A)
Answer for the question num 521: (D)
Answer for the question num 522: (C)
Answer for the question num 523: (A)
Answer for the question num 524: (E)
Answer for the question num 525: (D)
Answer for the question num 526: (A)
Answer for the question num 527: (F)
Answer for the question num 528: (C)
Answer for the question num 529: (B)
Answer for the question num 530: (E)
Answer for the question num 531: (C)
Answer for the question num 532: (D)
Answer for the question num 533: (C)
Answer for the question num 534: (A)
Answer for the question num 535: (G)
Answer for the question num 536: (A)
Answer for the question num 537: (F)
Answer for the question num 538: (C)
Answer for the question num 539: (A)
Answer for the question num 540: (G)
Answer for the question num 541: (C)
Answer for the question num 542: (D)
Answer for the question num 543: (E)

In [35]:
def extract_final_answer(text):
    marker = "### FINAL ANSWER"
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == marker:
            # Return the very next non-empty line (in case there are blank lines)
            for next_line in lines[i+1:]:
                if next_line.strip():
                    return next_line.strip()
    return []

# Create a DataFrame to store the final answers
final_answers_df = pd.DataFrame({
    'question_number': [i + 1 for i in range(len(final_answers_list))],
    'question': questions,
    'options': options,
    'ordering_quality': ordering_quality_list,
    'entities': entities_list,
    'generated_triples': [
        [f"({e1}, {rel}, {e2})" for e1, rel, e2 in kg_list[i].graph] for i in range(len(kg_list))
    ],
    'llm_response': final_answers_list,
    'final_answer': [extract_final_answer(answer) for answer in final_answers_str_list],
    'ground_truth': targets
})

final_answers_df

,question_number,question,options,ordering_quality,entities,generated_triples,llm_response,final_answer,ground_truth
0,1,The following paragraphs each describe a set o...,(A) The blue jay is the second from the left\n...,left to right,"[blue_jay, quail, falcon]","[(('entity_1', 'blue_jay'), ('entity_2', 'falc...",1. **Interpreting the Triples**:\n - The qua...,(A),(A)
1,2,The following paragraphs each describe a set o...,(A) The motorcyle is the oldest\n(B) The limou...,newest to oldest,"[motorcyle, limousine, convertible]","[(('entity_1', 'motorcyle'), ('entity_2', 'lim...",1. **Interpreting the Triples:**\n\n Given t...,(B),(B)
2,3,The following paragraphs each describe a set o...,(A) The blue book is the second from the left\...,left to right,"[blue_book, orange_book, red_book]","[(('entity_1', 'blue_book'), ('entity_2', '3')...",1. **Detailed Reasoning:**\n\n **Interpretin...,(C),(C)
3,4,The following paragraphs each describe a set o...,(A) The robin is the rightmost\n(B) The blue j...,left to right,"[robin, blue_jay, crow]","[(('entity_1', 'crow'), ('entity_2', 'robin'),...",1. **Detailed Reasoning**:\n\n Given the qua...,(B),(B)
4,5,The following paragraphs each describe a set o...,(A) The green book is the rightmost\n(B) The r...,left to right,"[green_book, red_book, blue_book]","[(('entity_1', 'red_book'), ('entity_2', '3'),...",1. **Interpreting each triple:**\n - The ord...,(B),(B)
...,...,...,...,...,...,...,...,...,...
745,746,The following paragraphs each describe a set o...,(A) Joe finished second-to-last\n(B) Mel finis...,highest to lowest rank,"[Joe, Mel, Mya, Eve, Rob, Ada, Dan]","[(('entity_1', 'Rob'), ('entity_2', '1'), ('ed...",### Reasoning\n\nThe given quality used to ord...,(A),(A)
746,747,The following paragraphs each describe a set o...,(A) The hawk is the second from the left\n(B) ...,left to right,"[hawk, hummingbird, quail, owl, crow, robin, c...","[(('entity_1', 'cardinal'), ('entity_2', '6'),...",1. **Interpretation of Triples Given the Quali...,(D),(D)
747,748,The following paragraphs each describe a set o...,(A) The white book is the fourth from the left...,left to right,"[white_book, gray_book, yellow_book, purple_bo...","[(('entity_1', 'black_book'), ('entity_2', '6'...",1. **Interpreting the Triples**:\n - From th...,(A),(A)
748,749,The following paragraphs each describe a set o...,(A) The quail is the third from the right\n(B)...,left to right,"[quail, raven, hummingbird, robin, falcon, owl...","[(('entity_1', 'blue_jay'), ('entity_2', 'falc...",### Reasoning\n\n**Quality Used to Order:** le...,(D),(F)
749,750,The following paragraphs each describe a set o...,(A) The sedan is the third-newest\n(B) The tru...,oldest to newest,"[sedan, truck, bus, station_wagon, tractor, co...","[(('entity_1', 'truck'), ('entity_2', '1'), ('...","1. **Map-positions**: \n - Quality is ""oldes...",(A),(D)

In [36]:
# Add is_correct column to check if the final answer matches the ground truth
def check_correctness(row):
    return 1 if row['final_answer'] == row['ground_truth'] else 0

final_answers_df['is_correct'] = final_answers_df.apply(check_correctness, axis=1)
final_answers_df

,question_number,question,options,ordering_quality,entities,generated_triples,llm_response,final_answer,ground_truth,is_correct
0,1,The following paragraphs each describe a set o...,(A) The blue jay is the second from the left\n...,left to right,"[blue_jay, quail, falcon]","[(('entity_1', 'blue_jay'), ('entity_2', 'falc...",1. **Interpreting the Triples**:\n - The qua...,(A),(A),1
1,2,The following paragraphs each describe a set o...,(A) The motorcyle is the oldest\n(B) The limou...,newest to oldest,"[motorcyle, limousine, convertible]","[(('entity_1', 'motorcyle'), ('entity_2', 'lim...",1. **Interpreting the Triples:**\n\n Given t...,(B),(B),1
2,3,The following paragraphs each describe a set o...,(A) The blue book is the second from the left\...,left to right,"[blue_book, orange_book, red_book]","[(('entity_1', 'blue_book'), ('entity_2', '3')...",1. **Detailed Reasoning:**\n\n **Interpretin...,(C),(C),1
3,4,The following paragraphs each describe a set o...,(A) The robin is the rightmost\n(B) The blue j...,left to right,"[robin, blue_jay, crow]","[(('entity_1', 'crow'), ('entity_2', 'robin'),...",1. **Detailed Reasoning**:\n\n Given the qua...,(B),(B),1
4,5,The following paragraphs each describe a set o...,(A) The green book is the rightmost\n(B) The r...,left to right,"[green_book, red_book, blue_book]","[(('entity_1', 'red_book'), ('entity_2', '3'),...",1. **Interpreting each triple:**\n - The ord...,(B),(B),1
...,...,...,...,...,...,...,...,...,...,...
745,746,The following paragraphs each describe a set o...,(A) Joe finished second-to-last\n(B) Mel finis...,highest to lowest rank,"[Joe, Mel, Mya, Eve, Rob, Ada, Dan]","[(('entity_1', 'Rob'), ('entity_2', '1'), ('ed...",### Reasoning\n\nThe given quality used to ord...,(A),(A),1
746,747,The following paragraphs each describe a set o...,(A) The hawk is the second from the left\n(B) ...,left to right,"[hawk, hummingbird, quail, owl, crow, robin, c...","[(('entity_1', 'cardinal'), ('entity_2', '6'),...",1. **Interpretation of Triples Given the Quali...,(D),(D),1
747,748,The following paragraphs each describe a set o...,(A) The white book is the fourth from the left...,left to right,"[white_book, gray_book, yellow_book, purple_bo...","[(('entity_1', 'black_book'), ('entity_2', '6'...",1. **Interpreting the Triples**:\n - From th...,(A),(A),1
748,749,The following paragraphs each describe a set o...,(A) The quail is the third from the right\n(B)...,left to right,"[quail, raven, hummingbird, robin, falcon, owl...","[(('entity_1', 'blue_jay'), ('entity_2', 'falc...",### Reasoning\n\n**Quality Used to Order:** le...,(D),(F),0
749,750,The following paragraphs each describe a set o...,(A) The sedan is the third-newest\n(B) The tru...,oldest to newest,"[sedan, truck, bus, station_wagon, tractor, co...","[(('entity_1', 'truck'), ('entity_2', '1'), ('...","1. **Map-positions**: \n - Quality is ""oldes...",(A),(D),0

# Conventional Method

In [44]:
conventional_prompt_system = """
First, create a knowledge graph by extracting facts from each sentence in the given input story. Once this is
done, I will provide several statements. Your primary task is to determine the correctness of these statements. To
assess the validity of a statement, sort the objects in the graph and evaluate the correctness of each statement.
Provide step by step reasoning first. Then, print this heading on its own line (exactly as written):
### FINAL ANSWER
On the very next line, output ONLY the correct option letter in parentheses, e.g. (F)
Finally, end without adding anything after that word.
"""

conventional_prompt_human = """
<story>
{story}
</story>

<statements>
{statements}
</statements>
"""

conventional_prompt = ChatPromptTemplate(
    [("system", conventional_prompt_system),
     ("human", conventional_prompt_human)]
)

conventional_chain = conventional_prompt | llm_model | StrOutputParser()

In [45]:
conventional_answer_list = []

# batch questions to pass to the LLM
conventional_batch = []

for i in range(len(questions)):
    conventional_batch.append({
        "story": questions[i],
        "statements": options[i]
    })

In [46]:
conventional_answers_str_list = conventional_chain.batch(conventional_batch)

In [47]:
for i, answer_str in enumerate(conventional_answers_str_list):
    print(f"Final Answer for Question {i + 1}: {answer_str}")
    conventional_answer_list.append(answer_str)
    print("-" * 40)

Final Answer for Question 1: To determine the correctness of the statements, we first need to construct a knowledge graph based on the story provided.

**Knowledge Graph Construction:**

- We have three birds: Blue jay, Quail, Falcon.
- The arrangement on the branch is as follows:
  1. "The falcon is to the right of the blue jay." This means the falcon is positioned after the blue jay. Therefore, falcon is farther to the right compared to the blue jay.
  2. "The blue jay is to the right of the quail." This indicates the blue jay is positioned after the quail, meaning the blue jay is farther to the right compared to the quail.

Based on these two points, the arrangement from left to right is: Quail, Blue jay, Falcon.

**Evaluation of Statements:**

(A) The blue jay is the second from the left.
- According to our arrangement (Quail, Blue jay, Falcon), this statement is correct. Blue jay is indeed the second bird from the left.

(B) The quail is the second from the left.
- As per our arrangement, the quail is the first bird on the left, not the second. Therefore, this statement is incorrect.

(C) The falcon is the second from the left.
- In our arrangement, the falcon is the third bird from the left, not the second. Thus, this statement is incorrect.

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 2: To determine the correctness of the statements based on the information in the story, let's analyze the facts given:

1. We have three vehicles: a motorcycle, a limousine, and a convertible.
2. The motorcycle is newer than the limousine.
3. The convertible is newer than the motorcycle.

From these facts, we can deduce the following order from oldest to newest:

- The limousine is the oldest, as the motorcycle is newer than it.
- The motorcycle is in the middle, as it is newer than the limousine but older than the convertible.
- The convertible is the newest, as it is newer than the motorcycle.

Let's evaluate each statement:

(A) The motorcycle is the oldest.
- This is false because the limousine is older than the motorcycle.

(B) The limousine is the oldest.
- This is true because the limousine is older than both the motorcycle and the convertible.

(C) The convertible is the oldest.
- This is false because the convertible is the newest among the three vehicles.

### FINAL ANSWER
(B)
----------------------------------------
Final Answer for Question 3: To assess the correctness of each statement, we can first construct the knowledge graph from the story that describes the order of the books:

1. There are three books:
   - Blue book
   - Orange book
   - Red book

2. Given information:
   - The blue book is the rightmost.
   - The orange book is the leftmost.

3. Using the provided information, we can deduce the position of each book from left to right:
   - Position 1 (leftmost): Orange book
   - Position 2: Red book (since it is not described as leftmost or rightmost, it must be in the middle position)
   - Position 3 (rightmost): Blue book

Now, evaluate the correctness of each statement:

(A) The blue book is the second from the left.
   - From the knowledge graph, the blue book is at position 3 (rightmost). Thus, it is not the second from the left. Therefore, this statement is incorrect.

(B) The orange book is the second from the left.
   - From the knowledge graph, the orange book is at position 1 (leftmost). Thus, it is not the second from the left. Therefore, this statement is incorrect.

(C) The red book is the second from the left.
   - From the knowledge graph, the red book is at position 2. Thus, it is indeed the second from the left. Therefore, this statement is correct.

The correct statement is (C).

### FINAL ANSWER
(C)
----------------------------------------
Final Answer for Question 4: To analyze the sentence and statements provided, let's first extract and sort the facts from the story into a knowledge graph:

1. Objects:
   - Robin
   - Blue Jay
   - Crow

2. Facts from the story:
   - The robin is to the right of the crow.
   - The robin is to the left of the blue jay.

Now, let's determine the correct arrangement of the three birds based on these facts:

- The robin is to the right of the crow, meaning the crow is on the far left, or at least left of the robin.
- The robin is to the left of the blue jay, meaning the blue jay is on the far right, or at least right of the robin.

Given these conditions, the correct order of the birds on the branch from left to right must be:

1. Crow
2. Robin
3. Blue Jay

Now, analyze the statements:

(A) The robin is the rightmost.
   - Based on our arrangement (Crow, Robin, Blue Jay), the robin is not the rightmost; the blue jay is.

(B) The blue jay is the rightmost.
   - According to our arrangement, this is correct; the blue jay is indeed the rightmost bird.

(C) The crow is the rightmost.
   - As per the arrangement, the crow is the leftmost bird, not the rightmost.

So, the correct statement is:

### FINAL ANSWER

(B)
----------------------------------------
Final Answer for Question 5: To solve this problem, we need to create a knowledge graph from the given story and use it to verify the statements.

### Extracting Facts:

1. There are three books: a green book, a red book, and a blue book.
2. The red book is the rightmost. This means the red book is at the far right position on the shelf.
3. The blue book is to the right of the green book. This means the blue book is placed further to the right compared to the green book, but not necessarily the rightmost.

From these facts, we can deduce the arrangement on the shelf from left to right:
- Since the red book is the rightmost, it must be on the far right.
- The blue book, being to the right of the green book but not further right than the red book, must be in the middle.
- Consequently, the green book is on the far left.

Thus, the arrangement from left to right on the shelf is:
1. Green Book
2. Blue Book
3. Red Book

### Analyzing Statements:

(A) The green book is the rightmost: False. The green book is on the far left.
(B) The red book is the rightmost: True. The story specifies that the red book is the rightmost.
(C) The blue book is the rightmost: False. The blue book is in the middle.

### FINAL ANSWER
(B)
----------------------------------------
Final Answer for Question 6: To determine the correctness of the statements, we need to extract the facts from the story and arrange the objects based on the given conditions:

1. The objects in the story are apples, peaches, and mangoes.
2. Let's define their prices as: Price(apple), Price(mango), Price(peach).

From the story, we have the following facts:
- The mangoes are less expensive than the peaches: Price(mango) < Price(peach)
- The apples are less expensive than the mangoes: Price(apple) < Price(mango)

Now, using these facts, we can arrange the fruits based on increasing price:
- Since Price(apple) < Price(mango), apples are cheaper than mangoes.
- Since Price(mango) < Price(peach), mangoes are cheaper than peaches.

So the order of the fruits from least to most expensive is:
1. Apples
2. Mangoes
3. Peaches

Now, let's evaluate the given statements based on this order:

(A) The apples are the second-most expensive
- Apples are the least expensive, not the second-most expensive. So, this statement is incorrect.

(B) The peaches are the second-most expensive
- Peaches are the most expensive, not the second-most expensive. So, this statement is incorrect.

(C) The mangoes are the second-most expensive
- Mangoes are indeed the second-most expensive according to the order. Thus, this statement is correct.

### FINAL ANSWER
(C)
----------------------------------------
Final Answer for Question 7: To solve this, let's first extract the facts from the story and create a knowledge graph of the order of the vehicles based on their age.

Based on the story:
1. We have three vehicles: a tractor, a truck, and a minivan.
2. The minivan is newer than the truck.
3. The tractor is older than the truck.

From these facts, we can order the vehicles based on their age:
- "The minivan is newer than the truck" implies: Minivan < Truck (Minivan is younger, or newer).
- "The tractor is older than the truck" implies: Tractor > Truck (Tractor is older).

Combining these two pieces of information:
- Minivan < Truck < Tractor

This ordering implies:
- The minivan is the youngest (newest).
- The truck is older than the minivan but younger than the tractor.
- The tractor is the oldest.

Now evaluate each statement:
(A) The tractor is the newest: Based on the order Tractor > Truck > Minivan, this is false.
(B) The truck is the newest: Based on the order Tractor > Truck > Minivan, this is false.
(C) The minivan is the newest: Based on the order Tractor > Truck > Minivan, this is true.

### FINAL ANSWER
(C)
----------------------------------------
Final Answer for Question 8: To evaluate the correctness of the statements, first, we'll construct a knowledge graph based on the narrative from the story.

**Story Analysis:**

1. Fact 1: There are three golfers - Eve, Rob, and Mel.
2. Fact 2: Rob finished below Mel.
3. Fact 3: Mel finished below Eve.

From these facts, we deduce the following order: Eve finished higher than Mel, and Mel finished higher than Rob. Therefore, the order of finishing is:
- Eve (first)
- Mel (second)
- Rob (third)

**Statement Analysis:**

(A) **Eve finished first**
   - According to our deduced order, Eve indeed finished first. This statement is correct.

(B) **Rob finished first**
   - Contrary to the order deduced (Eve > Mel > Rob), Rob finished last. Thus, this statement is incorrect.

(C) **Mel finished first**
   - Mel finished in between Eve and Rob, not first. Thus, this statement is incorrect.

With these conclusions, only statement (A) matches the deduced order of finishing positions.

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 9: To solve this problem, we need to construct a knowledge graph and visualize the arrangement of the books on the shelf based on the information provided in the story.

### Extracted Facts and Order Based on the Story:
1. There are three books: orange, yellow, and blue.
2. The blue book is to the right of the yellow book.
3. The orange book is the second from the left.

Let's analyze these facts:

- **Fact 3:** The orange book is in the second position from the left. It clearly means orange is the middle book.
- **Fact 2:** The blue book being to the right of the yellow book implies that yellow must be to the left of blue.

Based on these statements, we examine the possible arrangement:
1. The middle position is taken by the orange book, which is second from the left.
2. Since the blue book is to the right of the yellow book, we determine the arrangement of the books must be: Yellow on the leftmost, Orange in the middle, and Blue on the rightmost position.

Therefore, the order of the books from left to right is:
- Yellow Book (leftmost)
- Orange Book (middle)
- Blue Book (rightmost)

Next, let's verify the validity of each statement:

- **Statement (A):** "The orange book is the second from the left." - This is consistent with the order determined, so this statement is correct.
- **Statement (B):** "The yellow book is the second from the left." - This is incorrect, as the yellow book is at the first position (leftmost).
- **Statement (C):** "The blue book is the second from the left." - This is incorrect, as the blue book is at the third position (rightmost).

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 10: To solve this problem, we need to extract the facts and build a knowledge graph based on the story provided. The story gives us the following information:

1. The minivan is newer than the truck.
2. The station wagon is newer than the minivan.

From these facts, we can deduce the order of the vehicles from newest to oldest:

- The station wagon is newer than the minivan.
- The minivan is newer than the truck.

Based on this, the order from newest to oldest is:
1. Station Wagon
2. Minivan
3. Truck

Now, let's assess the correctness of each statement:

(A) The statement "The station wagon is the newest" aligns with our ordering where the station wagon is indeed the newest.

(B) The statement "The minivan is the newest" contradicts our ordering, since the minivan is not the newest; the station wagon is.

(C) The statement "The truck is the newest" contradicts our ordering, since the truck is the oldest.

Based on the analysis, statement (A) is the correct one.

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 11: To determine the correctness of the statements, we first create a knowledge graph based on the story:

1. Books involved:
   - Gray Book
   - Purple Book
   - Red Book

2. Facts extracted from the story:
   - The purple book is to the left of the red book.
   - The gray book is to the left of the purple book.

Now, let's sort the objects (books) based on the extracted facts:

- From the fact "The purple book is to the left of the red book," we know:
  - Order (partial): Purple Book, Red Book

- From the fact "The gray book is to the left of the purple book," we know:
  - Order (partial): Gray Book, Purple Book

Combining both facts gives us the full order:
- Gray Book, Purple Book, Red Book

Now, evaluate each statement:

(A) The gray book is the leftmost:
- According to the sorted order (Gray Book, Purple Book, Red Book), the gray book is indeed the leftmost.
- This statement is correct.

(B) The purple book is the leftmost:
- According to the sorted order (Gray Book, Purple Book, Red Book), the purple book is not the leftmost; it is in the middle.
- This statement is incorrect.

(C) The red book is the leftmost:
- According to the sorted order (Gray Book, Purple Book, Red Book), the red book is the rightmost.
- This statement is incorrect.

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 12: To solve the problem, let's first extract the facts and create a knowledge graph from the story:

1. There are three fruits sold at the stand: peaches, mangoes, and apples.
2. Peaches are more expensive than apples.
3. Mangoes are the cheapest.

From the given information:
- If mangoes are the cheapest, this implies they have the lowest price among the three fruits.
- Peaches are more expensive than apples, meaning apples are cheaper than peaches.

Based on the above reasoning, the order of fruits from cheapest to most expensive is:
1. Mangoes
2. Apples
3. Peaches

Now, evaluate each of the statements:

(A) The peaches are the second-most expensive.
- According to our ordered list, peaches are the most expensive, not the second-most expensive.
- Therefore, statement (A) is incorrect.

(B) The mangoes are the second-most expensive.
- According to our ordered list, mangoes are the cheapest and not the second-most expensive.
- Therefore, statement (B) is incorrect.

(C) The apples are the second-most expensive.
- From our ordering (Mangoes, Apples, Peaches), apples indeed are the second-most expensive.
- Therefore, statement (C) is correct.

### FINAL ANSWER
(C)
----------------------------------------
Final Answer for Question 13: To solve the problem, let's create a knowledge graph based on the story.

1. **Objects**: Three birds - blue jay, falcon, and hummingbird.
2. **Positions**:
   - The blue jay is to the right of the falcon.
   - The hummingbird is to the left of the falcon.

With these constraints, we need to determine the correct order of the birds.

Let's analyze:

- Since the hummingbird is to the left of the falcon, the hummingbird can't be on the far right. Thus, the hummingbird must be either first or second from the left.
- The blue jay being to the right of the falcon means the blue jay can't be leftmost. Thus, the blue jay must be either second or third from the left.

Considering the order possibilities:
- The only possible order that satisfies the constraints is: **Hummingbird, Falcon, Blue Jay**.
  - Hummingbird is to the left of both birds.
  - Falcon is in between the hummingbird and the blue jay.
  - Blue Jay is to the right of the falcon.

Now, let's evaluate each statement:

(A) The blue jay is the second from the left.
- Based on the determined order, the blue jay is the third from the left, not second. Thus, this statement is incorrect.

(B) The falcon is the second from the left.
- In the order "Hummingbird, Falcon, Blue Jay," the falcon indeed occupies the second position. Thus, this statement is correct.

(C) The hummingbird is the second from the left.
- The hummingbird is in the first position in the order "Hummingbird, Falcon, Blue Jay," not second. Thus, this statement is incorrect.

### FINAL ANSWER
(B)
----------------------------------------
Final Answer for Question 14: To solve the problem, we first need to arrange the objects (vehicles) based on the sentences in the story, and then evaluate which statement accurately considers the established order.

1. **Extract facts from the story:**
   - There are three vehicles: a minivan, a bus, and a sedan.
   - The sentence "The minivan is newer than the sedan" implies that in terms of age, the order starts with the sedan as the oldest, followed by the minivan.
   - The sentence "The minivan is older than the bus" further implies that in order of age, the order is: sedan (oldest), minivan, and bus (newest).

2. **Arrange the vehicles in order based on age (from oldest to newest):**
   - Sedan
   - Minivan
   - Bus

3. **Evaluate each of the given statements:**
   - **(A) The minivan is the second-newest.**
     - Based on the arrangement (sedan, minivan, bus), the minivan is indeed second from the newest (the bus being the newest), making this statement correct.

   - **(B) The bus is the second-newest.**
     - The bus is the newest (not the second-newest), making this statement incorrect.

   - **(C) The sedan is the second-newest.**
     - The sedan is the oldest, not the second-newest, thus making this statement incorrect.

Based on this analysis, only one statement is accurate according to the order determined from the facts given in the story.

### FINAL ANSWER
(A)
----------------------------------------
Final Answer for Question 15: To determine the correctness of each statement, we first extract facts from the sentences in the story and organize them in a meaningful order:

1. **Vehicles in the Show**: There are three vehicles: a hatchback, a convertible, and a tractor.

2. **Fact 1**: The convertible is older than the tractor. This implies:
   - Convertible > Tractor (in terms of age)

3. **Fact 2**: The hatchback is the second-newest. This implies:
   - There is one vehicle that is newer than the hatchback, and one that is older.

From Fact 2, since the hatchback is the second-newest, it means there is only one vehicle that is newer than it, and the third vehicle must be older than both the hatchback and the newest vehicle.

Considering all pieces of knowledge:
- If the hatchback is the second-newest, the oldest possible vehicle must logically be the convertible (since it's older than the tractor), leaving the tractor to be the newest.
- Thus the order from oldest to newest is: Convertible, Hatchback, Tractor.

We now evaluate the statements:

- Statement (A): "The hatchback is the second-newest."
  - This statement directly reflects Fact 2 and aligns with the derived order: Convertible (oldest), Hatchback (second-newest), Tractor (newest).
  - Therefore, Statement (A) is correct.

- Statement (B): "The convertible is the second-newest."
  - According to the derived order, the convertible is the oldest, not the second-newest.
  - Therefore, Statement (B) is incorrect.

- Statement (C): "The tractor is the second-newest."
  - According to the derived order, the tractor is the newest, not the second-newest.

In [48]:
def extract_final_answer(text):
    marker = "### FINAL ANSWER"
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == marker:
            # Return the very next non-empty line (in case there are blank lines)
            for next_line in lines[i+1:]:
                if next_line.strip():
                    return next_line.strip()
    return []

# Create a DataFrame to store the final answers
conventional_answers_df = pd.DataFrame({
    'question_number': [i + 1 for i in range(len(conventional_answers_str_list))],
    'question': questions,
    'options': options,
    'llm_response': conventional_answers_str_list,
    'final_answer': [extract_final_answer(answer) for answer in conventional_answers_str_list],
    'ground_truth': targets
})

conventional_answers_df

,question_number,question,options,llm_response,final_answer,ground_truth
0,1,The following paragraphs each describe a set o...,(A) The blue jay is the second from the left\n...,To determine the correctness of the statements...,(A),(A)
1,2,The following paragraphs each describe a set o...,(A) The motorcyle is the oldest\n(B) The limou...,To determine the correctness of the statements...,(B),(B)
2,3,The following paragraphs each describe a set o...,(A) The blue book is the second from the left\...,"To assess the correctness of each statement, w...",(C),(C)
3,4,The following paragraphs each describe a set o...,(A) The robin is the rightmost\n(B) The blue j...,To analyze the sentence and statements provide...,(B),(B)
4,5,The following paragraphs each describe a set o...,(A) The green book is the rightmost\n(B) The r...,"To solve this problem, we need to create a kno...",(B),(B)
...,...,...,...,...,...,...
745,746,The following paragraphs each describe a set o...,(A) Joe finished second-to-last\n(B) Mel finis...,"To solve this, we need to deduce the order of ...",(A),(A)
746,747,The following paragraphs each describe a set o...,(A) The hawk is the second from the left\n(B) ...,To determine the correctness of each statement...,(D),(D)
747,748,The following paragraphs each describe a set o...,(A) The white book is the fourth from the left...,To determine the correctness of the statements...,(A),(A)
748,749,The following paragraphs each describe a set o...,(A) The quail is the third from the right\n(B)...,Let's analyze the story's constraints and deri...,(F),(F)
749,750,The following paragraphs each describe a set o...,(A) The sedan is the third-newest\n(B) The tru...,"To solve this, we need to extract facts from t...",(D),(D)

In [49]:
# Add is_correct column to check if the final answer matches the ground truth
def check_correctness(row):
    return 1 if row['final_answer'] == row['ground_truth'] else 0

conventional_answers_df['is_correct'] = conventional_answers_df.apply(check_correctness, axis=1)
conventional_answers_df

,question_number,question,options,llm_response,final_answer,ground_truth,is_correct
0,1,The following paragraphs each describe a set o...,(A) The blue jay is the second from the left\n...,To determine the correctness of the statements...,(A),(A),1
1,2,The following paragraphs each describe a set o...,(A) The motorcyle is the oldest\n(B) The limou...,To determine the correctness of the statements...,(B),(B),1
2,3,The following paragraphs each describe a set o...,(A) The blue book is the second from the left\...,"To assess the correctness of each statement, w...",(C),(C),1
3,4,The following paragraphs each describe a set o...,(A) The robin is the rightmost\n(B) The blue j...,To analyze the sentence and statements provide...,(B),(B),1
4,5,The following paragraphs each describe a set o...,(A) The green book is the rightmost\n(B) The r...,"To solve this problem, we need to create a kno...",(B),(B),1
...,...,...,...,...,...,...,...
745,746,The following paragraphs each describe a set o...,(A) Joe finished second-to-last\n(B) Mel finis...,"To solve this, we need to deduce the order of ...",(A),(A),1
746,747,The following paragraphs each describe a set o...,(A) The hawk is the second from the left\n(B) ...,To determine the correctness of each statement...,(D),(D),1
747,748,The following paragraphs each describe a set o...,(A) The white book is the fourth from the left...,To determine the correctness of the statements...,(A),(A),1
748,749,The following paragraphs each describe a set o...,(A) The quail is the third from the right\n(B)...,Let's analyze the story's constraints and deri...,(F),(F),1
749,750,The following paragraphs each describe a set o...,(A) The sedan is the third-newest\n(B) The tru...,"To solve this, we need to extract facts from t...",(D),(D),1