In [1]:
import os
import pandas as pd

In [2]:
# Set the path to your directory
directory_path = "outputs/pre_revised_answers"
# directory_path = "outputs/conventional_answers"

# Get all CSV files in the directory
csv_files = [f for f in os.listdir(directory_path) if f.endswith('.csv')]

# Read and combine them into one DataFrame
df_list = [pd.read_csv(os.path.join(directory_path, file)) for file in csv_files]
combined_df = pd.concat(df_list, ignore_index=True)

# combined_df.to_csv("outputs/combined_df.csv", index=False)
combined_df.drop(columns=['reason'], inplace=True)
combined_df

,batch_num,question_num,chain,target_text,num_hops,final_answer
0,0,0,Clarence (has_granddaughter) -> Emily (has_bro...,grandson,2,Grandson
1,0,1,Clarence (has_grandson) -> Tony (has_sister) -...,granddaughter,2,Granddaughter
2,0,2,Clarence (has_grandson) -> Jeff (has_sister) -...,granddaughter,2,Granddaughter
3,0,3,Ashley (has_grandson) -> Tony (has_sister) -> ...,granddaughter,2,Granddaughter
4,0,4,Ashley (has_grandmother) -> Emily (has_brother...,grandson,2,Uncle
...,...,...,...,...,...,...
63,1,14,William (has_wife) -> Margaret (has_sister) ->...,sister,10,Sister
64,1,15,Ellen (has_daughter) -> Nadia (has_brother) ->...,niece,10,Grandmother
65,1,16,Charles (has_mother) -> Ellen (has_brother) ->...,grandmother,10,Grandmother
66,1,17,James (has_father) -> Orville (has_brother) ->...,nephew,10,Nephew
67,1,18,Patrice (has_mother) -> Nora (has_aunt) -> Ell...,nephew,10,Grandson

In [3]:
combined_df['final_answer'] = combined_df['final_answer'].str.lower()
combined_df['target_text'] = combined_df['target_text'].str.lower()
# combined_df['revised_answer'] = combined_df['revised_answer'].str.lower()
# combined_df['pass'] = combined_df.apply(
#     lambda row: 1 if str(row['target_text']).replace('-', '') in str(row['revised_answer']) else 0, axis=1
# )
combined_df['pass'] = combined_df.apply(
    lambda row: 1 if str(row['target_text']).replace('-', '') in str(row['final_answer']) else 0, axis=1
)
combined_df.to_csv("outputs/combined_df.csv", index=False)
combined_df

,batch_num,question_num,chain,target_text,num_hops,final_answer,pass
0,0,0,Clarence (has_granddaughter) -> Emily (has_bro...,grandson,2,grandson,1
1,0,1,Clarence (has_grandson) -> Tony (has_sister) -...,granddaughter,2,granddaughter,1
2,0,2,Clarence (has_grandson) -> Jeff (has_sister) -...,granddaughter,2,granddaughter,1
3,0,3,Ashley (has_grandson) -> Tony (has_sister) -> ...,granddaughter,2,granddaughter,1
4,0,4,Ashley (has_grandmother) -> Emily (has_brother...,grandson,2,uncle,0
...,...,...,...,...,...,...,...
63,1,14,William (has_wife) -> Margaret (has_sister) ->...,sister,10,sister,1
64,1,15,Ellen (has_daughter) -> Nadia (has_brother) ->...,niece,10,grandmother,0
65,1,16,Charles (has_mother) -> Ellen (has_brother) ->...,grandmother,10,grandmother,1
66,1,17,James (has_father) -> Orville (has_brother) ->...,nephew,10,nephew,1
67,1,18,Patrice (has_mother) -> Nora (has_aunt) -> Ell...,nephew,10,grandson,0

In [ ]:
# For conventional answers
combined_df['final_answer'] = combined_df['answer'].str.lower()
combined_df['target_text'] = combined_df['target_text'].str.lower()
combined_df['pass'] = combined_df.apply(
    lambda row: 1 if str(row['target_text']).replace('-', '') in str(row['final_answer']) else 0, axis=1
)
combined_df.to_csv("outputs/combined_df.csv", index=False)
combined_df

In [ ]:
combined_df['pass_pre_revised'] = combined_df.apply(
    lambda row: 1 if str(row['target_text']).replace('-', '') in str(row['final_answer']) else 0, axis=1
)
combined_df

In [ ]:
pass_count = combined_df['pass'].sum()
print(f"Total number of questions passed: {pass_count}")
pass_pre_revised_count = combined_df['pass_pre_revised'].sum()
print(f"Total number of questions passed before revision: {pass_pre_revised_count}")

In [ ]:
import os
import pandas as pd

# Set the path to your directory
conventional_directory_path = "outputs/conventional_answers"

# Get all CSV files in the directory
conventional_csv_files = [f for f in os.listdir(conventional_directory_path) if f.endswith('.csv')]

# Read and combine them into one DataFrame
conventional_df_list = [pd.read_csv(os.path.join(conventional_directory_path, file)) for file in conventional_csv_files]
conventional_combined_df = pd.concat(conventional_df_list, ignore_index=True)

conventional_combined_df

In [ ]:
def select_pass_row(group):
    # If there's at least one row with pass == 1, return the first of those
    if any(group['pass'] == 1):
        return group[group['pass'] == 1].iloc[0]
    else:
        return group.iloc[0]  # just return one row (all are pass == 0)


# Apply this logic to each group
grouped_df = combined_df.groupby(['batch_num', 'question_num'], as_index=False).apply(select_pass_row)

# Reset index if needed (since groupby + apply creates a multi-index)
grouped_df.reset_index(drop=True, inplace=True)
grouped_df.head(10)

In [ ]:
from datasets import load_dataset
import ast

ds = load_dataset("CLUTRR/v1", "gen_train234_test2to10")
df_test = ds['test'].to_pandas()
df_test['story_edges_list'] = df_test['story_edges'].apply(ast.literal_eval)
df_test['num_hops'] = df_test['story_edges_list'].apply(len)
df_test = df_test[['num_hops']]
df_test = df_test.groupby('num_hops').size().reset_index(name='count')
df_test

In [ ]:
total_questions_count = len(grouped_df.index)
print(f"total questions with answers: {total_questions_count}")

In [ ]:
num_pass = (grouped_df['pass'] == 1).sum()
print(f"total accurate answers: {num_pass}")

In [ ]:
total_accuracy = (num_pass / total_questions_count) * 100.0
print(f"accuracy: {total_accuracy:.2f}%")

In [ ]:
import matplotlib.pyplot as plt

# Group by num_hops
grouped_hop_count_df = grouped_df.groupby('num_hops')['pass'].sum().reset_index()
merged_df = grouped_hop_count_df.merge(df_test, on='num_hops', how='left')
merged_df

In [ ]:
# Set 'num_hops' as index so the bars align with hop counts
merged_df.set_index('num_hops', inplace=True)

# Calculate percentage of pass == 1
percent_pass = (merged_df['pass'] / merged_df['count'] * 100).round(2)
question_count = merged_df['count']

# Plotting
ax = percent_pass.plot(kind='bar', color='skyblue', edgecolor='black')
plt.title('Accuracy by number of hops')
plt.xlabel('number of hops')
plt.ylabel('Accuracy (%)')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

# Add annotations
for i, (pct, count) in enumerate(zip(percent_pass, question_count)):
    ax.text(i, pct + 1, f"{pct}%", ha='center', va='bottom', color='black', fontweight='bold')
    ax.text(i, 1, f"{count}", ha='center', va='bottom', color='black', fontweight='normal')  # Near base of the bar

plt.show()

In [ ]:
"""
Selected questions for the sample :-

hops 2:
- correct in both o3-mini and 4o - 0, 2
- correct in o3-mini but wrong in 4o - 5, 7
- correct in 4o but wrong in o3-mini -
- wrong in both o3-mini and 4o - 1, 12

hops 3:
- correct in both o3-mini and 4o - 39, 42
- correct in o3-mini but wrong in 4o - 40, 41
- correct in 4o but wrong in o3-mini - 140
- wrong in both o3-mini and 4o - 38, 46

hops 4:
- correct in both o3-mini and 4o - 146, 147
- correct in o3-mini but wrong in 4o - 148, 149
- correct in 4o but wrong in o3-mini - 166, 184
- wrong in both o3-mini and 4o - 145, 150

hops 5:
- correct in both o3-mini and 4o - 223, 224
- correct in o3-mini but wrong in 4o - 226, 227
- correct in 4o but wrong in o3-mini - 242, 347
- wrong in both o3-mini and 4o - 222, 225

hops 6:
- correct in both o3-mini and 4o - 502, 510
- correct in o3-mini but wrong in 4o - 500, 503
- correct in 4o but wrong in o3-mini - 505, 450
- wrong in both o3-mini and 4o - 501, 507

hops 7:
- correct in both o3-mini and 4o - 514, 524
- correct in o3-mini but wrong in 4o - 513, 518
- correct in 4o but wrong in o3-mini - 512, 523
- wrong in both o3-mini and 4o - 517, 526

hops 8:
- correct in both o3-mini and 4o - 671, 674
- correct in o3-mini but wrong in 4o - 668, 669
- correct in 4o but wrong in o3-mini - 670, 711
- wrong in both o3-mini and 4o - 667, 673

hops 9:
- correct in both o3-mini and 4o - 804, 805
- correct in o3-mini but wrong in 4o - 803, 807
- correct in 4o but wrong in o3-mini - 827, 852
- wrong in both o3-mini and 4o - 806, 809

hops 10:
- correct in both o3-mini and 4o - 935, 938
- correct in o3-mini but wrong in 4o - 928, 932
- correct in 4o but wrong in o3-mini - 927, 942
- wrong in both o3-mini and 4o - 926, 931

"""

In [2]:
import re

def chain_to_triples(chain: str) -> str:
    """
    Converts a relationship chain like:
        "Ashley (has_grandson) -> Tony (has_sister) -> Charlotte"
    Into a list of triples:
        [("Ashley", "has_grandson", "Tony"), ("Tony", "has_sister", "Charlotte")]
    """
    # Split the chain into parts by '->'
    parts = [part.strip() for part in chain.split('->')]

    nodes = []
    relations = []

    for part in parts:
        match = re.match(r'^(\w+)(?:\s*\((\w+)\))?$', part)
        if match:
            name, relation = match.groups()
            nodes.append(name)
            if relation:
                relations.append(relation)
        else:
            raise ValueError(f"Invalid part format: {part}")

    # Sanity check
    if len(nodes) != len(relations) + 1:
        raise ValueError("The number of relationships must be one less than the number of entities.")

    # Build triples
    triples = [
        (nodes[i], relations[i], nodes[i + 1])
        for i in range(len(relations))
    ]

    return_str = ""
    for i, (subject, relation, obj) in enumerate(triples):
        return_str += f"{i + 1}. ({subject}, {relation}, {obj})" + " \n"

    return return_str

In [7]:
print(chain_to_triples('Frances (has_father_in_law) -> Hugh (has_daughter) -> Vanetta'))

1. (Frances, has_father_in_law, Hugh)
2. (Hugh, has_daughter, Vanetta)