In [1]:
import json
import pandas as pd

BATCH_SIZE = 50
IS_DEBUG = True
DEBUG_QUESTION_SIZE = 10
LLM_MODEL = "gpt-4.1-mini"
DATASET_NAME = "hotpotQA"

In [2]:
from dotenv import load_dotenv
import os

load_dotenv()
openai_api_key = os.getenv("OPENAI_API_KEY")

## 1. Load the HotpotQA dataset

In [3]:
train_hotpot_qa_path = r'C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\hotpotQA\hotpot_train_v1.1.json'
test_hotpot_qa_path = r'C:\Users\Sudheera\Documents\Phd\LLMs_and_KGs\hotpotQA\hotpot_test_v1.1.json'

In [4]:
with open(train_hotpot_qa_path, 'r', encoding='utf-8') as f:
    train_hotpot_qa_json = json.load(f)

with open(test_hotpot_qa_path, 'r', encoding='utf-8') as f:
    test_hotpot_qa_json = json.load(f)

In [5]:
def divide_and_batch(train_json, batch_size):
    batch_context = []
    batch_question = []
    batch_answer = []

    for i in range(0, len(train_json), batch_size):
        batch = train_json[i:i + batch_size]
        context = []
        question = []
        answer = []

        for item in batch:
            context_text = ""
            j = 1
            for ctx in item['context']:
                context_text += f"Title {j} : {ctx[0]} \nParagraph {j} : {''.join(ctx[1])}\n"
                j += 1
            context.append(context_text)
            question.append(item['question'])
            answer.append(item['answer'])

        batch_context.append(context)
        batch_question.append(question)
        batch_answer.append(answer)

    return batch_context, batch_question, batch_answer

In [6]:
if IS_DEBUG:
    train_hotpot_qa_json = train_hotpot_qa_json[:DEBUG_QUESTION_SIZE]
    test_hotpot_qa_json = test_hotpot_qa_json[:DEBUG_QUESTION_SIZE]
    batch_context, batch_question, batch_answer = divide_and_batch(train_hotpot_qa_json, BATCH_SIZE)
else:
    batch_context, batch_question, batch_answer = divide_and_batch(test_hotpot_qa_json, BATCH_SIZE)

In [7]:
for i in range(len(batch_context[0])):
    print(f"Batch {i + 1}:")
    print("Context:", batch_context[0][i])
    print("Question:", batch_question[0][i])
    print("Answer:", batch_answer[0][i])
    print("-" * 50)
    if i == 9:  # Limit to 3 batches for brevity
        break

Batch 1:
Context: Title 1 : Radio City (Indian radio station)
Paragraph 1 : Radio City is India's first private FM radio station and was started on 3 July 2001. It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003). It plays Hindi, English and regional songs. It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007. Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features. The Radio station currently plays a mix of Hindi and Regional music. Abraham Thomas is the CEO of the company.
Title 2 : History of Albanian football
Paragraph 2 : Football in Albania existed before the Albanian Football Federation (FSHF) was created. This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) . Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946. In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.
Title 3 : Echosmith
Paragraph 3 : Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California. Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016. Echosmith started first as "Ready Set Go!" until they signed to Warner Bros. Records in May 2012. They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia. The song was Warner Bros. Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold. The band's debut album, "Talking Dreams", was released on October 8, 2013.
Title 4 : Women's colleges in the Southern United States
Paragraph 4 : Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States. Many started first as girls' seminaries or academies. Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women. Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.
Title 5 : First Arthur County Courthouse and Jail
Paragraph 5 : The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.
Title 6 : Arthur's Magazine
Paragraph 6 : Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century. Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others. In May 1846 it was merged into "Godey's Lady's Book".
Title 7 : 2014–15 Ukrainian Hockey Championship
Paragraph 7 : The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship. Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues. Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014. The regular season included just 12 rounds, where all the teams went to the semifinals. In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.
Title 8 : First for Women
Paragraph 8 : First for Women is a woman's magazine published by Bauer Media Group in the USA. The magazine was started in 1989. It is based in Englewood Cliffs, New Jersey. In 2011 the circulation of the magazine was 1,310,696 copies.
Title 9 : Freeway Complex Fire
Paragraph 9 : The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California. The fire started as two separate fires on November 15, 2008. The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later. These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.
Title 10 : William Rast
Paragraph 10 : William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala. It is most known for their premium jeans. On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line. The label also produces other clothing items such as jackets and tops. The company started first as a denim line, later evolving into a men’s and women’s clothing line.

Question: Which magazine was started first Arthur's Magazine or First for Women?
Answer: Arthur's Magazine
--------------------------------------------------
Batch 2:
Context: Title 1 : Ritz-Carlton Jakarta
Paragraph 1 : The Ritz-Carlton Jakarta is a hotel and skyscraper in Jakarta, Indonesia and 14th Tallest building in Jakarta. It is located in city center of Jakarta, near Mega Kuningan, adjacent to the sister JW Marriott Hotel. It is operated by The Ritz-Carlton Hotel Company. The complex has two towers that comprises a hotel and the Airlangga Apartment respectively. The hotel was opened in 2005.
Title 2 : Oberoi family
Paragraph 2 : The Oberoi family is an Indian family that is famous for its involvement in hotels, namely through The Oberoi Group.
Title 3 : Ishqbaaaz
Paragraph 3 : Ishqbaaaz (English: "Lovers") is an Indian drama television series which is broadcast on Star Plus. It premiered on 27 June 2016 and airs Mon-Fri 10-11pm IST.Nakuul Mehta, Kunal Jaisingh and Leenesh Mattoo respectively portray Shivaay, Omkara and Rudra, the three heirs of the Oberoi family. The show initially focused on the tale of three brothers, later become centered on the love story of Shivaay and Annika (Surbhi Chandna); with the story of Omkara and Rudra being shifted to the spinoff series "Dil Boley Oberoi". In July 2017 "Dil Boley Oberoi" ended and the storylines were merged back into "Ishqbaaaz" which doubled its runtime.
Title 4 : Hotel Tallcorn
Paragraph 4 : The Hotel Tallcorn is located in Marshalltown, Iowa. Today it is called the Tallcorn Towers Apartments. Built in 1928 by the Eppley Hotel Company, local citizens contributed $120,000 to ensure the successful completion of this seven-story hotel. It was completed in connection to the seventy-fifth anniversary of Marshalltown. The hotel's sale in 1956 from the Eppley chain to the Sheraton Corporation was part of the second largest hotel sale in United States history. The Tallcorn was listed as a contributing property in the Marshalltown Downtown Historic District on the National Register of Historic Places in 2002.
Title 5 : Mohan Singh Oberoi
Paragraph 5 : Rai Bahadur Mohan Singh Oberoi (15 August 1898 – 3 May 2002) was an Indian hotelier, the founder and chairman of Oberoi Hotels & Resorts, India's second-largest hotel company, with 35 hotels in India, Sri Lanka, Nepal, Egypt, Australia and Hungary.
Title 6 : Hotel Bond
Paragraph 6 : Hotel Bond is a historic hotel, built in two stages in 1913 and 1921, in downtown Hartford, Connecticut by hotelier Harry S. Bond. It is located near Bushnell Park, and was considered the grandest hotel in Hartford during its heyday. The second section is a 12 story building attached to the 6 story first section. A Statler Hotel opened in the area in 1954, creating competition, and the Bond Hotel company declared bankruptcy shortly after that. It was bought by the California-based Masaglia Hotel chain, which began an incremental renovation program. In 1964 it was sold to a Cincinnati, Ohio investment group which announced extensive renovation plans. However, the financing plans fell through and the hotel was again in bankruptcy. The building was sold at auction to the Roman Catholic Archdiocese of Hartford in 1965, and it became the home of the Saint Francis Hospital School of Nursing. The Bond Ballroom reopened in 2001, with the rest of the building becoming a Homewood Suites by Hilton in 2006.
Title 7 : The Oberoi Group
Paragraph 7 : The Oberoi Group is a hotel company with its head office in Delhi. Founded in 1934, the company owns and/or operates 30+ luxury hotels and two river cruise ships in six countries, primarily under its Oberoi Hotels & Resorts and Trident Hotels brands.
Title 8 : Future Fibre Technologies
Paragraph 8 : Future Fibre Technologies (FFT) is a fiber optic sensing technologies company based in Melbourne, Australia, with its US head office in Mountain View, California, Middle East head office in Dubai, Indian head office in New Delhi and European head office in London. Founded in 1994, Future Fibre Technologies product line provides optical fiber intrusion detection systems for perimeters, buried oil and gas pipelines and data communication networks.
Title 9 : 289th Military Police Company
Paragraph 9 : The 289th Military Police Company was activated on 1 November 1994 and attached to Hotel Company, 3rd Infantry (The Old Guard), Fort Myer, Virginia. Hotel Company is the regiment's specialty company.
Title 10 : Glennwanis Hotel
Paragraph 10 : The Glennwanis Hotel is a historic hotel in Glennville, Georgia, Tattnall County, Georgia, built on the site of the Hughes Hotel. The hotel is located at 209-215 East Barnard Street. The old Hughes Hotel was built out of Georgia pine circa 1905 and burned in 1920. The Glennwanis was built in brick in 1926. The local Kiwanis club led the effort to get the replacement hotel built, and organized a Glennville Hotel Company with directors being local business leaders. The wife of a local doctor won a naming contest with the name "Glennwanis Hotel", a suggestion combining "Glennville" and "Kiwanis".

Question: The Oberoi family is part of a hotel company that has a head office in what city?
Answer: Delhi
--------------------------------------------------
Batch 3:
Context: Title 1 : Lisa Simpson
Paragraph 1 : Lisa Marie Simpson is a fictional character in the animated television series "The Simpsons". She is the middle child and most intelligent of the Simpson family. Voiced by Yeardley Smith, Lisa first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed her while waiting to meet James L. Brooks. Groening had been invited to pitch a series of shorts based on his comic "Life in Hell", but instead decided to create a new set of characters. He named the elder Simpson daughter after his younger sister Lisa Groening. After appearing on "The Tracey Ullman Show" for three years, the Simpson family were moved to their own series on Fox, which debuted on December 17, 1989.
Title 2 : Marge Simpson
Paragraph 2 : Marjorie Jacqueline "Marge" Simpson (née Bouvier) is a fictional character in the American animated sitcom "The Simpsons" and part of the eponymous family. She is voiced by Julie Kavner and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Marge was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on "Life in Hell" but instead decided to create a new set of characters. He named the character after his mother Margaret Groening. After appearing on "The Tracey Ullman Show" for three seasons, the Simpson family received their own series on Fox, which debuted December 17, 1989.
Title 3 : Bart Simpson
Paragraph 3 : Bartholomew JoJo "Bart" Simpson is a fictional character in the American animated television series "The Simpsons" and part of the Simpson family. He is voiced by Nancy Cartwright and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed Bart while waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip, "Life in Hell", but instead decided to create a new set of characters. While the rest of the characters were named after Groening's family members, Bart's name is an anagram of the word "brat". After appearing on "The Tracey Ullman Show" for three years, the Simpson family received its own series on Fox, which debuted December 17, 1989.
Title 4 : Allie Goertz
Paragraph 4 : Allison Beth "Allie" Goertz (born March 2, 1991) is an American musician. Goertz is known for her satirical songs based on various pop culture topics. Her videos are posted on YouTube under the name of Cossbysweater. Subjects of her songs have included the film "The Room", the character Milhouse from the television show "The Simpsons", and the game Dungeons & Dragons. Her style has been compared to that of Bo Burnham. In December 2015, Goertz released a concept album based on the Adult Swim series "Rick and Morty", "Sad Dance Songs", with the album's cover emulating the animation and logo of the series. The album was made possible through Kickstarter. She is co-host of Everything's Coming Up Podcast, a Simpsons-focused podcast along with Julia Prescott.
Title 5 : Milhouse Van Houten
Paragraph 5 : Milhouse Mussolini van Houten is a fictional character featured in the animated television series "The Simpsons", voiced by Pamela Hayden, and created by Matt Groening who named the character after President Richard Nixon's middle name. Later in the series, it is revealed that Milhouse's middle name is "Mussolini."
Title 6 : Los Angeles Reader
Paragraph 6 : Los Angeles Reader was a weekly paper established in 1978 and distributed in Los Angeles, United States. It followed the format of the (still active) Chicago Reader. The paper was known for having lengthy, thoughtful reviews of movies, plays and concerts in the LA area. James Vowell was its founding editor. Among its writers were Keith Fitzgerald, Nigey Lennon, Lionel Rolfe, Lawrence Wechsler, Mick Farren, Richard Meltzer, Heidi Dvorak, Chris Morris, Jerry Stahl, Steven Kane, Andy Klein, Allen Levy, Jim Goad, Kirk Silsbee, Henry Sheehan, Samantha Dunn, Natalie Nichols, Steve Appleford, Eric Mankin (also editor), Paul Birchall, Eddie Rivera (who wrote the paper's first cover story), Amy Steinberg, Harry Sheehan, Dan Sallit, Myron Meisel, David Ehrenstein. Tom Davis, Bruce Bebb, Stuart Goldman, Ernest Hardy, Kevin Uhrich, Erik Himmelsbach and David L. Ulin. It is famous for being the first newspaper to publish Matt Groening's cartoon strip, Life in Hell on April 25, 1980. James Vowell hired Matt Groening as his assistant editor in 1979. Groening was also originally a Reader music critic. It also ran a cartoon strip by David Lynch (director of Blue Velvet) called The Angriest Dog in the World, a strip notable for having exactly the same drawing panels for its entire run. James Vowell and his wife Codette Wallace bought the Reader from the Chicago Reader in February 1989. They sold "The Reader" to New Times Media in 1996, which merged it with the "Los Angeles View" to form "New Times LA".
Title 7 : Homer Simpson
Paragraph 7 : Homer Jay Simpson is a fictional character and the main protagonist of the American animated television series "The Simpsons" as the patriarch of the eponymous family. He is voiced by Dan Castellaneta and first appeared on television, along with the rest of his family, in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Homer was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip "Life in Hell" but instead decided to create a new set of characters. He named the character after his father, Homer Groening. After appearing for three seasons on "The Tracey Ullman Show", the Simpson family got their own series on Fox that debuted December 17, 1989.
Title 8 : List of The Simpsons video games
Paragraph 8 : "The Simpsons" is an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company. The series is a satirical parody of a middle class American lifestyle epitomized by its eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. It is set in the fictional town of Springfield, and lampoons American culture, society and television, and many aspects of the human condition. The family was conceived by Groening shortly before a pitch for a series of animated shorts with producer James L. Brooks. Groening created a dysfunctional family and named the characters after members of his own family, substituting Bart for his own name. The shorts became a part of "The Tracey Ullman Show" on April 19, 1987 and after a three-season run, the sketch was developed into a half-hour prime time show and became a hit series for Fox. The growing popularity of the series motivated video game developers to create video games based on the series. Two pinball machines have also been produced; one self-titled, that was only made available for a limited time after the first season finale (1990) and "The Simpsons Pinball Party" (2003). Additionally, several handheld device games have been released, such as "Bartman: Avenger of Evil" (1990) and "Bart Simpson's Cupcake Crisis" (1991).
Title 9 : The Simpsons: An Uncensored, Unauthorized History
Paragraph 9 : The Simpsons: An Uncensored, Unauthorized History is a non-fiction book about the American animated television series "The Simpsons". It was written by John Ortved, and first published in October 2009 by Faber and Faber. In the United Kingdom, the book is called Simpsons Confidential: The uncensored, totally unauthorised history of the world's greatest TV show by the people that made it. The book is an oral history of the show, and concentrates particularly on the writers and producers of the show. The book includes entire chapters devoted to key figures such as creator Matt Groening and James L. Brooks and Sam Simon, who helped develop the series. According to National Public Radio reviewer Linda Holmes, "Ortved's thesis, essentially, is that lots of people are responsible for the success of "The Simpsons", and their creator, Matt Groening, has too often been viewed as the sole source to the detriment of others who also deserve to be praised."
Title 10 : List of The Simpsons guest stars
Paragraph 10 : In addition to the show's regular cast of voice actors, celebrity guest stars have been a staple of "The Simpsons", an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company, since its first season. "The Simpsons" focuses on the eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. The family was initially conceived by Groening for a series of animated shorts, which originally aired as a part of "The Tracey Ullman Show" between 1987 and 1989. The shorts were developed into a half-hour prime time series which began in December 1989. The series' 27th season began in September 2015 and episodes of "The Simpsons" have aired. A feature film adaptation of the series called "The Simpsons Movie", was released in 2007.

Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
Answer: President Richard Nixon

In [8]:
del train_hotpot_qa_json
del test_hotpot_qa_json

## 2. Generate LLM pipeline

In [9]:
from langchain_openai import ChatOpenAI
from langchain_core.globals import set_debug, set_verbose, set_llm_cache
from langchain_community.cache import InMemoryCache
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

set_debug(False)
set_verbose(False)
set_llm_cache(InMemoryCache())

llm_model = ChatOpenAI(model=LLM_MODEL, api_key=openai_api_key)

In [10]:
conventional_prompt_system = """
First, create a knowledge graph by extracting facts from each sentence in the given input story. Once this is
done, I will pose a complex question requiring multi-step reasoning. Decompose the question into simpler
sub-questions focusing on identifying crucial entities, their relationships, and specific details. Tackle these
sub-questions sequentially, referencing the knowledge graph for information. Connect the answers from these
sub-questions step by step, until arrive at a final answer to the initial complex question.
Provide step by step reasoning first. Then, print this heading on its own line (exactly as written):
### FINAL ANSWER
On the very next line, output ONLY the answer to the question.
Finally, end without adding anything after that word.
"""

conventional_prompt_human = """
<story>
{story}
</story>

<question>
{question}
</question>
"""

conventional_prompt = ChatPromptTemplate(
    [("system", conventional_prompt_system),
     ("human", conventional_prompt_human)]
)

conventional_chain = conventional_prompt | llm_model | StrOutputParser()

## 3. Generating batches

In [11]:
batch_input_list = []
main_df = pd.DataFrame()

for i in range(len(batch_context)):
    batch_num_list = [i] * len(batch_context[i])
    question_num_list = list(range(1, len(batch_context[i]) + 1))
    context_list = []
    question_list = []
    answers_list = []

    batch_input_item = []
    j = 0
    for batch in range(len(batch_context[i])):
        context = batch_context[i][batch]
        batch_input_item.append({
            "story": context,
            "question": batch_question[i][j]
        })
        context_list.append(context)
        question_list.append(batch_question[i][j])
        answers_list.append(batch_answer[i][j])
        j += 1
    batch_input_list.append(batch_input_item)
    df = pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "context": context_list,
        "question": question_list,
        "answer": answers_list
    })
    main_df = pd.concat([main_df, df], ignore_index=True)

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1}:")
    for item in batch:
        print("story:", item['story'])
        print("question:", item['question'])
        print("-" * 50)

Batch 1:
story: Title 1 : Radio City (Indian radio station)
Paragraph 1 : Radio City is India's first private FM radio station and was started on 3 July 2001. It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003). It plays Hindi, English and regional songs. It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007. Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features. The Radio station currently plays a mix of Hindi and Regional music. Abraham Thomas is the CEO of the company.
Title 2 : History of Albanian football
Paragraph 2 : Football in Albania existed before the Albanian Football Federation (FSHF) was created. This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) . Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946. In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.
Title 3 : Echosmith
Paragraph 3 : Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California. Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016. Echosmith started first as "Ready Set Go!" until they signed to Warner Bros. Records in May 2012. They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia. The song was Warner Bros. Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold. The band's debut album, "Talking Dreams", was released on October 8, 2013.
Title 4 : Women's colleges in the Southern United States
Paragraph 4 : Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States. Many started first as girls' seminaries or academies. Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women. Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.
Title 5 : First Arthur County Courthouse and Jail
Paragraph 5 : The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.
Title 6 : Arthur's Magazine
Paragraph 6 : Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century. Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others. In May 1846 it was merged into "Godey's Lady's Book".
Title 7 : 2014–15 Ukrainian Hockey Championship
Paragraph 7 : The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship. Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues. Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014. The regular season included just 12 rounds, where all the teams went to the semifinals. In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.
Title 8 : First for Women
Paragraph 8 : First for Women is a woman's magazine published by Bauer Media Group in the USA. The magazine was started in 1989. It is based in Englewood Cliffs, New Jersey. In 2011 the circulation of the magazine was 1,310,696 copies.
Title 9 : Freeway Complex Fire
Paragraph 9 : The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California. The fire started as two separate fires on November 15, 2008. The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later. These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.
Title 10 : William Rast
Paragraph 10 : William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala. It is most known for their premium jeans. On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line. The label also produces other clothing items such as jackets and tops. The company started first as a denim line, later evolving into a men’s and women’s clothing line.

question: Which magazine was started first Arthur's Magazine or First for Women?
--------------------------------------------------
story: Title 1 : Ritz-Carlton Jakarta
Paragraph 1 : The Ritz-Carlton Jakarta is a hotel and skyscraper in Jakarta, Indonesia and 14th Tallest building in Jakarta. It is located in city center of Jakarta, near Mega Kuningan, adjacent to the sister JW Marriott Hotel. It is operated by The Ritz-Carlton Hotel Company. The complex has two towers that comprises a hotel and the Airlangga Apartment respectively. The hotel was opened in 2005.
Title 2 : Oberoi family
Paragraph 2 : The Oberoi family is an Indian family that is famous for its involvement in hotels, namely through The Oberoi Group.
Title 3 : Ishqbaaaz
Paragraph 3 : Ishqbaaaz (English: "Lovers") is an Indian drama television series which is broadcast on Star Plus. It premiered on 27 June 2016 and airs Mon-Fri 10-11pm IST.Nakuul Mehta, Kunal Jaisingh and Leenesh Mattoo respectively portray Shivaay, Omkara and Rudra, the three heirs of the Oberoi family. The show initially focused on the tale of three brothers, later become centered on the love story of Shivaay and Annika (Surbhi Chandna); with the story of Omkara and Rudra being shifted to the spinoff series "Dil Boley Oberoi". In July 2017 "Dil Boley Oberoi" ended and the storylines were merged back into "Ishqbaaaz" which doubled its runtime.
Title 4 : Hotel Tallcorn
Paragraph 4 : The Hotel Tallcorn is located in Marshalltown, Iowa. Today it is called the Tallcorn Towers Apartments. Built in 1928 by the Eppley Hotel Company, local citizens contributed $120,000 to ensure the successful completion of this seven-story hotel. It was completed in connection to the seventy-fifth anniversary of Marshalltown. The hotel's sale in 1956 from the Eppley chain to the Sheraton Corporation was part of the second largest hotel sale in United States history. The Tallcorn was listed as a contributing property in the Marshalltown Downtown Historic District on the National Register of Historic Places in 2002.
Title 5 : Mohan Singh Oberoi
Paragraph 5 : Rai Bahadur Mohan Singh Oberoi (15 August 1898 – 3 May 2002) was an Indian hotelier, the founder and chairman of Oberoi Hotels & Resorts, India's second-largest hotel company, with 35 hotels in India, Sri Lanka, Nepal, Egypt, Australia and Hungary.
Title 6 : Hotel Bond
Paragraph 6 : Hotel Bond is a historic hotel, built in two stages in 1913 and 1921, in downtown Hartford, Connecticut by hotelier Harry S. Bond. It is located near Bushnell Park, and was considered the grandest hotel in Hartford during its heyday. The second section is a 12 story building attached to the 6 story first section. A Statler Hotel opened in the area in 1954, creating competition, and the Bond Hotel company declared bankruptcy shortly after that. It was bought by the California-based Masaglia Hotel chain, which began an incremental renovation program. In 1964 it was sold to a Cincinnati, Ohio investment group which announced extensive renovation plans. However, the financing plans fell through and the hotel was again in bankruptcy. The building was sold at auction to the Roman Catholic Archdiocese of Hartford in 1965, and it became the home of the Saint Francis Hospital School of Nursing. The Bond Ballroom reopened in 2001, with the rest of the building becoming a Homewood Suites by Hilton in 2006.
Title 7 : The Oberoi Group
Paragraph 7 : The Oberoi Group is a hotel company with its head office in Delhi. Founded in 1934, the company owns and/or operates 30+ luxury hotels and two river cruise ships in six countries, primarily under its Oberoi Hotels & Resorts and Trident Hotels brands.
Title 8 : Future Fibre Technologies
Paragraph 8 : Future Fibre Technologies (FFT) is a fiber optic sensing technologies company based in Melbourne, Australia, with its US head office in Mountain View, California, Middle East head office in Dubai, Indian head office in New Delhi and European head office in London. Founded in 1994, Future Fibre Technologies product line provides optical fiber intrusion detection systems for perimeters, buried oil and gas pipelines and data communication networks.
Title 9 : 289th Military Police Company
Paragraph 9 : The 289th Military Police Company was activated on 1 November 1994 and attached to Hotel Company, 3rd Infantry (The Old Guard), Fort Myer, Virginia. Hotel Company is the regiment's specialty company.
Title 10 : Glennwanis Hotel
Paragraph 10 : The Glennwanis Hotel is a historic hotel in Glennville, Georgia, Tattnall County, Georgia, built on the site of the Hughes Hotel. The hotel is located at 209-215 East Barnard Street. The old Hughes Hotel was built out of Georgia pine circa 1905 and burned in 1920. The Glennwanis was built in brick in 1926. The local Kiwanis club led the effort to get the replacement hotel built, and organized a Glennville Hotel Company with directors being local business leaders. The wife of a local doctor won a naming contest with the name "Glennwanis Hotel", a suggestion combining "Glennville" and "Kiwanis".

question: The Oberoi family is part of a hotel company that has a head office in what city?
--------------------------------------------------
story: Title 1 : Lisa Simpson
Paragraph 1 : Lisa Marie Simpson is a fictional character in the animated television series "The Simpsons". She is the middle child and most intelligent of the Simpson family. Voiced by Yeardley Smith, Lisa first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed her while waiting to meet James L. Brooks. Groening had been invited to pitch a series of shorts based on his comic "Life in Hell", but instead decided to create a new set of characters. He named the elder Simpson daughter after his younger sister Lisa Groening. After appearing on "The Tracey Ullman Show" for three years, the Simpson family were moved to their own series on Fox, which debuted on December 17, 1989.
Title 2 : Marge Simpson
Paragraph 2 : Marjorie Jacqueline "Marge" Simpson (née Bouvier) is a fictional character in the American animated sitcom "The Simpsons" and part of the eponymous family. She is voiced by Julie Kavner and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Marge was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on "Life in Hell" but instead decided to create a new set of characters. He named the character after his mother Margaret Groening. After appearing on "The Tracey Ullman Show" for three seasons, the Simpson family received their own series on Fox, which debuted December 17, 1989.
Title 3 : Bart Simpson
Paragraph 3 : Bartholomew JoJo "Bart" Simpson is a fictional character in the American animated television series "The Simpsons" and part of the Simpson family. He is voiced by Nancy Cartwright and first appeared on television in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Cartoonist Matt Groening created and designed Bart while waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip, "Life in Hell", but instead decided to create a new set of characters. While the rest of the characters were named after Groening's family members, Bart's name is an anagram of the word "brat". After appearing on "The Tracey Ullman Show" for three years, the Simpson family received its own series on Fox, which debuted December 17, 1989.
Title 4 : Allie Goertz
Paragraph 4 : Allison Beth "Allie" Goertz (born March 2, 1991) is an American musician. Goertz is known for her satirical songs based on various pop culture topics. Her videos are posted on YouTube under the name of Cossbysweater. Subjects of her songs have included the film "The Room", the character Milhouse from the television show "The Simpsons", and the game Dungeons & Dragons. Her style has been compared to that of Bo Burnham. In December 2015, Goertz released a concept album based on the Adult Swim series "Rick and Morty", "Sad Dance Songs", with the album's cover emulating the animation and logo of the series. The album was made possible through Kickstarter. She is co-host of Everything's Coming Up Podcast, a Simpsons-focused podcast along with Julia Prescott.
Title 5 : Milhouse Van Houten
Paragraph 5 : Milhouse Mussolini van Houten is a fictional character featured in the animated television series "The Simpsons", voiced by Pamela Hayden, and created by Matt Groening who named the character after President Richard Nixon's middle name. Later in the series, it is revealed that Milhouse's middle name is "Mussolini."
Title 6 : Los Angeles Reader
Paragraph 6 : Los Angeles Reader was a weekly paper established in 1978 and distributed in Los Angeles, United States. It followed the format of the (still active) Chicago Reader. The paper was known for having lengthy, thoughtful reviews of movies, plays and concerts in the LA area. James Vowell was its founding editor. Among its writers were Keith Fitzgerald, Nigey Lennon, Lionel Rolfe, Lawrence Wechsler, Mick Farren, Richard Meltzer, Heidi Dvorak, Chris Morris, Jerry Stahl, Steven Kane, Andy Klein, Allen Levy, Jim Goad, Kirk Silsbee, Henry Sheehan, Samantha Dunn, Natalie Nichols, Steve Appleford, Eric Mankin (also editor), Paul Birchall, Eddie Rivera (who wrote the paper's first cover story), Amy Steinberg, Harry Sheehan, Dan Sallit, Myron Meisel, David Ehrenstein. Tom Davis, Bruce Bebb, Stuart Goldman, Ernest Hardy, Kevin Uhrich, Erik Himmelsbach and David L. Ulin. It is famous for being the first newspaper to publish Matt Groening's cartoon strip, Life in Hell on April 25, 1980. James Vowell hired Matt Groening as his assistant editor in 1979. Groening was also originally a Reader music critic. It also ran a cartoon strip by David Lynch (director of Blue Velvet) called The Angriest Dog in the World, a strip notable for having exactly the same drawing panels for its entire run. James Vowell and his wife Codette Wallace bought the Reader from the Chicago Reader in February 1989. They sold "The Reader" to New Times Media in 1996, which merged it with the "Los Angeles View" to form "New Times LA".
Title 7 : Homer Simpson
Paragraph 7 : Homer Jay Simpson is a fictional character and the main protagonist of the American animated television series "The Simpsons" as the patriarch of the eponymous family. He is voiced by Dan Castellaneta and first appeared on television, along with the rest of his family, in "The Tracey Ullman Show" short "Good Night" on April 19, 1987. Homer was created and designed by cartoonist Matt Groening while he was waiting in the lobby of James L. Brooks' office. Groening had been called to pitch a series of shorts based on his comic strip "Life in Hell" but instead decided to create a new set of characters. He named the character after his father, Homer Groening. After appearing for three seasons on "The Tracey Ullman Show", the Simpson family got their own series on Fox that debuted December 17, 1989.
Title 8 : List of The Simpsons video games
Paragraph 8 : "The Simpsons" is an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company. The series is a satirical parody of a middle class American lifestyle epitomized by its eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. It is set in the fictional town of Springfield, and lampoons American culture, society and television, and many aspects of the human condition. The family was conceived by Groening shortly before a pitch for a series of animated shorts with producer James L. Brooks. Groening created a dysfunctional family and named the characters after members of his own family, substituting Bart for his own name. The shorts became a part of "The Tracey Ullman Show" on April 19, 1987 and after a three-season run, the sketch was developed into a half-hour prime time show and became a hit series for Fox. The growing popularity of the series motivated video game developers to create video games based on the series. Two pinball machines have also been produced; one self-titled, that was only made available for a limited time after the first season finale (1990) and "The Simpsons Pinball Party" (2003). Additionally, several handheld device games have been released, such as "Bartman: Avenger of Evil" (1990) and "Bart Simpson's Cupcake Crisis" (1991).
Title 9 : The Simpsons: An Uncensored, Unauthorized History
Paragraph 9 : The Simpsons: An Uncensored, Unauthorized History is a non-fiction book about the American animated television series "The Simpsons". It was written by John Ortved, and first published in October 2009 by Faber and Faber. In the United Kingdom, the book is called Simpsons Confidential: The uncensored, totally unauthorised history of the world's greatest TV show by the people that made it. The book is an oral history of the show, and concentrates particularly on the writers and producers of the show. The book includes entire chapters devoted to key figures such as creator Matt Groening and James L. Brooks and Sam Simon, who helped develop the series. According to National Public Radio reviewer Linda Holmes, "Ortved's thesis, essentially, is that lots of people are responsible for the success of "The Simpsons", and their creator, Matt Groening, has too often been viewed as the sole source to the detriment of others who also deserve to be praised."
Title 10 : List of The Simpsons guest stars
Paragraph 10 : In addition to the show's regular cast of voice actors, celebrity guest stars have been a staple of "The Simpsons", an American animated television sitcom created by Matt Groening for the Fox Broadcasting Company, since its first season. "The Simpsons" focuses on the eponymous family, which consists of Homer, Marge, Bart, Lisa and Maggie. The family was initially conceived by Groening for a series of animated shorts, which originally aired as a part of "The Tracey Ullman Show" between 1987 and 1989. The shorts were developed into a half-hour prime time series which began in December 1989. The series' 27th season began in September 2015 and episodes of "The Simpsons" have aired. A feature film adaptation of the series called "The Simpsons Movie", was released in 2007.

question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
--------------------------------------------------
story: Title 1 : Moloch: or, This Gentile World

In [12]:
main_df

,batch_num,question_num,context,question,answer
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long

## 4. Run the LLM pipeline to generate answers

In [13]:
conventional_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    conventional_str_list = conventional_chain.batch(batch)
    conventional_str_batch.append(conventional_str_list)

Batch 1 ... processing 10 items

In [14]:
for i, conventional_str_list in enumerate(conventional_str_batch):
    print(f"Batch {i + 1} ... processed {len(conventional_str_list)} items")
    for j, conventional_str in enumerate(conventional_str_list):
        print(f"Item {j + 1}:")
        print(conventional_str)
        print("-" * 50)

Batch 1 ... processed 10 items
Item 1:
Let's extract facts from the story to form a knowledge graph:

**Knowledge Graph Extraction:**

- Arthur's Magazine:
  - An American literary periodical.
  - Published in Philadelphia in the 19th century.
  - Edited by T.S. Arthur.
  - Existed from 1844–1846.
  - Started in 1844.

- First for Women:
  - A woman's magazine.
  - Published by Bauer Media Group in the USA.
  - Started in 1989.
  - Based in Englewood Cliffs, New Jersey.

**Complex Question Decomposition:**
"Which magazine was started first Arthur's Magazine or First for Women?"

**Sub-questions:**
1. When was Arthur's Magazine started?
2. When was First for Women started?
3. Which date is earlier?

**Step-by-step Reasoning:**

1. Arthur's Magazine was started in 1844 (from the knowledge graph: "Arthur's Magazine (1844–1846)").
2. First for Women was started in 1989 (from the knowledge graph: "The magazine was started in 1989").
3. 1844 is much earlier than 1989.

Thus, Arthur's Magazine was started first.

### FINAL ANSWER
Arthur's Magazine
--------------------------------------------------
Item 2:
Step by step reasoning:

1. First, from Paragraph 2, we know: The Oberoi family is famous for its involvement in hotels, namely through The Oberoi Group.
2. From Paragraph 7, we know: The Oberoi Group is a hotel company with its head office in Delhi.
3. Therefore, the hotel company that the Oberoi family is part of (The Oberoi Group) has its head office in Delhi.

### FINAL ANSWER
Delhi
--------------------------------------------------
Item 3:
Let's begin by creating a knowledge graph by extracting the main facts from each sentence in the story.

Knowledge Graph Extraction:
1. Lisa Simpson is a character in "The Simpsons", created by Matt Groening, first appeared on April 19, 1987, named after Matt Groening's younger sister Lisa Groening, voiced by Yeardley Smith.
2. Marge Simpson is a character in "The Simpsons", voiced by Julie Kavner, first appeared on April 19, 1987, created by Matt Groening, named after his mother Margaret Groening.
3. Bart Simpson is a character in "The Simpsons", voiced by Nancy Cartwright, first appeared April 19, 1987, created by Matt Groening, name is an anagram of "brat", other characters named after Groening's family, Bart's name is unique.
4. Allie Goertz is an American musician, satirical songwriter, made a song about Milhouse from "The Simpsons", co-hosts a Simpsons podcast, known as Cossbysweater.
5. Milhouse Van Houten is a character in "The Simpsons", voiced by Pamela Hayden, created by Matt Groening, character named after President Richard Nixon's middle name, Milhouse's middle name is Mussolini.
6. Los Angeles Reader: Paper which first published Matt Groening's "Life in Hell", unrelated to current question.
7. Homer Simpson: Character in "The Simpsons", created by Matt Groening, named after his father, Homer Groening.
8. "The Simpsons" conceived by Matt Groening, characters named after his family, Bart substituted.
9. Book about "The Simpsons" - not directly relevant.
10. Simpsons guest voices - not directly relevant.

Now, break down the question:
Main Question:
Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
So, the question is asking: After whom did Matt Groening name the character Milhouse?

Sub-questions:
1. Who is Allie Goertz? (Purpose: Confirmation and context)
   - From paragraph 4: Allie Goertz is an American musician, known for satirical songs, including one about Milhouse from "The Simpsons".

2. Who created the character Milhouse in "The Simpsons"?
   - Paragraph 5: Milhouse Van Houten is a fictional character featured in "The Simpsons", created by Matt Groening.

3. After whom did Matt Groening name the character Milhouse?
   - Directly in paragraph 5: "created by Matt Groening who named the character after President Richard Nixon's middle name." It is later clarified the character's middle name is Mussolini.

So, for the specific question, the answer is: "President Richard Nixon's middle name".

Step-by-step reasoning:
- Allie Goertz wrote a satirical song about Milhouse from "The Simpsons".
- Milhouse is a fictional character in "The Simpsons" created by Matt Groening.
- Matt Groening named Milhouse after President Richard Nixon's middle name ("Milhous").

### FINAL ANSWER
President Richard Nixon's middle name
--------------------------------------------------
Item 4:
Step by step reasoning:

1. Identify the relevant "James Henry Miller" in the input, as there may be more than one.
   - Paragraph 5: James Henry Miller (1915-1989), better known as Ewan MacColl.
   - Paragraph 10: James Henry Miller (born 1919), Australian footballer.

2. The question asks for "James Henry Miller's wife." Examine if either is known to have a wife with nationality stated.
   - Paragraph 10 (the footballer): No mention of a wife in provided paragraph.
   - Paragraph 5 (Ewan MacColl): Family details not in Paragraph 5, but his stage name is Ewan MacColl.

3. Scan the other paragraphs for spouses of these James Henry Millers.
   - Paragraph 6: Peggy Seeger was "married to singer and songwriter Ewan MacColl until his death in 1989."
   - So, James Henry Miller (Ewan MacColl) was married to Margaret "Peggy" Seeger.

4. Is Peggy Seeger's nationality stated?
   - Paragraph 6: Margaret "Peggy" Seeger (born June 17, 1935) is an American folksinger.

5. Therefore, James Henry Miller (Ewan MacColl)'s wife was American.

Connecting the facts:
- Ewan MacColl's real name is James Henry Miller.
- Ewan MacColl was married to Peggy Seeger.
- Peggy Seeger is American.

### FINAL ANSWER
American
--------------------------------------------------
Item 5:
Step by Step Reasoning:

1. The question is asking for a chemical in which Cadmium Chloride is "slightly soluble" and is "also called" by another name.
2. Start by reviewing the knowledge graph for information about the solubility of Cadmium chloride.
3. From Paragraph 1 (Cadmium chloride): "...highly soluble in water and slightly soluble in alcohol."
4. Now, look for a chemical among the entries that can mean "alcohol" and can be called by another name.
5. Paragraph 6 is about Ethanol, also called "alcohol", "ethyl alcohol", and "drinking alcohol".
6. This matches: Cadmium chloride is slightly soluble in alcohol, and "alcohol" is also called "ethanol" (and other names).
7. Connect these details: The chemical where Cadmium chloride is slightly soluble is alcohol, which is also called ethanol.

### FINAL ANSWER
Ethanol
--------------------------------------------------
Item 6:
First, let's extract and organize the facts relevant to the players Henri Leconte and Jonathan Stark from the story to build a knowledge graph.

**Knowledge Graph Extraction:**

- Henri Leconte
  - Nationality: French
  - Professional Status: Former tennis player
  - French Open Men's Singles finalist: 1988
  - French Open Men's Doubles title: 1984
  - Davis Cup win with France: 1991
  - Career-high singles ranking: World No. 5
  - 1986 Grand Prix German Open singles winner
  - No explicit mention of Grand Slam singles titles won
  - 1 Grand Slam doubles title (French Open Men's Doubles 1984)

- Jonathan Stark
  - Nationality: American
  - Professional Status: Former tennis player
  - Grand Slam doubles titles:
    - 1994 French Open Men's Doubles
    - 1995 Wimbledon Championships Mixed Doubles
  - Reached World No. 1 doubles ranking in 1994
  - Total Grand Slam titles (doubles/mixed): 2

**Complex Question:** Which tennis player won more Grand Slam titles, Henri Leconte or Jonathan Stark?

To answer this, let's break it down.

**Sub-Question 1:** How many Grand Slam titles (any kind) did Henri Leconte win?
- From the graph: Henri Leconte won 1 Grand Slam title (1984 French Open Men's Doubles).

**Sub-Question 2:** How many Grand Slam titles (any kind) did Jonathan Stark win?
- From the graph: Jonathan Stark won 2 Grand Slam titles (1994 French Open Men's Doubles and 1995 Wimbledon Mixed Doubles).

**Sub-Question 3:** Which number is greater: Henri Leconte's total or Jonathan Stark's total?
- Henri Leconte: 1 Grand Slam title
- Jonathan Stark: 2 Grand Slam titles
- 2 is greater than 1.

**Step-by-Step Connection:**
- Henri Leconte’s Grand Slam title count: 1
- Jonathan Stark’s Grand Slam title count: 2
- Therefore, Jonathan Stark won more Grand Slam titles than Henri Leconte.

### FINAL ANSWER
Jonathan Stark
--------------------------------------------------
Item 7:
Let me start by extracting a knowledge graph from the input story.

### Knowledge Graph

**From Titles 1, 2, 4: India**
- India is officially the Republic of India ("Bhārat Gaṇarājya").
- India is in South Asia.
- India is the seventh-largest country by area.
- India is the second-most populous country (>1.2 billion people).
- India is the most populous democracy.
- Geographically, India lies north of the equator between 8°4' to 37°6' north latitude and 68°7' to 97°25' east longitude.
- India has a total area of 3,287,263 km2.
- India measures 3,214 km from north to south and 2,933 km from east to west.
- India has a land frontier of 15,200 km.
- India has a coastline of 7,516.6 km.

**From Title 6: Nepita**
- Nepita is a genus of moth in the Arctiidae family.
- Nepita contains only one species: Nepita conferta.
- Nepita conferta can be found in India and Sri Lanka.
- Nepita conferta is commonly called the "footman moth."

**From Title 8: Indogrammodes**
- Indogrammodes is a genus of moths in the Crambidae family.
- Indogrammodes contains only one species: Indogrammodes pectinicornalis.
- Indogrammodes pectinicornalis is found in India.

(Other moth genera mentioned are found in North America, Japan, China, etc., but do not say they are in India except for Nepita and Indogrammodes.)

---

Now, let's process the complex question:

**Question:** Which genus of moth in the world's seventh-largest country contains only one species?

### Step-by-step Reasoning

**Step 1:** Identify "the world's seventh-largest country."
- According to the knowledge graph, India is the seventh-largest country by area.

**Step 2:** Find moth genera that are found in India.
- According to the knowledge graph, Nepita and Indogrammodes are two genera of moths found in India.

**Step 3:** Of these, check which contain only one species.
- Nepita: Contains only one species, Nepita conferta.
- Indogrammodes: Contains only one species, Indogrammodes pectinicornalis.

**Step 4:** Answer needs "Which genus" (singular), but both Nepita and Indogrammodes fit the description. The question is not exclusive; it asks for "which genus," not "the only genus." Thus, either answer is acceptable, though both fit.

**Step 5:** List either Nepita or Indogrammodes; or both if wanted. However, based on the structure, let's provide both in the final answer since the question could expect more than one if present.

### FINAL ANSWER
Nepita, Indogrammodes
--------------------------------------------------
Item 8:
Let's start by extracting facts from each sentence and building a knowledge graph.

### Knowledge Graph Construction

**Title 1: Verano de Escándalo (1998)**
- 1998 Verano de Escándalo: 2nd annual "Verano de Escándalo" show, promoted by AAA.
- Event date: September 18, 1998.
- Location: Madero, Tamaulipas, Mexico.
- Main event: Steel cage match.
- Teams: Heavy Metal & Blue Demon Jr. vs Kick Boxer & Abismo Negro.
- Stipulations: If Heavy Metal & Blue Demon Jr. lost, referee Guicho Dominguez would be El Tirante's "slave" for a week. If Kick Boxer & Abismo Negro lost, El Tirantes would be Guicho Dominguez's "slave" for a week.

**Title 2: Triplemanía VII**
- Triplemanía VII: Seventh show promoted by AAA.
- Event date: June 11, 1999.
- Location: Madero, Mexico.
- Main event: Six-man Lucha Libre rules tag team match.
- Teams: Perro Aguayo, Octagón, El Cobarde II vs El Texano, Perro Aguayo Jr., Sangre Chicana.
- Semi-main event: Heavy Metal & El Felino defended their father's (Pepe "Tropi" Casas, referee) hair, Kick Boxer & Thai Boxer defended referee El Tirantes's hair.
- Result: El Tirantes had his hair shaved off after the match.

**Title 3: Protection racket**
- Definition: Scheme providing illegal protection using violence.
- Racket deters harm to clients.
- Rackets arise where police/judiciary fail or law is absent.

**Title 4: E. Gordon Gee**
- Elwood Gordon Gee (b. 1944): American academic, President of West Virginia University (second term).
- Previous chief executive of several US universities.
- President of Ohio State University twice: 1990-1997 and until July 1, 2013.
- Headed Ohio State-based think tank after retirement in 2013.
- Retired due to controversies, last being anti-Catholic remarks about University of Notre Dame.

**Title 5: Badr Hari**
- Badr Hari (b. December 8, 1984): Moroccan-Dutch super heavyweight kickboxer.
- From Amsterdam, fights out of Mike's Gym in Oostzaan.
- Former K-1 Heavyweight champion (2007–2008).
- It's Showtime Heavyweight world champion (2009-2010).
- K-1 World Grand Prix 2009 finalist.
- Prominent figure in kickboxing, once considered best kickboxer in the world.
- Involved in controversies: "unsportsmanlike conducts" in sport, crimes of violence outside ring.

**Title 6: Guerra de Titanes (1998)**
- Guerra de Titanes (1998): Second such event, promoted by AAA.
- Event date: December 13, 1998.
- Location: Chihuahua, Mexico.
- Main event: Steel cage match, two feuds — Octagón vs Pentagón, Heavy Metal vs Kick Boxer.

**Title 7: Global Fighting Championship**
- Global Fighting Championship (GFC): UAE-based kickboxing/MMA event.
- Notable fighters: Badr Hari, Peter Aerts, Peter Graham, Dewey Cooper, Zabit Samedov.
- Major kickboxing/MMA promotion in Middle East.

**Title 8: Outrageous Betrayal**
- "Outrageous Betrayal": 1993 non-fiction book by Steven Pressman.
- Subject: Werner H. Erhard's life, businesses, self-improvement ventures, litigation/controversy, 60 Minutes expose, Erhard leaving USA.

**Title 9: Betting controversies in cricket**
- Cricket: Numerous controversies regarding players and betting (match-fixing, bribery, inside information).

**Title 10: Prosecution of gender-targeted crimes**
- Prosecution of gender-targeted crimes: E.g., rape/domestic violence.
- 1474: Sir Peter von Hagenbach convicted for rapes by troops.
- After WWII: Tokyo Tribunal, ICTY, ICTR specifically address gender-targeted crimes.

---

### Complex Question Decomposition

**Question:**
Who was once considered the best kick boxer in the world, however he has been involved in a number of controversies relating to his "unsportsmanlike conducts" in the sport and crimes of violence outside of the ring.

#### Step 1: Identify keywords and entities.
- "best kick boxer in the world"
- "controversies"
- "unsportsmanlike conducts"
- "crimes of violence outside of the ring"

#### Step 2: Scan the knowledge graph for entities matching "kick boxer" or related.
- Title 5 (Badr Hari) is about a kickboxer.
- Title 1/2/6/7 also mention kickboxing, but not "best in the world" or these particular controversies (except for GFC listing Badr Hari).

#### Step 3: Examine Title 5 facts.
- "Badr Hari ... is a Moroccan-Dutch super heavyweight kickboxer."
- "... was once considered the best kickboxer in the world..."
- "... involved in a number of controversies relating to his 'unsportsmanlike conducts' in the sport and crimes of violence outside of the ring."

#### Step 4: Check for matches with the question's qualifiers.
- "once considered best kick boxer in the world" ➔ Matches Badr Hari.
- "controversies relating to 'unsportsmanlike conducts' in the sport" ➔ Matches Badr Hari.
- "crimes of violence outside of the ring" ➔ Matches Badr Hari.

#### Step 5: No other titles mention these unique details or superlative status.

---

### Step by Step Reasoning

1. The question asks for someone who was once considered the best kickboxer in the world, and who has had controversies with unsportsmanlike conduct and crimes of violence outside the ring.
2. The knowledge graph shows that Badr Hari is described as a Moroccan-Dutch super heavyweight kickboxer from Amsterdam, a former K-1 Heavyweight champion, and was once considered the best kickboxer in the world.
3. The same entry notes that he has been involved in many controversies, both for unsportsmanlike conduct in the sport and for crimes of violence outside of the ring.
4. No other individual in the knowledge graph fits all these criteria.
5. Therefore, the person described in the question is Badr Hari.

### FINAL ANSWER
Badr Hari
--------------------------------------------------
Item 9:
First, create a knowledge graph by extracting facts from each sentence in the given input story.

### Knowledge Graph Extraction

#### Title 1: House of Anubis
- House of Anubis is a mystery television series.
- Developed for Nickelodeon.
- Based on Dutch-Belgian series "Het Huis Anubis".
- Created by Hans Bourlon and Gert Verhulst.
- Premiered on Nickelodeon on 1 Jan 2011 in US, 25 Feb 2011 in UK.
- First Nickelodeon series filmed outside US.
- First telenovela-format for network.
- Aired from 1 Jan 2011 to 17 Jun 2013.

#### Title 2: Batibot
- Batibot is a Philippine children's TV series, produced by PCTV.
- Based on "Sesame Street".
- First aired in 1984 on RPN as "Sesame!".
- Co-produced by Children's Television Workshop (now Sesame Workshop), partnership broke up.
- "Sesame!" became "Batibot" in 1985, full Filipino language.
- Aired until 1998, on at least 4 networks.
- Revived by TV5, aired 2010–2013.
- Mobile app released in 2015.

#### Title 3: Wolfblood
- Wolfblood is a British–German fantasy teen drama.
- Created by Debbie Moon.
- Co-production between CBBC and ZDF/ZDFE.
- Focus on "wolfbloods" (humans who can turn into wolves).
- Five complete series aired (detailed air dates/seasons given).

#### Title 4: List of House of Anubis episodes
- This is an episode list for "House of Anubis," a mystery/comedy-drama on Nickelodeon.

#### Title 5: Majisuka Gakuen
- Japanese TV drama, first aired on TV Tokyo, stars AKB48.
- Multiple seasons, later seasons moved to NTV and Hulu.
- Special spin-off aired Nov 28, 2015.

#### Title 6: Graduation Day (Buffy the Vampire Slayer)
- "Graduation Day" is season 3 finale of Buffy.
- Episodes written and directed by Joss Whedon.
- "Part 1" aired on May 18, 1999, "Part 2" aired July 13, 1999 (postponed from May 25 due to Columbine).

#### Title 7: Fish Police (TV series)
- Animated series by Hanna-Barbera, based on comics by Steve Moncuse.
- First aired CBS in 1992, lasted for six episodes.
- Three episodes aired in US, full series aired in Europe.

#### Title 8: Nathalia Ramos
- Nathalia Ramos Cohen (b. July 3, 1992), Spanish-Australian actress, U.S. citizenship.
- Known for playing Nina Martin in "House of Anubis".

#### Title 9: Het Huis Anubis
- "Het Huis Anubis" means "The House of Anubis".
- Belgian-Dutch children's drama.
- Created by Studio 100 and Nickelodeon.
- Aired in Netherlands and Flanders.
- First aired September 2006.
- Last episode December 4, 2009.
- Huge success in Benelux.
- Low budget first two seasons.

#### Title 10: Das Haus Anubis
- "Das Haus Anubis" produced by Studio 100 and Nickelodeon.
- First remake of "Het Huis Anubis".
- English remake "House of Anubis" aired in 2011.
- Seven-figure production budget, one of Nick's largest.
- First German daily soap for older children.
- Ran Sep 29, 2009 to May 4, 2012.

---

### Multi-Step Reasoning for the Question

**Main question:** The Dutch-Belgian television series that "House of Anubis" was based on first aired in what year?

#### Sub-question 1: What is the Dutch-Belgian TV series that "House of Anubis" is based on?
- From Title 1: House of Anubis is based on "Het Huis Anubis".

#### Sub-question 2: When did "Het Huis Anubis" first air?
- From Title 9: "Het Huis Anubis" first aired in September 2006.

#### Assemble the Answer:

In [15]:
conventional_str_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "answer_str": []
})

for i, conventional_str_list in enumerate(conventional_str_batch):
    batch_num_list = [i] * len(conventional_str_list)
    question_num_list = list(range(1, len(conventional_str_list) + 1))
    conventional_str_df = pd.concat([conventional_str_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "answer_str": conventional_str_list
    })], ignore_index=True)

# del conventional_str_batch
# del conventional_str_list
# del batch_input_list
# del batch_context
# del batch_question
# del batch_answer

conventional_str_df

   batch_num  question_num                                         answer_str
0        0.0           1.0  Let's extract facts from the story to form a k...
1        0.0           2.0  Step by step reasoning:\n\n1. First, from Para...
2        0.0           3.0  Let's begin by creating a knowledge graph by e...
3        0.0           4.0  Step by step reasoning:\n\n1. Identify the rel...
4        0.0           5.0  Step by Step Reasoning:\n\n1. The question is ...
5        0.0           6.0  First, let's extract and organize the facts re...
6        0.0           7.0  Let me start by extracting a knowledge graph f...
7        0.0           8.0  Let's start by extracting facts from each sent...
8        0.0           9.0  First, create a knowledge graph by extracting ...
9        0.0          10.0  Knowledge Graph Extraction:\n\n1. Mount Panora...

In [16]:
import re

def extract_final_answer(row):
    # Regex pattern to find the final answer
    final_answer_pat = r'### FINAL ANSWER\s*(.*)'
    match = re.search(final_answer_pat, row['answer_str'], re.DOTALL)
    return match.group(1).strip() if match else "No answer found"

conventional_str_df['llm_answer'] = conventional_str_df.apply(extract_final_answer, axis=1)
conventional_str_df

,batch_num,question_num,answer_str,llm_answer
0,0.0,1.0,Let's extract facts from the story to form a k...,Arthur's Magazine
1,0.0,2.0,"Step by step reasoning:\n\n1. First, from Para...",Delhi
2,0.0,3.0,Let's begin by creating a knowledge graph by e...,President Richard Nixon's middle name
3,0.0,4.0,Step by step reasoning:\n\n1. Identify the rel...,American
4,0.0,5.0,Step by Step Reasoning:\n\n1. The question is ...,Ethanol
5,0.0,6.0,"First, let's extract and organize the facts re...",Jonathan Stark
6,0.0,7.0,Let me start by extracting a knowledge graph f...,"Nepita, Indogrammodes"
7,0.0,8.0,Let's start by extracting facts from each sent...,Badr Hari
8,0.0,9.0,"First, create a knowledge graph by extracting ...",2006
9,0.0,10.0,Knowledge Graph Extraction:\n\n1. Mount Panora...,6.213 km

In [17]:
main_df = main_df.merge(conventional_str_df, on=['batch_num', 'question_num'], how='left')
main_df

,batch_num,question_num,context,question,answer,answer_str,llm_answer
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine,Let's extract facts from the story to form a k...,Arthur's Magazine
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi,"Step by step reasoning:\n\n1. First, from Para...",Delhi
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,Let's begin by creating a knowledge graph by e...,President Richard Nixon's middle name
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American,Step by step reasoning:\n\n1. Identify the rel...,American
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol,Step by Step Reasoning:\n\n1. The question is ...,Ethanol
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark,"First, let's extract and organize the facts re...",Jonathan Stark
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae,Let me start by extracting a knowledge graph f...,"Nepita, Indogrammodes"
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari,Let's start by extracting facts from each sent...,Badr Hari
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006,"First, create a knowledge graph by extracting ...",2006
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long,Knowledge Graph Extraction:\n\n1. Mount Panora...,6.213 km

## 5. Calculate accuracy

In [18]:
system_msg = """
<role>
    You are a meticulous LLM answer evaluator. Your task is to determine if the provided llm_answer correctly matches the correct_answer for a given question.
</role>

<behavior>
    <rule name="case-insensitive-match">
        Treat answers as correct even if their case (uppercase/lowercase) does not match, as long as the content matches.
    </rule>
    <rule name="synonyms-acceptable">
        Accept synonyms, short forms, or equivalent factual answers (e.g., "alcohol" and "ethanol") as correct, unless there is a clear difference in meaning or context.
    </rule>
    <rule name="factual-containment">
        Accept answers that contain the correct answer as a substring, or are paraphrased, provided no contradictory information is introduced.
    </rule>
    <rule name="insufficient-data">
        Mark as incorrect if llm_answer indicates "insufficient data" or similar phrases, but a correct factual answer is actually provided in correct_answer.
    </rule>
    <rule name="incorrect-content">
        Mark as incorrect if the llm_answer gives a wrong, contradictory, or irrelevant response compared to correct_answer.
    </rule>
    <rule name="format-neutrality">
        Do not penalize for minor differences in format, such as punctuation or extra explanatory words, as long as the meaning is unchanged.
    </rule>
    <rule name="numerical-tolerance">
        For numerical answers, accept equivalent formats (e.g., "2006" and "September 2006" are correct if both indicate the correct year), but mark as incorrect if the core value is wrong.
    </rule>
</behavior>

<format>
1) Output your reasoning step by step, referencing the question, correct_answer, and llm_answer.
2) Clearly state if the llm_answer matches the correct_answer according to the behavior rules above.
3) End your output with the heading "### FINAL_ANSWER" followed by TRUE if the llm_answer is correct or FALSE if incorrect.
</format>
"""

human_msg = """
<question>
{question}
</question>

<correct_answer>
{correct_answer}
</correct_answer>

<llm_answer>
{llm_answer}
</llm_answer>
"""

prompt = ChatPromptTemplate([("system", system_msg), ("human", human_msg)])

In [19]:
chain = prompt | llm_model | StrOutputParser()

In [20]:
# preparing the input for the evaluation chain
batch_input_list = []

for i in range(0, main_df.shape[0], BATCH_SIZE):
    batch_df = main_df.iloc[i:i+BATCH_SIZE]
    batch_input_item = []

    for i, (index, row) in enumerate(batch_df.iterrows()):
        batch_input_item.append({
            "question": row['question'],
            "correct_answer": row['answer'],
            "llm_answer": row['llm_answer']
        })
    batch_input_list.append(batch_input_item)

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1}:")
    for item in batch:
        print("Question:", item['question'])
        print("Correct Answer:", item['correct_answer'])
        print("LLM Answer:", item['llm_answer'])
        print("-" * 50)

Batch 1:
Question: Which magazine was started first Arthur's Magazine or First for Women?
Correct Answer: Arthur's Magazine
LLM Answer: Arthur's Magazine
--------------------------------------------------
Question: The Oberoi family is part of a hotel company that has a head office in what city?
Correct Answer: Delhi
LLM Answer: Delhi
--------------------------------------------------
Question: Musician and satirist Allie Goertz wrote a song about the "The Simpsons" character Milhouse, who Matt Groening named after who?
Correct Answer: President Richard Nixon
LLM Answer: President Richard Nixon's middle name
--------------------------------------------------
Question:  What nationality was James Henry Miller's wife?
Correct Answer: American
LLM Answer: American
--------------------------------------------------
Question: Cadmium Chloride is slightly soluble in this chemical, it is also called what?
Correct Answer: alcohol
LLM Answer: Ethanol
--------------------------------------------------
Question: Which tennis player won more Grand Slam titles, Henri Leconte or Jonathan Stark?
Correct Answer: Jonathan Stark
LLM Answer: Jonathan Stark
--------------------------------------------------
Question: Which genus of moth in the world's seventh-largest country contains only one species?
Correct Answer: Crambidae
LLM Answer: Nepita, Indogrammodes
--------------------------------------------------
Question: Who was once considered the best kick boxer in the world, however he has been involved in a number of controversies relating to his "unsportsmanlike conducts" in the sport and crimes of violence outside of the ring.
Correct Answer: Badr Hari
LLM Answer: Badr Hari
--------------------------------------------------
Question: The Dutch-Belgian television series that "House of Anubis" was based on first aired in what year?
Correct Answer: 2006
LLM Answer: 2006
--------------------------------------------------
Question: What is the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged?
Correct Answer: 6.213 km long
LLM Answer: 6.213 km
--------------------------------------------------

In [21]:
answer_check_str_batch = []

for i, batch in enumerate(batch_input_list):
    print(f"Batch {i + 1} ... processing {len(batch)} items")
    answer_check_str_list = chain.batch(batch)
    answer_check_str_batch.append(answer_check_str_list)

Batch 1 ... processing 10 items

In [22]:
for i, answer_check_str_list in enumerate(answer_check_str_batch):
    print(f"Batch {i + 1} ... processed {len(answer_check_str_list)} items")
    for j, answer_check_str in enumerate(answer_check_str_list):
        print(f"Item {j + 1}:")
        print(answer_check_str)
        print("-" * 50)

Batch 1 ... processed 10 items
Item 1:
1) The question asks which magazine was started first: Arthur's Magazine or First for Women?
2) The correct_answer given is "Arthur's Magazine."
3) The llm_answer is also "Arthur's Magazine."
4) According to the rules:
    - The content of the llm_answer exactly matches the correct_answer with no case or format discrepancies (format-neutrality, case-insensitive-match).
    - There is no irrelevant or contradictory information (incorrect-content).
    - The answer directly identifies the correct magazine, matching the correct factual answer (factual-containment).
5) Therefore, the llm_answer matches the correct_answer.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 2:
1) The question asks for the city where the Oberoi hotel company's head office is located.
2) The correct_answer is "Delhi."
3) The llm_answer also states "Delhi."
4) According to behavior rules, there are no issues with case, format, or synonyms here. The answers match exactly.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 3:
1) Let's examine the question: It asks about who Matt Groening named the "The Simpsons" character Milhouse after.

2) The correct_answer: "President Richard Nixon." This indicates the character was named after US President Richard Nixon.

3) The llm_answer: "President Richard Nixon's middle name."
   - This refers to the fact that Richard Nixon's middle name is "Milhous," and Matt Groening named Milhouse after this middle name.

4) Does the llm_answer match the correct_answer?
   - According to the behavior rules:
     - The llm_answer is more specific, indicating the reference is to Nixon's middle name, whereas the correct_answer lists only "President Richard Nixon."
     - These are factually related: the character Milhouse is named after Nixon's middle name, and this is a common trivia fact.
     - The llm_answer does not introduce contradictory information and arguably provides more detail.
     - Both answers ultimately refer to President Richard Nixon as the origin, through his middle name.

5) By the rules (especially "factual-containment" and "format-neutrality"), the llm_answer is acceptable as it is more specific and accurate, not misleading, and does not contradict the correct answer.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 4:
1) The question is: "What nationality was James Henry Miller's wife?"
2) The correct_answer is "American".
3) The llm_answer is also "American".
4) The llm_answer is exactly the same as the correct_answer, with no differences in case, spelling, or meaning.
5) According to the rules (case-insensitive match, factual containment, format neutrality), this is a perfectly correct match.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 5:
1) The question asks for the alternative/common name of a chemical in which cadmium chloride is slightly soluble. The correct answer is "alcohol." The llm_answer given is "Ethanol."
2) According to the <synonyms-acceptable> rule, ethanol and alcohol are considered as synonyms in a chemical context since ethanol is the type of alcohol most commonly referred to as "alcohol" in chemistry.
3) No contradictory information is introduced, and "Ethanol" matches the factual intent behind "alcohol" for this question.
4) There are no formatting or minor context discrepancies.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 6:
1) The question asks which tennis player, Henri Leconte or Jonathan Stark, won more Grand Slam titles.
2) The correct_answer is "Jonathan Stark".
3) The llm_answer is also "Jonathan Stark".
4) Both answers are exactly the same, with matching content and no contradictory or extraneous information.
5) According to the behavior rules ("case-insensitive-match", "format-neutrality", etc.), the llm_answer matches the correct_answer perfectly.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 7:
1) Step-by-step reasoning:

- The question asks for a genus of moth in the world's seventh-largest country (India) that contains only one species (i.e., a monotypic genus).
- The correct_answer given is "Crambidae". However, "Crambidae" is not a genus; it is a family of moths. A genus would be a more specific taxonomic level within the family Crambidae.
- The llm_answer provided is "Nepita, Indogrammodes". Both "Nepita" and "Indogrammodes" are legitimate genera of moths and have been documented as monotypic genera found in India.
- Comparing the answers: The correct_answer given appears to be incorrect in terms of taxonomic rank (it is a family, not a genus). The llm_answer supplies two valid genus names, which are appropriate responses to the question.
- According to Rule 5 ("incorrect-content"), we only mark as incorrect if the llm_answer is wrong, contradictory, or irrelevant. Here, the llm_answer is actually more correct than the correct_answer, as it provides actual genus names instead of a family.
- Based on the rules, even though the correct_answer itself is factually questionable, the llm_answer actually fits the question more accurately.

2) Therefore, the llm_answer matches (and in fact, improves upon) the correct_answer's intent, which was to identify a genus of moth in India that contains only one species.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 8:
1) The question asks for the name of the kickboxer who was widely considered the best in the world and was known for controversies related to unsportsmanlike conduct and violent crimes outside the ring.
2) The correct_answer is "Badr Hari".
3) The llm_answer is "Badr Hari".
4) The llm_answer matches the correct_answer exactly in content.
5) According to the rules ("case-insensitive-match" and "format-neutrality"), this is an unequivocal match.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 9:
1) The question asks for the year the Dutch-Belgian television series that "House of Anubis" is based on first aired.
2) The correct_answer is "2006."
3) The llm_answer is also "2006."
4) According to the behavior rules:
   - The answers are exactly the same, with no case sensitivity or format issues.
   - There are no extra explanations or irrelevant information.
   - The core numerical value matches precisely.

### FINAL_ANSWER
TRUE
--------------------------------------------------
Item 10:
1) The question asks for the length of the track for the 2013 Liqui Moly Bathurst 12 Hour.
2) The correct_answer is "6.213 km long".
3) The llm_answer is "6.213 km".
4) According to the rules:
   - The difference between "6.213 km long" and "6.213 km" is only in format/extra word ("long"), with no change in meaning (format-neutrality).
   - The content is factually identical and the units are present.
   - There is no additional or contradictory information in the llm_answer.
5) Therefore, the llm_answer correctly matches the correct_answer as per the behavior rules.

### FINAL_ANSWER
TRUE
--------------------------------------------------

In [23]:
# Create a DataFrame to store the evaluation results
answer_check_df = pd.DataFrame({
    "batch_num": [],
    "question_num": [],
    "answer_check_str": []
})

for i, answer_check_str_list in enumerate(answer_check_str_batch):
    batch_num_list = [i] * len(answer_check_str_list)
    question_num_list = list(range(1, len(answer_check_str_list) + 1))
    answer_check_df = pd.concat([answer_check_df, pd.DataFrame({
        "batch_num": batch_num_list,
        "question_num": question_num_list,
        "answer_check_str": answer_check_str_list
    })], ignore_index=True)

In [24]:
answer_check_df

   batch_num  question_num                                   answer_check_str
0        0.0           1.0  1) The question asks which magazine was starte...
1        0.0           2.0  1) The question asks for the city where the Ob...
2        0.0           3.0  1) Let's examine the question: It asks about w...
3        0.0           4.0  1) The question is: "What nationality was Jame...
4        0.0           5.0  1) The question asks for the alternative/commo...
5        0.0           6.0  1) The question asks which tennis player, Henr...
6        0.0           7.0  1) Step-by-step reasoning:\n\n- The question a...
7        0.0           8.0  1) The question asks for the name of the kickb...
8        0.0           9.0  1) The question asks for the year the Dutch-Be...
9        0.0          10.0  1) The question asks for the length of the tra...

In [25]:
# Extract is_correct from the answer_check_str
def extract_is_correct(row):
    # Regex pattern to find the final answer
    final_answer_pat = r'### FINAL_ANSWER\s*(TRUE|FALSE)'
    match = re.search(final_answer_pat, row['answer_check_str'], re.DOTALL)
    return match.group(1).strip() if match else False

# Merge the llm_answer_str_df with main_df to get the final answers
answer_check_df['is_correct'] = answer_check_df.apply(extract_is_correct, axis=1)
main_df = main_df.merge(answer_check_df, on=['batch_num', 'question_num'], how='left')
main_df

,batch_num,question_num,context,question,answer,answer_str,llm_answer,answer_check_str,is_correct
0,0,1,Title 1 : Radio City (Indian radio station) \n...,Which magazine was started first Arthur's Maga...,Arthur's Magazine,Let's extract facts from the story to form a k...,Arthur's Magazine,1) The question asks which magazine was starte...,TRUE
1,0,2,Title 1 : Ritz-Carlton Jakarta \nParagraph 1 :...,The Oberoi family is part of a hotel company t...,Delhi,"Step by step reasoning:\n\n1. First, from Para...",Delhi,1) The question asks for the city where the Ob...,TRUE
2,0,3,Title 1 : Lisa Simpson \nParagraph 1 : Lisa Ma...,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,Let's begin by creating a knowledge graph by e...,President Richard Nixon's middle name,1) Let's examine the question: It asks about w...,TRUE
3,0,4,"Title 1 : Moloch: or, This Gentile World \nPar...",What nationality was James Henry Miller's wife?,American,Step by step reasoning:\n\n1. Identify the rel...,American,"1) The question is: ""What nationality was Jame...",TRUE
4,0,5,Title 1 : Cadmium chloride \nParagraph 1 : Cad...,Cadmium Chloride is slightly soluble in this c...,alcohol,Step by Step Reasoning:\n\n1. The question is ...,Ethanol,1) The question asks for the alternative/commo...,TRUE
5,0,6,Title 1 : Li Na \nParagraph 1 : Li Na (; ; bor...,Which tennis player won more Grand Slam titles...,Jonathan Stark,"First, let's extract and organize the facts re...",Jonathan Stark,"1) The question asks which tennis player, Henr...",TRUE
6,0,7,"Title 1 : India \nParagraph 1 : India, officia...",Which genus of moth in the world's seventh-lar...,Crambidae,Let me start by extracting a knowledge graph f...,"Nepita, Indogrammodes",1) Step-by-step reasoning:\n\n- The question a...,TRUE
7,0,8,Title 1 : Verano de Escándalo (1998) \nParagra...,Who was once considered the best kick boxer in...,Badr Hari,Let's start by extracting facts from each sent...,Badr Hari,1) The question asks for the name of the kickb...,TRUE
8,0,9,Title 1 : House of Anubis \nParagraph 1 : Hous...,"The Dutch-Belgian television series that ""Hous...",2006,"First, create a knowledge graph by extracting ...",2006,1) The question asks for the year the Dutch-Be...,TRUE
9,0,10,Title 1 : Mount Panorama Circuit \nParagraph 1...,What is the length of the track where the 2013...,6.213 km long,Knowledge Graph Extraction:\n\n1. Mount Panora...,6.213 km,1) The question asks for the length of the tra...,TRUE

In [26]:
# Calculate the accuracy
accuracy = main_df['is_correct'].value_counts(normalize=True).get('TRUE', 0) * 100
print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 100.00%

In [ ]:
# GPT 4.1 - Accuracy: 100.00%